/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.llamamod.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.llamamod.item.inventory.NetheritebackpackInventoryCapability;
import net.mcreator.llamamod.item.inventory.BackpackInventoryCapability;
import net.mcreator.llamamod.item.*;
import net.mcreator.llamamod.LlamaModMod;

import java.util.function.Function;

@EventBusSubscriber
public class LlamaModModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(LlamaModMod.MODID);
	public static final DeferredItem<Item> BANANA_PLANT;
	public static final DeferredItem<Item> BANANA;
	public static final DeferredItem<Item> BACKPACK;
	public static final DeferredItem<Item> NETHERITEBACKPACK;
	public static final DeferredItem<Item> ACID_BUCKET;
	public static final DeferredItem<Item> REDBRICKS;
	public static final DeferredItem<Item> ORANGEBRICKS;
	public static final DeferredItem<Item> YELLOWBRICKS;
	public static final DeferredItem<Item> GREENBRICKS;
	public static final DeferredItem<Item> LIGHTBLUEBRICKS;
	public static final DeferredItem<Item> BLUEBRICKS;
	public static final DeferredItem<Item> MAGENTABRICKS;
	public static final DeferredItem<Item> PINKBRICKS;
	public static final DeferredItem<Item> BROWNBRICKS;
	public static final DeferredItem<Item> BLACKBRICKS;
	public static final DeferredItem<Item> INDUSTRIALBRICKS;
	public static final DeferredItem<Item> COMPUTER;
	public static final DeferredItem<Item> TILES;
	public static final DeferredItem<Item> FARMSCRAPS;
	public static final DeferredItem<Item> CEILINGTILES;
	public static final DeferredItem<Item> AUTHENTICATORBLOCK;
	public static final DeferredItem<Item> PASSWORDCHANGER;
	public static final DeferredItem<Item> REDBRICKSLAB;
	public static final DeferredItem<Item> REDBRICKSTAIR;
	public static final DeferredItem<Item> ORANGEBRICKSLAB;
	public static final DeferredItem<Item> ORANGEBRICKSTAIR;
	public static final DeferredItem<Item> YELLOWBRICKSLAB;
	public static final DeferredItem<Item> YELLOWBRICKSTAIR;
	public static final DeferredItem<Item> LIGHTBLUEBRICKSLAB;
	public static final DeferredItem<Item> LIGHTBLUEBRICKSTAIR;
	public static final DeferredItem<Item> BLUEBRICKSLAB;
	public static final DeferredItem<Item> BLUEBRICKSTAIR;
	public static final DeferredItem<Item> MAGENTABRICKSLAB;
	public static final DeferredItem<Item> MAGENTABRICKSTAIR;
	public static final DeferredItem<Item> PINKBRICKSLAB;
	public static final DeferredItem<Item> PINKBRICKSTAIR;
	public static final DeferredItem<Item> BROWNBRICKSLAB;
	public static final DeferredItem<Item> BROWNBRICKSTAIR;
	public static final DeferredItem<Item> BLACKBRICKSLAB;
	public static final DeferredItem<Item> BLACKBRICKSTAIR;
	public static final DeferredItem<Item> INDUSTRIALBRICKSLAB;
	public static final DeferredItem<Item> INDUSTRIALBRICKSTAIR;
	public static final DeferredItem<Item> TILESLAB;
	public static final DeferredItem<Item> TILESTAIR;
	public static final DeferredItem<Item> CEILINGTILESLAB;
	public static final DeferredItem<Item> CEILINGTILESTAIR;
	public static final DeferredItem<Item> WHITEBRICKS;
	public static final DeferredItem<Item> LIGHTGRAYBRICKS;
	public static final DeferredItem<Item> GRAYBRICKS;
	public static final DeferredItem<Item> LIMEBRICKS;
	public static final DeferredItem<Item> CYANBRICKS;
	public static final DeferredItem<Item> CHERRYBRICKS;
	public static final DeferredItem<Item> PURPLEBRICKS;
	public static final DeferredItem<Item> LIMEBRICKSLAB;
	public static final DeferredItem<Item> LIMEBRICKSTAIR;
	public static final DeferredItem<Item> GREENBRICKSSLAB;
	public static final DeferredItem<Item> GREENBRICKSSTAIR;
	public static final DeferredItem<Item> CYANBRICKSLAB;
	public static final DeferredItem<Item> CYANBRICKSTAIR;
	public static final DeferredItem<Item> PURPLEBRICKSLAB;
	public static final DeferredItem<Item> PURPLEBRICKSTAIR;
	public static final DeferredItem<Item> WHITEBRICKSLAB;
	public static final DeferredItem<Item> WHITEBRICKSTAIR;
	public static final DeferredItem<Item> LIGHTGRAYBRICKSLAB;
	public static final DeferredItem<Item> LIGHTGRAYBRICKSTAIR;
	public static final DeferredItem<Item> GRAYBRICKSLAB;
	public static final DeferredItem<Item> GRAYBRICKSTAIR;
	public static final DeferredItem<Item> CHERRYBRICKSLAB;
	public static final DeferredItem<Item> CHERRYBRICKSTAIR;
	public static final DeferredItem<Item> REDBRICKWALL;
	public static final DeferredItem<Item> ORANGEBRICKWALL;
	public static final DeferredItem<Item> YELLOWBRICKWALL;
	public static final DeferredItem<Item> GREENBRICKWALL;
	public static final DeferredItem<Item> LIGHTBLUEBRICKWALL;
	public static final DeferredItem<Item> BLUEBRICKWALL;
	public static final DeferredItem<Item> MAGENTABRICKWALL;
	public static final DeferredItem<Item> PINKBRICKWALL;
	public static final DeferredItem<Item> BROWNBRICKWALL;
	public static final DeferredItem<Item> BLACKBRICKWALL;
	public static final DeferredItem<Item> INDUSTRIALBRICKWALL;
	public static final DeferredItem<Item> WHITEBRICKWALL;
	public static final DeferredItem<Item> LIGHTGRAYBRICKWALL;
	public static final DeferredItem<Item> GRAYBRICKWALL;
	public static final DeferredItem<Item> LIMEBRICKWALL;
	public static final DeferredItem<Item> CYANBRICKWALL;
	public static final DeferredItem<Item> CHERRYBRICKWALL;
	public static final DeferredItem<Item> PURPLEBRICKWALL;
	public static final DeferredItem<Item> CEILINGTILEWALL;
	public static final DeferredItem<Item> TILEWALL;
	public static final DeferredItem<Item> INDUSTRIALBRICKFENCE;
	public static final DeferredItem<Item> INDUSTRIALBRICKFENCEGATE;
	public static final DeferredItem<Item> INDUSTRIALBRICKBUTTON;
	public static final DeferredItem<Item> INDUSTRIALBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> REDBRICKFENCE;
	public static final DeferredItem<Item> ORANGEBRICKFENCE;
	public static final DeferredItem<Item> YELLOWBRICKFENCE;
	public static final DeferredItem<Item> GREENBRICKFENCE;
	public static final DeferredItem<Item> LIGHTBLUEBRICKFENCE;
	public static final DeferredItem<Item> BLUEBRICKFENCE;
	public static final DeferredItem<Item> MAGENTABRICKFENCE;
	public static final DeferredItem<Item> PINKBRICKFENCE;
	public static final DeferredItem<Item> BROWNBRICKFENCE;
	public static final DeferredItem<Item> BLACKBRICKFENCE;
	public static final DeferredItem<Item> WHITEBRICKFENCE;
	public static final DeferredItem<Item> LIGHTGRAYBRICKFENCE;
	public static final DeferredItem<Item> GRAYBRICKFENCE;
	public static final DeferredItem<Item> LIMEBRICKFENCE;
	public static final DeferredItem<Item> CYANBRICKFENCE;
	public static final DeferredItem<Item> PURPLEBRICKFENCE;
	public static final DeferredItem<Item> CHERRYBRICKFENCE;
	public static final DeferredItem<Item> REDBRICKFENCEGATE;
	public static final DeferredItem<Item> ORANGEBRICKFENCEGATE;
	public static final DeferredItem<Item> YELLOWBRICKFENCEAGTE;
	public static final DeferredItem<Item> GREENBRICKFENCEGATE;
	public static final DeferredItem<Item> LIGHTBLUEBRICKFENCEGATE;
	public static final DeferredItem<Item> BLUEBRICKFENCEGATE;
	public static final DeferredItem<Item> MAGENTABRICKFENCEGATE;
	public static final DeferredItem<Item> PINKBRICKFENCEGATE;
	public static final DeferredItem<Item> BROWNBRICKFENCEGATE;
	public static final DeferredItem<Item> BLACKBRICKFENCEGATE;
	public static final DeferredItem<Item> WHITEBRICKFENCEGATE;
	public static final DeferredItem<Item> LIGHTGRAYBRICKFENCEGATE;
	public static final DeferredItem<Item> GRAYBRICKFENCEGATE;
	public static final DeferredItem<Item> LIMEBRICKFENCEGATE;
	public static final DeferredItem<Item> CYANBRICKFENCEGATE;
	public static final DeferredItem<Item> PURPLEBRICKFENCEGATE;
	public static final DeferredItem<Item> CHERRYBRICKFENCEGATE;
	public static final DeferredItem<Item> REDBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> ORANGEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> YELLOWBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> GREENBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTBLUEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> BLUEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> MAGENTABRICKPRESSUREPLATE;
	public static final DeferredItem<Item> PINKBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> BROWNBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> BLACKBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> WHITEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTGRAYBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> GRAYBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> LIMEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> CYANBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> PURPLEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> CHERRYBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> REDBRICKBUTTON;
	public static final DeferredItem<Item> ORANGEBRICKBUTTON;
	public static final DeferredItem<Item> YELLOWBRICKBUTTON;
	public static final DeferredItem<Item> GREENBRICKBUTTON;
	public static final DeferredItem<Item> LIGHTBLUEBRICKBUTTON;
	public static final DeferredItem<Item> BLUEBRICKBUTTON;
	public static final DeferredItem<Item> MAGENTABRICKBUTTON;
	public static final DeferredItem<Item> PINKBRICKBUTTON;
	public static final DeferredItem<Item> BROWNBRICKBUTTON;
	public static final DeferredItem<Item> BLACKBRICKBUTTON;
	public static final DeferredItem<Item> WHITEBRICKBUTTON;
	public static final DeferredItem<Item> LIGHTGRAYBRICKBUTTON;
	public static final DeferredItem<Item> GRAYBRICKBUTTON;
	public static final DeferredItem<Item> LIMEBRICKBUTTON;
	public static final DeferredItem<Item> CYANBRICKBUTTON;
	public static final DeferredItem<Item> PURPLEBRICKBUTTON;
	public static final DeferredItem<Item> CHERRYBRICKBUTTON;
	public static final DeferredItem<Item> TILEPRESSUREPLATE;
	public static final DeferredItem<Item> TILEBUTTON;
	public static final DeferredItem<Item> CEILINGTILEPRESSUREPLATE;
	public static final DeferredItem<Item> CEILINGTILEBUTTON;
	public static final DeferredItem<Item> WHITELARGETILE;
	public static final DeferredItem<Item> WHITELARGETILESTAIR;
	public static final DeferredItem<Item> WHITELARGETILESLAB;
	public static final DeferredItem<Item> WHITELARGETILEWALL;
	public static final DeferredItem<Item> WHITELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> WHITELARGETILEBUTTON;
	public static final DeferredItem<Item> VARIABLELIGHT;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILE;
	public static final DeferredItem<Item> GRAYLARGETILE;
	public static final DeferredItem<Item> BLACKLARGETILE;
	public static final DeferredItem<Item> ORANGELARGETILE;
	public static final DeferredItem<Item> MAGENTALARGETILE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILE;
	public static final DeferredItem<Item> BLUELARGETILE;
	public static final DeferredItem<Item> YELLOWLARGETILE;
	public static final DeferredItem<Item> LIMELARGETILE;
	public static final DeferredItem<Item> GREENLARGETILE;
	public static final DeferredItem<Item> PINKLARGETILE;
	public static final DeferredItem<Item> CYANLARGETILE;
	public static final DeferredItem<Item> PURPLELARGETILE;
	public static final DeferredItem<Item> BROWNLARGETILE;
	public static final DeferredItem<Item> REDLARGETILE;
	public static final DeferredItem<Item> LARGETILEFENCE;
	public static final DeferredItem<Item> LARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILESTAIR;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILESLAB;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEWALL;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEFENCE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEBUTTON;
	public static final DeferredItem<Item> GRAYLARGETILESTAIR;
	public static final DeferredItem<Item> GRAYLARGETILESLAB;
	public static final DeferredItem<Item> GRAYLARGETILEWALL;
	public static final DeferredItem<Item> GRAYLARGETILEFENCE;
	public static final DeferredItem<Item> GRAYLARGETILEFENCEGATE;
	public static final DeferredItem<Item> GRAYLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> GRAYLARGETILEBUTTON;
	public static final DeferredItem<Item> BLACKLARGETILESTAIR;
	public static final DeferredItem<Item> BLACKLARGETILESLAB;
	public static final DeferredItem<Item> BLACKLARGETILEWALL;
	public static final DeferredItem<Item> BLACKLARGETILEFENCE;
	public static final DeferredItem<Item> BLACKLARGETILEFENCEGATE;
	public static final DeferredItem<Item> BLACKLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> BLACKLARGETILEBUTTON;
	public static final DeferredItem<Item> BROWNLARGETILESTAIR;
	public static final DeferredItem<Item> BROWNLARGETILESLAB;
	public static final DeferredItem<Item> BROWNLARGETILEWALL;
	public static final DeferredItem<Item> BROWNLARGETILEFENCE;
	public static final DeferredItem<Item> BROWNLARGETILEFENCEGATE;
	public static final DeferredItem<Item> BROWNLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> BROWNLARGETILEBUTTON;
	public static final DeferredItem<Item> REDLARGETILESTAIR;
	public static final DeferredItem<Item> REDLARGETILESLAB;
	public static final DeferredItem<Item> REDLARGETILEWALL;
	public static final DeferredItem<Item> REDLARGETILEFENCE;
	public static final DeferredItem<Item> REDLARGETILEFENCEGATE;
	public static final DeferredItem<Item> REDLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> REDLARGETILEBUTTON;
	public static final DeferredItem<Item> ORANGELARGETILESTAIR;
	public static final DeferredItem<Item> ORANGELARGETILESLAB;
	public static final DeferredItem<Item> ORANGELARGETILEWALL;
	public static final DeferredItem<Item> ORANGELARGETILEFENCE;
	public static final DeferredItem<Item> ORANGELARGETILEFENCEGATE;
	public static final DeferredItem<Item> ORANGELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> ORANGELARGETILEBUTTON;
	public static final DeferredItem<Item> YELLOWLARGETILESTAIR;
	public static final DeferredItem<Item> YELLOWLARGETILESLAB;
	public static final DeferredItem<Item> YELLOWLARGETILEWALL;
	public static final DeferredItem<Item> YELLOWLARGETILEFENCE;
	public static final DeferredItem<Item> YELLOWLARGETILEFENCEGATE;
	public static final DeferredItem<Item> YELLOWLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> YELLOWLARGETILEBUTTON;
	public static final DeferredItem<Item> LIMELARGETILESTAIR;
	public static final DeferredItem<Item> LIMELARGETILESLAB;
	public static final DeferredItem<Item> LIMELARGETILEWALL;
	public static final DeferredItem<Item> LIMELARGETILEFENCE;
	public static final DeferredItem<Item> LIMELARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIMELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> LIMELARGETILEBUTTON;
	public static final DeferredItem<Item> GREENLARGETILESTAIR;
	public static final DeferredItem<Item> GREENLARGETILESLAB;
	public static final DeferredItem<Item> GREENLARGETILEWALL;
	public static final DeferredItem<Item> GREENLARGETILEFENCE;
	public static final DeferredItem<Item> GREENLARGETILEFENCEGATE;
	public static final DeferredItem<Item> GREENLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> GREENLARGETILEBUTTON;
	public static final DeferredItem<Item> CYANLARGETILESTAIR;
	public static final DeferredItem<Item> CYANLARGETILESLAB;
	public static final DeferredItem<Item> CYANLARGETILEWALL;
	public static final DeferredItem<Item> CYANLARGETILEFENCE;
	public static final DeferredItem<Item> CYANLARGETILEFENCEGATE;
	public static final DeferredItem<Item> CYANLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> CYANLARGETILEBUTTON;
	public static final DeferredItem<Item> LIGHTBLUELARGETILESTAIR;
	public static final DeferredItem<Item> LIGHTBLUELARGETILESLAB;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEWALL;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEFENCE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEBUTTON;
	public static final DeferredItem<Item> BLUELARGETILESTAIR;
	public static final DeferredItem<Item> BLUELARGETILESLAB;
	public static final DeferredItem<Item> BLUELARGETILEWALL;
	public static final DeferredItem<Item> BLUELARGETILEFENCE;
	public static final DeferredItem<Item> BLUELARGETILEFENCEGATE;
	public static final DeferredItem<Item> BLUELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> BLUELARGETILEBUTTON;
	public static final DeferredItem<Item> PURPLELARGETILESTAIR;
	public static final DeferredItem<Item> PURPLELARGETILESLAB;
	public static final DeferredItem<Item> PURPLELARGETILEWALL;
	public static final DeferredItem<Item> PURPLELARGETILEFENCE;
	public static final DeferredItem<Item> PURPLELARGETILEFENCEGATE;
	public static final DeferredItem<Item> PURPLELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> PURPLELARGETILEBUTTON;
	public static final DeferredItem<Item> MAGENTALARGETILESTAIR;
	public static final DeferredItem<Item> MAGENTALARGETILESLAB;
	public static final DeferredItem<Item> MAGENTALARGETILEWALL;
	public static final DeferredItem<Item> MAGENTALARGETILEFENCE;
	public static final DeferredItem<Item> MAGENTALARGETILEFENCEGATE;
	public static final DeferredItem<Item> MAGENTALARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> MAGENTALARGETILEBUTTON;
	public static final DeferredItem<Item> PINKLARGETILESTAIR;
	public static final DeferredItem<Item> PINKLARGETILESLAB;
	public static final DeferredItem<Item> PINKLARGETILEWALL;
	public static final DeferredItem<Item> PINKLARGETILEFENCE;
	public static final DeferredItem<Item> PINKLARGETILEFENCEGATE;
	public static final DeferredItem<Item> PINKLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> PINKLARGETILEBUTTON;
	public static final DeferredItem<Item> CEILINGTILEFENCE;
	public static final DeferredItem<Item> CEILINGTILEFENCEGATE;
	public static final DeferredItem<Item> TILEFENCE;
	public static final DeferredItem<Item> TILEFENCEGATE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILESTAIR;
	public static final DeferredItem<Item> INDUSTRIALLARGETILESLAB;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEWALL;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEFENCE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEFENCEGATE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEBUTTON;
	public static final DeferredItem<Item> WHITELARGETILETRAPDOOR;
	public static final DeferredItem<Item> INDUSTRIALLARGETILETRAPDOOR;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILETRAPDOOR;
	public static final DeferredItem<Item> GRAYLARGETILETRAPDOOR;
	public static final DeferredItem<Item> BLACKLARGETILETRAPDOOR;
	public static final DeferredItem<Item> BROWNLARGETILETRAPDOOR;
	public static final DeferredItem<Item> REDLARGETILETRAPDOOR;
	public static final DeferredItem<Item> ORANGELARGETILETRAPDOOR;
	public static final DeferredItem<Item> YELLOWLARGETILETRAPDOOR;
	public static final DeferredItem<Item> LIMELARGETILETRAPDOOR;
	public static final DeferredItem<Item> GREENLARGETILETRAPDOOR;
	public static final DeferredItem<Item> CYANLARGETILETRAPDOOR;
	public static final DeferredItem<Item> LIGHTBLUELARGETILETRAPDOOR;
	public static final DeferredItem<Item> BLUELARGETILETRAPDOOR;
	public static final DeferredItem<Item> PURPLELARGETILETRAPDOOR;
	public static final DeferredItem<Item> MAGENTALARGETILETRAPDOOR;
	public static final DeferredItem<Item> PINKLARGETILETRAPDOOR;
	public static final DeferredItem<Item> WHITEBRICKTRAPDOOR;
	public static final DeferredItem<Item> LIGHTGRAYBRICKTRAPDOOR;
	public static final DeferredItem<Item> GRAYBRICKTRAPDOOR;
	public static final DeferredItem<Item> BLACKBRICKTRAPDOOR;
	public static final DeferredItem<Item> BROWNBRICKTRAPDOOR;
	public static final DeferredItem<Item> REDBRICKTRAPDOOR;
	public static final DeferredItem<Item> ORANGEBRICKTRAPDOOR;
	public static final DeferredItem<Item> YELLOWBRICKTRAPDOOR;
	public static final DeferredItem<Item> LIMEBRICKTRAPDOOR;
	public static final DeferredItem<Item> GREENBRICKTRAPDOOR;
	public static final DeferredItem<Item> CYANBRICKTRAPDOOR;
	public static final DeferredItem<Item> LIGHTBLUEBRICKTRAPDOOR;
	public static final DeferredItem<Item> BLUEBRICKTRAPDOOR;
	public static final DeferredItem<Item> PURPLEBRICKTRAPDOOR;
	public static final DeferredItem<Item> MAGENTABRICKTRAPDOOR;
	public static final DeferredItem<Item> PINKBRICKTRAPDOOR;
	public static final DeferredItem<Item> CHERRYBRICKTRAPDOOR;
	public static final DeferredItem<Item> INDUSTRIALBRICKTRAPDOOR;
	public static final DeferredItem<Item> CEILINGTILETRAPDOOR;
	public static final DeferredItem<Item> TILETRAPDOOR;
	public static final DeferredItem<Item> CHERRYLARGETILE;
	public static final DeferredItem<Item> CHERRYLARGETILESTAIR;
	public static final DeferredItem<Item> CHERRYLARGETILESLAB;
	public static final DeferredItem<Item> CHERRYLARGETILEWALL;
	public static final DeferredItem<Item> CHERRYLARGETILEFENCE;
	public static final DeferredItem<Item> CHERRYLARGETILEFENCEGATE;
	public static final DeferredItem<Item> CHERRYLARGETILETRAPDOOR;
	public static final DeferredItem<Item> CHERRYLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> CHERRYLARGETILEBUTTON;
	public static final DeferredItem<Item> SECURESTORAGEBLOCK;
	public static final DeferredItem<Item> TEALBRICKS;
	public static final DeferredItem<Item> TEALLARGETILE;
	public static final DeferredItem<Item> TEALLARGETILESTAIR;
	public static final DeferredItem<Item> TEALLARGETILESLAB;
	public static final DeferredItem<Item> TEALLARGETILEWALL;
	public static final DeferredItem<Item> TEALLARGETILEFENCE;
	public static final DeferredItem<Item> TEALLARGETILEFENCEGATE;
	public static final DeferredItem<Item> TEALLARGETILETRAPDOOR;
	public static final DeferredItem<Item> TEALLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> TEALLARGETILEBUTTON;
	public static final DeferredItem<Item> TEALBRICKSTAIR;
	public static final DeferredItem<Item> TEALBRICKSLAB;
	public static final DeferredItem<Item> TEALBRICKWALL;
	public static final DeferredItem<Item> TEALBRICKFENCE;
	public static final DeferredItem<Item> TEALBRICKFENCEGATE;
	public static final DeferredItem<Item> TEALBRICKTRAPDOOR;
	public static final DeferredItem<Item> TEALBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> TEALBRICKBUTTON;
	static {
		BANANA_PLANT = block(LlamaModModBlocks.BANANA_PLANT);
		BANANA = register("banana", BannanaItem::new);
		BACKPACK = register("backpack", BackpackItem::new);
		NETHERITEBACKPACK = register("netheritebackpack", NetheritebackpackItem::new);
		ACID_BUCKET = register("acid_bucket", AcidItem::new);
		REDBRICKS = block(LlamaModModBlocks.REDBRICKS);
		ORANGEBRICKS = block(LlamaModModBlocks.ORANGEBRICKS);
		YELLOWBRICKS = block(LlamaModModBlocks.YELLOWBRICKS);
		GREENBRICKS = block(LlamaModModBlocks.GREENBRICKS);
		LIGHTBLUEBRICKS = block(LlamaModModBlocks.LIGHTBLUEBRICKS);
		BLUEBRICKS = block(LlamaModModBlocks.BLUEBRICKS);
		MAGENTABRICKS = block(LlamaModModBlocks.MAGENTABRICKS);
		PINKBRICKS = block(LlamaModModBlocks.PINKBRICKS);
		BROWNBRICKS = block(LlamaModModBlocks.BROWNBRICKS);
		BLACKBRICKS = block(LlamaModModBlocks.BLACKBRICKS);
		INDUSTRIALBRICKS = block(LlamaModModBlocks.INDUSTRIALBRICKS);
		COMPUTER = block(LlamaModModBlocks.COMPUTER);
		TILES = block(LlamaModModBlocks.TILES);
		FARMSCRAPS = register("farmscraps", FarmscrapsItem::new);
		CEILINGTILES = block(LlamaModModBlocks.CEILINGTILES);
		AUTHENTICATORBLOCK = block(LlamaModModBlocks.AUTHENTICATORBLOCK);
		PASSWORDCHANGER = register("passwordchanger", PasswordchangerItem::new);
		REDBRICKSLAB = block(LlamaModModBlocks.REDBRICKSLAB);
		REDBRICKSTAIR = block(LlamaModModBlocks.REDBRICKSTAIR);
		ORANGEBRICKSLAB = block(LlamaModModBlocks.ORANGEBRICKSLAB);
		ORANGEBRICKSTAIR = block(LlamaModModBlocks.ORANGEBRICKSTAIR);
		YELLOWBRICKSLAB = block(LlamaModModBlocks.YELLOWBRICKSLAB);
		YELLOWBRICKSTAIR = block(LlamaModModBlocks.YELLOWBRICKSTAIR);
		LIGHTBLUEBRICKSLAB = block(LlamaModModBlocks.LIGHTBLUEBRICKSLAB);
		LIGHTBLUEBRICKSTAIR = block(LlamaModModBlocks.LIGHTBLUEBRICKSTAIR);
		BLUEBRICKSLAB = block(LlamaModModBlocks.BLUEBRICKSLAB);
		BLUEBRICKSTAIR = block(LlamaModModBlocks.BLUEBRICKSTAIR);
		MAGENTABRICKSLAB = block(LlamaModModBlocks.MAGENTABRICKSLAB);
		MAGENTABRICKSTAIR = block(LlamaModModBlocks.MAGENTABRICKSTAIR);
		PINKBRICKSLAB = block(LlamaModModBlocks.PINKBRICKSLAB);
		PINKBRICKSTAIR = block(LlamaModModBlocks.PINKBRICKSTAIR);
		BROWNBRICKSLAB = block(LlamaModModBlocks.BROWNBRICKSLAB);
		BROWNBRICKSTAIR = block(LlamaModModBlocks.BROWNBRICKSTAIR);
		BLACKBRICKSLAB = block(LlamaModModBlocks.BLACKBRICKSLAB);
		BLACKBRICKSTAIR = block(LlamaModModBlocks.BLACKBRICKSTAIR);
		INDUSTRIALBRICKSLAB = block(LlamaModModBlocks.INDUSTRIALBRICKSLAB);
		INDUSTRIALBRICKSTAIR = block(LlamaModModBlocks.INDUSTRIALBRICKSTAIR);
		TILESLAB = block(LlamaModModBlocks.TILESLAB);
		TILESTAIR = block(LlamaModModBlocks.TILESTAIR, new Item.Properties().fireResistant());
		CEILINGTILESLAB = block(LlamaModModBlocks.CEILINGTILESLAB);
		CEILINGTILESTAIR = block(LlamaModModBlocks.CEILINGTILESTAIR);
		WHITEBRICKS = block(LlamaModModBlocks.WHITEBRICKS);
		LIGHTGRAYBRICKS = block(LlamaModModBlocks.LIGHTGRAYBRICKS);
		GRAYBRICKS = block(LlamaModModBlocks.GRAYBRICKS);
		LIMEBRICKS = block(LlamaModModBlocks.LIMEBRICKS);
		CYANBRICKS = block(LlamaModModBlocks.CYANBRICKS);
		CHERRYBRICKS = block(LlamaModModBlocks.CHERRYBRICKS);
		PURPLEBRICKS = block(LlamaModModBlocks.PURPLEBRICKS);
		LIMEBRICKSLAB = block(LlamaModModBlocks.LIMEBRICKSLAB);
		LIMEBRICKSTAIR = block(LlamaModModBlocks.LIMEBRICKSTAIR);
		GREENBRICKSSLAB = block(LlamaModModBlocks.GREENBRICKSSLAB);
		GREENBRICKSSTAIR = block(LlamaModModBlocks.GREENBRICKSSTAIR);
		CYANBRICKSLAB = block(LlamaModModBlocks.CYANBRICKSLAB);
		CYANBRICKSTAIR = block(LlamaModModBlocks.CYANBRICKSTAIR);
		PURPLEBRICKSLAB = block(LlamaModModBlocks.PURPLEBRICKSLAB);
		PURPLEBRICKSTAIR = block(LlamaModModBlocks.PURPLEBRICKSTAIR);
		WHITEBRICKSLAB = block(LlamaModModBlocks.WHITEBRICKSLAB);
		WHITEBRICKSTAIR = block(LlamaModModBlocks.WHITEBRICKSTAIR);
		LIGHTGRAYBRICKSLAB = block(LlamaModModBlocks.LIGHTGRAYBRICKSLAB);
		LIGHTGRAYBRICKSTAIR = block(LlamaModModBlocks.LIGHTGRAYBRICKSTAIR);
		GRAYBRICKSLAB = block(LlamaModModBlocks.GRAYBRICKSLAB);
		GRAYBRICKSTAIR = block(LlamaModModBlocks.GRAYBRICKSTAIR);
		CHERRYBRICKSLAB = block(LlamaModModBlocks.CHERRYBRICKSLAB);
		CHERRYBRICKSTAIR = block(LlamaModModBlocks.CHERRYBRICKSTAIR);
		REDBRICKWALL = block(LlamaModModBlocks.REDBRICKWALL);
		ORANGEBRICKWALL = block(LlamaModModBlocks.ORANGEBRICKWALL);
		YELLOWBRICKWALL = block(LlamaModModBlocks.YELLOWBRICKWALL);
		GREENBRICKWALL = block(LlamaModModBlocks.GREENBRICKWALL);
		LIGHTBLUEBRICKWALL = block(LlamaModModBlocks.LIGHTBLUEBRICKWALL);
		BLUEBRICKWALL = block(LlamaModModBlocks.BLUEBRICKWALL);
		MAGENTABRICKWALL = block(LlamaModModBlocks.MAGENTABRICKWALL);
		PINKBRICKWALL = block(LlamaModModBlocks.PINKBRICKWALL);
		BROWNBRICKWALL = block(LlamaModModBlocks.BROWNBRICKWALL);
		BLACKBRICKWALL = block(LlamaModModBlocks.BLACKBRICKWALL);
		INDUSTRIALBRICKWALL = block(LlamaModModBlocks.INDUSTRIALBRICKWALL);
		WHITEBRICKWALL = block(LlamaModModBlocks.WHITEBRICKWALL);
		LIGHTGRAYBRICKWALL = block(LlamaModModBlocks.LIGHTGRAYBRICKWALL);
		GRAYBRICKWALL = block(LlamaModModBlocks.GRAYBRICKWALL);
		LIMEBRICKWALL = block(LlamaModModBlocks.LIMEBRICKWALL);
		CYANBRICKWALL = block(LlamaModModBlocks.CYANBRICKWALL);
		CHERRYBRICKWALL = block(LlamaModModBlocks.CHERRYBRICKWALL);
		PURPLEBRICKWALL = block(LlamaModModBlocks.PURPLEBRICKWALL);
		CEILINGTILEWALL = block(LlamaModModBlocks.CEILINGTILEWALL);
		TILEWALL = block(LlamaModModBlocks.TILEWALL, new Item.Properties().fireResistant());
		INDUSTRIALBRICKFENCE = block(LlamaModModBlocks.INDUSTRIALBRICKFENCE);
		INDUSTRIALBRICKFENCEGATE = block(LlamaModModBlocks.INDUSTRIALBRICKFENCEGATE);
		INDUSTRIALBRICKBUTTON = block(LlamaModModBlocks.INDUSTRIALBRICKBUTTON);
		INDUSTRIALBRICKPRESSUREPLATE = block(LlamaModModBlocks.INDUSTRIALBRICKPRESSUREPLATE);
		REDBRICKFENCE = block(LlamaModModBlocks.REDBRICKFENCE);
		ORANGEBRICKFENCE = block(LlamaModModBlocks.ORANGEBRICKFENCE);
		YELLOWBRICKFENCE = block(LlamaModModBlocks.YELLOWBRICKFENCE);
		GREENBRICKFENCE = block(LlamaModModBlocks.GREENBRICKFENCE);
		LIGHTBLUEBRICKFENCE = block(LlamaModModBlocks.LIGHTBLUEBRICKFENCE);
		BLUEBRICKFENCE = block(LlamaModModBlocks.BLUEBRICKFENCE);
		MAGENTABRICKFENCE = block(LlamaModModBlocks.MAGENTABRICKFENCE);
		PINKBRICKFENCE = block(LlamaModModBlocks.PINKBRICKFENCE);
		BROWNBRICKFENCE = block(LlamaModModBlocks.BROWNBRICKFENCE);
		BLACKBRICKFENCE = block(LlamaModModBlocks.BLACKBRICKFENCE);
		WHITEBRICKFENCE = block(LlamaModModBlocks.WHITEBRICKFENCE);
		LIGHTGRAYBRICKFENCE = block(LlamaModModBlocks.LIGHTGRAYBRICKFENCE);
		GRAYBRICKFENCE = block(LlamaModModBlocks.GRAYBRICKFENCE);
		LIMEBRICKFENCE = block(LlamaModModBlocks.LIMEBRICKFENCE);
		CYANBRICKFENCE = block(LlamaModModBlocks.CYANBRICKFENCE);
		PURPLEBRICKFENCE = block(LlamaModModBlocks.PURPLEBRICKFENCE);
		CHERRYBRICKFENCE = block(LlamaModModBlocks.CHERRYBRICKFENCE);
		REDBRICKFENCEGATE = block(LlamaModModBlocks.REDBRICKFENCEGATE);
		ORANGEBRICKFENCEGATE = block(LlamaModModBlocks.ORANGEBRICKFENCEGATE);
		YELLOWBRICKFENCEAGTE = block(LlamaModModBlocks.YELLOWBRICKFENCEAGTE);
		GREENBRICKFENCEGATE = block(LlamaModModBlocks.GREENBRICKFENCEGATE);
		LIGHTBLUEBRICKFENCEGATE = block(LlamaModModBlocks.LIGHTBLUEBRICKFENCEGATE);
		BLUEBRICKFENCEGATE = block(LlamaModModBlocks.BLUEBRICKFENCEGATE);
		MAGENTABRICKFENCEGATE = block(LlamaModModBlocks.MAGENTABRICKFENCEGATE);
		PINKBRICKFENCEGATE = block(LlamaModModBlocks.PINKBRICKFENCEGATE);
		BROWNBRICKFENCEGATE = block(LlamaModModBlocks.BROWNBRICKFENCEGATE);
		BLACKBRICKFENCEGATE = block(LlamaModModBlocks.BLACKBRICKFENCEGATE);
		WHITEBRICKFENCEGATE = block(LlamaModModBlocks.WHITEBRICKFENCEGATE);
		LIGHTGRAYBRICKFENCEGATE = block(LlamaModModBlocks.LIGHTGRAYBRICKFENCEGATE);
		GRAYBRICKFENCEGATE = block(LlamaModModBlocks.GRAYBRICKFENCEGATE);
		LIMEBRICKFENCEGATE = block(LlamaModModBlocks.LIMEBRICKFENCEGATE);
		CYANBRICKFENCEGATE = block(LlamaModModBlocks.CYANBRICKFENCEGATE);
		PURPLEBRICKFENCEGATE = block(LlamaModModBlocks.PURPLEBRICKFENCEGATE);
		CHERRYBRICKFENCEGATE = block(LlamaModModBlocks.CHERRYBRICKFENCEGATE);
		REDBRICKPRESSUREPLATE = block(LlamaModModBlocks.REDBRICKPRESSUREPLATE);
		ORANGEBRICKPRESSUREPLATE = block(LlamaModModBlocks.ORANGEBRICKPRESSUREPLATE);
		YELLOWBRICKPRESSUREPLATE = block(LlamaModModBlocks.YELLOWBRICKPRESSUREPLATE);
		GREENBRICKPRESSUREPLATE = block(LlamaModModBlocks.GREENBRICKPRESSUREPLATE);
		LIGHTBLUEBRICKPRESSUREPLATE = block(LlamaModModBlocks.LIGHTBLUEBRICKPRESSUREPLATE);
		BLUEBRICKPRESSUREPLATE = block(LlamaModModBlocks.BLUEBRICKPRESSUREPLATE);
		MAGENTABRICKPRESSUREPLATE = block(LlamaModModBlocks.MAGENTABRICKPRESSUREPLATE);
		PINKBRICKPRESSUREPLATE = block(LlamaModModBlocks.PINKBRICKPRESSUREPLATE);
		BROWNBRICKPRESSUREPLATE = block(LlamaModModBlocks.BROWNBRICKPRESSUREPLATE);
		BLACKBRICKPRESSUREPLATE = block(LlamaModModBlocks.BLACKBRICKPRESSUREPLATE);
		WHITEBRICKPRESSUREPLATE = block(LlamaModModBlocks.WHITEBRICKPRESSUREPLATE);
		LIGHTGRAYBRICKPRESSUREPLATE = block(LlamaModModBlocks.LIGHTGRAYBRICKPRESSUREPLATE);
		GRAYBRICKPRESSUREPLATE = block(LlamaModModBlocks.GRAYBRICKPRESSUREPLATE);
		LIMEBRICKPRESSUREPLATE = block(LlamaModModBlocks.LIMEBRICKPRESSUREPLATE);
		CYANBRICKPRESSUREPLATE = block(LlamaModModBlocks.CYANBRICKPRESSUREPLATE);
		PURPLEBRICKPRESSUREPLATE = block(LlamaModModBlocks.PURPLEBRICKPRESSUREPLATE);
		CHERRYBRICKPRESSUREPLATE = block(LlamaModModBlocks.CHERRYBRICKPRESSUREPLATE);
		REDBRICKBUTTON = block(LlamaModModBlocks.REDBRICKBUTTON);
		ORANGEBRICKBUTTON = block(LlamaModModBlocks.ORANGEBRICKBUTTON);
		YELLOWBRICKBUTTON = block(LlamaModModBlocks.YELLOWBRICKBUTTON);
		GREENBRICKBUTTON = block(LlamaModModBlocks.GREENBRICKBUTTON);
		LIGHTBLUEBRICKBUTTON = block(LlamaModModBlocks.LIGHTBLUEBRICKBUTTON);
		BLUEBRICKBUTTON = block(LlamaModModBlocks.BLUEBRICKBUTTON);
		MAGENTABRICKBUTTON = block(LlamaModModBlocks.MAGENTABRICKBUTTON);
		PINKBRICKBUTTON = block(LlamaModModBlocks.PINKBRICKBUTTON);
		BROWNBRICKBUTTON = block(LlamaModModBlocks.BROWNBRICKBUTTON);
		BLACKBRICKBUTTON = block(LlamaModModBlocks.BLACKBRICKBUTTON);
		WHITEBRICKBUTTON = block(LlamaModModBlocks.WHITEBRICKBUTTON);
		LIGHTGRAYBRICKBUTTON = block(LlamaModModBlocks.LIGHTGRAYBRICKBUTTON);
		GRAYBRICKBUTTON = block(LlamaModModBlocks.GRAYBRICKBUTTON);
		LIMEBRICKBUTTON = block(LlamaModModBlocks.LIMEBRICKBUTTON);
		CYANBRICKBUTTON = block(LlamaModModBlocks.CYANBRICKBUTTON);
		PURPLEBRICKBUTTON = block(LlamaModModBlocks.PURPLEBRICKBUTTON);
		CHERRYBRICKBUTTON = block(LlamaModModBlocks.CHERRYBRICKBUTTON);
		TILEPRESSUREPLATE = block(LlamaModModBlocks.TILEPRESSUREPLATE);
		TILEBUTTON = block(LlamaModModBlocks.TILEBUTTON);
		CEILINGTILEPRESSUREPLATE = block(LlamaModModBlocks.CEILINGTILEPRESSUREPLATE);
		CEILINGTILEBUTTON = block(LlamaModModBlocks.CEILINGTILEBUTTON);
		WHITELARGETILE = block(LlamaModModBlocks.WHITELARGETILE);
		WHITELARGETILESTAIR = block(LlamaModModBlocks.WHITELARGETILESTAIR);
		WHITELARGETILESLAB = block(LlamaModModBlocks.WHITELARGETILESLAB);
		WHITELARGETILEWALL = block(LlamaModModBlocks.WHITELARGETILEWALL);
		WHITELARGETILEPRESSUREPLATE = block(LlamaModModBlocks.WHITELARGETILEPRESSUREPLATE);
		WHITELARGETILEBUTTON = block(LlamaModModBlocks.WHITELARGETILEBUTTON);
		VARIABLELIGHT = block(LlamaModModBlocks.VARIABLELIGHT);
		LIGHTGRAYLARGETILE = block(LlamaModModBlocks.LIGHTGRAYLARGETILE);
		GRAYLARGETILE = block(LlamaModModBlocks.GRAYLARGETILE);
		BLACKLARGETILE = block(LlamaModModBlocks.BLACKLARGETILE);
		ORANGELARGETILE = block(LlamaModModBlocks.ORANGELARGETILE);
		MAGENTALARGETILE = block(LlamaModModBlocks.MAGENTALARGETILE);
		LIGHTBLUELARGETILE = block(LlamaModModBlocks.LIGHTBLUELARGETILE);
		BLUELARGETILE = block(LlamaModModBlocks.BLUELARGETILE);
		YELLOWLARGETILE = block(LlamaModModBlocks.YELLOWLARGETILE);
		LIMELARGETILE = block(LlamaModModBlocks.LIMELARGETILE);
		GREENLARGETILE = block(LlamaModModBlocks.GREENLARGETILE);
		PINKLARGETILE = block(LlamaModModBlocks.PINKLARGETILE);
		CYANLARGETILE = block(LlamaModModBlocks.CYANLARGETILE);
		PURPLELARGETILE = block(LlamaModModBlocks.PURPLELARGETILE);
		BROWNLARGETILE = block(LlamaModModBlocks.BROWNLARGETILE);
		REDLARGETILE = block(LlamaModModBlocks.REDLARGETILE);
		LARGETILEFENCE = block(LlamaModModBlocks.LARGETILEFENCE);
		LARGETILEFENCEGATE = block(LlamaModModBlocks.LARGETILEFENCEGATE);
		LIGHTGRAYLARGETILESTAIR = block(LlamaModModBlocks.LIGHTGRAYLARGETILESTAIR);
		LIGHTGRAYLARGETILESLAB = block(LlamaModModBlocks.LIGHTGRAYLARGETILESLAB);
		LIGHTGRAYLARGETILEWALL = block(LlamaModModBlocks.LIGHTGRAYLARGETILEWALL);
		LIGHTGRAYLARGETILEFENCE = block(LlamaModModBlocks.LIGHTGRAYLARGETILEFENCE);
		LIGHTGRAYLARGETILEFENCEGATE = block(LlamaModModBlocks.LIGHTGRAYLARGETILEFENCEGATE);
		LIGHTGRAYLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.LIGHTGRAYLARGETILEPRESSUREPLATE);
		LIGHTGRAYLARGETILEBUTTON = block(LlamaModModBlocks.LIGHTGRAYLARGETILEBUTTON);
		GRAYLARGETILESTAIR = block(LlamaModModBlocks.GRAYLARGETILESTAIR);
		GRAYLARGETILESLAB = block(LlamaModModBlocks.GRAYLARGETILESLAB);
		GRAYLARGETILEWALL = block(LlamaModModBlocks.GRAYLARGETILEWALL);
		GRAYLARGETILEFENCE = block(LlamaModModBlocks.GRAYLARGETILEFENCE);
		GRAYLARGETILEFENCEGATE = block(LlamaModModBlocks.GRAYLARGETILEFENCEGATE);
		GRAYLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.GRAYLARGETILEPRESSUREPLATE);
		GRAYLARGETILEBUTTON = block(LlamaModModBlocks.GRAYLARGETILEBUTTON);
		BLACKLARGETILESTAIR = block(LlamaModModBlocks.BLACKLARGETILESTAIR);
		BLACKLARGETILESLAB = block(LlamaModModBlocks.BLACKLARGETILESLAB);
		BLACKLARGETILEWALL = block(LlamaModModBlocks.BLACKLARGETILEWALL);
		BLACKLARGETILEFENCE = block(LlamaModModBlocks.BLACKLARGETILEFENCE);
		BLACKLARGETILEFENCEGATE = block(LlamaModModBlocks.BLACKLARGETILEFENCEGATE);
		BLACKLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.BLACKLARGETILEPRESSUREPLATE);
		BLACKLARGETILEBUTTON = block(LlamaModModBlocks.BLACKLARGETILEBUTTON);
		BROWNLARGETILESTAIR = block(LlamaModModBlocks.BROWNLARGETILESTAIR);
		BROWNLARGETILESLAB = block(LlamaModModBlocks.BROWNLARGETILESLAB);
		BROWNLARGETILEWALL = block(LlamaModModBlocks.BROWNLARGETILEWALL);
		BROWNLARGETILEFENCE = block(LlamaModModBlocks.BROWNLARGETILEFENCE);
		BROWNLARGETILEFENCEGATE = block(LlamaModModBlocks.BROWNLARGETILEFENCEGATE);
		BROWNLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.BROWNLARGETILEPRESSUREPLATE);
		BROWNLARGETILEBUTTON = block(LlamaModModBlocks.BROWNLARGETILEBUTTON);
		REDLARGETILESTAIR = block(LlamaModModBlocks.REDLARGETILESTAIR);
		REDLARGETILESLAB = block(LlamaModModBlocks.REDLARGETILESLAB);
		REDLARGETILEWALL = block(LlamaModModBlocks.REDLARGETILEWALL);
		REDLARGETILEFENCE = block(LlamaModModBlocks.REDLARGETILEFENCE);
		REDLARGETILEFENCEGATE = block(LlamaModModBlocks.REDLARGETILEFENCEGATE);
		REDLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.REDLARGETILEPRESSUREPLATE);
		REDLARGETILEBUTTON = block(LlamaModModBlocks.REDLARGETILEBUTTON);
		ORANGELARGETILESTAIR = block(LlamaModModBlocks.ORANGELARGETILESTAIR);
		ORANGELARGETILESLAB = block(LlamaModModBlocks.ORANGELARGETILESLAB);
		ORANGELARGETILEWALL = block(LlamaModModBlocks.ORANGELARGETILEWALL);
		ORANGELARGETILEFENCE = block(LlamaModModBlocks.ORANGELARGETILEFENCE);
		ORANGELARGETILEFENCEGATE = block(LlamaModModBlocks.ORANGELARGETILEFENCEGATE);
		ORANGELARGETILEPRESSUREPLATE = block(LlamaModModBlocks.ORANGELARGETILEPRESSUREPLATE);
		ORANGELARGETILEBUTTON = block(LlamaModModBlocks.ORANGELARGETILEBUTTON);
		YELLOWLARGETILESTAIR = block(LlamaModModBlocks.YELLOWLARGETILESTAIR);
		YELLOWLARGETILESLAB = block(LlamaModModBlocks.YELLOWLARGETILESLAB);
		YELLOWLARGETILEWALL = block(LlamaModModBlocks.YELLOWLARGETILEWALL);
		YELLOWLARGETILEFENCE = block(LlamaModModBlocks.YELLOWLARGETILEFENCE);
		YELLOWLARGETILEFENCEGATE = block(LlamaModModBlocks.YELLOWLARGETILEFENCEGATE);
		YELLOWLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.YELLOWLARGETILEPRESSUREPLATE);
		YELLOWLARGETILEBUTTON = block(LlamaModModBlocks.YELLOWLARGETILEBUTTON);
		LIMELARGETILESTAIR = block(LlamaModModBlocks.LIMELARGETILESTAIR);
		LIMELARGETILESLAB = block(LlamaModModBlocks.LIMELARGETILESLAB);
		LIMELARGETILEWALL = block(LlamaModModBlocks.LIMELARGETILEWALL);
		LIMELARGETILEFENCE = block(LlamaModModBlocks.LIMELARGETILEFENCE);
		LIMELARGETILEFENCEGATE = block(LlamaModModBlocks.LIMELARGETILEFENCEGATE);
		LIMELARGETILEPRESSUREPLATE = block(LlamaModModBlocks.LIMELARGETILEPRESSUREPLATE);
		LIMELARGETILEBUTTON = block(LlamaModModBlocks.LIMELARGETILEBUTTON);
		GREENLARGETILESTAIR = block(LlamaModModBlocks.GREENLARGETILESTAIR);
		GREENLARGETILESLAB = block(LlamaModModBlocks.GREENLARGETILESLAB);
		GREENLARGETILEWALL = block(LlamaModModBlocks.GREENLARGETILEWALL);
		GREENLARGETILEFENCE = block(LlamaModModBlocks.GREENLARGETILEFENCE);
		GREENLARGETILEFENCEGATE = block(LlamaModModBlocks.GREENLARGETILEFENCEGATE);
		GREENLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.GREENLARGETILEPRESSUREPLATE);
		GREENLARGETILEBUTTON = block(LlamaModModBlocks.GREENLARGETILEBUTTON);
		CYANLARGETILESTAIR = block(LlamaModModBlocks.CYANLARGETILESTAIR);
		CYANLARGETILESLAB = block(LlamaModModBlocks.CYANLARGETILESLAB);
		CYANLARGETILEWALL = block(LlamaModModBlocks.CYANLARGETILEWALL);
		CYANLARGETILEFENCE = block(LlamaModModBlocks.CYANLARGETILEFENCE);
		CYANLARGETILEFENCEGATE = block(LlamaModModBlocks.CYANLARGETILEFENCEGATE);
		CYANLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.CYANLARGETILEPRESSUREPLATE);
		CYANLARGETILEBUTTON = block(LlamaModModBlocks.CYANLARGETILEBUTTON);
		LIGHTBLUELARGETILESTAIR = block(LlamaModModBlocks.LIGHTBLUELARGETILESTAIR);
		LIGHTBLUELARGETILESLAB = block(LlamaModModBlocks.LIGHTBLUELARGETILESLAB);
		LIGHTBLUELARGETILEWALL = block(LlamaModModBlocks.LIGHTBLUELARGETILEWALL);
		LIGHTBLUELARGETILEFENCE = block(LlamaModModBlocks.LIGHTBLUELARGETILEFENCE);
		LIGHTBLUELARGETILEFENCEGATE = block(LlamaModModBlocks.LIGHTBLUELARGETILEFENCEGATE);
		LIGHTBLUELARGETILEPRESSUREPLATE = block(LlamaModModBlocks.LIGHTBLUELARGETILEPRESSUREPLATE);
		LIGHTBLUELARGETILEBUTTON = block(LlamaModModBlocks.LIGHTBLUELARGETILEBUTTON);
		BLUELARGETILESTAIR = block(LlamaModModBlocks.BLUELARGETILESTAIR);
		BLUELARGETILESLAB = block(LlamaModModBlocks.BLUELARGETILESLAB);
		BLUELARGETILEWALL = block(LlamaModModBlocks.BLUELARGETILEWALL);
		BLUELARGETILEFENCE = block(LlamaModModBlocks.BLUELARGETILEFENCE);
		BLUELARGETILEFENCEGATE = block(LlamaModModBlocks.BLUELARGETILEFENCEGATE);
		BLUELARGETILEPRESSUREPLATE = block(LlamaModModBlocks.BLUELARGETILEPRESSUREPLATE);
		BLUELARGETILEBUTTON = block(LlamaModModBlocks.BLUELARGETILEBUTTON);
		PURPLELARGETILESTAIR = block(LlamaModModBlocks.PURPLELARGETILESTAIR);
		PURPLELARGETILESLAB = block(LlamaModModBlocks.PURPLELARGETILESLAB);
		PURPLELARGETILEWALL = block(LlamaModModBlocks.PURPLELARGETILEWALL);
		PURPLELARGETILEFENCE = block(LlamaModModBlocks.PURPLELARGETILEFENCE);
		PURPLELARGETILEFENCEGATE = block(LlamaModModBlocks.PURPLELARGETILEFENCEGATE);
		PURPLELARGETILEPRESSUREPLATE = block(LlamaModModBlocks.PURPLELARGETILEPRESSUREPLATE);
		PURPLELARGETILEBUTTON = block(LlamaModModBlocks.PURPLELARGETILEBUTTON);
		MAGENTALARGETILESTAIR = block(LlamaModModBlocks.MAGENTALARGETILESTAIR);
		MAGENTALARGETILESLAB = block(LlamaModModBlocks.MAGENTALARGETILESLAB);
		MAGENTALARGETILEWALL = block(LlamaModModBlocks.MAGENTALARGETILEWALL);
		MAGENTALARGETILEFENCE = block(LlamaModModBlocks.MAGENTALARGETILEFENCE);
		MAGENTALARGETILEFENCEGATE = block(LlamaModModBlocks.MAGENTALARGETILEFENCEGATE);
		MAGENTALARGETILEPRESSUREPLATE = block(LlamaModModBlocks.MAGENTALARGETILEPRESSUREPLATE);
		MAGENTALARGETILEBUTTON = block(LlamaModModBlocks.MAGENTALARGETILEBUTTON);
		PINKLARGETILESTAIR = block(LlamaModModBlocks.PINKLARGETILESTAIR);
		PINKLARGETILESLAB = block(LlamaModModBlocks.PINKLARGETILESLAB);
		PINKLARGETILEWALL = block(LlamaModModBlocks.PINKLARGETILEWALL);
		PINKLARGETILEFENCE = block(LlamaModModBlocks.PINKLARGETILEFENCE);
		PINKLARGETILEFENCEGATE = block(LlamaModModBlocks.PINKLARGETILEFENCEGATE);
		PINKLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.PINKLARGETILEPRESSUREPLATE);
		PINKLARGETILEBUTTON = block(LlamaModModBlocks.PINKLARGETILEBUTTON);
		CEILINGTILEFENCE = block(LlamaModModBlocks.CEILINGTILEFENCE);
		CEILINGTILEFENCEGATE = block(LlamaModModBlocks.CEILINGTILEFENCEGATE);
		TILEFENCE = block(LlamaModModBlocks.TILEFENCE, new Item.Properties().fireResistant());
		TILEFENCEGATE = block(LlamaModModBlocks.TILEFENCEGATE, new Item.Properties().fireResistant());
		INDUSTRIALLARGETILE = block(LlamaModModBlocks.INDUSTRIALLARGETILE);
		INDUSTRIALLARGETILESTAIR = block(LlamaModModBlocks.INDUSTRIALLARGETILESTAIR);
		INDUSTRIALLARGETILESLAB = block(LlamaModModBlocks.INDUSTRIALLARGETILESLAB);
		INDUSTRIALLARGETILEWALL = block(LlamaModModBlocks.INDUSTRIALLARGETILEWALL);
		INDUSTRIALLARGETILEFENCE = block(LlamaModModBlocks.INDUSTRIALLARGETILEFENCE);
		INDUSTRIALLARGETILEFENCEGATE = block(LlamaModModBlocks.INDUSTRIALLARGETILEFENCEGATE);
		INDUSTRIALLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.INDUSTRIALLARGETILEPRESSUREPLATE);
		INDUSTRIALLARGETILEBUTTON = block(LlamaModModBlocks.INDUSTRIALLARGETILEBUTTON);
		WHITELARGETILETRAPDOOR = block(LlamaModModBlocks.WHITELARGETILETRAPDOOR);
		INDUSTRIALLARGETILETRAPDOOR = block(LlamaModModBlocks.INDUSTRIALLARGETILETRAPDOOR);
		LIGHTGRAYLARGETILETRAPDOOR = block(LlamaModModBlocks.LIGHTGRAYLARGETILETRAPDOOR);
		GRAYLARGETILETRAPDOOR = block(LlamaModModBlocks.GRAYLARGETILETRAPDOOR);
		BLACKLARGETILETRAPDOOR = block(LlamaModModBlocks.BLACKLARGETILETRAPDOOR);
		BROWNLARGETILETRAPDOOR = block(LlamaModModBlocks.BROWNLARGETILETRAPDOOR);
		REDLARGETILETRAPDOOR = block(LlamaModModBlocks.REDLARGETILETRAPDOOR);
		ORANGELARGETILETRAPDOOR = block(LlamaModModBlocks.ORANGELARGETILETRAPDOOR);
		YELLOWLARGETILETRAPDOOR = block(LlamaModModBlocks.YELLOWLARGETILETRAPDOOR);
		LIMELARGETILETRAPDOOR = block(LlamaModModBlocks.LIMELARGETILETRAPDOOR);
		GREENLARGETILETRAPDOOR = block(LlamaModModBlocks.GREENLARGETILETRAPDOOR);
		CYANLARGETILETRAPDOOR = block(LlamaModModBlocks.CYANLARGETILETRAPDOOR);
		LIGHTBLUELARGETILETRAPDOOR = block(LlamaModModBlocks.LIGHTBLUELARGETILETRAPDOOR);
		BLUELARGETILETRAPDOOR = block(LlamaModModBlocks.BLUELARGETILETRAPDOOR);
		PURPLELARGETILETRAPDOOR = block(LlamaModModBlocks.PURPLELARGETILETRAPDOOR);
		MAGENTALARGETILETRAPDOOR = block(LlamaModModBlocks.MAGENTALARGETILETRAPDOOR);
		PINKLARGETILETRAPDOOR = block(LlamaModModBlocks.PINKLARGETILETRAPDOOR);
		WHITEBRICKTRAPDOOR = block(LlamaModModBlocks.WHITEBRICKTRAPDOOR);
		LIGHTGRAYBRICKTRAPDOOR = block(LlamaModModBlocks.LIGHTGRAYBRICKTRAPDOOR);
		GRAYBRICKTRAPDOOR = block(LlamaModModBlocks.GRAYBRICKTRAPDOOR);
		BLACKBRICKTRAPDOOR = block(LlamaModModBlocks.BLACKBRICKTRAPDOOR);
		BROWNBRICKTRAPDOOR = block(LlamaModModBlocks.BROWNBRICKTRAPDOOR);
		REDBRICKTRAPDOOR = block(LlamaModModBlocks.REDBRICKTRAPDOOR);
		ORANGEBRICKTRAPDOOR = block(LlamaModModBlocks.ORANGEBRICKTRAPDOOR);
		YELLOWBRICKTRAPDOOR = block(LlamaModModBlocks.YELLOWBRICKTRAPDOOR);
		LIMEBRICKTRAPDOOR = block(LlamaModModBlocks.LIMEBRICKTRAPDOOR);
		GREENBRICKTRAPDOOR = block(LlamaModModBlocks.GREENBRICKTRAPDOOR);
		CYANBRICKTRAPDOOR = block(LlamaModModBlocks.CYANBRICKTRAPDOOR);
		LIGHTBLUEBRICKTRAPDOOR = block(LlamaModModBlocks.LIGHTBLUEBRICKTRAPDOOR);
		BLUEBRICKTRAPDOOR = block(LlamaModModBlocks.BLUEBRICKTRAPDOOR);
		PURPLEBRICKTRAPDOOR = block(LlamaModModBlocks.PURPLEBRICKTRAPDOOR);
		MAGENTABRICKTRAPDOOR = block(LlamaModModBlocks.MAGENTABRICKTRAPDOOR);
		PINKBRICKTRAPDOOR = block(LlamaModModBlocks.PINKBRICKTRAPDOOR);
		CHERRYBRICKTRAPDOOR = block(LlamaModModBlocks.CHERRYBRICKTRAPDOOR);
		INDUSTRIALBRICKTRAPDOOR = block(LlamaModModBlocks.INDUSTRIALBRICKTRAPDOOR);
		CEILINGTILETRAPDOOR = block(LlamaModModBlocks.CEILINGTILETRAPDOOR);
		TILETRAPDOOR = block(LlamaModModBlocks.TILETRAPDOOR);
		CHERRYLARGETILE = block(LlamaModModBlocks.CHERRYLARGETILE);
		CHERRYLARGETILESTAIR = block(LlamaModModBlocks.CHERRYLARGETILESTAIR);
		CHERRYLARGETILESLAB = block(LlamaModModBlocks.CHERRYLARGETILESLAB);
		CHERRYLARGETILEWALL = block(LlamaModModBlocks.CHERRYLARGETILEWALL);
		CHERRYLARGETILEFENCE = block(LlamaModModBlocks.CHERRYLARGETILEFENCE);
		CHERRYLARGETILEFENCEGATE = block(LlamaModModBlocks.CHERRYLARGETILEFENCEGATE);
		CHERRYLARGETILETRAPDOOR = block(LlamaModModBlocks.CHERRYLARGETILETRAPDOOR);
		CHERRYLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.CHERRYLARGETILEPRESSUREPLATE);
		CHERRYLARGETILEBUTTON = block(LlamaModModBlocks.CHERRYLARGETILEBUTTON);
		SECURESTORAGEBLOCK = block(LlamaModModBlocks.SECURESTORAGEBLOCK);
		TEALBRICKS = block(LlamaModModBlocks.TEALBRICKS);
		TEALLARGETILE = block(LlamaModModBlocks.TEALLARGETILE);
		TEALLARGETILESTAIR = block(LlamaModModBlocks.TEALLARGETILESTAIR);
		TEALLARGETILESLAB = block(LlamaModModBlocks.TEALLARGETILESLAB);
		TEALLARGETILEWALL = block(LlamaModModBlocks.TEALLARGETILEWALL);
		TEALLARGETILEFENCE = block(LlamaModModBlocks.TEALLARGETILEFENCE);
		TEALLARGETILEFENCEGATE = block(LlamaModModBlocks.TEALLARGETILEFENCEGATE);
		TEALLARGETILETRAPDOOR = block(LlamaModModBlocks.TEALLARGETILETRAPDOOR);
		TEALLARGETILEPRESSUREPLATE = block(LlamaModModBlocks.TEALLARGETILEPRESSUREPLATE);
		TEALLARGETILEBUTTON = block(LlamaModModBlocks.TEALLARGETILEBUTTON);
		TEALBRICKSTAIR = block(LlamaModModBlocks.TEALBRICKSTAIR);
		TEALBRICKSLAB = block(LlamaModModBlocks.TEALBRICKSLAB);
		TEALBRICKWALL = block(LlamaModModBlocks.TEALBRICKWALL);
		TEALBRICKFENCE = block(LlamaModModBlocks.TEALBRICKFENCE);
		TEALBRICKFENCEGATE = block(LlamaModModBlocks.TEALBRICKFENCEGATE);
		TEALBRICKTRAPDOOR = block(LlamaModModBlocks.TEALBRICKTRAPDOOR);
		TEALBRICKPRESSUREPLATE = block(LlamaModModBlocks.TEALBRICKPRESSUREPLATE);
		TEALBRICKBUTTON = block(LlamaModModBlocks.TEALBRICKBUTTON);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new BackpackInventoryCapability(stack), BACKPACK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new NetheritebackpackInventoryCapability(stack), NETHERITEBACKPACK.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), ACID_BUCKET.get());
	}
}