/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.llamamod.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import net.mcreator.llamamod.block.*;
import net.mcreator.llamamod.LlamaModMod;

import java.util.function.Function;

public class LlamaModModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(LlamaModMod.MODID);
	public static final DeferredBlock<Block> BANANA_PLANT;
	public static final DeferredBlock<Block> ACID;
	public static final DeferredBlock<Block> REDBRICKS;
	public static final DeferredBlock<Block> ORANGEBRICKS;
	public static final DeferredBlock<Block> YELLOWBRICKS;
	public static final DeferredBlock<Block> GREENBRICKS;
	public static final DeferredBlock<Block> LIGHTBLUEBRICKS;
	public static final DeferredBlock<Block> BLUEBRICKS;
	public static final DeferredBlock<Block> MAGENTABRICKS;
	public static final DeferredBlock<Block> PINKBRICKS;
	public static final DeferredBlock<Block> BROWNBRICKS;
	public static final DeferredBlock<Block> BLACKBRICKS;
	public static final DeferredBlock<Block> INDUSTRIALBRICKS;
	public static final DeferredBlock<Block> COMPUTER;
	public static final DeferredBlock<Block> TILES;
	public static final DeferredBlock<Block> CEILINGTILES;
	public static final DeferredBlock<Block> AUTHENTICATORBLOCK;
	public static final DeferredBlock<Block> REDBRICKSLAB;
	public static final DeferredBlock<Block> REDBRICKSTAIR;
	public static final DeferredBlock<Block> ORANGEBRICKSLAB;
	public static final DeferredBlock<Block> ORANGEBRICKSTAIR;
	public static final DeferredBlock<Block> YELLOWBRICKSLAB;
	public static final DeferredBlock<Block> YELLOWBRICKSTAIR;
	public static final DeferredBlock<Block> LIGHTBLUEBRICKSLAB;
	public static final DeferredBlock<Block> LIGHTBLUEBRICKSTAIR;
	public static final DeferredBlock<Block> BLUEBRICKSLAB;
	public static final DeferredBlock<Block> BLUEBRICKSTAIR;
	public static final DeferredBlock<Block> MAGENTABRICKSLAB;
	public static final DeferredBlock<Block> MAGENTABRICKSTAIR;
	public static final DeferredBlock<Block> PINKBRICKSLAB;
	public static final DeferredBlock<Block> PINKBRICKSTAIR;
	public static final DeferredBlock<Block> BROWNBRICKSLAB;
	public static final DeferredBlock<Block> BROWNBRICKSTAIR;
	public static final DeferredBlock<Block> BLACKBRICKSLAB;
	public static final DeferredBlock<Block> BLACKBRICKSTAIR;
	public static final DeferredBlock<Block> INDUSTRIALBRICKSLAB;
	public static final DeferredBlock<Block> INDUSTRIALBRICKSTAIR;
	public static final DeferredBlock<Block> TILESLAB;
	public static final DeferredBlock<Block> TILESTAIR;
	public static final DeferredBlock<Block> CEILINGTILESLAB;
	public static final DeferredBlock<Block> CEILINGTILESTAIR;
	public static final DeferredBlock<Block> WHITEBRICKS;
	public static final DeferredBlock<Block> LIGHTGRAYBRICKS;
	public static final DeferredBlock<Block> GRAYBRICKS;
	public static final DeferredBlock<Block> LIMEBRICKS;
	public static final DeferredBlock<Block> CYANBRICKS;
	public static final DeferredBlock<Block> CHERRYBRICKS;
	public static final DeferredBlock<Block> PURPLEBRICKS;
	public static final DeferredBlock<Block> LIMEBRICKSLAB;
	public static final DeferredBlock<Block> LIMEBRICKSTAIR;
	public static final DeferredBlock<Block> GREENBRICKSSLAB;
	public static final DeferredBlock<Block> GREENBRICKSSTAIR;
	public static final DeferredBlock<Block> CYANBRICKSLAB;
	public static final DeferredBlock<Block> CYANBRICKSTAIR;
	public static final DeferredBlock<Block> PURPLEBRICKSLAB;
	public static final DeferredBlock<Block> PURPLEBRICKSTAIR;
	public static final DeferredBlock<Block> WHITEBRICKSLAB;
	public static final DeferredBlock<Block> WHITEBRICKSTAIR;
	public static final DeferredBlock<Block> LIGHTGRAYBRICKSLAB;
	public static final DeferredBlock<Block> LIGHTGRAYBRICKSTAIR;
	public static final DeferredBlock<Block> GRAYBRICKSLAB;
	public static final DeferredBlock<Block> GRAYBRICKSTAIR;
	public static final DeferredBlock<Block> CHERRYBRICKSLAB;
	public static final DeferredBlock<Block> CHERRYBRICKSTAIR;
	public static final DeferredBlock<Block> REDBRICKWALL;
	public static final DeferredBlock<Block> ORANGEBRICKWALL;
	public static final DeferredBlock<Block> YELLOWBRICKWALL;
	public static final DeferredBlock<Block> GREENBRICKWALL;
	public static final DeferredBlock<Block> LIGHTBLUEBRICKWALL;
	public static final DeferredBlock<Block> BLUEBRICKWALL;
	public static final DeferredBlock<Block> MAGENTABRICKWALL;
	public static final DeferredBlock<Block> PINKBRICKWALL;
	public static final DeferredBlock<Block> BROWNBRICKWALL;
	public static final DeferredBlock<Block> BLACKBRICKWALL;
	public static final DeferredBlock<Block> INDUSTRIALBRICKWALL;
	public static final DeferredBlock<Block> WHITEBRICKWALL;
	public static final DeferredBlock<Block> LIGHTGRAYBRICKWALL;
	public static final DeferredBlock<Block> GRAYBRICKWALL;
	public static final DeferredBlock<Block> LIMEBRICKWALL;
	public static final DeferredBlock<Block> CYANBRICKWALL;
	public static final DeferredBlock<Block> CHERRYBRICKWALL;
	public static final DeferredBlock<Block> PURPLEBRICKWALL;
	public static final DeferredBlock<Block> CEILINGTILEWALL;
	public static final DeferredBlock<Block> TILEWALL;
	public static final DeferredBlock<Block> INDUSTRIALBRICKFENCE;
	public static final DeferredBlock<Block> INDUSTRIALBRICKFENCEGATE;
	public static final DeferredBlock<Block> INDUSTRIALBRICKBUTTON;
	public static final DeferredBlock<Block> INDUSTRIALBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> REDBRICKFENCE;
	public static final DeferredBlock<Block> ORANGEBRICKFENCE;
	public static final DeferredBlock<Block> YELLOWBRICKFENCE;
	public static final DeferredBlock<Block> GREENBRICKFENCE;
	public static final DeferredBlock<Block> LIGHTBLUEBRICKFENCE;
	public static final DeferredBlock<Block> BLUEBRICKFENCE;
	public static final DeferredBlock<Block> MAGENTABRICKFENCE;
	public static final DeferredBlock<Block> PINKBRICKFENCE;
	public static final DeferredBlock<Block> BROWNBRICKFENCE;
	public static final DeferredBlock<Block> BLACKBRICKFENCE;
	public static final DeferredBlock<Block> WHITEBRICKFENCE;
	public static final DeferredBlock<Block> LIGHTGRAYBRICKFENCE;
	public static final DeferredBlock<Block> GRAYBRICKFENCE;
	public static final DeferredBlock<Block> LIMEBRICKFENCE;
	public static final DeferredBlock<Block> CYANBRICKFENCE;
	public static final DeferredBlock<Block> PURPLEBRICKFENCE;
	public static final DeferredBlock<Block> CHERRYBRICKFENCE;
	public static final DeferredBlock<Block> REDBRICKFENCEGATE;
	public static final DeferredBlock<Block> ORANGEBRICKFENCEGATE;
	public static final DeferredBlock<Block> YELLOWBRICKFENCEAGTE;
	public static final DeferredBlock<Block> GREENBRICKFENCEGATE;
	public static final DeferredBlock<Block> LIGHTBLUEBRICKFENCEGATE;
	public static final DeferredBlock<Block> BLUEBRICKFENCEGATE;
	public static final DeferredBlock<Block> MAGENTABRICKFENCEGATE;
	public static final DeferredBlock<Block> PINKBRICKFENCEGATE;
	public static final DeferredBlock<Block> BROWNBRICKFENCEGATE;
	public static final DeferredBlock<Block> BLACKBRICKFENCEGATE;
	public static final DeferredBlock<Block> WHITEBRICKFENCEGATE;
	public static final DeferredBlock<Block> LIGHTGRAYBRICKFENCEGATE;
	public static final DeferredBlock<Block> GRAYBRICKFENCEGATE;
	public static final DeferredBlock<Block> LIMEBRICKFENCEGATE;
	public static final DeferredBlock<Block> CYANBRICKFENCEGATE;
	public static final DeferredBlock<Block> PURPLEBRICKFENCEGATE;
	public static final DeferredBlock<Block> CHERRYBRICKFENCEGATE;
	public static final DeferredBlock<Block> REDBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> ORANGEBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> YELLOWBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> GREENBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> LIGHTBLUEBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> BLUEBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> MAGENTABRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> PINKBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> BROWNBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> BLACKBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> WHITEBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> LIGHTGRAYBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> GRAYBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> LIMEBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> CYANBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> PURPLEBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> CHERRYBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> REDBRICKBUTTON;
	public static final DeferredBlock<Block> ORANGEBRICKBUTTON;
	public static final DeferredBlock<Block> YELLOWBRICKBUTTON;
	public static final DeferredBlock<Block> GREENBRICKBUTTON;
	public static final DeferredBlock<Block> LIGHTBLUEBRICKBUTTON;
	public static final DeferredBlock<Block> BLUEBRICKBUTTON;
	public static final DeferredBlock<Block> MAGENTABRICKBUTTON;
	public static final DeferredBlock<Block> PINKBRICKBUTTON;
	public static final DeferredBlock<Block> BROWNBRICKBUTTON;
	public static final DeferredBlock<Block> BLACKBRICKBUTTON;
	public static final DeferredBlock<Block> WHITEBRICKBUTTON;
	public static final DeferredBlock<Block> LIGHTGRAYBRICKBUTTON;
	public static final DeferredBlock<Block> GRAYBRICKBUTTON;
	public static final DeferredBlock<Block> LIMEBRICKBUTTON;
	public static final DeferredBlock<Block> CYANBRICKBUTTON;
	public static final DeferredBlock<Block> PURPLEBRICKBUTTON;
	public static final DeferredBlock<Block> CHERRYBRICKBUTTON;
	public static final DeferredBlock<Block> TILEPRESSUREPLATE;
	public static final DeferredBlock<Block> TILEBUTTON;
	public static final DeferredBlock<Block> CEILINGTILEPRESSUREPLATE;
	public static final DeferredBlock<Block> CEILINGTILEBUTTON;
	public static final DeferredBlock<Block> WHITELARGETILE;
	public static final DeferredBlock<Block> WHITELARGETILESTAIR;
	public static final DeferredBlock<Block> WHITELARGETILESLAB;
	public static final DeferredBlock<Block> WHITELARGETILEWALL;
	public static final DeferredBlock<Block> WHITELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> WHITELARGETILEBUTTON;
	public static final DeferredBlock<Block> VARIABLELIGHT;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILE;
	public static final DeferredBlock<Block> GRAYLARGETILE;
	public static final DeferredBlock<Block> BLACKLARGETILE;
	public static final DeferredBlock<Block> ORANGELARGETILE;
	public static final DeferredBlock<Block> MAGENTALARGETILE;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILE;
	public static final DeferredBlock<Block> BLUELARGETILE;
	public static final DeferredBlock<Block> YELLOWLARGETILE;
	public static final DeferredBlock<Block> LIMELARGETILE;
	public static final DeferredBlock<Block> GREENLARGETILE;
	public static final DeferredBlock<Block> PINKLARGETILE;
	public static final DeferredBlock<Block> CYANLARGETILE;
	public static final DeferredBlock<Block> PURPLELARGETILE;
	public static final DeferredBlock<Block> BROWNLARGETILE;
	public static final DeferredBlock<Block> REDLARGETILE;
	public static final DeferredBlock<Block> LARGETILEFENCE;
	public static final DeferredBlock<Block> LARGETILEFENCEGATE;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILESTAIR;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILESLAB;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEWALL;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEFENCE;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEBUTTON;
	public static final DeferredBlock<Block> GRAYLARGETILESTAIR;
	public static final DeferredBlock<Block> GRAYLARGETILESLAB;
	public static final DeferredBlock<Block> GRAYLARGETILEWALL;
	public static final DeferredBlock<Block> GRAYLARGETILEFENCE;
	public static final DeferredBlock<Block> GRAYLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> GRAYLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> GRAYLARGETILEBUTTON;
	public static final DeferredBlock<Block> BLACKLARGETILESTAIR;
	public static final DeferredBlock<Block> BLACKLARGETILESLAB;
	public static final DeferredBlock<Block> BLACKLARGETILEWALL;
	public static final DeferredBlock<Block> BLACKLARGETILEFENCE;
	public static final DeferredBlock<Block> BLACKLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> BLACKLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> BLACKLARGETILEBUTTON;
	public static final DeferredBlock<Block> BROWNLARGETILESTAIR;
	public static final DeferredBlock<Block> BROWNLARGETILESLAB;
	public static final DeferredBlock<Block> BROWNLARGETILEWALL;
	public static final DeferredBlock<Block> BROWNLARGETILEFENCE;
	public static final DeferredBlock<Block> BROWNLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> BROWNLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> BROWNLARGETILEBUTTON;
	public static final DeferredBlock<Block> REDLARGETILESTAIR;
	public static final DeferredBlock<Block> REDLARGETILESLAB;
	public static final DeferredBlock<Block> REDLARGETILEWALL;
	public static final DeferredBlock<Block> REDLARGETILEFENCE;
	public static final DeferredBlock<Block> REDLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> REDLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> REDLARGETILEBUTTON;
	public static final DeferredBlock<Block> ORANGELARGETILESTAIR;
	public static final DeferredBlock<Block> ORANGELARGETILESLAB;
	public static final DeferredBlock<Block> ORANGELARGETILEWALL;
	public static final DeferredBlock<Block> ORANGELARGETILEFENCE;
	public static final DeferredBlock<Block> ORANGELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> ORANGELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> ORANGELARGETILEBUTTON;
	public static final DeferredBlock<Block> YELLOWLARGETILESTAIR;
	public static final DeferredBlock<Block> YELLOWLARGETILESLAB;
	public static final DeferredBlock<Block> YELLOWLARGETILEWALL;
	public static final DeferredBlock<Block> YELLOWLARGETILEFENCE;
	public static final DeferredBlock<Block> YELLOWLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> YELLOWLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> YELLOWLARGETILEBUTTON;
	public static final DeferredBlock<Block> LIMELARGETILESTAIR;
	public static final DeferredBlock<Block> LIMELARGETILESLAB;
	public static final DeferredBlock<Block> LIMELARGETILEWALL;
	public static final DeferredBlock<Block> LIMELARGETILEFENCE;
	public static final DeferredBlock<Block> LIMELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> LIMELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> LIMELARGETILEBUTTON;
	public static final DeferredBlock<Block> GREENLARGETILESTAIR;
	public static final DeferredBlock<Block> GREENLARGETILESLAB;
	public static final DeferredBlock<Block> GREENLARGETILEWALL;
	public static final DeferredBlock<Block> GREENLARGETILEFENCE;
	public static final DeferredBlock<Block> GREENLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> GREENLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> GREENLARGETILEBUTTON;
	public static final DeferredBlock<Block> CYANLARGETILESTAIR;
	public static final DeferredBlock<Block> CYANLARGETILESLAB;
	public static final DeferredBlock<Block> CYANLARGETILEWALL;
	public static final DeferredBlock<Block> CYANLARGETILEFENCE;
	public static final DeferredBlock<Block> CYANLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> CYANLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> CYANLARGETILEBUTTON;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILESTAIR;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILESLAB;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEWALL;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEFENCE;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEBUTTON;
	public static final DeferredBlock<Block> BLUELARGETILESTAIR;
	public static final DeferredBlock<Block> BLUELARGETILESLAB;
	public static final DeferredBlock<Block> BLUELARGETILEWALL;
	public static final DeferredBlock<Block> BLUELARGETILEFENCE;
	public static final DeferredBlock<Block> BLUELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> BLUELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> BLUELARGETILEBUTTON;
	public static final DeferredBlock<Block> PURPLELARGETILESTAIR;
	public static final DeferredBlock<Block> PURPLELARGETILESLAB;
	public static final DeferredBlock<Block> PURPLELARGETILEWALL;
	public static final DeferredBlock<Block> PURPLELARGETILEFENCE;
	public static final DeferredBlock<Block> PURPLELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> PURPLELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> PURPLELARGETILEBUTTON;
	public static final DeferredBlock<Block> MAGENTALARGETILESTAIR;
	public static final DeferredBlock<Block> MAGENTALARGETILESLAB;
	public static final DeferredBlock<Block> MAGENTALARGETILEWALL;
	public static final DeferredBlock<Block> MAGENTALARGETILEFENCE;
	public static final DeferredBlock<Block> MAGENTALARGETILEFENCEGATE;
	public static final DeferredBlock<Block> MAGENTALARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> MAGENTALARGETILEBUTTON;
	public static final DeferredBlock<Block> PINKLARGETILESTAIR;
	public static final DeferredBlock<Block> PINKLARGETILESLAB;
	public static final DeferredBlock<Block> PINKLARGETILEWALL;
	public static final DeferredBlock<Block> PINKLARGETILEFENCE;
	public static final DeferredBlock<Block> PINKLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> PINKLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> PINKLARGETILEBUTTON;
	public static final DeferredBlock<Block> CEILINGTILEFENCE;
	public static final DeferredBlock<Block> CEILINGTILEFENCEGATE;
	public static final DeferredBlock<Block> TILEFENCE;
	public static final DeferredBlock<Block> TILEFENCEGATE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILESTAIR;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILESLAB;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEWALL;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEFENCE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEBUTTON;
	public static final DeferredBlock<Block> WHITELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> GRAYLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> BLACKLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> BROWNLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> REDLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> ORANGELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> YELLOWLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> LIMELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> GREENLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> CYANLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> BLUELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> PURPLELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> MAGENTALARGETILETRAPDOOR;
	public static final DeferredBlock<Block> PINKLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> WHITEBRICKTRAPDOOR;
	public static final DeferredBlock<Block> LIGHTGRAYBRICKTRAPDOOR;
	public static final DeferredBlock<Block> GRAYBRICKTRAPDOOR;
	public static final DeferredBlock<Block> BLACKBRICKTRAPDOOR;
	public static final DeferredBlock<Block> BROWNBRICKTRAPDOOR;
	public static final DeferredBlock<Block> REDBRICKTRAPDOOR;
	public static final DeferredBlock<Block> ORANGEBRICKTRAPDOOR;
	public static final DeferredBlock<Block> YELLOWBRICKTRAPDOOR;
	public static final DeferredBlock<Block> LIMEBRICKTRAPDOOR;
	public static final DeferredBlock<Block> GREENBRICKTRAPDOOR;
	public static final DeferredBlock<Block> CYANBRICKTRAPDOOR;
	public static final DeferredBlock<Block> LIGHTBLUEBRICKTRAPDOOR;
	public static final DeferredBlock<Block> BLUEBRICKTRAPDOOR;
	public static final DeferredBlock<Block> PURPLEBRICKTRAPDOOR;
	public static final DeferredBlock<Block> MAGENTABRICKTRAPDOOR;
	public static final DeferredBlock<Block> PINKBRICKTRAPDOOR;
	public static final DeferredBlock<Block> CHERRYBRICKTRAPDOOR;
	public static final DeferredBlock<Block> INDUSTRIALBRICKTRAPDOOR;
	public static final DeferredBlock<Block> CEILINGTILETRAPDOOR;
	public static final DeferredBlock<Block> TILETRAPDOOR;
	public static final DeferredBlock<Block> CHERRYLARGETILE;
	public static final DeferredBlock<Block> CHERRYLARGETILESTAIR;
	public static final DeferredBlock<Block> CHERRYLARGETILESLAB;
	public static final DeferredBlock<Block> CHERRYLARGETILEWALL;
	public static final DeferredBlock<Block> CHERRYLARGETILEFENCE;
	public static final DeferredBlock<Block> CHERRYLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> CHERRYLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> CHERRYLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> CHERRYLARGETILEBUTTON;
	public static final DeferredBlock<Block> SECURESTORAGEBLOCK;
	public static final DeferredBlock<Block> TEALBRICKS;
	public static final DeferredBlock<Block> TEALLARGETILE;
	public static final DeferredBlock<Block> TEALLARGETILESTAIR;
	public static final DeferredBlock<Block> TEALLARGETILESLAB;
	public static final DeferredBlock<Block> TEALLARGETILEWALL;
	public static final DeferredBlock<Block> TEALLARGETILEFENCE;
	public static final DeferredBlock<Block> TEALLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> TEALLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> TEALLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> TEALLARGETILEBUTTON;
	public static final DeferredBlock<Block> TEALBRICKSTAIR;
	public static final DeferredBlock<Block> TEALBRICKSLAB;
	public static final DeferredBlock<Block> TEALBRICKWALL;
	public static final DeferredBlock<Block> TEALBRICKFENCE;
	public static final DeferredBlock<Block> TEALBRICKFENCEGATE;
	public static final DeferredBlock<Block> TEALBRICKTRAPDOOR;
	public static final DeferredBlock<Block> TEALBRICKPRESSUREPLATE;
	public static final DeferredBlock<Block> TEALBRICKBUTTON;
	static {
		BANANA_PLANT = register("banana_plant", BannanaplantBlock::new);
		ACID = register("acid", AcidBlock::new);
		REDBRICKS = register("redbricks", RedbricksBlock::new);
		ORANGEBRICKS = register("orangebricks", OrangebricksBlock::new);
		YELLOWBRICKS = register("yellowbricks", YellowbricksBlock::new);
		GREENBRICKS = register("greenbricks", GreenbricksBlock::new);
		LIGHTBLUEBRICKS = register("lightbluebricks", LightbluebricksBlock::new);
		BLUEBRICKS = register("bluebricks", BluebricksBlock::new);
		MAGENTABRICKS = register("magentabricks", MagentabricksBlock::new);
		PINKBRICKS = register("pinkbricks", PinkbricksBlock::new);
		BROWNBRICKS = register("brownbricks", BrownbricksBlock::new);
		BLACKBRICKS = register("blackbricks", BlackbricksBlock::new);
		INDUSTRIALBRICKS = register("industrialbricks", IndustrialbricksBlock::new);
		COMPUTER = register("computer", ComputerBlock::new);
		TILES = register("tiles", TilesBlock::new);
		CEILINGTILES = register("ceilingtiles", CeilingtilesBlock::new);
		AUTHENTICATORBLOCK = register("authenticatorblock", AuthenticatorblockBlock::new);
		REDBRICKSLAB = register("redbrickslab", RedbrickslabBlock::new);
		REDBRICKSTAIR = register("redbrickstair", RedbrickstairBlock::new);
		ORANGEBRICKSLAB = register("orangebrickslab", OrangebrickslabBlock::new);
		ORANGEBRICKSTAIR = register("orangebrickstair", OrangebrickstairBlock::new);
		YELLOWBRICKSLAB = register("yellowbrickslab", YellowbrickslabBlock::new);
		YELLOWBRICKSTAIR = register("yellowbrickstair", YellowbrickstairBlock::new);
		LIGHTBLUEBRICKSLAB = register("lightbluebrickslab", LightbluebrickslabBlock::new);
		LIGHTBLUEBRICKSTAIR = register("lightbluebrickstair", LightbluebrickstairBlock::new);
		BLUEBRICKSLAB = register("bluebrickslab", BluebrickslabBlock::new);
		BLUEBRICKSTAIR = register("bluebrickstair", BluebrickstairBlock::new);
		MAGENTABRICKSLAB = register("magentabrickslab", MagentabrickslabBlock::new);
		MAGENTABRICKSTAIR = register("magentabrickstair", MagentabrickstairBlock::new);
		PINKBRICKSLAB = register("pinkbrickslab", PinkbrickslabBlock::new);
		PINKBRICKSTAIR = register("pinkbrickstair", PinkbrickstairBlock::new);
		BROWNBRICKSLAB = register("brownbrickslab", BrownbrickslabBlock::new);
		BROWNBRICKSTAIR = register("brownbrickstair", BrownbrickstairBlock::new);
		BLACKBRICKSLAB = register("blackbrickslab", BlackbrickslabBlock::new);
		BLACKBRICKSTAIR = register("blackbrickstair", BlackbrickstairBlock::new);
		INDUSTRIALBRICKSLAB = register("industrialbrickslab", IndustrialbrickslabBlock::new);
		INDUSTRIALBRICKSTAIR = register("industrialbrickstair", IndustrialbrickstairBlock::new);
		TILESLAB = register("tileslab", TileslabBlock::new);
		TILESTAIR = register("tilestair", TilestairBlock::new);
		CEILINGTILESLAB = register("ceilingtileslab", CeilingtileslabBlock::new);
		CEILINGTILESTAIR = register("ceilingtilestair", CeilingtilestairBlock::new);
		WHITEBRICKS = register("whitebricks", WhitebricksBlock::new);
		LIGHTGRAYBRICKS = register("lightgraybricks", LightGrayBricksBlock::new);
		GRAYBRICKS = register("graybricks", GrayBricksBlock::new);
		LIMEBRICKS = register("limebricks", LimeBricksBlock::new);
		CYANBRICKS = register("cyanbricks", CyanBricksBlock::new);
		CHERRYBRICKS = register("cherrybricks", CherryBricksBlock::new);
		PURPLEBRICKS = register("purplebricks", PurpleBricksNewBlock::new);
		LIMEBRICKSLAB = register("limebrickslab", LimeBrickSlabBlock::new);
		LIMEBRICKSTAIR = register("limebrickstair", LimeBrickStairBlock::new);
		GREENBRICKSSLAB = register("greenbricksslab", GreenbricksSlabBlock::new);
		GREENBRICKSSTAIR = register("greenbricksstair", GreenbricksstairBlock::new);
		CYANBRICKSLAB = register("cyanbrickslab", CyanbrickslabBlock::new);
		CYANBRICKSTAIR = register("cyanbrickstair", CyanbrickstairBlock::new);
		PURPLEBRICKSLAB = register("purplebrickslab", PurplebrickslabBlock::new);
		PURPLEBRICKSTAIR = register("purplebrickstair", PurplebrickstairBlock::new);
		WHITEBRICKSLAB = register("whitebrickslab", WhitebrickslabBlock::new);
		WHITEBRICKSTAIR = register("whitebrickstair", WhitebrickstairBlock::new);
		LIGHTGRAYBRICKSLAB = register("lightgraybrickslab", LightgraybrickslabBlock::new);
		LIGHTGRAYBRICKSTAIR = register("lightgraybrickstair", LightgraybrickstairBlock::new);
		GRAYBRICKSLAB = register("graybrickslab", GraybrickslabBlock::new);
		GRAYBRICKSTAIR = register("graybrickstair", GraybrickstairBlock::new);
		CHERRYBRICKSLAB = register("cherrybrickslab", CherrybrickslabBlock::new);
		CHERRYBRICKSTAIR = register("cherrybrickstair", CherrybrickstairBlock::new);
		REDBRICKWALL = register("redbrickwall", RedbrickwallBlock::new);
		ORANGEBRICKWALL = register("orangebrickwall", OrangebrickwallBlock::new);
		YELLOWBRICKWALL = register("yellowbrickwall", YellowbrickwallBlock::new);
		GREENBRICKWALL = register("greenbrickwall", GreenbrickwallBlock::new);
		LIGHTBLUEBRICKWALL = register("lightbluebrickwall", LightbluebrickwallBlock::new);
		BLUEBRICKWALL = register("bluebrickwall", BluebrickwallBlock::new);
		MAGENTABRICKWALL = register("magentabrickwall", MagentabrickwallBlock::new);
		PINKBRICKWALL = register("pinkbrickwall", PinkbrickwallBlock::new);
		BROWNBRICKWALL = register("brownbrickwall", BrownbrickwallBlock::new);
		BLACKBRICKWALL = register("blackbrickwall", BlackbrickwallBlock::new);
		INDUSTRIALBRICKWALL = register("industrialbrickwall", IndustrialbrickwallBlock::new);
		WHITEBRICKWALL = register("whitebrickwall", WhitebrickwallBlock::new);
		LIGHTGRAYBRICKWALL = register("lightgraybrickwall", LightgraybrickwallBlock::new);
		GRAYBRICKWALL = register("graybrickwall", GraybrickwallBlock::new);
		LIMEBRICKWALL = register("limebrickwall", LimebrickwallBlock::new);
		CYANBRICKWALL = register("cyanbrickwall", CyanbrickwallBlock::new);
		CHERRYBRICKWALL = register("cherrybrickwall", CherrybrickwallBlock::new);
		PURPLEBRICKWALL = register("purplebrickwall", PurplebrickwallBlock::new);
		CEILINGTILEWALL = register("ceilingtilewall", CeilingtilewallBlock::new);
		TILEWALL = register("tilewall", TilewallBlock::new);
		INDUSTRIALBRICKFENCE = register("industrialbrickfence", IndustrialbrickfenceBlock::new);
		INDUSTRIALBRICKFENCEGATE = register("industrialbrickfencegate", IndustrialbrickfencegateBlock::new);
		INDUSTRIALBRICKBUTTON = register("industrialbrickbutton", IndustrialbrickbuttonBlock::new);
		INDUSTRIALBRICKPRESSUREPLATE = register("industrialbrickpressureplate", IndustrialbrickpreasureplateBlock::new);
		REDBRICKFENCE = register("redbrickfence", RedbrickfenceBlock::new);
		ORANGEBRICKFENCE = register("orangebrickfence", OrangebrickfenceBlock::new);
		YELLOWBRICKFENCE = register("yellowbrickfence", YellowbrickfenceBlock::new);
		GREENBRICKFENCE = register("greenbrickfence", GreenbrickfenceBlock::new);
		LIGHTBLUEBRICKFENCE = register("lightbluebrickfence", LightbluebrickfenceBlock::new);
		BLUEBRICKFENCE = register("bluebrickfence", BluebrickfenceBlock::new);
		MAGENTABRICKFENCE = register("magentabrickfence", MagentabrickfenceBlock::new);
		PINKBRICKFENCE = register("pinkbrickfence", PinkbrickfenceBlock::new);
		BROWNBRICKFENCE = register("brownbrickfence", BrownbrickfenceBlock::new);
		BLACKBRICKFENCE = register("blackbrickfence", BlackbrickfenceBlock::new);
		WHITEBRICKFENCE = register("whitebrickfence", WhitebrickfenceBlock::new);
		LIGHTGRAYBRICKFENCE = register("lightgraybrickfence", LightgraybrickfenceBlock::new);
		GRAYBRICKFENCE = register("graybrickfence", GraybrickfenceBlock::new);
		LIMEBRICKFENCE = register("limebrickfence", LimebrickfenceBlock::new);
		CYANBRICKFENCE = register("cyanbrickfence", CyanbrickfenceBlock::new);
		PURPLEBRICKFENCE = register("purplebrickfence", PurplebrickfenceBlock::new);
		CHERRYBRICKFENCE = register("cherrybrickfence", CherrybrickfenceBlock::new);
		REDBRICKFENCEGATE = register("redbrickfencegate", RedbrickfencegateBlock::new);
		ORANGEBRICKFENCEGATE = register("orangebrickfencegate", OrangebrickfencegateBlock::new);
		YELLOWBRICKFENCEAGTE = register("yellowbrickfenceagte", YellowbrickfenceagteBlock::new);
		GREENBRICKFENCEGATE = register("greenbrickfencegate", GreenbrickfencegateBlock::new);
		LIGHTBLUEBRICKFENCEGATE = register("lightbluebrickfencegate", LightbluebrickfencegateBlock::new);
		BLUEBRICKFENCEGATE = register("bluebrickfencegate", BluebrickfencegateBlock::new);
		MAGENTABRICKFENCEGATE = register("magentabrickfencegate", MagentabrickfencegateBlock::new);
		PINKBRICKFENCEGATE = register("pinkbrickfencegate", PinkbrickfencegateBlock::new);
		BROWNBRICKFENCEGATE = register("brownbrickfencegate", BrownbrickfencegateBlock::new);
		BLACKBRICKFENCEGATE = register("blackbrickfencegate", BlackbrickfencegateBlock::new);
		WHITEBRICKFENCEGATE = register("whitebrickfencegate", WhitebrickfencegateBlock::new);
		LIGHTGRAYBRICKFENCEGATE = register("lightgraybrickfencegate", LightgraybrickfencegateBlock::new);
		GRAYBRICKFENCEGATE = register("graybrickfencegate", GraybrickfencegateBlock::new);
		LIMEBRICKFENCEGATE = register("limebrickfencegate", LimebrickfencegateBlock::new);
		CYANBRICKFENCEGATE = register("cyanbrickfencegate", CyanbrickfencegateBlock::new);
		PURPLEBRICKFENCEGATE = register("purplebrickfencegate", PurplebrickfencegateBlock::new);
		CHERRYBRICKFENCEGATE = register("cherrybrickfencegate", CherrybrickfencegateBlock::new);
		REDBRICKPRESSUREPLATE = register("redbrickpressureplate", RedbrickpreasureplateBlock::new);
		ORANGEBRICKPRESSUREPLATE = register("orangebrickpressureplate", OrangebrickfencegatepreasureplateBlock::new);
		YELLOWBRICKPRESSUREPLATE = register("yellowbrickpressureplate", YellowbrickfenceagtepreasureplateBlock::new);
		GREENBRICKPRESSUREPLATE = register("greenbrickpressureplate", GreenbrickpreasureplateBlock::new);
		LIGHTBLUEBRICKPRESSUREPLATE = register("lightbluebrickpressureplate", LightbluebrickpreasureplateBlock::new);
		BLUEBRICKPRESSUREPLATE = register("bluebrickpressureplate", BluebrickpreasureplateBlock::new);
		MAGENTABRICKPRESSUREPLATE = register("magentabrickpressureplate", MagentabrickpreasureplateBlock::new);
		PINKBRICKPRESSUREPLATE = register("pinkbrickpressureplate", PinkbrickpreasureplateBlock::new);
		BROWNBRICKPRESSUREPLATE = register("brownbrickpressureplate", BrownbrickpreasureplateBlock::new);
		BLACKBRICKPRESSUREPLATE = register("blackbrickpressureplate", BlackbrickpreasureplateBlock::new);
		WHITEBRICKPRESSUREPLATE = register("whitebrickpressureplate", WhitebrickpreasureplateBlock::new);
		LIGHTGRAYBRICKPRESSUREPLATE = register("lightgraybrickpressureplate", LightgraybrickpreasureplateBlock::new);
		GRAYBRICKPRESSUREPLATE = register("graybrickpressureplate", GraybrickpreasureplateBlock::new);
		LIMEBRICKPRESSUREPLATE = register("limebrickpressureplate", LimebrickpreasureplateBlock::new);
		CYANBRICKPRESSUREPLATE = register("cyanbrickpressureplate", CyanbrickpreasureplateBlock::new);
		PURPLEBRICKPRESSUREPLATE = register("purplebrickpressureplate", PurplebrickpreasureplateBlock::new);
		CHERRYBRICKPRESSUREPLATE = register("cherrybrickpressureplate", CherrybrickpreasureplateBlock::new);
		REDBRICKBUTTON = register("redbrickbutton", RedbrickbuttonBlock::new);
		ORANGEBRICKBUTTON = register("orangebrickbutton", OrangebrickbuttonBlock::new);
		YELLOWBRICKBUTTON = register("yellowbrickbutton", YellowbrickbuttonBlock::new);
		GREENBRICKBUTTON = register("greenbrickbutton", GreenbrickbuttonBlock::new);
		LIGHTBLUEBRICKBUTTON = register("lightbluebrickbutton", LightbluebrickbuttonBlock::new);
		BLUEBRICKBUTTON = register("bluebrickbutton", BluebrickbuttonBlock::new);
		MAGENTABRICKBUTTON = register("magentabrickbutton", MagentabrickbuttonBlock::new);
		PINKBRICKBUTTON = register("pinkbrickbutton", PinkbrickbuttonBlock::new);
		BROWNBRICKBUTTON = register("brownbrickbutton", BrownbrickbuttonBlock::new);
		BLACKBRICKBUTTON = register("blackbrickbutton", BlackbrickbuttonBlock::new);
		WHITEBRICKBUTTON = register("whitebrickbutton", WhitebrickbuttonBlock::new);
		LIGHTGRAYBRICKBUTTON = register("lightgraybrickbutton", LightgraybrickbuttonBlock::new);
		GRAYBRICKBUTTON = register("graybrickbutton", GraybrickbuttonBlock::new);
		LIMEBRICKBUTTON = register("limebrickbutton", LimebrickbuttonBlock::new);
		CYANBRICKBUTTON = register("cyanbrickbutton", CyanbrickbuttonBlock::new);
		PURPLEBRICKBUTTON = register("purplebrickbutton", PurplebrickbuttonBlock::new);
		CHERRYBRICKBUTTON = register("cherrybrickbutton", CherrybrickbuttonBlock::new);
		TILEPRESSUREPLATE = register("tilepressureplate", TilepressureplateBlock::new);
		TILEBUTTON = register("tilebutton", TilebuttonBlock::new);
		CEILINGTILEPRESSUREPLATE = register("ceilingtilepressureplate", CeilingtilepressureplateBlock::new);
		CEILINGTILEBUTTON = register("ceilingtilebutton", CeilingtilebuttonBlock::new);
		WHITELARGETILE = register("whitelargetile", LargetileBlock::new);
		WHITELARGETILESTAIR = register("whitelargetilestair", LargetilestairBlock::new);
		WHITELARGETILESLAB = register("whitelargetileslab", LargetileslabBlock::new);
		WHITELARGETILEWALL = register("whitelargetilewall", LargetilewallBlock::new);
		WHITELARGETILEPRESSUREPLATE = register("whitelargetilepressureplate", LargetilepressureplateBlock::new);
		WHITELARGETILEBUTTON = register("whitelargetilebutton", LargetilebuttonBlock::new);
		VARIABLELIGHT = register("variablelight", VariablelightBlock::new);
		LIGHTGRAYLARGETILE = register("lightgraylargetile", LightGrayLargeTileBlock::new);
		GRAYLARGETILE = register("graylargetile", GrayLargeTileBlock::new);
		BLACKLARGETILE = register("blacklargetile", BlackLargeTileBlock::new);
		ORANGELARGETILE = register("orangelargetile", OrangeLargeTileBlock::new);
		MAGENTALARGETILE = register("magentalargetile", MagentaLargeTileBlock::new);
		LIGHTBLUELARGETILE = register("lightbluelargetile", LightBlueLargeTileBlock::new);
		BLUELARGETILE = register("bluelargetile", BlueLargeTileBlock::new);
		YELLOWLARGETILE = register("yellowlargetile", YellowLargeTileBlock::new);
		LIMELARGETILE = register("limelargetile", LimeLargeTileBlock::new);
		GREENLARGETILE = register("greenlargetile", GreenLargeTileBlock::new);
		PINKLARGETILE = register("pinklargetile", PinkLargeTileBlock::new);
		CYANLARGETILE = register("cyanlargetile", CyanLargeTileBlock::new);
		PURPLELARGETILE = register("purplelargetile", PurpleLargeTileBlock::new);
		BROWNLARGETILE = register("brownlargetile", BrownLargeTileBlock::new);
		REDLARGETILE = register("redlargetile", RedLargeTileBlock::new);
		LARGETILEFENCE = register("largetilefence", LargetilefenceBlock::new);
		LARGETILEFENCEGATE = register("largetilefencegate", LargetilefencegateBlock::new);
		LIGHTGRAYLARGETILESTAIR = register("lightgraylargetilestair", LightGrayLargeTileStairBlock::new);
		LIGHTGRAYLARGETILESLAB = register("lightgraylargetileslab", LightGrayLargeTileSlabBlock::new);
		LIGHTGRAYLARGETILEWALL = register("lightgraylargetilewall", LightGrayLargeTileWallBlock::new);
		LIGHTGRAYLARGETILEFENCE = register("lightgraylargetilefence", LightGrayLargeTileFenceBlock::new);
		LIGHTGRAYLARGETILEFENCEGATE = register("lightgraylargetilefencegate", LightGrayLargeTileFenceGateBlock::new);
		LIGHTGRAYLARGETILEPRESSUREPLATE = register("lightgraylargetilepressureplate", LightGrayLargeTilePressurePlateBlock::new);
		LIGHTGRAYLARGETILEBUTTON = register("lightgraylargetilebutton", LightGrayLargeTileButtonBlock::new);
		GRAYLARGETILESTAIR = register("graylargetilestair", GrayLargeTileStairBlock::new);
		GRAYLARGETILESLAB = register("graylargetileslab", GrayLargeTileSlabBlock::new);
		GRAYLARGETILEWALL = register("graylargetilewall", GrayLargeTileWallBlock::new);
		GRAYLARGETILEFENCE = register("graylargetilefence", GrayLargeTileFenceBlock::new);
		GRAYLARGETILEFENCEGATE = register("graylargetilefencegate", GrayLargeTileFenceGateBlock::new);
		GRAYLARGETILEPRESSUREPLATE = register("graylargetilepressureplate", GrayLargeTilePressurePlateBlock::new);
		GRAYLARGETILEBUTTON = register("graylargetilebutton", GrayLargeTileButtonBlock::new);
		BLACKLARGETILESTAIR = register("blacklargetilestair", BlackLargeTileStairBlock::new);
		BLACKLARGETILESLAB = register("blacklargetileslab", BlackLargeTileSlabBlock::new);
		BLACKLARGETILEWALL = register("blacklargetilewall", BlackLargeTileWallBlock::new);
		BLACKLARGETILEFENCE = register("blacklargetilefence", BlackLargeTileFenceBlock::new);
		BLACKLARGETILEFENCEGATE = register("blacklargetilefencegate", BlackLargeTileFenceGateBlock::new);
		BLACKLARGETILEPRESSUREPLATE = register("blacklargetilepressureplate", BlackLargeTilePressurePlateBlock::new);
		BLACKLARGETILEBUTTON = register("blacklargetilebutton", BlackLargeTileButtonBlock::new);
		BROWNLARGETILESTAIR = register("brownlargetilestair", BrownLargeTileStairBlock::new);
		BROWNLARGETILESLAB = register("brownlargetileslab", BrownLargeTileSlabBlock::new);
		BROWNLARGETILEWALL = register("brownlargetilewall", BrownLargeTileWallBlock::new);
		BROWNLARGETILEFENCE = register("brownlargetilefence", BrownLargeTileFenceBlock::new);
		BROWNLARGETILEFENCEGATE = register("brownlargetilefencegate", BrownLargeTileFenceGateBlock::new);
		BROWNLARGETILEPRESSUREPLATE = register("brownlargetilepressureplate", BrownLargeTilePressurePlateBlock::new);
		BROWNLARGETILEBUTTON = register("brownlargetilebutton", BrownLargeTileButtonBlock::new);
		REDLARGETILESTAIR = register("redlargetilestair", RedLargeTileStairBlock::new);
		REDLARGETILESLAB = register("redlargetileslab", RedLargeTileSlabBlock::new);
		REDLARGETILEWALL = register("redlargetilewall", RedLargeTileWallBlock::new);
		REDLARGETILEFENCE = register("redlargetilefence", RedLargeTileFenceBlock::new);
		REDLARGETILEFENCEGATE = register("redlargetilefencegate", RedLargeTileFenceGateBlock::new);
		REDLARGETILEPRESSUREPLATE = register("redlargetilepressureplate", RedLargeTilePressurePlateBlock::new);
		REDLARGETILEBUTTON = register("redlargetilebutton", RedLargeTileButtonBlock::new);
		ORANGELARGETILESTAIR = register("orangelargetilestair", OrangeLargeTileStairBlock::new);
		ORANGELARGETILESLAB = register("orangelargetileslab", OrangeLargeTileSlabBlock::new);
		ORANGELARGETILEWALL = register("orangelargetilewall", OrangeLargeTileWallBlock::new);
		ORANGELARGETILEFENCE = register("orangelargetilefence", OrangeLargeTileFenceBlock::new);
		ORANGELARGETILEFENCEGATE = register("orangelargetilefencegate", OrangeLargeTileFenceGateBlock::new);
		ORANGELARGETILEPRESSUREPLATE = register("orangelargetilepressureplate", OrangeLargeTilePressurePlateBlock::new);
		ORANGELARGETILEBUTTON = register("orangelargetilebutton", OrangeLargeTileButtonBlock::new);
		YELLOWLARGETILESTAIR = register("yellowlargetilestair", YellowLargeTileStairBlock::new);
		YELLOWLARGETILESLAB = register("yellowlargetileslab", YellowLargeTileSlabBlock::new);
		YELLOWLARGETILEWALL = register("yellowlargetilewall", YellowLargeTileWallBlock::new);
		YELLOWLARGETILEFENCE = register("yellowlargetilefence", YellowLargeTileFenceBlock::new);
		YELLOWLARGETILEFENCEGATE = register("yellowlargetilefencegate", YellowLargeTileFenceGateBlock::new);
		YELLOWLARGETILEPRESSUREPLATE = register("yellowlargetilepressureplate", YellowLargeTilePressurePlateBlock::new);
		YELLOWLARGETILEBUTTON = register("yellowlargetilebutton", YellowLargeTileButtonBlock::new);
		LIMELARGETILESTAIR = register("limelargetilestair", LimeLargeTileStairBlock::new);
		LIMELARGETILESLAB = register("limelargetileslab", LimeLargeTileSlabBlock::new);
		LIMELARGETILEWALL = register("limelargetilewall", LimeLargeTileWallBlock::new);
		LIMELARGETILEFENCE = register("limelargetilefence", LimeLargeTileFenceBlock::new);
		LIMELARGETILEFENCEGATE = register("limelargetilefencegate", LimeLargeTileFenceGateBlock::new);
		LIMELARGETILEPRESSUREPLATE = register("limelargetilepressureplate", LimeLargeTilePressurePlateBlock::new);
		LIMELARGETILEBUTTON = register("limelargetilebutton", LimeLargeTileButtonBlock::new);
		GREENLARGETILESTAIR = register("greenlargetilestair", GreenLargeTileStairBlock::new);
		GREENLARGETILESLAB = register("greenlargetileslab", GreenLargeTileSlabBlock::new);
		GREENLARGETILEWALL = register("greenlargetilewall", GreenLargeTileWallBlock::new);
		GREENLARGETILEFENCE = register("greenlargetilefence", GreenLargeTileFenceBlock::new);
		GREENLARGETILEFENCEGATE = register("greenlargetilefencegate", GreenLargeTileFenceGateBlock::new);
		GREENLARGETILEPRESSUREPLATE = register("greenlargetilepressureplate", GreenLargeTilePressurePlateBlock::new);
		GREENLARGETILEBUTTON = register("greenlargetilebutton", GreenLargeTileButtonBlock::new);
		CYANLARGETILESTAIR = register("cyanlargetilestair", CyanLargeTileStairBlock::new);
		CYANLARGETILESLAB = register("cyanlargetileslab", CyanLargeTileSlabBlock::new);
		CYANLARGETILEWALL = register("cyanlargetilewall", CyanLargeTileWallBlock::new);
		CYANLARGETILEFENCE = register("cyanlargetilefence", CyanLargeTileFenceBlock::new);
		CYANLARGETILEFENCEGATE = register("cyanlargetilefencegate", CyanLargeTileFenceGateBlock::new);
		CYANLARGETILEPRESSUREPLATE = register("cyanlargetilepressureplate", CyanLargeTilePressurePlateBlock::new);
		CYANLARGETILEBUTTON = register("cyanlargetilebutton", CyanLargeTileButtonBlock::new);
		LIGHTBLUELARGETILESTAIR = register("lightbluelargetilestair", LightBlueLargeTileStairBlock::new);
		LIGHTBLUELARGETILESLAB = register("lightbluelargetileslab", LightBlueLargeTileSlabBlock::new);
		LIGHTBLUELARGETILEWALL = register("lightbluelargetilewall", LightBlueLargeTileWallBlock::new);
		LIGHTBLUELARGETILEFENCE = register("lightbluelargetilefence", LightBlueLargeTileFenceBlock::new);
		LIGHTBLUELARGETILEFENCEGATE = register("lightbluelargetilefencegate", LightBlueLargeTileFenceGateBlock::new);
		LIGHTBLUELARGETILEPRESSUREPLATE = register("lightbluelargetilepressureplate", LightBlueLargeTilePressurePlateBlock::new);
		LIGHTBLUELARGETILEBUTTON = register("lightbluelargetilebutton", LightBlueLargeTileButtonBlock::new);
		BLUELARGETILESTAIR = register("bluelargetilestair", BlueLargeTileStairBlock::new);
		BLUELARGETILESLAB = register("bluelargetileslab", BlueLargeTileSlabBlock::new);
		BLUELARGETILEWALL = register("bluelargetilewall", BlueLargeTileWallBlock::new);
		BLUELARGETILEFENCE = register("bluelargetilefence", BlueLargeTileFenceBlock::new);
		BLUELARGETILEFENCEGATE = register("bluelargetilefencegate", BlueLargeTileFenceGateBlock::new);
		BLUELARGETILEPRESSUREPLATE = register("bluelargetilepressureplate", BlueLargeTilePressurePlateBlock::new);
		BLUELARGETILEBUTTON = register("bluelargetilebutton", BlueLargeTileButtonBlock::new);
		PURPLELARGETILESTAIR = register("purplelargetilestair", PurpleLargeTileStairBlock::new);
		PURPLELARGETILESLAB = register("purplelargetileslab", PurpleLargeTileSlabBlock::new);
		PURPLELARGETILEWALL = register("purplelargetilewall", PurpleLargeTileWallBlock::new);
		PURPLELARGETILEFENCE = register("purplelargetilefence", PurpleLargeTileFenceBlock::new);
		PURPLELARGETILEFENCEGATE = register("purplelargetilefencegate", PurpleLargeTileFenceGateBlock::new);
		PURPLELARGETILEPRESSUREPLATE = register("purplelargetilepressureplate", PurpleLargeTilePressurePlateBlock::new);
		PURPLELARGETILEBUTTON = register("purplelargetilebutton", PurpleLargeTileButtonBlock::new);
		MAGENTALARGETILESTAIR = register("magentalargetilestair", MagentaLargeTileStairBlock::new);
		MAGENTALARGETILESLAB = register("magentalargetileslab", MagentaLargeTileSlabBlock::new);
		MAGENTALARGETILEWALL = register("magentalargetilewall", MagentaLargeTileWallBlock::new);
		MAGENTALARGETILEFENCE = register("magentalargetilefence", MagentaLargeTileFenceBlock::new);
		MAGENTALARGETILEFENCEGATE = register("magentalargetilefencegate", MagentaLargeTileFenceGateBlock::new);
		MAGENTALARGETILEPRESSUREPLATE = register("magentalargetilepressureplate", MagentaLargeTilePressurePlateBlock::new);
		MAGENTALARGETILEBUTTON = register("magentalargetilebutton", MagentaLargeTileButtonBlock::new);
		PINKLARGETILESTAIR = register("pinklargetilestair", PinkLargeTileStairBlock::new);
		PINKLARGETILESLAB = register("pinklargetileslab", PinkLargeTileSlabBlock::new);
		PINKLARGETILEWALL = register("pinklargetilewall", PinkLargeTileWallBlock::new);
		PINKLARGETILEFENCE = register("pinklargetilefence", PinkLargeTileFenceBlock::new);
		PINKLARGETILEFENCEGATE = register("pinklargetilefencegate", PinkLargeTileFenceGateBlock::new);
		PINKLARGETILEPRESSUREPLATE = register("pinklargetilepressureplate", PinkLargeTilePressurePlateBlock::new);
		PINKLARGETILEBUTTON = register("pinklargetilebutton", PinkLargeTileButtonBlock::new);
		CEILINGTILEFENCE = register("ceilingtilefence", CeilingtilefenceBlock::new);
		CEILINGTILEFENCEGATE = register("ceilingtilefencegate", CeilingtilefencegateBlock::new);
		TILEFENCE = register("tilefence", TilefenceBlock::new);
		TILEFENCEGATE = register("tilefencegate", TilefencegateBlock::new);
		INDUSTRIALLARGETILE = register("industriallargetile", IndustrialLargeTileBlock::new);
		INDUSTRIALLARGETILESTAIR = register("industriallargetilestair", IndustrialLargeTileStairBlock::new);
		INDUSTRIALLARGETILESLAB = register("industriallargetileslab", IndustrialLargeTileSlabBlock::new);
		INDUSTRIALLARGETILEWALL = register("industriallargetilewall", IndustrialLargeTileWallBlock::new);
		INDUSTRIALLARGETILEFENCE = register("industriallargetilefence", IndustrialLargeTileFenceBlock::new);
		INDUSTRIALLARGETILEFENCEGATE = register("industriallargetilefencegate", IndustrialLargeTileFenceGateBlock::new);
		INDUSTRIALLARGETILEPRESSUREPLATE = register("industriallargetilepressureplate", IndustrialLargeTilePressurePlateBlock::new);
		INDUSTRIALLARGETILEBUTTON = register("industriallargetilebutton", IndustrialLargeTileButtonBlock::new);
		WHITELARGETILETRAPDOOR = register("whitelargetiletrapdoor", WhitelargetiletrapdoorBlock::new);
		INDUSTRIALLARGETILETRAPDOOR = register("industriallargetiletrapdoor", IndustriallargetiletrapdoorBlock::new);
		LIGHTGRAYLARGETILETRAPDOOR = register("lightgraylargetiletrapdoor", LightgraylargetiletrapdoorBlock::new);
		GRAYLARGETILETRAPDOOR = register("graylargetiletrapdoor", GraylargetiletrapdoorBlock::new);
		BLACKLARGETILETRAPDOOR = register("blacklargetiletrapdoor", BlacklargetiletrapdoorBlock::new);
		BROWNLARGETILETRAPDOOR = register("brownlargetiletrapdoor", BrownlargetiletrapdoorBlock::new);
		REDLARGETILETRAPDOOR = register("redlargetiletrapdoor", RedlargetiletrapdoorBlock::new);
		ORANGELARGETILETRAPDOOR = register("orangelargetiletrapdoor", OrangelargetiletrapdoorBlock::new);
		YELLOWLARGETILETRAPDOOR = register("yellowlargetiletrapdoor", YellowlargetiletrapdoorBlock::new);
		LIMELARGETILETRAPDOOR = register("limelargetiletrapdoor", LimelargetiletrapdoorBlock::new);
		GREENLARGETILETRAPDOOR = register("greenlargetiletrapdoor", GreenlargetiletrapdoorBlock::new);
		CYANLARGETILETRAPDOOR = register("cyanlargetiletrapdoor", CyanlargetiletrapdoorBlock::new);
		LIGHTBLUELARGETILETRAPDOOR = register("lightbluelargetiletrapdoor", LightbluelargetiletrapdoorBlock::new);
		BLUELARGETILETRAPDOOR = register("bluelargetiletrapdoor", BluelargetiletrapdoorBlock::new);
		PURPLELARGETILETRAPDOOR = register("purplelargetiletrapdoor", PurplelargetiletrapdoorBlock::new);
		MAGENTALARGETILETRAPDOOR = register("magentalargetiletrapdoor", MagentalargetiletrapdoorBlock::new);
		PINKLARGETILETRAPDOOR = register("pinklargetiletrapdoor", PinklargetiletrapdoorBlock::new);
		WHITEBRICKTRAPDOOR = register("whitebricktrapdoor", WhitebricktrapdoorBlock::new);
		LIGHTGRAYBRICKTRAPDOOR = register("lightgraybricktrapdoor", LightgraybricktrapdoorBlock::new);
		GRAYBRICKTRAPDOOR = register("graybricktrapdoor", GraybricktrapdoorBlock::new);
		BLACKBRICKTRAPDOOR = register("blackbricktrapdoor", BlackbricktrapdoorBlock::new);
		BROWNBRICKTRAPDOOR = register("brownbricktrapdoor", BrownbricktrapdoorBlock::new);
		REDBRICKTRAPDOOR = register("redbricktrapdoor", RedbricktrapdoorBlock::new);
		ORANGEBRICKTRAPDOOR = register("orangebricktrapdoor", OrangebricktrapdoorBlock::new);
		YELLOWBRICKTRAPDOOR = register("yellowbricktrapdoor", YellowbricktrapdoorBlock::new);
		LIMEBRICKTRAPDOOR = register("limebricktrapdoor", LimebricktrapdoorBlock::new);
		GREENBRICKTRAPDOOR = register("greenbricktrapdoor", GreenbricktrapdoorBlock::new);
		CYANBRICKTRAPDOOR = register("cyanbricktrapdoor", CyanbricktrapdoorBlock::new);
		LIGHTBLUEBRICKTRAPDOOR = register("lightbluebricktrapdoor", LightbluebricktrapdoorBlock::new);
		BLUEBRICKTRAPDOOR = register("bluebricktrapdoor", BluebricktrapdoorBlock::new);
		PURPLEBRICKTRAPDOOR = register("purplebricktrapdoor", PurplebricktrapdoorBlock::new);
		MAGENTABRICKTRAPDOOR = register("magentabricktrapdoor", MagentabricktrapdoorBlock::new);
		PINKBRICKTRAPDOOR = register("pinkbricktrapdoor", PinkbricktrapdoorBlock::new);
		CHERRYBRICKTRAPDOOR = register("cherrybricktrapdoor", CherrybricktrapdoorBlock::new);
		INDUSTRIALBRICKTRAPDOOR = register("industrialbricktrapdoor", IndustrialbricktrapdoorBlock::new);
		CEILINGTILETRAPDOOR = register("ceilingtiletrapdoor", CeilingtiletrapdoorBlock::new);
		TILETRAPDOOR = register("tiletrapdoor", TiletrapdoorBlock::new);
		CHERRYLARGETILE = register("cherrylargetile", CherrylargetileBlock::new);
		CHERRYLARGETILESTAIR = register("cherrylargetilestair", CherrylargetilestairBlock::new);
		CHERRYLARGETILESLAB = register("cherrylargetileslab", CherrylargetileslabBlock::new);
		CHERRYLARGETILEWALL = register("cherrylargetilewall", CherrylargetilewallBlock::new);
		CHERRYLARGETILEFENCE = register("cherrylargetilefence", CherrylargetilefenceBlock::new);
		CHERRYLARGETILEFENCEGATE = register("cherrylargetilefencegate", CherrylargetilefencegateBlock::new);
		CHERRYLARGETILETRAPDOOR = register("cherrylargetiletrapdoor", CherrylargetiletrapdoorBlock::new);
		CHERRYLARGETILEPRESSUREPLATE = register("cherrylargetilepressureplate", CherrylargetilepressureplateBlock::new);
		CHERRYLARGETILEBUTTON = register("cherrylargetilebutton", CherrylargetilebuttonBlock::new);
		SECURESTORAGEBLOCK = register("securestorageblock", SecurestorageblockBlock::new);
		TEALBRICKS = register("tealbricks", TealbricksBlock::new);
		TEALLARGETILE = register("teallargetile", TealLargeTileBlock::new);
		TEALLARGETILESTAIR = register("teallargetilestair", TealLargeTileStairBlock::new);
		TEALLARGETILESLAB = register("teallargetileslab", TeallargetileslabBlock::new);
		TEALLARGETILEWALL = register("teallargetilewall", TeallargetilewallBlock::new);
		TEALLARGETILEFENCE = register("teallargetilefence", TeallargetilefenceBlock::new);
		TEALLARGETILEFENCEGATE = register("teallargetilefencegate", TeallargetilefencegateBlock::new);
		TEALLARGETILETRAPDOOR = register("teallargetiletrapdoor", TeallargetiletrapdoorBlock::new);
		TEALLARGETILEPRESSUREPLATE = register("teallargetilepressureplate", TeallargetilepressureplateBlock::new);
		TEALLARGETILEBUTTON = register("teallargetilebutton", TeallargetilebuttonBlock::new);
		TEALBRICKSTAIR = register("tealbrickstair", TealbrickstairBlock::new);
		TEALBRICKSLAB = register("tealbrickslab", TealbrickslabBlock::new);
		TEALBRICKWALL = register("tealbrickwall", TealbrickwallBlock::new);
		TEALBRICKFENCE = register("tealbrickfence", TealbrickfenceBlock::new);
		TEALBRICKFENCEGATE = register("tealbrickfencegate", TealbrickfencegateBlock::new);
		TEALBRICKTRAPDOOR = register("tealbricktrapdoor", TealbricktrapdoorBlock::new);
		TEALBRICKPRESSUREPLATE = register("tealbrickpressureplate", TealbrickpressureplateBlock::new);
		TEALBRICKBUTTON = register("tealbrickbutton", TealbrickbuttonBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			BannanaplantBlock.blockColorLoad(event);
		}
	}
}