/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.ihavenowebsite.omegabird.llamamod.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.ihavenowebsite.omegabird.llamamod.item.inventory.NetheritebackpackInventoryCapability;
import net.ihavenowebsite.omegabird.llamamod.item.inventory.BackpackInventoryCapability;
import net.ihavenowebsite.omegabird.llamamod.item.*;
import net.ihavenowebsite.omegabird.llamamod.LlamamodMod;

import java.util.function.Function;

@EventBusSubscriber
public class LlamamodModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(LlamamodMod.MODID);
	public static final DeferredItem<Item> BANANA_PLANT;
	public static final DeferredItem<Item> BANANA;
	public static final DeferredItem<Item> BACKPACK;
	public static final DeferredItem<Item> NETHERITEBACKPACK;
	public static final DeferredItem<Item> ACID_BUCKET;
	public static final DeferredItem<Item> RED_BRICKS;
	public static final DeferredItem<Item> ORANGE_BRICKS;
	public static final DeferredItem<Item> YELLOW_BRICKS;
	public static final DeferredItem<Item> GREEN_BRICKS;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICKS;
	public static final DeferredItem<Item> BLUE_BRICKS;
	public static final DeferredItem<Item> MAGENTA_BRICKS;
	public static final DeferredItem<Item> PINK_BRICKS;
	public static final DeferredItem<Item> BROWN_BRICKS;
	public static final DeferredItem<Item> BLACK_BRICKS;
	public static final DeferredItem<Item> INDUSTRIAL_BRICKS;
	public static final DeferredItem<Item> COMPUTER;
	public static final DeferredItem<Item> TILES;
	public static final DeferredItem<Item> FARMSCRAPS;
	public static final DeferredItem<Item> CEILING_TILES;
	public static final DeferredItem<Item> AUTHENTICATOR;
	public static final DeferredItem<Item> PASSWORDCHANGER;
	public static final DeferredItem<Item> RED_BRICK_SLAB;
	public static final DeferredItem<Item> RED_BRICK_STAIRS;
	public static final DeferredItem<Item> ORANGE_BRICK_SLAB;
	public static final DeferredItem<Item> ORANGE_BRICK_STAIRS;
	public static final DeferredItem<Item> YELLOW_BRICK_SLAB;
	public static final DeferredItem<Item> YELLOW_BRICK_STAIRS;
	public static final DeferredItem<Item> LIGHTBLUEBRICKSLAB;
	public static final DeferredItem<Item> LIGHTBLUEBRICKSTAIR;
	public static final DeferredItem<Item> BLUEBRICKSLAB;
	public static final DeferredItem<Item> BLUEBRICKSTAIR;
	public static final DeferredItem<Item> MAGENTABRICKSLAB;
	public static final DeferredItem<Item> MAGENTABRICKSTAIR;
	public static final DeferredItem<Item> PINKBRICKSLAB;
	public static final DeferredItem<Item> PINKBRICKSTAIR;
	public static final DeferredItem<Item> BROWNBRICKSLAB;
	public static final DeferredItem<Item> BROWNBRICKSTAIR;
	public static final DeferredItem<Item> BLACKBRICKSLAB;
	public static final DeferredItem<Item> BLACKBRICKSTAIR;
	public static final DeferredItem<Item> INDUSTRIALBRICKSLAB;
	public static final DeferredItem<Item> INDUSTRIALBRICKSTAIR;
	public static final DeferredItem<Item> TILE_SLAB;
	public static final DeferredItem<Item> TILE_STAIR;
	public static final DeferredItem<Item> CEILING_TILE_SLAB;
	public static final DeferredItem<Item> CEILING_TILE_STAIR;
	public static final DeferredItem<Item> WHITEBRICKS;
	public static final DeferredItem<Item> LIGHTGRAYBRICKS;
	public static final DeferredItem<Item> GRAYBRICKS;
	public static final DeferredItem<Item> LIMEBRICKS;
	public static final DeferredItem<Item> CYANBRICKS;
	public static final DeferredItem<Item> CHERRYBRICKS;
	public static final DeferredItem<Item> PURPLEBRICKS;
	public static final DeferredItem<Item> LIMEBRICKSLAB;
	public static final DeferredItem<Item> LIMEBRICKSTAIR;
	public static final DeferredItem<Item> GREENBRICKSSLAB;
	public static final DeferredItem<Item> GREENBRICKSSTAIR;
	public static final DeferredItem<Item> CYANBRICKSLAB;
	public static final DeferredItem<Item> CYANBRICKSTAIR;
	public static final DeferredItem<Item> PURPLEBRICKSLAB;
	public static final DeferredItem<Item> PURPLEBRICKSTAIR;
	public static final DeferredItem<Item> WHITEBRICKSLAB;
	public static final DeferredItem<Item> WHITEBRICKSTAIR;
	public static final DeferredItem<Item> LIGHTGRAYBRICKSLAB;
	public static final DeferredItem<Item> LIGHTGRAYBRICKSTAIR;
	public static final DeferredItem<Item> GRAYBRICKSLAB;
	public static final DeferredItem<Item> GRAYBRICKSTAIR;
	public static final DeferredItem<Item> CHERRYBRICKSLAB;
	public static final DeferredItem<Item> CHERRYBRICKSTAIR;
	public static final DeferredItem<Item> REDBRICKWALL;
	public static final DeferredItem<Item> ORANGEBRICKWALL;
	public static final DeferredItem<Item> YELLOWBRICKWALL;
	public static final DeferredItem<Item> GREENBRICKWALL;
	public static final DeferredItem<Item> LIGHTBLUEBRICKWALL;
	public static final DeferredItem<Item> BLUEBRICKWALL;
	public static final DeferredItem<Item> MAGENTABRICKWALL;
	public static final DeferredItem<Item> PINKBRICKWALL;
	public static final DeferredItem<Item> BROWNBRICKWALL;
	public static final DeferredItem<Item> BLACKBRICKWALL;
	public static final DeferredItem<Item> INDUSTRIALBRICKWALL;
	public static final DeferredItem<Item> WHITEBRICKWALL;
	public static final DeferredItem<Item> LIGHTGRAYBRICKWALL;
	public static final DeferredItem<Item> GRAYBRICKWALL;
	public static final DeferredItem<Item> LIMEBRICKWALL;
	public static final DeferredItem<Item> CYANBRICKWALL;
	public static final DeferredItem<Item> CHERRYBRICKWALL;
	public static final DeferredItem<Item> PURPLEBRICKWALL;
	public static final DeferredItem<Item> CEILING_TILE_WALL;
	public static final DeferredItem<Item> TILE_WALL;
	public static final DeferredItem<Item> INDUSTRIALBRICKFENCE;
	public static final DeferredItem<Item> INDUSTRIALBRICKFENCEGATE;
	public static final DeferredItem<Item> INDUSTRIALBRICKBUTTON;
	public static final DeferredItem<Item> INDUSTRIALBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> REDBRICKFENCE;
	public static final DeferredItem<Item> ORANGEBRICKFENCE;
	public static final DeferredItem<Item> YELLOWBRICKFENCE;
	public static final DeferredItem<Item> GREENBRICKFENCE;
	public static final DeferredItem<Item> LIGHTBLUEBRICKFENCE;
	public static final DeferredItem<Item> BLUEBRICKFENCE;
	public static final DeferredItem<Item> MAGENTABRICKFENCE;
	public static final DeferredItem<Item> PINKBRICKFENCE;
	public static final DeferredItem<Item> BROWNBRICKFENCE;
	public static final DeferredItem<Item> BLACKBRICKFENCE;
	public static final DeferredItem<Item> WHITEBRICKFENCE;
	public static final DeferredItem<Item> LIGHTGRAYBRICKFENCE;
	public static final DeferredItem<Item> GRAYBRICKFENCE;
	public static final DeferredItem<Item> LIMEBRICKFENCE;
	public static final DeferredItem<Item> CYANBRICKFENCE;
	public static final DeferredItem<Item> PURPLEBRICKFENCE;
	public static final DeferredItem<Item> CHERRYBRICKFENCE;
	public static final DeferredItem<Item> REDBRICKFENCEGATE;
	public static final DeferredItem<Item> ORANGEBRICKFENCEGATE;
	public static final DeferredItem<Item> YELLOWBRICKFENCEAGTE;
	public static final DeferredItem<Item> GREENBRICKFENCEGATE;
	public static final DeferredItem<Item> LIGHTBLUEBRICKFENCEGATE;
	public static final DeferredItem<Item> BLUEBRICKFENCEGATE;
	public static final DeferredItem<Item> MAGENTABRICKFENCEGATE;
	public static final DeferredItem<Item> PINKBRICKFENCEGATE;
	public static final DeferredItem<Item> BROWNBRICKFENCEGATE;
	public static final DeferredItem<Item> BLACKBRICKFENCEGATE;
	public static final DeferredItem<Item> WHITEBRICKFENCEGATE;
	public static final DeferredItem<Item> LIGHTGRAYBRICKFENCEGATE;
	public static final DeferredItem<Item> GRAYBRICKFENCEGATE;
	public static final DeferredItem<Item> LIMEBRICKFENCEGATE;
	public static final DeferredItem<Item> CYANBRICKFENCEGATE;
	public static final DeferredItem<Item> PURPLEBRICKFENCEGATE;
	public static final DeferredItem<Item> CHERRYBRICKFENCEGATE;
	public static final DeferredItem<Item> REDBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> ORANGEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> YELLOWBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> GREENBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTBLUEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> BLUEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> MAGENTABRICKPRESSUREPLATE;
	public static final DeferredItem<Item> PINKBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> BROWNBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> BLACKBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> WHITEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTGRAYBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> GRAYBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> LIMEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> CYANBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> PURPLEBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> CHERRYBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> REDBRICKBUTTON;
	public static final DeferredItem<Item> ORANGEBRICKBUTTON;
	public static final DeferredItem<Item> YELLOWBRICKBUTTON;
	public static final DeferredItem<Item> GREENBRICKBUTTON;
	public static final DeferredItem<Item> LIGHTBLUEBRICKBUTTON;
	public static final DeferredItem<Item> BLUEBRICKBUTTON;
	public static final DeferredItem<Item> MAGENTABRICKBUTTON;
	public static final DeferredItem<Item> PINKBRICKBUTTON;
	public static final DeferredItem<Item> BROWNBRICKBUTTON;
	public static final DeferredItem<Item> BLACKBRICKBUTTON;
	public static final DeferredItem<Item> WHITEBRICKBUTTON;
	public static final DeferredItem<Item> LIGHTGRAYBRICKBUTTON;
	public static final DeferredItem<Item> GRAYBRICKBUTTON;
	public static final DeferredItem<Item> LIMEBRICKBUTTON;
	public static final DeferredItem<Item> CYANBRICKBUTTON;
	public static final DeferredItem<Item> PURPLEBRICKBUTTON;
	public static final DeferredItem<Item> CHERRYBRICKBUTTON;
	public static final DeferredItem<Item> TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> TILE_BUTTON;
	public static final DeferredItem<Item> CEILING_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> CEILING_TILE_BUTTON;
	public static final DeferredItem<Item> WHITELARGETILE;
	public static final DeferredItem<Item> WHITELARGETILESTAIR;
	public static final DeferredItem<Item> WHITELARGETILESLAB;
	public static final DeferredItem<Item> WHITELARGETILEWALL;
	public static final DeferredItem<Item> WHITELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> WHITELARGETILEBUTTON;
	public static final DeferredItem<Item> VARIABLE_LIGHT;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILE;
	public static final DeferredItem<Item> GRAYLARGETILE;
	public static final DeferredItem<Item> BLACKLARGETILE;
	public static final DeferredItem<Item> ORANGELARGETILE;
	public static final DeferredItem<Item> MAGENTALARGETILE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILE;
	public static final DeferredItem<Item> BLUELARGETILE;
	public static final DeferredItem<Item> YELLOWLARGETILE;
	public static final DeferredItem<Item> LIMELARGETILE;
	public static final DeferredItem<Item> GREENLARGETILE;
	public static final DeferredItem<Item> PINKLARGETILE;
	public static final DeferredItem<Item> CYANLARGETILE;
	public static final DeferredItem<Item> PURPLELARGETILE;
	public static final DeferredItem<Item> BROWNLARGETILE;
	public static final DeferredItem<Item> REDLARGETILE;
	public static final DeferredItem<Item> LARGETILEFENCE;
	public static final DeferredItem<Item> LARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILESTAIR;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILESLAB;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEWALL;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEFENCE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEBUTTON;
	public static final DeferredItem<Item> GRAYLARGETILESTAIR;
	public static final DeferredItem<Item> GRAYLARGETILESLAB;
	public static final DeferredItem<Item> GRAYLARGETILEWALL;
	public static final DeferredItem<Item> GRAYLARGETILEFENCE;
	public static final DeferredItem<Item> GRAYLARGETILEFENCEGATE;
	public static final DeferredItem<Item> GRAYLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> GRAYLARGETILEBUTTON;
	public static final DeferredItem<Item> BLACKLARGETILESTAIR;
	public static final DeferredItem<Item> BLACKLARGETILESLAB;
	public static final DeferredItem<Item> BLACKLARGETILEWALL;
	public static final DeferredItem<Item> BLACKLARGETILEFENCE;
	public static final DeferredItem<Item> BLACKLARGETILEFENCEGATE;
	public static final DeferredItem<Item> BLACKLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> BLACKLARGETILEBUTTON;
	public static final DeferredItem<Item> BROWNLARGETILESTAIR;
	public static final DeferredItem<Item> BROWNLARGETILESLAB;
	public static final DeferredItem<Item> BROWNLARGETILEWALL;
	public static final DeferredItem<Item> BROWNLARGETILEFENCE;
	public static final DeferredItem<Item> BROWNLARGETILEFENCEGATE;
	public static final DeferredItem<Item> BROWNLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> BROWNLARGETILEBUTTON;
	public static final DeferredItem<Item> REDLARGETILESTAIR;
	public static final DeferredItem<Item> REDLARGETILESLAB;
	public static final DeferredItem<Item> REDLARGETILEWALL;
	public static final DeferredItem<Item> REDLARGETILEFENCE;
	public static final DeferredItem<Item> REDLARGETILEFENCEGATE;
	public static final DeferredItem<Item> REDLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> REDLARGETILEBUTTON;
	public static final DeferredItem<Item> ORANGELARGETILESTAIR;
	public static final DeferredItem<Item> ORANGELARGETILESLAB;
	public static final DeferredItem<Item> ORANGELARGETILEWALL;
	public static final DeferredItem<Item> ORANGELARGETILEFENCE;
	public static final DeferredItem<Item> ORANGELARGETILEFENCEGATE;
	public static final DeferredItem<Item> ORANGELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> ORANGELARGETILEBUTTON;
	public static final DeferredItem<Item> YELLOWLARGETILESTAIR;
	public static final DeferredItem<Item> YELLOWLARGETILESLAB;
	public static final DeferredItem<Item> YELLOWLARGETILEWALL;
	public static final DeferredItem<Item> YELLOWLARGETILEFENCE;
	public static final DeferredItem<Item> YELLOWLARGETILEFENCEGATE;
	public static final DeferredItem<Item> YELLOWLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> YELLOWLARGETILEBUTTON;
	public static final DeferredItem<Item> LIMELARGETILESTAIR;
	public static final DeferredItem<Item> LIMELARGETILESLAB;
	public static final DeferredItem<Item> LIMELARGETILEWALL;
	public static final DeferredItem<Item> LIMELARGETILEFENCE;
	public static final DeferredItem<Item> LIMELARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIMELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> LIMELARGETILEBUTTON;
	public static final DeferredItem<Item> GREENLARGETILESTAIR;
	public static final DeferredItem<Item> GREENLARGETILESLAB;
	public static final DeferredItem<Item> GREENLARGETILEWALL;
	public static final DeferredItem<Item> GREENLARGETILEFENCE;
	public static final DeferredItem<Item> GREENLARGETILEFENCEGATE;
	public static final DeferredItem<Item> GREENLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> GREENLARGETILEBUTTON;
	public static final DeferredItem<Item> CYANLARGETILESTAIR;
	public static final DeferredItem<Item> CYANLARGETILESLAB;
	public static final DeferredItem<Item> CYANLARGETILEWALL;
	public static final DeferredItem<Item> CYANLARGETILEFENCE;
	public static final DeferredItem<Item> CYANLARGETILEFENCEGATE;
	public static final DeferredItem<Item> CYANLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> CYANLARGETILEBUTTON;
	public static final DeferredItem<Item> LIGHTBLUELARGETILESTAIR;
	public static final DeferredItem<Item> LIGHTBLUELARGETILESLAB;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEWALL;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEFENCE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEBUTTON;
	public static final DeferredItem<Item> BLUELARGETILESTAIR;
	public static final DeferredItem<Item> BLUELARGETILESLAB;
	public static final DeferredItem<Item> BLUELARGETILEWALL;
	public static final DeferredItem<Item> BLUELARGETILEFENCE;
	public static final DeferredItem<Item> BLUELARGETILEFENCEGATE;
	public static final DeferredItem<Item> BLUELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> BLUELARGETILEBUTTON;
	public static final DeferredItem<Item> PURPLELARGETILESTAIR;
	public static final DeferredItem<Item> PURPLELARGETILESLAB;
	public static final DeferredItem<Item> PURPLELARGETILEWALL;
	public static final DeferredItem<Item> PURPLELARGETILEFENCE;
	public static final DeferredItem<Item> PURPLELARGETILEFENCEGATE;
	public static final DeferredItem<Item> PURPLELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> PURPLELARGETILEBUTTON;
	public static final DeferredItem<Item> MAGENTALARGETILESTAIR;
	public static final DeferredItem<Item> MAGENTALARGETILESLAB;
	public static final DeferredItem<Item> MAGENTALARGETILEWALL;
	public static final DeferredItem<Item> MAGENTALARGETILEFENCE;
	public static final DeferredItem<Item> MAGENTALARGETILEFENCEGATE;
	public static final DeferredItem<Item> MAGENTALARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> MAGENTALARGETILEBUTTON;
	public static final DeferredItem<Item> PINKLARGETILESTAIR;
	public static final DeferredItem<Item> PINKLARGETILESLAB;
	public static final DeferredItem<Item> PINKLARGETILEWALL;
	public static final DeferredItem<Item> PINKLARGETILEFENCE;
	public static final DeferredItem<Item> PINKLARGETILEFENCEGATE;
	public static final DeferredItem<Item> PINKLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> PINKLARGETILEBUTTON;
	public static final DeferredItem<Item> CEILING_TILE_FENCE;
	public static final DeferredItem<Item> CEILING_TILE_FENCE_GATE;
	public static final DeferredItem<Item> TILE_FENCE;
	public static final DeferredItem<Item> TILE_FENCE_GATE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILESTAIR;
	public static final DeferredItem<Item> INDUSTRIALLARGETILESLAB;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEWALL;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEFENCE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEFENCEGATE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEBUTTON;
	public static final DeferredItem<Item> WHITELARGETILETRAPDOOR;
	public static final DeferredItem<Item> INDUSTRIALLARGETILETRAPDOOR;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILETRAPDOOR;
	public static final DeferredItem<Item> GRAYLARGETILETRAPDOOR;
	public static final DeferredItem<Item> BLACKLARGETILETRAPDOOR;
	public static final DeferredItem<Item> BROWNLARGETILETRAPDOOR;
	public static final DeferredItem<Item> REDLARGETILETRAPDOOR;
	public static final DeferredItem<Item> ORANGELARGETILETRAPDOOR;
	public static final DeferredItem<Item> YELLOWLARGETILETRAPDOOR;
	public static final DeferredItem<Item> LIMELARGETILETRAPDOOR;
	public static final DeferredItem<Item> GREENLARGETILETRAPDOOR;
	public static final DeferredItem<Item> CYANLARGETILETRAPDOOR;
	public static final DeferredItem<Item> LIGHTBLUELARGETILETRAPDOOR;
	public static final DeferredItem<Item> BLUELARGETILETRAPDOOR;
	public static final DeferredItem<Item> PURPLELARGETILETRAPDOOR;
	public static final DeferredItem<Item> MAGENTALARGETILETRAPDOOR;
	public static final DeferredItem<Item> PINKLARGETILETRAPDOOR;
	public static final DeferredItem<Item> WHITEBRICKTRAPDOOR;
	public static final DeferredItem<Item> LIGHTGRAYBRICKTRAPDOOR;
	public static final DeferredItem<Item> GRAYBRICKTRAPDOOR;
	public static final DeferredItem<Item> BLACKBRICKTRAPDOOR;
	public static final DeferredItem<Item> BROWNBRICKTRAPDOOR;
	public static final DeferredItem<Item> REDBRICKTRAPDOOR;
	public static final DeferredItem<Item> ORANGEBRICKTRAPDOOR;
	public static final DeferredItem<Item> YELLOWBRICKTRAPDOOR;
	public static final DeferredItem<Item> LIMEBRICKTRAPDOOR;
	public static final DeferredItem<Item> GREENBRICKTRAPDOOR;
	public static final DeferredItem<Item> CYANBRICKTRAPDOOR;
	public static final DeferredItem<Item> LIGHTBLUEBRICKTRAPDOOR;
	public static final DeferredItem<Item> BLUEBRICKTRAPDOOR;
	public static final DeferredItem<Item> PURPLEBRICKTRAPDOOR;
	public static final DeferredItem<Item> MAGENTABRICKTRAPDOOR;
	public static final DeferredItem<Item> PINKBRICKTRAPDOOR;
	public static final DeferredItem<Item> CHERRYBRICKTRAPDOOR;
	public static final DeferredItem<Item> INDUSTRIALBRICKTRAPDOOR;
	public static final DeferredItem<Item> CEILING_TILE_TRAPDOOR;
	public static final DeferredItem<Item> TILE_TRAPDOOR;
	public static final DeferredItem<Item> CHERRYLARGETILE;
	public static final DeferredItem<Item> CHERRYLARGETILESTAIR;
	public static final DeferredItem<Item> CHERRYLARGETILESLAB;
	public static final DeferredItem<Item> CHERRYLARGETILEWALL;
	public static final DeferredItem<Item> CHERRYLARGETILEFENCE;
	public static final DeferredItem<Item> CHERRYLARGETILEFENCEGATE;
	public static final DeferredItem<Item> CHERRYLARGETILETRAPDOOR;
	public static final DeferredItem<Item> CHERRYLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> CHERRYLARGETILEBUTTON;
	public static final DeferredItem<Item> SECURE_STORAGE_BLOCK;
	public static final DeferredItem<Item> TEALBRICKS;
	public static final DeferredItem<Item> TEALLARGETILE;
	public static final DeferredItem<Item> TEALLARGETILESTAIR;
	public static final DeferredItem<Item> TEALLARGETILESLAB;
	public static final DeferredItem<Item> TEALLARGETILEWALL;
	public static final DeferredItem<Item> TEALLARGETILEFENCE;
	public static final DeferredItem<Item> TEALLARGETILEFENCEGATE;
	public static final DeferredItem<Item> TEALLARGETILETRAPDOOR;
	public static final DeferredItem<Item> TEALLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> TEALLARGETILEBUTTON;
	public static final DeferredItem<Item> TEALBRICKSTAIR;
	public static final DeferredItem<Item> TEALBRICKSLAB;
	public static final DeferredItem<Item> TEALBRICKWALL;
	public static final DeferredItem<Item> TEALBRICKFENCE;
	public static final DeferredItem<Item> TEALBRICKFENCEGATE;
	public static final DeferredItem<Item> TEALBRICKTRAPDOOR;
	public static final DeferredItem<Item> TEALBRICKPRESSUREPLATE;
	public static final DeferredItem<Item> TEALBRICKBUTTON;
	static {
		BANANA_PLANT = block(LlamamodModBlocks.BANANA_PLANT);
		BANANA = register("banana", BannanaItem::new);
		BACKPACK = register("backpack", BackpackItem::new);
		NETHERITEBACKPACK = register("netheritebackpack", NetheritebackpackItem::new);
		ACID_BUCKET = register("acid_bucket", AcidItem::new);
		RED_BRICKS = block(LlamamodModBlocks.RED_BRICKS);
		ORANGE_BRICKS = block(LlamamodModBlocks.ORANGE_BRICKS);
		YELLOW_BRICKS = block(LlamamodModBlocks.YELLOW_BRICKS);
		GREEN_BRICKS = block(LlamamodModBlocks.GREEN_BRICKS);
		LIGHT_BLUE_BRICKS = block(LlamamodModBlocks.LIGHT_BLUE_BRICKS);
		BLUE_BRICKS = block(LlamamodModBlocks.BLUE_BRICKS);
		MAGENTA_BRICKS = block(LlamamodModBlocks.MAGENTA_BRICKS);
		PINK_BRICKS = block(LlamamodModBlocks.PINK_BRICKS);
		BROWN_BRICKS = block(LlamamodModBlocks.BROWN_BRICKS);
		BLACK_BRICKS = block(LlamamodModBlocks.BLACK_BRICKS);
		INDUSTRIAL_BRICKS = block(LlamamodModBlocks.INDUSTRIAL_BRICKS);
		COMPUTER = block(LlamamodModBlocks.COMPUTER);
		TILES = block(LlamamodModBlocks.TILES);
		FARMSCRAPS = register("farmscraps", FarmscrapsItem::new);
		CEILING_TILES = block(LlamamodModBlocks.CEILING_TILES);
		AUTHENTICATOR = block(LlamamodModBlocks.AUTHENTICATOR);
		PASSWORDCHANGER = register("passwordchanger", PasswordchangerItem::new);
		RED_BRICK_SLAB = block(LlamamodModBlocks.RED_BRICK_SLAB);
		RED_BRICK_STAIRS = block(LlamamodModBlocks.RED_BRICK_STAIRS);
		ORANGE_BRICK_SLAB = block(LlamamodModBlocks.ORANGE_BRICK_SLAB);
		ORANGE_BRICK_STAIRS = block(LlamamodModBlocks.ORANGE_BRICK_STAIRS);
		YELLOW_BRICK_SLAB = block(LlamamodModBlocks.YELLOW_BRICK_SLAB);
		YELLOW_BRICK_STAIRS = block(LlamamodModBlocks.YELLOW_BRICK_STAIRS);
		LIGHTBLUEBRICKSLAB = block(LlamamodModBlocks.LIGHTBLUEBRICKSLAB);
		LIGHTBLUEBRICKSTAIR = block(LlamamodModBlocks.LIGHTBLUEBRICKSTAIR);
		BLUEBRICKSLAB = block(LlamamodModBlocks.BLUEBRICKSLAB);
		BLUEBRICKSTAIR = block(LlamamodModBlocks.BLUEBRICKSTAIR);
		MAGENTABRICKSLAB = block(LlamamodModBlocks.MAGENTABRICKSLAB);
		MAGENTABRICKSTAIR = block(LlamamodModBlocks.MAGENTABRICKSTAIR);
		PINKBRICKSLAB = block(LlamamodModBlocks.PINKBRICKSLAB);
		PINKBRICKSTAIR = block(LlamamodModBlocks.PINKBRICKSTAIR);
		BROWNBRICKSLAB = block(LlamamodModBlocks.BROWNBRICKSLAB);
		BROWNBRICKSTAIR = block(LlamamodModBlocks.BROWNBRICKSTAIR);
		BLACKBRICKSLAB = block(LlamamodModBlocks.BLACKBRICKSLAB);
		BLACKBRICKSTAIR = block(LlamamodModBlocks.BLACKBRICKSTAIR);
		INDUSTRIALBRICKSLAB = block(LlamamodModBlocks.INDUSTRIALBRICKSLAB);
		INDUSTRIALBRICKSTAIR = block(LlamamodModBlocks.INDUSTRIALBRICKSTAIR);
		TILE_SLAB = block(LlamamodModBlocks.TILE_SLAB);
		TILE_STAIR = block(LlamamodModBlocks.TILE_STAIR, new Item.Properties().fireResistant());
		CEILING_TILE_SLAB = block(LlamamodModBlocks.CEILING_TILE_SLAB);
		CEILING_TILE_STAIR = block(LlamamodModBlocks.CEILING_TILE_STAIR);
		WHITEBRICKS = block(LlamamodModBlocks.WHITEBRICKS);
		LIGHTGRAYBRICKS = block(LlamamodModBlocks.LIGHTGRAYBRICKS);
		GRAYBRICKS = block(LlamamodModBlocks.GRAYBRICKS);
		LIMEBRICKS = block(LlamamodModBlocks.LIMEBRICKS);
		CYANBRICKS = block(LlamamodModBlocks.CYANBRICKS);
		CHERRYBRICKS = block(LlamamodModBlocks.CHERRYBRICKS);
		PURPLEBRICKS = block(LlamamodModBlocks.PURPLEBRICKS);
		LIMEBRICKSLAB = block(LlamamodModBlocks.LIMEBRICKSLAB);
		LIMEBRICKSTAIR = block(LlamamodModBlocks.LIMEBRICKSTAIR);
		GREENBRICKSSLAB = block(LlamamodModBlocks.GREENBRICKSSLAB);
		GREENBRICKSSTAIR = block(LlamamodModBlocks.GREENBRICKSSTAIR);
		CYANBRICKSLAB = block(LlamamodModBlocks.CYANBRICKSLAB);
		CYANBRICKSTAIR = block(LlamamodModBlocks.CYANBRICKSTAIR);
		PURPLEBRICKSLAB = block(LlamamodModBlocks.PURPLEBRICKSLAB);
		PURPLEBRICKSTAIR = block(LlamamodModBlocks.PURPLEBRICKSTAIR);
		WHITEBRICKSLAB = block(LlamamodModBlocks.WHITEBRICKSLAB);
		WHITEBRICKSTAIR = block(LlamamodModBlocks.WHITEBRICKSTAIR);
		LIGHTGRAYBRICKSLAB = block(LlamamodModBlocks.LIGHTGRAYBRICKSLAB);
		LIGHTGRAYBRICKSTAIR = block(LlamamodModBlocks.LIGHTGRAYBRICKSTAIR);
		GRAYBRICKSLAB = block(LlamamodModBlocks.GRAYBRICKSLAB);
		GRAYBRICKSTAIR = block(LlamamodModBlocks.GRAYBRICKSTAIR);
		CHERRYBRICKSLAB = block(LlamamodModBlocks.CHERRYBRICKSLAB);
		CHERRYBRICKSTAIR = block(LlamamodModBlocks.CHERRYBRICKSTAIR);
		REDBRICKWALL = block(LlamamodModBlocks.REDBRICKWALL);
		ORANGEBRICKWALL = block(LlamamodModBlocks.ORANGEBRICKWALL);
		YELLOWBRICKWALL = block(LlamamodModBlocks.YELLOWBRICKWALL);
		GREENBRICKWALL = block(LlamamodModBlocks.GREENBRICKWALL);
		LIGHTBLUEBRICKWALL = block(LlamamodModBlocks.LIGHTBLUEBRICKWALL);
		BLUEBRICKWALL = block(LlamamodModBlocks.BLUEBRICKWALL);
		MAGENTABRICKWALL = block(LlamamodModBlocks.MAGENTABRICKWALL);
		PINKBRICKWALL = block(LlamamodModBlocks.PINKBRICKWALL);
		BROWNBRICKWALL = block(LlamamodModBlocks.BROWNBRICKWALL);
		BLACKBRICKWALL = block(LlamamodModBlocks.BLACKBRICKWALL);
		INDUSTRIALBRICKWALL = block(LlamamodModBlocks.INDUSTRIALBRICKWALL);
		WHITEBRICKWALL = block(LlamamodModBlocks.WHITEBRICKWALL);
		LIGHTGRAYBRICKWALL = block(LlamamodModBlocks.LIGHTGRAYBRICKWALL);
		GRAYBRICKWALL = block(LlamamodModBlocks.GRAYBRICKWALL);
		LIMEBRICKWALL = block(LlamamodModBlocks.LIMEBRICKWALL);
		CYANBRICKWALL = block(LlamamodModBlocks.CYANBRICKWALL);
		CHERRYBRICKWALL = block(LlamamodModBlocks.CHERRYBRICKWALL);
		PURPLEBRICKWALL = block(LlamamodModBlocks.PURPLEBRICKWALL);
		CEILING_TILE_WALL = block(LlamamodModBlocks.CEILING_TILE_WALL);
		TILE_WALL = block(LlamamodModBlocks.TILE_WALL, new Item.Properties().fireResistant());
		INDUSTRIALBRICKFENCE = block(LlamamodModBlocks.INDUSTRIALBRICKFENCE);
		INDUSTRIALBRICKFENCEGATE = block(LlamamodModBlocks.INDUSTRIALBRICKFENCEGATE);
		INDUSTRIALBRICKBUTTON = block(LlamamodModBlocks.INDUSTRIALBRICKBUTTON);
		INDUSTRIALBRICKPRESSUREPLATE = block(LlamamodModBlocks.INDUSTRIALBRICKPRESSUREPLATE);
		REDBRICKFENCE = block(LlamamodModBlocks.REDBRICKFENCE);
		ORANGEBRICKFENCE = block(LlamamodModBlocks.ORANGEBRICKFENCE);
		YELLOWBRICKFENCE = block(LlamamodModBlocks.YELLOWBRICKFENCE);
		GREENBRICKFENCE = block(LlamamodModBlocks.GREENBRICKFENCE);
		LIGHTBLUEBRICKFENCE = block(LlamamodModBlocks.LIGHTBLUEBRICKFENCE);
		BLUEBRICKFENCE = block(LlamamodModBlocks.BLUEBRICKFENCE);
		MAGENTABRICKFENCE = block(LlamamodModBlocks.MAGENTABRICKFENCE);
		PINKBRICKFENCE = block(LlamamodModBlocks.PINKBRICKFENCE);
		BROWNBRICKFENCE = block(LlamamodModBlocks.BROWNBRICKFENCE);
		BLACKBRICKFENCE = block(LlamamodModBlocks.BLACKBRICKFENCE);
		WHITEBRICKFENCE = block(LlamamodModBlocks.WHITEBRICKFENCE);
		LIGHTGRAYBRICKFENCE = block(LlamamodModBlocks.LIGHTGRAYBRICKFENCE);
		GRAYBRICKFENCE = block(LlamamodModBlocks.GRAYBRICKFENCE);
		LIMEBRICKFENCE = block(LlamamodModBlocks.LIMEBRICKFENCE);
		CYANBRICKFENCE = block(LlamamodModBlocks.CYANBRICKFENCE);
		PURPLEBRICKFENCE = block(LlamamodModBlocks.PURPLEBRICKFENCE);
		CHERRYBRICKFENCE = block(LlamamodModBlocks.CHERRYBRICKFENCE);
		REDBRICKFENCEGATE = block(LlamamodModBlocks.REDBRICKFENCEGATE);
		ORANGEBRICKFENCEGATE = block(LlamamodModBlocks.ORANGEBRICKFENCEGATE);
		YELLOWBRICKFENCEAGTE = block(LlamamodModBlocks.YELLOWBRICKFENCEAGTE);
		GREENBRICKFENCEGATE = block(LlamamodModBlocks.GREENBRICKFENCEGATE);
		LIGHTBLUEBRICKFENCEGATE = block(LlamamodModBlocks.LIGHTBLUEBRICKFENCEGATE);
		BLUEBRICKFENCEGATE = block(LlamamodModBlocks.BLUEBRICKFENCEGATE);
		MAGENTABRICKFENCEGATE = block(LlamamodModBlocks.MAGENTABRICKFENCEGATE);
		PINKBRICKFENCEGATE = block(LlamamodModBlocks.PINKBRICKFENCEGATE);
		BROWNBRICKFENCEGATE = block(LlamamodModBlocks.BROWNBRICKFENCEGATE);
		BLACKBRICKFENCEGATE = block(LlamamodModBlocks.BLACKBRICKFENCEGATE);
		WHITEBRICKFENCEGATE = block(LlamamodModBlocks.WHITEBRICKFENCEGATE);
		LIGHTGRAYBRICKFENCEGATE = block(LlamamodModBlocks.LIGHTGRAYBRICKFENCEGATE);
		GRAYBRICKFENCEGATE = block(LlamamodModBlocks.GRAYBRICKFENCEGATE);
		LIMEBRICKFENCEGATE = block(LlamamodModBlocks.LIMEBRICKFENCEGATE);
		CYANBRICKFENCEGATE = block(LlamamodModBlocks.CYANBRICKFENCEGATE);
		PURPLEBRICKFENCEGATE = block(LlamamodModBlocks.PURPLEBRICKFENCEGATE);
		CHERRYBRICKFENCEGATE = block(LlamamodModBlocks.CHERRYBRICKFENCEGATE);
		REDBRICKPRESSUREPLATE = block(LlamamodModBlocks.REDBRICKPRESSUREPLATE);
		ORANGEBRICKPRESSUREPLATE = block(LlamamodModBlocks.ORANGEBRICKPRESSUREPLATE);
		YELLOWBRICKPRESSUREPLATE = block(LlamamodModBlocks.YELLOWBRICKPRESSUREPLATE);
		GREENBRICKPRESSUREPLATE = block(LlamamodModBlocks.GREENBRICKPRESSUREPLATE);
		LIGHTBLUEBRICKPRESSUREPLATE = block(LlamamodModBlocks.LIGHTBLUEBRICKPRESSUREPLATE);
		BLUEBRICKPRESSUREPLATE = block(LlamamodModBlocks.BLUEBRICKPRESSUREPLATE);
		MAGENTABRICKPRESSUREPLATE = block(LlamamodModBlocks.MAGENTABRICKPRESSUREPLATE);
		PINKBRICKPRESSUREPLATE = block(LlamamodModBlocks.PINKBRICKPRESSUREPLATE);
		BROWNBRICKPRESSUREPLATE = block(LlamamodModBlocks.BROWNBRICKPRESSUREPLATE);
		BLACKBRICKPRESSUREPLATE = block(LlamamodModBlocks.BLACKBRICKPRESSUREPLATE);
		WHITEBRICKPRESSUREPLATE = block(LlamamodModBlocks.WHITEBRICKPRESSUREPLATE);
		LIGHTGRAYBRICKPRESSUREPLATE = block(LlamamodModBlocks.LIGHTGRAYBRICKPRESSUREPLATE);
		GRAYBRICKPRESSUREPLATE = block(LlamamodModBlocks.GRAYBRICKPRESSUREPLATE);
		LIMEBRICKPRESSUREPLATE = block(LlamamodModBlocks.LIMEBRICKPRESSUREPLATE);
		CYANBRICKPRESSUREPLATE = block(LlamamodModBlocks.CYANBRICKPRESSUREPLATE);
		PURPLEBRICKPRESSUREPLATE = block(LlamamodModBlocks.PURPLEBRICKPRESSUREPLATE);
		CHERRYBRICKPRESSUREPLATE = block(LlamamodModBlocks.CHERRYBRICKPRESSUREPLATE);
		REDBRICKBUTTON = block(LlamamodModBlocks.REDBRICKBUTTON);
		ORANGEBRICKBUTTON = block(LlamamodModBlocks.ORANGEBRICKBUTTON);
		YELLOWBRICKBUTTON = block(LlamamodModBlocks.YELLOWBRICKBUTTON);
		GREENBRICKBUTTON = block(LlamamodModBlocks.GREENBRICKBUTTON);
		LIGHTBLUEBRICKBUTTON = block(LlamamodModBlocks.LIGHTBLUEBRICKBUTTON);
		BLUEBRICKBUTTON = block(LlamamodModBlocks.BLUEBRICKBUTTON);
		MAGENTABRICKBUTTON = block(LlamamodModBlocks.MAGENTABRICKBUTTON);
		PINKBRICKBUTTON = block(LlamamodModBlocks.PINKBRICKBUTTON);
		BROWNBRICKBUTTON = block(LlamamodModBlocks.BROWNBRICKBUTTON);
		BLACKBRICKBUTTON = block(LlamamodModBlocks.BLACKBRICKBUTTON);
		WHITEBRICKBUTTON = block(LlamamodModBlocks.WHITEBRICKBUTTON);
		LIGHTGRAYBRICKBUTTON = block(LlamamodModBlocks.LIGHTGRAYBRICKBUTTON);
		GRAYBRICKBUTTON = block(LlamamodModBlocks.GRAYBRICKBUTTON);
		LIMEBRICKBUTTON = block(LlamamodModBlocks.LIMEBRICKBUTTON);
		CYANBRICKBUTTON = block(LlamamodModBlocks.CYANBRICKBUTTON);
		PURPLEBRICKBUTTON = block(LlamamodModBlocks.PURPLEBRICKBUTTON);
		CHERRYBRICKBUTTON = block(LlamamodModBlocks.CHERRYBRICKBUTTON);
		TILE_PRESSURE_PLATE = block(LlamamodModBlocks.TILE_PRESSURE_PLATE);
		TILE_BUTTON = block(LlamamodModBlocks.TILE_BUTTON);
		CEILING_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.CEILING_TILE_PRESSURE_PLATE);
		CEILING_TILE_BUTTON = block(LlamamodModBlocks.CEILING_TILE_BUTTON);
		WHITELARGETILE = block(LlamamodModBlocks.WHITELARGETILE);
		WHITELARGETILESTAIR = block(LlamamodModBlocks.WHITELARGETILESTAIR);
		WHITELARGETILESLAB = block(LlamamodModBlocks.WHITELARGETILESLAB);
		WHITELARGETILEWALL = block(LlamamodModBlocks.WHITELARGETILEWALL);
		WHITELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.WHITELARGETILEPRESSUREPLATE);
		WHITELARGETILEBUTTON = block(LlamamodModBlocks.WHITELARGETILEBUTTON);
		VARIABLE_LIGHT = block(LlamamodModBlocks.VARIABLE_LIGHT);
		LIGHTGRAYLARGETILE = block(LlamamodModBlocks.LIGHTGRAYLARGETILE);
		GRAYLARGETILE = block(LlamamodModBlocks.GRAYLARGETILE);
		BLACKLARGETILE = block(LlamamodModBlocks.BLACKLARGETILE);
		ORANGELARGETILE = block(LlamamodModBlocks.ORANGELARGETILE);
		MAGENTALARGETILE = block(LlamamodModBlocks.MAGENTALARGETILE);
		LIGHTBLUELARGETILE = block(LlamamodModBlocks.LIGHTBLUELARGETILE);
		BLUELARGETILE = block(LlamamodModBlocks.BLUELARGETILE);
		YELLOWLARGETILE = block(LlamamodModBlocks.YELLOWLARGETILE);
		LIMELARGETILE = block(LlamamodModBlocks.LIMELARGETILE);
		GREENLARGETILE = block(LlamamodModBlocks.GREENLARGETILE);
		PINKLARGETILE = block(LlamamodModBlocks.PINKLARGETILE);
		CYANLARGETILE = block(LlamamodModBlocks.CYANLARGETILE);
		PURPLELARGETILE = block(LlamamodModBlocks.PURPLELARGETILE);
		BROWNLARGETILE = block(LlamamodModBlocks.BROWNLARGETILE);
		REDLARGETILE = block(LlamamodModBlocks.REDLARGETILE);
		LARGETILEFENCE = block(LlamamodModBlocks.LARGETILEFENCE);
		LARGETILEFENCEGATE = block(LlamamodModBlocks.LARGETILEFENCEGATE);
		LIGHTGRAYLARGETILESTAIR = block(LlamamodModBlocks.LIGHTGRAYLARGETILESTAIR);
		LIGHTGRAYLARGETILESLAB = block(LlamamodModBlocks.LIGHTGRAYLARGETILESLAB);
		LIGHTGRAYLARGETILEWALL = block(LlamamodModBlocks.LIGHTGRAYLARGETILEWALL);
		LIGHTGRAYLARGETILEFENCE = block(LlamamodModBlocks.LIGHTGRAYLARGETILEFENCE);
		LIGHTGRAYLARGETILEFENCEGATE = block(LlamamodModBlocks.LIGHTGRAYLARGETILEFENCEGATE);
		LIGHTGRAYLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.LIGHTGRAYLARGETILEPRESSUREPLATE);
		LIGHTGRAYLARGETILEBUTTON = block(LlamamodModBlocks.LIGHTGRAYLARGETILEBUTTON);
		GRAYLARGETILESTAIR = block(LlamamodModBlocks.GRAYLARGETILESTAIR);
		GRAYLARGETILESLAB = block(LlamamodModBlocks.GRAYLARGETILESLAB);
		GRAYLARGETILEWALL = block(LlamamodModBlocks.GRAYLARGETILEWALL);
		GRAYLARGETILEFENCE = block(LlamamodModBlocks.GRAYLARGETILEFENCE);
		GRAYLARGETILEFENCEGATE = block(LlamamodModBlocks.GRAYLARGETILEFENCEGATE);
		GRAYLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.GRAYLARGETILEPRESSUREPLATE);
		GRAYLARGETILEBUTTON = block(LlamamodModBlocks.GRAYLARGETILEBUTTON);
		BLACKLARGETILESTAIR = block(LlamamodModBlocks.BLACKLARGETILESTAIR);
		BLACKLARGETILESLAB = block(LlamamodModBlocks.BLACKLARGETILESLAB);
		BLACKLARGETILEWALL = block(LlamamodModBlocks.BLACKLARGETILEWALL);
		BLACKLARGETILEFENCE = block(LlamamodModBlocks.BLACKLARGETILEFENCE);
		BLACKLARGETILEFENCEGATE = block(LlamamodModBlocks.BLACKLARGETILEFENCEGATE);
		BLACKLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.BLACKLARGETILEPRESSUREPLATE);
		BLACKLARGETILEBUTTON = block(LlamamodModBlocks.BLACKLARGETILEBUTTON);
		BROWNLARGETILESTAIR = block(LlamamodModBlocks.BROWNLARGETILESTAIR);
		BROWNLARGETILESLAB = block(LlamamodModBlocks.BROWNLARGETILESLAB);
		BROWNLARGETILEWALL = block(LlamamodModBlocks.BROWNLARGETILEWALL);
		BROWNLARGETILEFENCE = block(LlamamodModBlocks.BROWNLARGETILEFENCE);
		BROWNLARGETILEFENCEGATE = block(LlamamodModBlocks.BROWNLARGETILEFENCEGATE);
		BROWNLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.BROWNLARGETILEPRESSUREPLATE);
		BROWNLARGETILEBUTTON = block(LlamamodModBlocks.BROWNLARGETILEBUTTON);
		REDLARGETILESTAIR = block(LlamamodModBlocks.REDLARGETILESTAIR);
		REDLARGETILESLAB = block(LlamamodModBlocks.REDLARGETILESLAB);
		REDLARGETILEWALL = block(LlamamodModBlocks.REDLARGETILEWALL);
		REDLARGETILEFENCE = block(LlamamodModBlocks.REDLARGETILEFENCE);
		REDLARGETILEFENCEGATE = block(LlamamodModBlocks.REDLARGETILEFENCEGATE);
		REDLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.REDLARGETILEPRESSUREPLATE);
		REDLARGETILEBUTTON = block(LlamamodModBlocks.REDLARGETILEBUTTON);
		ORANGELARGETILESTAIR = block(LlamamodModBlocks.ORANGELARGETILESTAIR);
		ORANGELARGETILESLAB = block(LlamamodModBlocks.ORANGELARGETILESLAB);
		ORANGELARGETILEWALL = block(LlamamodModBlocks.ORANGELARGETILEWALL);
		ORANGELARGETILEFENCE = block(LlamamodModBlocks.ORANGELARGETILEFENCE);
		ORANGELARGETILEFENCEGATE = block(LlamamodModBlocks.ORANGELARGETILEFENCEGATE);
		ORANGELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.ORANGELARGETILEPRESSUREPLATE);
		ORANGELARGETILEBUTTON = block(LlamamodModBlocks.ORANGELARGETILEBUTTON);
		YELLOWLARGETILESTAIR = block(LlamamodModBlocks.YELLOWLARGETILESTAIR);
		YELLOWLARGETILESLAB = block(LlamamodModBlocks.YELLOWLARGETILESLAB);
		YELLOWLARGETILEWALL = block(LlamamodModBlocks.YELLOWLARGETILEWALL);
		YELLOWLARGETILEFENCE = block(LlamamodModBlocks.YELLOWLARGETILEFENCE);
		YELLOWLARGETILEFENCEGATE = block(LlamamodModBlocks.YELLOWLARGETILEFENCEGATE);
		YELLOWLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.YELLOWLARGETILEPRESSUREPLATE);
		YELLOWLARGETILEBUTTON = block(LlamamodModBlocks.YELLOWLARGETILEBUTTON);
		LIMELARGETILESTAIR = block(LlamamodModBlocks.LIMELARGETILESTAIR);
		LIMELARGETILESLAB = block(LlamamodModBlocks.LIMELARGETILESLAB);
		LIMELARGETILEWALL = block(LlamamodModBlocks.LIMELARGETILEWALL);
		LIMELARGETILEFENCE = block(LlamamodModBlocks.LIMELARGETILEFENCE);
		LIMELARGETILEFENCEGATE = block(LlamamodModBlocks.LIMELARGETILEFENCEGATE);
		LIMELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.LIMELARGETILEPRESSUREPLATE);
		LIMELARGETILEBUTTON = block(LlamamodModBlocks.LIMELARGETILEBUTTON);
		GREENLARGETILESTAIR = block(LlamamodModBlocks.GREENLARGETILESTAIR);
		GREENLARGETILESLAB = block(LlamamodModBlocks.GREENLARGETILESLAB);
		GREENLARGETILEWALL = block(LlamamodModBlocks.GREENLARGETILEWALL);
		GREENLARGETILEFENCE = block(LlamamodModBlocks.GREENLARGETILEFENCE);
		GREENLARGETILEFENCEGATE = block(LlamamodModBlocks.GREENLARGETILEFENCEGATE);
		GREENLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.GREENLARGETILEPRESSUREPLATE);
		GREENLARGETILEBUTTON = block(LlamamodModBlocks.GREENLARGETILEBUTTON);
		CYANLARGETILESTAIR = block(LlamamodModBlocks.CYANLARGETILESTAIR);
		CYANLARGETILESLAB = block(LlamamodModBlocks.CYANLARGETILESLAB);
		CYANLARGETILEWALL = block(LlamamodModBlocks.CYANLARGETILEWALL);
		CYANLARGETILEFENCE = block(LlamamodModBlocks.CYANLARGETILEFENCE);
		CYANLARGETILEFENCEGATE = block(LlamamodModBlocks.CYANLARGETILEFENCEGATE);
		CYANLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.CYANLARGETILEPRESSUREPLATE);
		CYANLARGETILEBUTTON = block(LlamamodModBlocks.CYANLARGETILEBUTTON);
		LIGHTBLUELARGETILESTAIR = block(LlamamodModBlocks.LIGHTBLUELARGETILESTAIR);
		LIGHTBLUELARGETILESLAB = block(LlamamodModBlocks.LIGHTBLUELARGETILESLAB);
		LIGHTBLUELARGETILEWALL = block(LlamamodModBlocks.LIGHTBLUELARGETILEWALL);
		LIGHTBLUELARGETILEFENCE = block(LlamamodModBlocks.LIGHTBLUELARGETILEFENCE);
		LIGHTBLUELARGETILEFENCEGATE = block(LlamamodModBlocks.LIGHTBLUELARGETILEFENCEGATE);
		LIGHTBLUELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.LIGHTBLUELARGETILEPRESSUREPLATE);
		LIGHTBLUELARGETILEBUTTON = block(LlamamodModBlocks.LIGHTBLUELARGETILEBUTTON);
		BLUELARGETILESTAIR = block(LlamamodModBlocks.BLUELARGETILESTAIR);
		BLUELARGETILESLAB = block(LlamamodModBlocks.BLUELARGETILESLAB);
		BLUELARGETILEWALL = block(LlamamodModBlocks.BLUELARGETILEWALL);
		BLUELARGETILEFENCE = block(LlamamodModBlocks.BLUELARGETILEFENCE);
		BLUELARGETILEFENCEGATE = block(LlamamodModBlocks.BLUELARGETILEFENCEGATE);
		BLUELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.BLUELARGETILEPRESSUREPLATE);
		BLUELARGETILEBUTTON = block(LlamamodModBlocks.BLUELARGETILEBUTTON);
		PURPLELARGETILESTAIR = block(LlamamodModBlocks.PURPLELARGETILESTAIR);
		PURPLELARGETILESLAB = block(LlamamodModBlocks.PURPLELARGETILESLAB);
		PURPLELARGETILEWALL = block(LlamamodModBlocks.PURPLELARGETILEWALL);
		PURPLELARGETILEFENCE = block(LlamamodModBlocks.PURPLELARGETILEFENCE);
		PURPLELARGETILEFENCEGATE = block(LlamamodModBlocks.PURPLELARGETILEFENCEGATE);
		PURPLELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.PURPLELARGETILEPRESSUREPLATE);
		PURPLELARGETILEBUTTON = block(LlamamodModBlocks.PURPLELARGETILEBUTTON);
		MAGENTALARGETILESTAIR = block(LlamamodModBlocks.MAGENTALARGETILESTAIR);
		MAGENTALARGETILESLAB = block(LlamamodModBlocks.MAGENTALARGETILESLAB);
		MAGENTALARGETILEWALL = block(LlamamodModBlocks.MAGENTALARGETILEWALL);
		MAGENTALARGETILEFENCE = block(LlamamodModBlocks.MAGENTALARGETILEFENCE);
		MAGENTALARGETILEFENCEGATE = block(LlamamodModBlocks.MAGENTALARGETILEFENCEGATE);
		MAGENTALARGETILEPRESSUREPLATE = block(LlamamodModBlocks.MAGENTALARGETILEPRESSUREPLATE);
		MAGENTALARGETILEBUTTON = block(LlamamodModBlocks.MAGENTALARGETILEBUTTON);
		PINKLARGETILESTAIR = block(LlamamodModBlocks.PINKLARGETILESTAIR);
		PINKLARGETILESLAB = block(LlamamodModBlocks.PINKLARGETILESLAB);
		PINKLARGETILEWALL = block(LlamamodModBlocks.PINKLARGETILEWALL);
		PINKLARGETILEFENCE = block(LlamamodModBlocks.PINKLARGETILEFENCE);
		PINKLARGETILEFENCEGATE = block(LlamamodModBlocks.PINKLARGETILEFENCEGATE);
		PINKLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.PINKLARGETILEPRESSUREPLATE);
		PINKLARGETILEBUTTON = block(LlamamodModBlocks.PINKLARGETILEBUTTON);
		CEILING_TILE_FENCE = block(LlamamodModBlocks.CEILING_TILE_FENCE);
		CEILING_TILE_FENCE_GATE = block(LlamamodModBlocks.CEILING_TILE_FENCE_GATE);
		TILE_FENCE = block(LlamamodModBlocks.TILE_FENCE, new Item.Properties().fireResistant());
		TILE_FENCE_GATE = block(LlamamodModBlocks.TILE_FENCE_GATE, new Item.Properties().fireResistant());
		INDUSTRIALLARGETILE = block(LlamamodModBlocks.INDUSTRIALLARGETILE);
		INDUSTRIALLARGETILESTAIR = block(LlamamodModBlocks.INDUSTRIALLARGETILESTAIR);
		INDUSTRIALLARGETILESLAB = block(LlamamodModBlocks.INDUSTRIALLARGETILESLAB);
		INDUSTRIALLARGETILEWALL = block(LlamamodModBlocks.INDUSTRIALLARGETILEWALL);
		INDUSTRIALLARGETILEFENCE = block(LlamamodModBlocks.INDUSTRIALLARGETILEFENCE);
		INDUSTRIALLARGETILEFENCEGATE = block(LlamamodModBlocks.INDUSTRIALLARGETILEFENCEGATE);
		INDUSTRIALLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.INDUSTRIALLARGETILEPRESSUREPLATE);
		INDUSTRIALLARGETILEBUTTON = block(LlamamodModBlocks.INDUSTRIALLARGETILEBUTTON);
		WHITELARGETILETRAPDOOR = block(LlamamodModBlocks.WHITELARGETILETRAPDOOR);
		INDUSTRIALLARGETILETRAPDOOR = block(LlamamodModBlocks.INDUSTRIALLARGETILETRAPDOOR);
		LIGHTGRAYLARGETILETRAPDOOR = block(LlamamodModBlocks.LIGHTGRAYLARGETILETRAPDOOR);
		GRAYLARGETILETRAPDOOR = block(LlamamodModBlocks.GRAYLARGETILETRAPDOOR);
		BLACKLARGETILETRAPDOOR = block(LlamamodModBlocks.BLACKLARGETILETRAPDOOR);
		BROWNLARGETILETRAPDOOR = block(LlamamodModBlocks.BROWNLARGETILETRAPDOOR);
		REDLARGETILETRAPDOOR = block(LlamamodModBlocks.REDLARGETILETRAPDOOR);
		ORANGELARGETILETRAPDOOR = block(LlamamodModBlocks.ORANGELARGETILETRAPDOOR);
		YELLOWLARGETILETRAPDOOR = block(LlamamodModBlocks.YELLOWLARGETILETRAPDOOR);
		LIMELARGETILETRAPDOOR = block(LlamamodModBlocks.LIMELARGETILETRAPDOOR);
		GREENLARGETILETRAPDOOR = block(LlamamodModBlocks.GREENLARGETILETRAPDOOR);
		CYANLARGETILETRAPDOOR = block(LlamamodModBlocks.CYANLARGETILETRAPDOOR);
		LIGHTBLUELARGETILETRAPDOOR = block(LlamamodModBlocks.LIGHTBLUELARGETILETRAPDOOR);
		BLUELARGETILETRAPDOOR = block(LlamamodModBlocks.BLUELARGETILETRAPDOOR);
		PURPLELARGETILETRAPDOOR = block(LlamamodModBlocks.PURPLELARGETILETRAPDOOR);
		MAGENTALARGETILETRAPDOOR = block(LlamamodModBlocks.MAGENTALARGETILETRAPDOOR);
		PINKLARGETILETRAPDOOR = block(LlamamodModBlocks.PINKLARGETILETRAPDOOR);
		WHITEBRICKTRAPDOOR = block(LlamamodModBlocks.WHITEBRICKTRAPDOOR);
		LIGHTGRAYBRICKTRAPDOOR = block(LlamamodModBlocks.LIGHTGRAYBRICKTRAPDOOR);
		GRAYBRICKTRAPDOOR = block(LlamamodModBlocks.GRAYBRICKTRAPDOOR);
		BLACKBRICKTRAPDOOR = block(LlamamodModBlocks.BLACKBRICKTRAPDOOR);
		BROWNBRICKTRAPDOOR = block(LlamamodModBlocks.BROWNBRICKTRAPDOOR);
		REDBRICKTRAPDOOR = block(LlamamodModBlocks.REDBRICKTRAPDOOR);
		ORANGEBRICKTRAPDOOR = block(LlamamodModBlocks.ORANGEBRICKTRAPDOOR);
		YELLOWBRICKTRAPDOOR = block(LlamamodModBlocks.YELLOWBRICKTRAPDOOR);
		LIMEBRICKTRAPDOOR = block(LlamamodModBlocks.LIMEBRICKTRAPDOOR);
		GREENBRICKTRAPDOOR = block(LlamamodModBlocks.GREENBRICKTRAPDOOR);
		CYANBRICKTRAPDOOR = block(LlamamodModBlocks.CYANBRICKTRAPDOOR);
		LIGHTBLUEBRICKTRAPDOOR = block(LlamamodModBlocks.LIGHTBLUEBRICKTRAPDOOR);
		BLUEBRICKTRAPDOOR = block(LlamamodModBlocks.BLUEBRICKTRAPDOOR);
		PURPLEBRICKTRAPDOOR = block(LlamamodModBlocks.PURPLEBRICKTRAPDOOR);
		MAGENTABRICKTRAPDOOR = block(LlamamodModBlocks.MAGENTABRICKTRAPDOOR);
		PINKBRICKTRAPDOOR = block(LlamamodModBlocks.PINKBRICKTRAPDOOR);
		CHERRYBRICKTRAPDOOR = block(LlamamodModBlocks.CHERRYBRICKTRAPDOOR);
		INDUSTRIALBRICKTRAPDOOR = block(LlamamodModBlocks.INDUSTRIALBRICKTRAPDOOR);
		CEILING_TILE_TRAPDOOR = block(LlamamodModBlocks.CEILING_TILE_TRAPDOOR);
		TILE_TRAPDOOR = block(LlamamodModBlocks.TILE_TRAPDOOR);
		CHERRYLARGETILE = block(LlamamodModBlocks.CHERRYLARGETILE);
		CHERRYLARGETILESTAIR = block(LlamamodModBlocks.CHERRYLARGETILESTAIR);
		CHERRYLARGETILESLAB = block(LlamamodModBlocks.CHERRYLARGETILESLAB);
		CHERRYLARGETILEWALL = block(LlamamodModBlocks.CHERRYLARGETILEWALL);
		CHERRYLARGETILEFENCE = block(LlamamodModBlocks.CHERRYLARGETILEFENCE);
		CHERRYLARGETILEFENCEGATE = block(LlamamodModBlocks.CHERRYLARGETILEFENCEGATE);
		CHERRYLARGETILETRAPDOOR = block(LlamamodModBlocks.CHERRYLARGETILETRAPDOOR);
		CHERRYLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.CHERRYLARGETILEPRESSUREPLATE);
		CHERRYLARGETILEBUTTON = block(LlamamodModBlocks.CHERRYLARGETILEBUTTON);
		SECURE_STORAGE_BLOCK = block(LlamamodModBlocks.SECURE_STORAGE_BLOCK);
		TEALBRICKS = block(LlamamodModBlocks.TEALBRICKS);
		TEALLARGETILE = block(LlamamodModBlocks.TEALLARGETILE);
		TEALLARGETILESTAIR = block(LlamamodModBlocks.TEALLARGETILESTAIR);
		TEALLARGETILESLAB = block(LlamamodModBlocks.TEALLARGETILESLAB);
		TEALLARGETILEWALL = block(LlamamodModBlocks.TEALLARGETILEWALL);
		TEALLARGETILEFENCE = block(LlamamodModBlocks.TEALLARGETILEFENCE);
		TEALLARGETILEFENCEGATE = block(LlamamodModBlocks.TEALLARGETILEFENCEGATE);
		TEALLARGETILETRAPDOOR = block(LlamamodModBlocks.TEALLARGETILETRAPDOOR);
		TEALLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.TEALLARGETILEPRESSUREPLATE);
		TEALLARGETILEBUTTON = block(LlamamodModBlocks.TEALLARGETILEBUTTON);
		TEALBRICKSTAIR = block(LlamamodModBlocks.TEALBRICKSTAIR);
		TEALBRICKSLAB = block(LlamamodModBlocks.TEALBRICKSLAB);
		TEALBRICKWALL = block(LlamamodModBlocks.TEALBRICKWALL);
		TEALBRICKFENCE = block(LlamamodModBlocks.TEALBRICKFENCE);
		TEALBRICKFENCEGATE = block(LlamamodModBlocks.TEALBRICKFENCEGATE);
		TEALBRICKTRAPDOOR = block(LlamamodModBlocks.TEALBRICKTRAPDOOR);
		TEALBRICKPRESSUREPLATE = block(LlamamodModBlocks.TEALBRICKPRESSUREPLATE);
		TEALBRICKBUTTON = block(LlamamodModBlocks.TEALBRICKBUTTON);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new BackpackInventoryCapability(stack), BACKPACK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new NetheritebackpackInventoryCapability(stack), NETHERITEBACKPACK.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), ACID_BUCKET.get());
	}
}