/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.ihavenowebsite.omegabird.llamamod.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import net.ihavenowebsite.omegabird.llamamod.block.*;
import net.ihavenowebsite.omegabird.llamamod.LlamamodMod;

import java.util.function.Function;

public class LlamamodModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(LlamamodMod.MODID);
	public static final DeferredBlock<Block> BANANA_PLANT;
	public static final DeferredBlock<Block> ACID;
	public static final DeferredBlock<Block> RED_BRICKS;
	public static final DeferredBlock<Block> ORANGE_BRICKS;
	public static final DeferredBlock<Block> YELLOW_BRICKS;
	public static final DeferredBlock<Block> GREEN_BRICKS;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICKS;
	public static final DeferredBlock<Block> BLUE_BRICKS;
	public static final DeferredBlock<Block> MAGENTA_BRICKS;
	public static final DeferredBlock<Block> PINK_BRICKS;
	public static final DeferredBlock<Block> BROWN_BRICKS;
	public static final DeferredBlock<Block> BLACK_BRICKS;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICKS;
	public static final DeferredBlock<Block> COMPUTER;
	public static final DeferredBlock<Block> TILES;
	public static final DeferredBlock<Block> CEILING_TILES;
	public static final DeferredBlock<Block> AUTHENTICATOR;
	public static final DeferredBlock<Block> RED_BRICK_SLAB;
	public static final DeferredBlock<Block> RED_BRICK_STAIRS;
	public static final DeferredBlock<Block> ORANGE_BRICK_SLAB;
	public static final DeferredBlock<Block> ORANGE_BRICK_STAIRS;
	public static final DeferredBlock<Block> YELLOW_BRICK_SLAB;
	public static final DeferredBlock<Block> YELLOW_BRICK_STAIRS;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_SLAB;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_STAIRS;
	public static final DeferredBlock<Block> BLUE_BRICK_SLAB;
	public static final DeferredBlock<Block> BLUE_BRICK_STAIRS;
	public static final DeferredBlock<Block> MAGENTA_BRICK_SLAB;
	public static final DeferredBlock<Block> MAGENTA_BRICK_STAIRS;
	public static final DeferredBlock<Block> PINK_BRICK_SLAB;
	public static final DeferredBlock<Block> PINK_BRICK_STAIRS;
	public static final DeferredBlock<Block> BROWN_BRICK_SLAB;
	public static final DeferredBlock<Block> BROWN_BRICK_STAIRS;
	public static final DeferredBlock<Block> BLACK_BRICK_SLAB;
	public static final DeferredBlock<Block> BLACK_BRICK_STAIRS;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_SLAB;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_STAIRS;
	public static final DeferredBlock<Block> TILE_SLAB;
	public static final DeferredBlock<Block> TILE_STAIR;
	public static final DeferredBlock<Block> CEILING_TILE_SLAB;
	public static final DeferredBlock<Block> CEILING_TILE_STAIR;
	public static final DeferredBlock<Block> WHITE_BRICKS;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICKS;
	public static final DeferredBlock<Block> GRAY_BRICKS;
	public static final DeferredBlock<Block> LIME_BRICKS;
	public static final DeferredBlock<Block> CYAN_BRICKS;
	public static final DeferredBlock<Block> CHERRY_BRICKS;
	public static final DeferredBlock<Block> PURPLE_BRICKS;
	public static final DeferredBlock<Block> LIME_BRICK_SLAB;
	public static final DeferredBlock<Block> LIME_BRICK_STAIRS;
	public static final DeferredBlock<Block> GREEN_BRICK_SLAB;
	public static final DeferredBlock<Block> GREEN_BRICK_STAIRS;
	public static final DeferredBlock<Block> CYAN_BRICK_SLAB;
	public static final DeferredBlock<Block> CYAN_BRICK_STAIRS;
	public static final DeferredBlock<Block> PURPLE_BRICK_SLAB;
	public static final DeferredBlock<Block> PURPLE_BRICK_STAIRS;
	public static final DeferredBlock<Block> WHITE_BRICK_SLAB;
	public static final DeferredBlock<Block> WHITE_BRICK_STAIRS;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_SLAB;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_STAIRS;
	public static final DeferredBlock<Block> GRAY_BRICK_SLAB;
	public static final DeferredBlock<Block> GRAY_BRICK_STAIRS;
	public static final DeferredBlock<Block> CHERRY_BRICK_SLAB;
	public static final DeferredBlock<Block> CHERRY_BRICK_STAIR;
	public static final DeferredBlock<Block> RED_BRICK_WALL;
	public static final DeferredBlock<Block> ORANGE_BRICK_WALL;
	public static final DeferredBlock<Block> YELLOW_BRICK_WALL;
	public static final DeferredBlock<Block> GREEN_BRICK_WALL;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_WALL;
	public static final DeferredBlock<Block> BLUE_BRICK_WALL;
	public static final DeferredBlock<Block> MAGENTA_BRICK_WALL;
	public static final DeferredBlock<Block> PINK_BRICK_WALL;
	public static final DeferredBlock<Block> BROWN_BRICK_WALL;
	public static final DeferredBlock<Block> BLACK_BRICK_WALL;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_WALL;
	public static final DeferredBlock<Block> WHITE_BRICK_WALL;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_WALL;
	public static final DeferredBlock<Block> GRAY_BRICK_WALL;
	public static final DeferredBlock<Block> LIME_BRICK_WALL;
	public static final DeferredBlock<Block> CYAN_BRICK_WALL;
	public static final DeferredBlock<Block> CHERRY_BRICK_WALL;
	public static final DeferredBlock<Block> PURPLE_BRICK_WALL;
	public static final DeferredBlock<Block> CEILING_TILE_WALL;
	public static final DeferredBlock<Block> TILE_WALL;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_FENCE;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_BUTTON;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> RED_BRICK_FENCE;
	public static final DeferredBlock<Block> ORANGE_BRICK_FENCE;
	public static final DeferredBlock<Block> YELLOW_BRICK_FENCE;
	public static final DeferredBlock<Block> GREEN_BRICK_FENCE;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_FENCE;
	public static final DeferredBlock<Block> BLUE_BRICK_FENCE;
	public static final DeferredBlock<Block> MAGENTA_BRICK_FENCE;
	public static final DeferredBlock<Block> PINK_BRICK_FENCE;
	public static final DeferredBlock<Block> BROWN_BRICK_FENCE;
	public static final DeferredBlock<Block> BLACK_BRICK_FENCE;
	public static final DeferredBlock<Block> WHITE_BRICK_FENCE;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_FENCE;
	public static final DeferredBlock<Block> GRAY_BRICK_FENCE;
	public static final DeferredBlock<Block> LIME_BRICK_FENCE;
	public static final DeferredBlock<Block> CYAN_BRICK_FENCE;
	public static final DeferredBlock<Block> PURPLE_BRICK_FENCE;
	public static final DeferredBlock<Block> CHERRY_BRICK_FENCE;
	public static final DeferredBlock<Block> RED_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> ORANGE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> YELLOW_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> GREEN_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> BLUE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> MAGENTA_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> PINK_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> BROWN_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> BLACK_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> WHITE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> GRAY_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> LIME_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> CYAN_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> PURPLE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> CHERRY_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> RED_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> ORANGE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> YELLOW_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> GREEN_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> BLUE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> MAGENTA_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> PINK_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> BROWN_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> BLACK_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> WHITE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> GRAY_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> LIME_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CYAN_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> PURPLE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CHERRY_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> RED_BRICK_BUTTON;
	public static final DeferredBlock<Block> ORANGE_BRICK_BUTTON;
	public static final DeferredBlock<Block> YELLOW_BRICK_BUTTON;
	public static final DeferredBlock<Block> GREEN_BRICK_BUTTON;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_BUTTON;
	public static final DeferredBlock<Block> BLUE_BRICK_BUTTON;
	public static final DeferredBlock<Block> MAGENTA_BRICK_BUTTON;
	public static final DeferredBlock<Block> PINK_BRICK_BUTTON;
	public static final DeferredBlock<Block> BROWN_BRICK_BUTTON;
	public static final DeferredBlock<Block> BLACK_BRICK_BUTTON;
	public static final DeferredBlock<Block> WHITE_BRICK_BUTTON;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_BUTTON;
	public static final DeferredBlock<Block> GRAY_BRICK_BUTTON;
	public static final DeferredBlock<Block> LIME_BRICK_BUTTON;
	public static final DeferredBlock<Block> CYAN_BRICK_BUTTON;
	public static final DeferredBlock<Block> PURPLE_BRICK_BUTTON;
	public static final DeferredBlock<Block> CHERRY_BRICK_BUTTON;
	public static final DeferredBlock<Block> TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> TILE_BUTTON;
	public static final DeferredBlock<Block> CEILING_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CEILING_TILE_BUTTON;
	public static final DeferredBlock<Block> WHITELARGETILE;
	public static final DeferredBlock<Block> WHITELARGETILESTAIR;
	public static final DeferredBlock<Block> WHITELARGETILESLAB;
	public static final DeferredBlock<Block> WHITELARGETILEWALL;
	public static final DeferredBlock<Block> WHITELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> WHITELARGETILEBUTTON;
	public static final DeferredBlock<Block> VARIABLE_LIGHT;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILE;
	public static final DeferredBlock<Block> GRAYLARGETILE;
	public static final DeferredBlock<Block> BLACKLARGETILE;
	public static final DeferredBlock<Block> ORANGELARGETILE;
	public static final DeferredBlock<Block> MAGENTALARGETILE;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILE;
	public static final DeferredBlock<Block> BLUELARGETILE;
	public static final DeferredBlock<Block> YELLOWLARGETILE;
	public static final DeferredBlock<Block> LIMELARGETILE;
	public static final DeferredBlock<Block> GREENLARGETILE;
	public static final DeferredBlock<Block> PINKLARGETILE;
	public static final DeferredBlock<Block> CYANLARGETILE;
	public static final DeferredBlock<Block> PURPLELARGETILE;
	public static final DeferredBlock<Block> BROWNLARGETILE;
	public static final DeferredBlock<Block> REDLARGETILE;
	public static final DeferredBlock<Block> LARGETILEFENCE;
	public static final DeferredBlock<Block> LARGETILEFENCEGATE;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILESTAIR;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILESLAB;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEWALL;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEFENCE;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILEBUTTON;
	public static final DeferredBlock<Block> GRAYLARGETILESTAIR;
	public static final DeferredBlock<Block> GRAYLARGETILESLAB;
	public static final DeferredBlock<Block> GRAYLARGETILEWALL;
	public static final DeferredBlock<Block> GRAYLARGETILEFENCE;
	public static final DeferredBlock<Block> GRAYLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> GRAYLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> GRAYLARGETILEBUTTON;
	public static final DeferredBlock<Block> BLACKLARGETILESTAIR;
	public static final DeferredBlock<Block> BLACKLARGETILESLAB;
	public static final DeferredBlock<Block> BLACKLARGETILEWALL;
	public static final DeferredBlock<Block> BLACKLARGETILEFENCE;
	public static final DeferredBlock<Block> BLACKLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> BLACKLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> BLACKLARGETILEBUTTON;
	public static final DeferredBlock<Block> BROWNLARGETILESTAIR;
	public static final DeferredBlock<Block> BROWNLARGETILESLAB;
	public static final DeferredBlock<Block> BROWNLARGETILEWALL;
	public static final DeferredBlock<Block> BROWNLARGETILEFENCE;
	public static final DeferredBlock<Block> BROWNLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> BROWNLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> BROWNLARGETILEBUTTON;
	public static final DeferredBlock<Block> REDLARGETILESTAIR;
	public static final DeferredBlock<Block> REDLARGETILESLAB;
	public static final DeferredBlock<Block> REDLARGETILEWALL;
	public static final DeferredBlock<Block> REDLARGETILEFENCE;
	public static final DeferredBlock<Block> REDLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> REDLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> REDLARGETILEBUTTON;
	public static final DeferredBlock<Block> ORANGELARGETILESTAIR;
	public static final DeferredBlock<Block> ORANGELARGETILESLAB;
	public static final DeferredBlock<Block> ORANGELARGETILEWALL;
	public static final DeferredBlock<Block> ORANGELARGETILEFENCE;
	public static final DeferredBlock<Block> ORANGELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> ORANGELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> ORANGELARGETILEBUTTON;
	public static final DeferredBlock<Block> YELLOWLARGETILESTAIR;
	public static final DeferredBlock<Block> YELLOWLARGETILESLAB;
	public static final DeferredBlock<Block> YELLOWLARGETILEWALL;
	public static final DeferredBlock<Block> YELLOWLARGETILEFENCE;
	public static final DeferredBlock<Block> YELLOWLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> YELLOWLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> YELLOWLARGETILEBUTTON;
	public static final DeferredBlock<Block> LIMELARGETILESTAIR;
	public static final DeferredBlock<Block> LIMELARGETILESLAB;
	public static final DeferredBlock<Block> LIMELARGETILEWALL;
	public static final DeferredBlock<Block> LIMELARGETILEFENCE;
	public static final DeferredBlock<Block> LIMELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> LIMELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> LIMELARGETILEBUTTON;
	public static final DeferredBlock<Block> GREENLARGETILESTAIR;
	public static final DeferredBlock<Block> GREENLARGETILESLAB;
	public static final DeferredBlock<Block> GREENLARGETILEWALL;
	public static final DeferredBlock<Block> GREENLARGETILEFENCE;
	public static final DeferredBlock<Block> GREENLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> GREENLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> GREENLARGETILEBUTTON;
	public static final DeferredBlock<Block> CYANLARGETILESTAIR;
	public static final DeferredBlock<Block> CYANLARGETILESLAB;
	public static final DeferredBlock<Block> CYANLARGETILEWALL;
	public static final DeferredBlock<Block> CYANLARGETILEFENCE;
	public static final DeferredBlock<Block> CYANLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> CYANLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> CYANLARGETILEBUTTON;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILESTAIR;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILESLAB;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEWALL;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEFENCE;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILEBUTTON;
	public static final DeferredBlock<Block> BLUELARGETILESTAIR;
	public static final DeferredBlock<Block> BLUELARGETILESLAB;
	public static final DeferredBlock<Block> BLUELARGETILEWALL;
	public static final DeferredBlock<Block> BLUELARGETILEFENCE;
	public static final DeferredBlock<Block> BLUELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> BLUELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> BLUELARGETILEBUTTON;
	public static final DeferredBlock<Block> PURPLELARGETILESTAIR;
	public static final DeferredBlock<Block> PURPLELARGETILESLAB;
	public static final DeferredBlock<Block> PURPLELARGETILEWALL;
	public static final DeferredBlock<Block> PURPLELARGETILEFENCE;
	public static final DeferredBlock<Block> PURPLELARGETILEFENCEGATE;
	public static final DeferredBlock<Block> PURPLELARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> PURPLELARGETILEBUTTON;
	public static final DeferredBlock<Block> MAGENTALARGETILESTAIR;
	public static final DeferredBlock<Block> MAGENTALARGETILESLAB;
	public static final DeferredBlock<Block> MAGENTALARGETILEWALL;
	public static final DeferredBlock<Block> MAGENTALARGETILEFENCE;
	public static final DeferredBlock<Block> MAGENTALARGETILEFENCEGATE;
	public static final DeferredBlock<Block> MAGENTALARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> MAGENTALARGETILEBUTTON;
	public static final DeferredBlock<Block> PINKLARGETILESTAIR;
	public static final DeferredBlock<Block> PINKLARGETILESLAB;
	public static final DeferredBlock<Block> PINKLARGETILEWALL;
	public static final DeferredBlock<Block> PINKLARGETILEFENCE;
	public static final DeferredBlock<Block> PINKLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> PINKLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> PINKLARGETILEBUTTON;
	public static final DeferredBlock<Block> CEILING_TILE_FENCE;
	public static final DeferredBlock<Block> CEILING_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> TILE_FENCE;
	public static final DeferredBlock<Block> TILE_FENCE_GATE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILESTAIR;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILESLAB;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEWALL;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEFENCE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILEBUTTON;
	public static final DeferredBlock<Block> WHITELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> INDUSTRIALLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> LIGHTGRAYLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> GRAYLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> BLACKLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> BROWNLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> REDLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> ORANGELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> YELLOWLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> LIMELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> GREENLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> CYANLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> LIGHTBLUELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> BLUELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> PURPLELARGETILETRAPDOOR;
	public static final DeferredBlock<Block> MAGENTALARGETILETRAPDOOR;
	public static final DeferredBlock<Block> PINKLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> WHITE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> GRAY_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> BLACK_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> BROWN_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> RED_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> ORANGE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> YELLOW_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> LIME_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> GREEN_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> CYAN_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> BLUE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> PURPLE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> MAGENTA_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> PINK_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> CHERRY_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> CEILING_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> TILE_TRAPDOOR;
	public static final DeferredBlock<Block> CHERRYLARGETILE;
	public static final DeferredBlock<Block> CHERRYLARGETILESTAIR;
	public static final DeferredBlock<Block> CHERRYLARGETILESLAB;
	public static final DeferredBlock<Block> CHERRYLARGETILEWALL;
	public static final DeferredBlock<Block> CHERRYLARGETILEFENCE;
	public static final DeferredBlock<Block> CHERRYLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> CHERRYLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> CHERRYLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> CHERRYLARGETILEBUTTON;
	public static final DeferredBlock<Block> SECURE_STORAGE_BLOCK;
	public static final DeferredBlock<Block> TEAL_BRICKS;
	public static final DeferredBlock<Block> TEALLARGETILE;
	public static final DeferredBlock<Block> TEALLARGETILESTAIR;
	public static final DeferredBlock<Block> TEALLARGETILESLAB;
	public static final DeferredBlock<Block> TEALLARGETILEWALL;
	public static final DeferredBlock<Block> TEALLARGETILEFENCE;
	public static final DeferredBlock<Block> TEALLARGETILEFENCEGATE;
	public static final DeferredBlock<Block> TEALLARGETILETRAPDOOR;
	public static final DeferredBlock<Block> TEALLARGETILEPRESSUREPLATE;
	public static final DeferredBlock<Block> TEALLARGETILEBUTTON;
	public static final DeferredBlock<Block> TEAL_BRICK_STAIRS;
	public static final DeferredBlock<Block> TEAL_BRICK_SLAB;
	public static final DeferredBlock<Block> TEAL_BRICK_WALL;
	public static final DeferredBlock<Block> TEAL_BRICK_FENCE;
	public static final DeferredBlock<Block> TEAL_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> TEAL_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> TEAL_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> TEAL_BRICK_BUTTON;
	static {
		BANANA_PLANT = register("banana_plant", BannanaplantBlock::new);
		ACID = register("acid", AcidBlock::new);
		RED_BRICKS = register("red_bricks", RedbricksBlock::new);
		ORANGE_BRICKS = register("orange_bricks", OrangebricksBlock::new);
		YELLOW_BRICKS = register("yellow_bricks", YellowbricksBlock::new);
		GREEN_BRICKS = register("green_bricks", GreenbricksBlock::new);
		LIGHT_BLUE_BRICKS = register("light_blue_bricks", LightbluebricksBlock::new);
		BLUE_BRICKS = register("blue_bricks", BluebricksBlock::new);
		MAGENTA_BRICKS = register("magenta_bricks", MagentabricksBlock::new);
		PINK_BRICKS = register("pink_bricks", PinkbricksBlock::new);
		BROWN_BRICKS = register("brown_bricks", BrownbricksBlock::new);
		BLACK_BRICKS = register("black_bricks", BlackbricksBlock::new);
		INDUSTRIAL_BRICKS = register("industrial_bricks", IndustrialbricksBlock::new);
		COMPUTER = register("computer", ComputerBlock::new);
		TILES = register("tiles", TilesBlock::new);
		CEILING_TILES = register("ceiling_tiles", CeilingtilesBlock::new);
		AUTHENTICATOR = register("authenticator", AuthenticatorblockBlock::new);
		RED_BRICK_SLAB = register("red_brick_slab", RedbrickslabBlock::new);
		RED_BRICK_STAIRS = register("red_brick_stairs", RedbrickstairBlock::new);
		ORANGE_BRICK_SLAB = register("orange_brick_slab", OrangebrickslabBlock::new);
		ORANGE_BRICK_STAIRS = register("orange_brick_stairs", OrangebrickstairBlock::new);
		YELLOW_BRICK_SLAB = register("yellow_brick_slab", YellowbrickslabBlock::new);
		YELLOW_BRICK_STAIRS = register("yellow_brick_stairs", YellowbrickstairBlock::new);
		LIGHT_BLUE_BRICK_SLAB = register("light_blue_brick_slab", LightbluebrickslabBlock::new);
		LIGHT_BLUE_BRICK_STAIRS = register("light_blue_brick_stairs", LightbluebrickstairBlock::new);
		BLUE_BRICK_SLAB = register("blue_brick_slab", BluebrickslabBlock::new);
		BLUE_BRICK_STAIRS = register("blue_brick_stairs", BluebrickstairBlock::new);
		MAGENTA_BRICK_SLAB = register("magenta_brick_slab", MagentabrickslabBlock::new);
		MAGENTA_BRICK_STAIRS = register("magenta_brick_stairs", MagentabrickstairBlock::new);
		PINK_BRICK_SLAB = register("pink_brick_slab", PinkbrickslabBlock::new);
		PINK_BRICK_STAIRS = register("pink_brick_stairs", PinkbrickstairBlock::new);
		BROWN_BRICK_SLAB = register("brown_brick_slab", BrownbrickslabBlock::new);
		BROWN_BRICK_STAIRS = register("brown_brick_stairs", BrownbrickstairBlock::new);
		BLACK_BRICK_SLAB = register("black_brick_slab", BlackbrickslabBlock::new);
		BLACK_BRICK_STAIRS = register("black_brick_stairs", BlackbrickstairBlock::new);
		INDUSTRIAL_BRICK_SLAB = register("industrial_brick_slab", IndustrialbrickslabBlock::new);
		INDUSTRIAL_BRICK_STAIRS = register("industrial_brick_stairs", IndustrialbrickstairBlock::new);
		TILE_SLAB = register("tile_slab", TileslabBlock::new);
		TILE_STAIR = register("tile_stair", TilestairBlock::new);
		CEILING_TILE_SLAB = register("ceiling_tile_slab", CeilingtileslabBlock::new);
		CEILING_TILE_STAIR = register("ceiling_tile_stair", CeilingtilestairBlock::new);
		WHITE_BRICKS = register("white_bricks", WhitebricksBlock::new);
		LIGHT_GRAY_BRICKS = register("light_gray_bricks", LightGrayBricksBlock::new);
		GRAY_BRICKS = register("gray_bricks", GrayBricksBlock::new);
		LIME_BRICKS = register("lime_bricks", LimeBricksBlock::new);
		CYAN_BRICKS = register("cyan_bricks", CyanBricksBlock::new);
		CHERRY_BRICKS = register("cherry_bricks", CherryBricksBlock::new);
		PURPLE_BRICKS = register("purple_bricks", PurpleBricksNewBlock::new);
		LIME_BRICK_SLAB = register("lime_brick_slab", LimeBrickSlabBlock::new);
		LIME_BRICK_STAIRS = register("lime_brick_stairs", LimeBrickStairBlock::new);
		GREEN_BRICK_SLAB = register("green_brick_slab", GreenbricksSlabBlock::new);
		GREEN_BRICK_STAIRS = register("green_brick_stairs", GreenbricksstairBlock::new);
		CYAN_BRICK_SLAB = register("cyan_brick_slab", CyanbrickslabBlock::new);
		CYAN_BRICK_STAIRS = register("cyan_brick_stairs", CyanbrickstairBlock::new);
		PURPLE_BRICK_SLAB = register("purple_brick_slab", PurplebrickslabBlock::new);
		PURPLE_BRICK_STAIRS = register("purple_brick_stairs", PurplebrickstairBlock::new);
		WHITE_BRICK_SLAB = register("white_brick_slab", WhitebrickslabBlock::new);
		WHITE_BRICK_STAIRS = register("white_brick_stairs", WhitebrickstairBlock::new);
		LIGHT_GRAY_BRICK_SLAB = register("light_gray_brick_slab", LightgraybrickslabBlock::new);
		LIGHT_GRAY_BRICK_STAIRS = register("light_gray_brick_stairs", LightgraybrickstairBlock::new);
		GRAY_BRICK_SLAB = register("gray_brick_slab", GraybrickslabBlock::new);
		GRAY_BRICK_STAIRS = register("gray_brick_stairs", GraybrickstairBlock::new);
		CHERRY_BRICK_SLAB = register("cherry_brick_slab", CherrybrickslabBlock::new);
		CHERRY_BRICK_STAIR = register("cherry_brick_stair", CherrybrickstairBlock::new);
		RED_BRICK_WALL = register("red_brick_wall", RedbrickwallBlock::new);
		ORANGE_BRICK_WALL = register("orange_brick_wall", OrangebrickwallBlock::new);
		YELLOW_BRICK_WALL = register("yellow_brick_wall", YellowbrickwallBlock::new);
		GREEN_BRICK_WALL = register("green_brick_wall", GreenbrickwallBlock::new);
		LIGHT_BLUE_BRICK_WALL = register("light_blue_brick_wall", LightbluebrickwallBlock::new);
		BLUE_BRICK_WALL = register("blue_brick_wall", BluebrickwallBlock::new);
		MAGENTA_BRICK_WALL = register("magenta_brick_wall", MagentabrickwallBlock::new);
		PINK_BRICK_WALL = register("pink_brick_wall", PinkbrickwallBlock::new);
		BROWN_BRICK_WALL = register("brown_brick_wall", BrownbrickwallBlock::new);
		BLACK_BRICK_WALL = register("black_brick_wall", BlackbrickwallBlock::new);
		INDUSTRIAL_BRICK_WALL = register("industrial_brick_wall", IndustrialbrickwallBlock::new);
		WHITE_BRICK_WALL = register("white_brick_wall", WhitebrickwallBlock::new);
		LIGHT_GRAY_BRICK_WALL = register("light_gray_brick_wall", LightgraybrickwallBlock::new);
		GRAY_BRICK_WALL = register("gray_brick_wall", GraybrickwallBlock::new);
		LIME_BRICK_WALL = register("lime_brick_wall", LimebrickwallBlock::new);
		CYAN_BRICK_WALL = register("cyan_brick_wall", CyanbrickwallBlock::new);
		CHERRY_BRICK_WALL = register("cherry_brick_wall", CherrybrickwallBlock::new);
		PURPLE_BRICK_WALL = register("purple_brick_wall", PurplebrickwallBlock::new);
		CEILING_TILE_WALL = register("ceiling_tile_wall", CeilingtilewallBlock::new);
		TILE_WALL = register("tile_wall", TilewallBlock::new);
		INDUSTRIAL_BRICK_FENCE = register("industrial_brick_fence", IndustrialbrickfenceBlock::new);
		INDUSTRIAL_BRICK_FENCE_GATE = register("industrial_brick_fence_gate", IndustrialbrickfencegateBlock::new);
		INDUSTRIAL_BRICK_BUTTON = register("industrial_brick_button", IndustrialbrickbuttonBlock::new);
		INDUSTRIAL_BRICK_PRESSURE_PLATE = register("industrial_brick_pressure_plate", IndustrialbrickpreasureplateBlock::new);
		RED_BRICK_FENCE = register("red_brick_fence", RedbrickfenceBlock::new);
		ORANGE_BRICK_FENCE = register("orange_brick_fence", OrangebrickfenceBlock::new);
		YELLOW_BRICK_FENCE = register("yellow_brick_fence", YellowbrickfenceBlock::new);
		GREEN_BRICK_FENCE = register("green_brick_fence", GreenbrickfenceBlock::new);
		LIGHT_BLUE_BRICK_FENCE = register("light_blue_brick_fence", LightbluebrickfenceBlock::new);
		BLUE_BRICK_FENCE = register("blue_brick_fence", BluebrickfenceBlock::new);
		MAGENTA_BRICK_FENCE = register("magenta_brick_fence", MagentabrickfenceBlock::new);
		PINK_BRICK_FENCE = register("pink_brick_fence", PinkbrickfenceBlock::new);
		BROWN_BRICK_FENCE = register("brown_brick_fence", BrownbrickfenceBlock::new);
		BLACK_BRICK_FENCE = register("black_brick_fence", BlackbrickfenceBlock::new);
		WHITE_BRICK_FENCE = register("white_brick_fence", WhitebrickfenceBlock::new);
		LIGHT_GRAY_BRICK_FENCE = register("light_gray_brick_fence", LightgraybrickfenceBlock::new);
		GRAY_BRICK_FENCE = register("gray_brick_fence", GraybrickfenceBlock::new);
		LIME_BRICK_FENCE = register("lime_brick_fence", LimebrickfenceBlock::new);
		CYAN_BRICK_FENCE = register("cyan_brick_fence", CyanbrickfenceBlock::new);
		PURPLE_BRICK_FENCE = register("purple_brick_fence", PurplebrickfenceBlock::new);
		CHERRY_BRICK_FENCE = register("cherry_brick_fence", CherrybrickfenceBlock::new);
		RED_BRICK_FENCE_GATE = register("red_brick_fence_gate", RedbrickfencegateBlock::new);
		ORANGE_BRICK_FENCE_GATE = register("orange_brick_fence_gate", OrangebrickfencegateBlock::new);
		YELLOW_BRICK_FENCE_GATE = register("yellow_brick_fence_gate", YellowbrickfenceagteBlock::new);
		GREEN_BRICK_FENCE_GATE = register("green_brick_fence_gate", GreenbrickfencegateBlock::new);
		LIGHT_BLUE_BRICK_FENCE_GATE = register("light_blue_brick_fence_gate", LightbluebrickfencegateBlock::new);
		BLUE_BRICK_FENCE_GATE = register("blue_brick_fence_gate", BluebrickfencegateBlock::new);
		MAGENTA_BRICK_FENCE_GATE = register("magenta_brick_fence_gate", MagentabrickfencegateBlock::new);
		PINK_BRICK_FENCE_GATE = register("pink_brick_fence_gate", PinkbrickfencegateBlock::new);
		BROWN_BRICK_FENCE_GATE = register("brown_brick_fence_gate", BrownbrickfencegateBlock::new);
		BLACK_BRICK_FENCE_GATE = register("black_brick_fence_gate", BlackbrickfencegateBlock::new);
		WHITE_BRICK_FENCE_GATE = register("white_brick_fence_gate", WhitebrickfencegateBlock::new);
		LIGHT_GRAY_BRICK_FENCE_GATE = register("light_gray_brick_fence_gate", LightgraybrickfencegateBlock::new);
		GRAY_BRICK_FENCE_GATE = register("gray_brick_fence_gate", GraybrickfencegateBlock::new);
		LIME_BRICK_FENCE_GATE = register("lime_brick_fence_gate", LimebrickfencegateBlock::new);
		CYAN_BRICK_FENCE_GATE = register("cyan_brick_fence_gate", CyanbrickfencegateBlock::new);
		PURPLE_BRICK_FENCE_GATE = register("purple_brick_fence_gate", PurplebrickfencegateBlock::new);
		CHERRY_BRICK_FENCE_GATE = register("cherry_brick_fence_gate", CherrybrickfencegateBlock::new);
		RED_BRICK_PRESSURE_PLATE = register("red_brick_pressure_plate", RedbrickpreasureplateBlock::new);
		ORANGE_BRICK_PRESSURE_PLATE = register("orange_brick_pressure_plate", OrangebrickfencegatepreasureplateBlock::new);
		YELLOW_BRICK_PRESSURE_PLATE = register("yellow_brick_pressure_plate", YellowbrickfenceagtepreasureplateBlock::new);
		GREEN_BRICK_PRESSURE_PLATE = register("green_brick_pressure_plate", GreenbrickpreasureplateBlock::new);
		LIGHT_BLUE_BRICK_PRESSURE_PLATE = register("light_blue_brick_pressure_plate", LightbluebrickpreasureplateBlock::new);
		BLUE_BRICK_PRESSURE_PLATE = register("blue_brick_pressure_plate", BluebrickpreasureplateBlock::new);
		MAGENTA_BRICK_PRESSURE_PLATE = register("magenta_brick_pressure_plate", MagentabrickpreasureplateBlock::new);
		PINK_BRICK_PRESSURE_PLATE = register("pink_brick_pressure_plate", PinkbrickpreasureplateBlock::new);
		BROWN_BRICK_PRESSURE_PLATE = register("brown_brick_pressure_plate", BrownbrickpreasureplateBlock::new);
		BLACK_BRICK_PRESSURE_PLATE = register("black_brick_pressure_plate", BlackbrickpreasureplateBlock::new);
		WHITE_BRICK_PRESSURE_PLATE = register("white_brick_pressure_plate", WhitebrickpreasureplateBlock::new);
		LIGHT_GRAY_BRICK_PRESSURE_PLATE = register("light_gray_brick_pressure_plate", LightgraybrickpreasureplateBlock::new);
		GRAY_BRICK_PRESSURE_PLATE = register("gray_brick_pressure_plate", GraybrickpreasureplateBlock::new);
		LIME_BRICK_PRESSURE_PLATE = register("lime_brick_pressure_plate", LimebrickpreasureplateBlock::new);
		CYAN_BRICK_PRESSURE_PLATE = register("cyan_brick_pressure_plate", CyanbrickpreasureplateBlock::new);
		PURPLE_BRICK_PRESSURE_PLATE = register("purple_brick_pressure_plate", PurplebrickpreasureplateBlock::new);
		CHERRY_BRICK_PRESSURE_PLATE = register("cherry_brick_pressure_plate", CherrybrickpreasureplateBlock::new);
		RED_BRICK_BUTTON = register("red_brick_button", RedbrickbuttonBlock::new);
		ORANGE_BRICK_BUTTON = register("orange_brick_button", OrangebrickbuttonBlock::new);
		YELLOW_BRICK_BUTTON = register("yellow_brick_button", YellowbrickbuttonBlock::new);
		GREEN_BRICK_BUTTON = register("green_brick_button", GreenbrickbuttonBlock::new);
		LIGHT_BLUE_BRICK_BUTTON = register("light_blue_brick_button", LightbluebrickbuttonBlock::new);
		BLUE_BRICK_BUTTON = register("blue_brick_button", BluebrickbuttonBlock::new);
		MAGENTA_BRICK_BUTTON = register("magenta_brick_button", MagentabrickbuttonBlock::new);
		PINK_BRICK_BUTTON = register("pink_brick_button", PinkbrickbuttonBlock::new);
		BROWN_BRICK_BUTTON = register("brown_brick_button", BrownbrickbuttonBlock::new);
		BLACK_BRICK_BUTTON = register("black_brick_button", BlackbrickbuttonBlock::new);
		WHITE_BRICK_BUTTON = register("white_brick_button", WhitebrickbuttonBlock::new);
		LIGHT_GRAY_BRICK_BUTTON = register("light_gray_brick_button", LightgraybrickbuttonBlock::new);
		GRAY_BRICK_BUTTON = register("gray_brick_button", GraybrickbuttonBlock::new);
		LIME_BRICK_BUTTON = register("lime_brick_button", LimebrickbuttonBlock::new);
		CYAN_BRICK_BUTTON = register("cyan_brick_button", CyanbrickbuttonBlock::new);
		PURPLE_BRICK_BUTTON = register("purple_brick_button", PurplebrickbuttonBlock::new);
		CHERRY_BRICK_BUTTON = register("cherry_brick_button", CherrybrickbuttonBlock::new);
		TILE_PRESSURE_PLATE = register("tile_pressure_plate", TilepressureplateBlock::new);
		TILE_BUTTON = register("tile_button", TilebuttonBlock::new);
		CEILING_TILE_PRESSURE_PLATE = register("ceiling_tile_pressure_plate", CeilingtilepressureplateBlock::new);
		CEILING_TILE_BUTTON = register("ceiling_tile_button", CeilingtilebuttonBlock::new);
		WHITELARGETILE = register("whitelargetile", LargetileBlock::new);
		WHITELARGETILESTAIR = register("whitelargetilestair", LargetilestairBlock::new);
		WHITELARGETILESLAB = register("whitelargetileslab", LargetileslabBlock::new);
		WHITELARGETILEWALL = register("whitelargetilewall", LargetilewallBlock::new);
		WHITELARGETILEPRESSUREPLATE = register("whitelargetilepressureplate", LargetilepressureplateBlock::new);
		WHITELARGETILEBUTTON = register("whitelargetilebutton", LargetilebuttonBlock::new);
		VARIABLE_LIGHT = register("variable_light", VariablelightBlock::new);
		LIGHTGRAYLARGETILE = register("lightgraylargetile", LightGrayLargeTileBlock::new);
		GRAYLARGETILE = register("graylargetile", GrayLargeTileBlock::new);
		BLACKLARGETILE = register("blacklargetile", BlackLargeTileBlock::new);
		ORANGELARGETILE = register("orangelargetile", OrangeLargeTileBlock::new);
		MAGENTALARGETILE = register("magentalargetile", MagentaLargeTileBlock::new);
		LIGHTBLUELARGETILE = register("lightbluelargetile", LightBlueLargeTileBlock::new);
		BLUELARGETILE = register("bluelargetile", BlueLargeTileBlock::new);
		YELLOWLARGETILE = register("yellowlargetile", YellowLargeTileBlock::new);
		LIMELARGETILE = register("limelargetile", LimeLargeTileBlock::new);
		GREENLARGETILE = register("greenlargetile", GreenLargeTileBlock::new);
		PINKLARGETILE = register("pinklargetile", PinkLargeTileBlock::new);
		CYANLARGETILE = register("cyanlargetile", CyanLargeTileBlock::new);
		PURPLELARGETILE = register("purplelargetile", PurpleLargeTileBlock::new);
		BROWNLARGETILE = register("brownlargetile", BrownLargeTileBlock::new);
		REDLARGETILE = register("redlargetile", RedLargeTileBlock::new);
		LARGETILEFENCE = register("largetilefence", LargetilefenceBlock::new);
		LARGETILEFENCEGATE = register("largetilefencegate", LargetilefencegateBlock::new);
		LIGHTGRAYLARGETILESTAIR = register("lightgraylargetilestair", LightGrayLargeTileStairBlock::new);
		LIGHTGRAYLARGETILESLAB = register("lightgraylargetileslab", LightGrayLargeTileSlabBlock::new);
		LIGHTGRAYLARGETILEWALL = register("lightgraylargetilewall", LightGrayLargeTileWallBlock::new);
		LIGHTGRAYLARGETILEFENCE = register("lightgraylargetilefence", LightGrayLargeTileFenceBlock::new);
		LIGHTGRAYLARGETILEFENCEGATE = register("lightgraylargetilefencegate", LightGrayLargeTileFenceGateBlock::new);
		LIGHTGRAYLARGETILEPRESSUREPLATE = register("lightgraylargetilepressureplate", LightGrayLargeTilePressurePlateBlock::new);
		LIGHTGRAYLARGETILEBUTTON = register("lightgraylargetilebutton", LightGrayLargeTileButtonBlock::new);
		GRAYLARGETILESTAIR = register("graylargetilestair", GrayLargeTileStairBlock::new);
		GRAYLARGETILESLAB = register("graylargetileslab", GrayLargeTileSlabBlock::new);
		GRAYLARGETILEWALL = register("graylargetilewall", GrayLargeTileWallBlock::new);
		GRAYLARGETILEFENCE = register("graylargetilefence", GrayLargeTileFenceBlock::new);
		GRAYLARGETILEFENCEGATE = register("graylargetilefencegate", GrayLargeTileFenceGateBlock::new);
		GRAYLARGETILEPRESSUREPLATE = register("graylargetilepressureplate", GrayLargeTilePressurePlateBlock::new);
		GRAYLARGETILEBUTTON = register("graylargetilebutton", GrayLargeTileButtonBlock::new);
		BLACKLARGETILESTAIR = register("blacklargetilestair", BlackLargeTileStairBlock::new);
		BLACKLARGETILESLAB = register("blacklargetileslab", BlackLargeTileSlabBlock::new);
		BLACKLARGETILEWALL = register("blacklargetilewall", BlackLargeTileWallBlock::new);
		BLACKLARGETILEFENCE = register("blacklargetilefence", BlackLargeTileFenceBlock::new);
		BLACKLARGETILEFENCEGATE = register("blacklargetilefencegate", BlackLargeTileFenceGateBlock::new);
		BLACKLARGETILEPRESSUREPLATE = register("blacklargetilepressureplate", BlackLargeTilePressurePlateBlock::new);
		BLACKLARGETILEBUTTON = register("blacklargetilebutton", BlackLargeTileButtonBlock::new);
		BROWNLARGETILESTAIR = register("brownlargetilestair", BrownLargeTileStairBlock::new);
		BROWNLARGETILESLAB = register("brownlargetileslab", BrownLargeTileSlabBlock::new);
		BROWNLARGETILEWALL = register("brownlargetilewall", BrownLargeTileWallBlock::new);
		BROWNLARGETILEFENCE = register("brownlargetilefence", BrownLargeTileFenceBlock::new);
		BROWNLARGETILEFENCEGATE = register("brownlargetilefencegate", BrownLargeTileFenceGateBlock::new);
		BROWNLARGETILEPRESSUREPLATE = register("brownlargetilepressureplate", BrownLargeTilePressurePlateBlock::new);
		BROWNLARGETILEBUTTON = register("brownlargetilebutton", BrownLargeTileButtonBlock::new);
		REDLARGETILESTAIR = register("redlargetilestair", RedLargeTileStairBlock::new);
		REDLARGETILESLAB = register("redlargetileslab", RedLargeTileSlabBlock::new);
		REDLARGETILEWALL = register("redlargetilewall", RedLargeTileWallBlock::new);
		REDLARGETILEFENCE = register("redlargetilefence", RedLargeTileFenceBlock::new);
		REDLARGETILEFENCEGATE = register("redlargetilefencegate", RedLargeTileFenceGateBlock::new);
		REDLARGETILEPRESSUREPLATE = register("redlargetilepressureplate", RedLargeTilePressurePlateBlock::new);
		REDLARGETILEBUTTON = register("redlargetilebutton", RedLargeTileButtonBlock::new);
		ORANGELARGETILESTAIR = register("orangelargetilestair", OrangeLargeTileStairBlock::new);
		ORANGELARGETILESLAB = register("orangelargetileslab", OrangeLargeTileSlabBlock::new);
		ORANGELARGETILEWALL = register("orangelargetilewall", OrangeLargeTileWallBlock::new);
		ORANGELARGETILEFENCE = register("orangelargetilefence", OrangeLargeTileFenceBlock::new);
		ORANGELARGETILEFENCEGATE = register("orangelargetilefencegate", OrangeLargeTileFenceGateBlock::new);
		ORANGELARGETILEPRESSUREPLATE = register("orangelargetilepressureplate", OrangeLargeTilePressurePlateBlock::new);
		ORANGELARGETILEBUTTON = register("orangelargetilebutton", OrangeLargeTileButtonBlock::new);
		YELLOWLARGETILESTAIR = register("yellowlargetilestair", YellowLargeTileStairBlock::new);
		YELLOWLARGETILESLAB = register("yellowlargetileslab", YellowLargeTileSlabBlock::new);
		YELLOWLARGETILEWALL = register("yellowlargetilewall", YellowLargeTileWallBlock::new);
		YELLOWLARGETILEFENCE = register("yellowlargetilefence", YellowLargeTileFenceBlock::new);
		YELLOWLARGETILEFENCEGATE = register("yellowlargetilefencegate", YellowLargeTileFenceGateBlock::new);
		YELLOWLARGETILEPRESSUREPLATE = register("yellowlargetilepressureplate", YellowLargeTilePressurePlateBlock::new);
		YELLOWLARGETILEBUTTON = register("yellowlargetilebutton", YellowLargeTileButtonBlock::new);
		LIMELARGETILESTAIR = register("limelargetilestair", LimeLargeTileStairBlock::new);
		LIMELARGETILESLAB = register("limelargetileslab", LimeLargeTileSlabBlock::new);
		LIMELARGETILEWALL = register("limelargetilewall", LimeLargeTileWallBlock::new);
		LIMELARGETILEFENCE = register("limelargetilefence", LimeLargeTileFenceBlock::new);
		LIMELARGETILEFENCEGATE = register("limelargetilefencegate", LimeLargeTileFenceGateBlock::new);
		LIMELARGETILEPRESSUREPLATE = register("limelargetilepressureplate", LimeLargeTilePressurePlateBlock::new);
		LIMELARGETILEBUTTON = register("limelargetilebutton", LimeLargeTileButtonBlock::new);
		GREENLARGETILESTAIR = register("greenlargetilestair", GreenLargeTileStairBlock::new);
		GREENLARGETILESLAB = register("greenlargetileslab", GreenLargeTileSlabBlock::new);
		GREENLARGETILEWALL = register("greenlargetilewall", GreenLargeTileWallBlock::new);
		GREENLARGETILEFENCE = register("greenlargetilefence", GreenLargeTileFenceBlock::new);
		GREENLARGETILEFENCEGATE = register("greenlargetilefencegate", GreenLargeTileFenceGateBlock::new);
		GREENLARGETILEPRESSUREPLATE = register("greenlargetilepressureplate", GreenLargeTilePressurePlateBlock::new);
		GREENLARGETILEBUTTON = register("greenlargetilebutton", GreenLargeTileButtonBlock::new);
		CYANLARGETILESTAIR = register("cyanlargetilestair", CyanLargeTileStairBlock::new);
		CYANLARGETILESLAB = register("cyanlargetileslab", CyanLargeTileSlabBlock::new);
		CYANLARGETILEWALL = register("cyanlargetilewall", CyanLargeTileWallBlock::new);
		CYANLARGETILEFENCE = register("cyanlargetilefence", CyanLargeTileFenceBlock::new);
		CYANLARGETILEFENCEGATE = register("cyanlargetilefencegate", CyanLargeTileFenceGateBlock::new);
		CYANLARGETILEPRESSUREPLATE = register("cyanlargetilepressureplate", CyanLargeTilePressurePlateBlock::new);
		CYANLARGETILEBUTTON = register("cyanlargetilebutton", CyanLargeTileButtonBlock::new);
		LIGHTBLUELARGETILESTAIR = register("lightbluelargetilestair", LightBlueLargeTileStairBlock::new);
		LIGHTBLUELARGETILESLAB = register("lightbluelargetileslab", LightBlueLargeTileSlabBlock::new);
		LIGHTBLUELARGETILEWALL = register("lightbluelargetilewall", LightBlueLargeTileWallBlock::new);
		LIGHTBLUELARGETILEFENCE = register("lightbluelargetilefence", LightBlueLargeTileFenceBlock::new);
		LIGHTBLUELARGETILEFENCEGATE = register("lightbluelargetilefencegate", LightBlueLargeTileFenceGateBlock::new);
		LIGHTBLUELARGETILEPRESSUREPLATE = register("lightbluelargetilepressureplate", LightBlueLargeTilePressurePlateBlock::new);
		LIGHTBLUELARGETILEBUTTON = register("lightbluelargetilebutton", LightBlueLargeTileButtonBlock::new);
		BLUELARGETILESTAIR = register("bluelargetilestair", BlueLargeTileStairBlock::new);
		BLUELARGETILESLAB = register("bluelargetileslab", BlueLargeTileSlabBlock::new);
		BLUELARGETILEWALL = register("bluelargetilewall", BlueLargeTileWallBlock::new);
		BLUELARGETILEFENCE = register("bluelargetilefence", BlueLargeTileFenceBlock::new);
		BLUELARGETILEFENCEGATE = register("bluelargetilefencegate", BlueLargeTileFenceGateBlock::new);
		BLUELARGETILEPRESSUREPLATE = register("bluelargetilepressureplate", BlueLargeTilePressurePlateBlock::new);
		BLUELARGETILEBUTTON = register("bluelargetilebutton", BlueLargeTileButtonBlock::new);
		PURPLELARGETILESTAIR = register("purplelargetilestair", PurpleLargeTileStairBlock::new);
		PURPLELARGETILESLAB = register("purplelargetileslab", PurpleLargeTileSlabBlock::new);
		PURPLELARGETILEWALL = register("purplelargetilewall", PurpleLargeTileWallBlock::new);
		PURPLELARGETILEFENCE = register("purplelargetilefence", PurpleLargeTileFenceBlock::new);
		PURPLELARGETILEFENCEGATE = register("purplelargetilefencegate", PurpleLargeTileFenceGateBlock::new);
		PURPLELARGETILEPRESSUREPLATE = register("purplelargetilepressureplate", PurpleLargeTilePressurePlateBlock::new);
		PURPLELARGETILEBUTTON = register("purplelargetilebutton", PurpleLargeTileButtonBlock::new);
		MAGENTALARGETILESTAIR = register("magentalargetilestair", MagentaLargeTileStairBlock::new);
		MAGENTALARGETILESLAB = register("magentalargetileslab", MagentaLargeTileSlabBlock::new);
		MAGENTALARGETILEWALL = register("magentalargetilewall", MagentaLargeTileWallBlock::new);
		MAGENTALARGETILEFENCE = register("magentalargetilefence", MagentaLargeTileFenceBlock::new);
		MAGENTALARGETILEFENCEGATE = register("magentalargetilefencegate", MagentaLargeTileFenceGateBlock::new);
		MAGENTALARGETILEPRESSUREPLATE = register("magentalargetilepressureplate", MagentaLargeTilePressurePlateBlock::new);
		MAGENTALARGETILEBUTTON = register("magentalargetilebutton", MagentaLargeTileButtonBlock::new);
		PINKLARGETILESTAIR = register("pinklargetilestair", PinkLargeTileStairBlock::new);
		PINKLARGETILESLAB = register("pinklargetileslab", PinkLargeTileSlabBlock::new);
		PINKLARGETILEWALL = register("pinklargetilewall", PinkLargeTileWallBlock::new);
		PINKLARGETILEFENCE = register("pinklargetilefence", PinkLargeTileFenceBlock::new);
		PINKLARGETILEFENCEGATE = register("pinklargetilefencegate", PinkLargeTileFenceGateBlock::new);
		PINKLARGETILEPRESSUREPLATE = register("pinklargetilepressureplate", PinkLargeTilePressurePlateBlock::new);
		PINKLARGETILEBUTTON = register("pinklargetilebutton", PinkLargeTileButtonBlock::new);
		CEILING_TILE_FENCE = register("ceiling_tile_fence", CeilingtilefenceBlock::new);
		CEILING_TILE_FENCE_GATE = register("ceiling_tile_fence_gate", CeilingtilefencegateBlock::new);
		TILE_FENCE = register("tile_fence", TilefenceBlock::new);
		TILE_FENCE_GATE = register("tile_fence_gate", TilefencegateBlock::new);
		INDUSTRIALLARGETILE = register("industriallargetile", IndustrialLargeTileBlock::new);
		INDUSTRIALLARGETILESTAIR = register("industriallargetilestair", IndustrialLargeTileStairBlock::new);
		INDUSTRIALLARGETILESLAB = register("industriallargetileslab", IndustrialLargeTileSlabBlock::new);
		INDUSTRIALLARGETILEWALL = register("industriallargetilewall", IndustrialLargeTileWallBlock::new);
		INDUSTRIALLARGETILEFENCE = register("industriallargetilefence", IndustrialLargeTileFenceBlock::new);
		INDUSTRIALLARGETILEFENCEGATE = register("industriallargetilefencegate", IndustrialLargeTileFenceGateBlock::new);
		INDUSTRIALLARGETILEPRESSUREPLATE = register("industriallargetilepressureplate", IndustrialLargeTilePressurePlateBlock::new);
		INDUSTRIALLARGETILEBUTTON = register("industriallargetilebutton", IndustrialLargeTileButtonBlock::new);
		WHITELARGETILETRAPDOOR = register("whitelargetiletrapdoor", WhitelargetiletrapdoorBlock::new);
		INDUSTRIALLARGETILETRAPDOOR = register("industriallargetiletrapdoor", IndustriallargetiletrapdoorBlock::new);
		LIGHTGRAYLARGETILETRAPDOOR = register("lightgraylargetiletrapdoor", LightgraylargetiletrapdoorBlock::new);
		GRAYLARGETILETRAPDOOR = register("graylargetiletrapdoor", GraylargetiletrapdoorBlock::new);
		BLACKLARGETILETRAPDOOR = register("blacklargetiletrapdoor", BlacklargetiletrapdoorBlock::new);
		BROWNLARGETILETRAPDOOR = register("brownlargetiletrapdoor", BrownlargetiletrapdoorBlock::new);
		REDLARGETILETRAPDOOR = register("redlargetiletrapdoor", RedlargetiletrapdoorBlock::new);
		ORANGELARGETILETRAPDOOR = register("orangelargetiletrapdoor", OrangelargetiletrapdoorBlock::new);
		YELLOWLARGETILETRAPDOOR = register("yellowlargetiletrapdoor", YellowlargetiletrapdoorBlock::new);
		LIMELARGETILETRAPDOOR = register("limelargetiletrapdoor", LimelargetiletrapdoorBlock::new);
		GREENLARGETILETRAPDOOR = register("greenlargetiletrapdoor", GreenlargetiletrapdoorBlock::new);
		CYANLARGETILETRAPDOOR = register("cyanlargetiletrapdoor", CyanlargetiletrapdoorBlock::new);
		LIGHTBLUELARGETILETRAPDOOR = register("lightbluelargetiletrapdoor", LightbluelargetiletrapdoorBlock::new);
		BLUELARGETILETRAPDOOR = register("bluelargetiletrapdoor", BluelargetiletrapdoorBlock::new);
		PURPLELARGETILETRAPDOOR = register("purplelargetiletrapdoor", PurplelargetiletrapdoorBlock::new);
		MAGENTALARGETILETRAPDOOR = register("magentalargetiletrapdoor", MagentalargetiletrapdoorBlock::new);
		PINKLARGETILETRAPDOOR = register("pinklargetiletrapdoor", PinklargetiletrapdoorBlock::new);
		WHITE_BRICK_TRAPDOOR = register("white_brick_trapdoor", WhitebricktrapdoorBlock::new);
		LIGHT_GRAY_BRICK_TRAPDOOR = register("light_gray_brick_trapdoor", LightgraybricktrapdoorBlock::new);
		GRAY_BRICK_TRAPDOOR = register("gray_brick_trapdoor", GraybricktrapdoorBlock::new);
		BLACK_BRICK_TRAPDOOR = register("black_brick_trapdoor", BlackbricktrapdoorBlock::new);
		BROWN_BRICK_TRAPDOOR = register("brown_brick_trapdoor", BrownbricktrapdoorBlock::new);
		RED_BRICK_TRAPDOOR = register("red_brick_trapdoor", RedbricktrapdoorBlock::new);
		ORANGE_BRICK_TRAPDOOR = register("orange_brick_trapdoor", OrangebricktrapdoorBlock::new);
		YELLOW_BRICK_TRAPDOOR = register("yellow_brick_trapdoor", YellowbricktrapdoorBlock::new);
		LIME_BRICK_TRAPDOOR = register("lime_brick_trapdoor", LimebricktrapdoorBlock::new);
		GREEN_BRICK_TRAPDOOR = register("green_brick_trapdoor", GreenbricktrapdoorBlock::new);
		CYAN_BRICK_TRAPDOOR = register("cyan_brick_trapdoor", CyanbricktrapdoorBlock::new);
		LIGHT_BLUE_BRICK_TRAPDOOR = register("light_blue_brick_trapdoor", LightbluebricktrapdoorBlock::new);
		BLUE_BRICK_TRAPDOOR = register("blue_brick_trapdoor", BluebricktrapdoorBlock::new);
		PURPLE_BRICK_TRAPDOOR = register("purple_brick_trapdoor", PurplebricktrapdoorBlock::new);
		MAGENTA_BRICK_TRAPDOOR = register("magenta_brick_trapdoor", MagentabricktrapdoorBlock::new);
		PINK_BRICK_TRAPDOOR = register("pink_brick_trapdoor", PinkbricktrapdoorBlock::new);
		CHERRY_BRICK_TRAPDOOR = register("cherry_brick_trapdoor", CherrybricktrapdoorBlock::new);
		INDUSTRIAL_BRICK_TRAPDOOR = register("industrial_brick_trapdoor", IndustrialbricktrapdoorBlock::new);
		CEILING_TILE_TRAPDOOR = register("ceiling_tile_trapdoor", CeilingtiletrapdoorBlock::new);
		TILE_TRAPDOOR = register("tile_trapdoor", TiletrapdoorBlock::new);
		CHERRYLARGETILE = register("cherrylargetile", CherrylargetileBlock::new);
		CHERRYLARGETILESTAIR = register("cherrylargetilestair", CherrylargetilestairBlock::new);
		CHERRYLARGETILESLAB = register("cherrylargetileslab", CherrylargetileslabBlock::new);
		CHERRYLARGETILEWALL = register("cherrylargetilewall", CherrylargetilewallBlock::new);
		CHERRYLARGETILEFENCE = register("cherrylargetilefence", CherrylargetilefenceBlock::new);
		CHERRYLARGETILEFENCEGATE = register("cherrylargetilefencegate", CherrylargetilefencegateBlock::new);
		CHERRYLARGETILETRAPDOOR = register("cherrylargetiletrapdoor", CherrylargetiletrapdoorBlock::new);
		CHERRYLARGETILEPRESSUREPLATE = register("cherrylargetilepressureplate", CherrylargetilepressureplateBlock::new);
		CHERRYLARGETILEBUTTON = register("cherrylargetilebutton", CherrylargetilebuttonBlock::new);
		SECURE_STORAGE_BLOCK = register("secure_storage_block", SecurestorageblockBlock::new);
		TEAL_BRICKS = register("teal_bricks", TealbricksBlock::new);
		TEALLARGETILE = register("teallargetile", TealLargeTileBlock::new);
		TEALLARGETILESTAIR = register("teallargetilestair", TealLargeTileStairBlock::new);
		TEALLARGETILESLAB = register("teallargetileslab", TeallargetileslabBlock::new);
		TEALLARGETILEWALL = register("teallargetilewall", TeallargetilewallBlock::new);
		TEALLARGETILEFENCE = register("teallargetilefence", TeallargetilefenceBlock::new);
		TEALLARGETILEFENCEGATE = register("teallargetilefencegate", TeallargetilefencegateBlock::new);
		TEALLARGETILETRAPDOOR = register("teallargetiletrapdoor", TeallargetiletrapdoorBlock::new);
		TEALLARGETILEPRESSUREPLATE = register("teallargetilepressureplate", TeallargetilepressureplateBlock::new);
		TEALLARGETILEBUTTON = register("teallargetilebutton", TeallargetilebuttonBlock::new);
		TEAL_BRICK_STAIRS = register("teal_brick_stairs", TealbrickstairBlock::new);
		TEAL_BRICK_SLAB = register("teal_brick_slab", TealbrickslabBlock::new);
		TEAL_BRICK_WALL = register("teal_brick_wall", TealbrickwallBlock::new);
		TEAL_BRICK_FENCE = register("teal_brick_fence", TealbrickfenceBlock::new);
		TEAL_BRICK_FENCE_GATE = register("teal_brick_fence_gate", TealbrickfencegateBlock::new);
		TEAL_BRICK_TRAPDOOR = register("teal_brick_trapdoor", TealbricktrapdoorBlock::new);
		TEAL_BRICK_PRESSURE_PLATE = register("teal_brick_pressure_plate", TealbrickpressureplateBlock::new);
		TEAL_BRICK_BUTTON = register("teal_brick_button", TealbrickbuttonBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			BannanaplantBlock.blockColorLoad(event);
		}
	}
}