/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.ihavenowebsite.omegabird.llamamod.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.ihavenowebsite.omegabird.llamamod.item.inventory.NetheritebackpackInventoryCapability;
import net.ihavenowebsite.omegabird.llamamod.item.inventory.BackpackInventoryCapability;
import net.ihavenowebsite.omegabird.llamamod.item.*;
import net.ihavenowebsite.omegabird.llamamod.LlamamodMod;

import java.util.function.Function;

@EventBusSubscriber
public class LlamamodModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(LlamamodMod.MODID);
	public static final DeferredItem<Item> BANANA_PLANT;
	public static final DeferredItem<Item> BANANA;
	public static final DeferredItem<Item> BACKPACK;
	public static final DeferredItem<Item> NETHERITE_BACKPACK;
	public static final DeferredItem<Item> ACID_BUCKET;
	public static final DeferredItem<Item> RED_BRICKS;
	public static final DeferredItem<Item> ORANGE_BRICKS;
	public static final DeferredItem<Item> YELLOW_BRICKS;
	public static final DeferredItem<Item> GREEN_BRICKS;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICKS;
	public static final DeferredItem<Item> BLUE_BRICKS;
	public static final DeferredItem<Item> MAGENTA_BRICKS;
	public static final DeferredItem<Item> PINK_BRICKS;
	public static final DeferredItem<Item> BROWN_BRICKS;
	public static final DeferredItem<Item> BLACK_BRICKS;
	public static final DeferredItem<Item> INDUSTRIAL_BRICKS;
	public static final DeferredItem<Item> COMPUTER;
	public static final DeferredItem<Item> TILES;
	public static final DeferredItem<Item> FARMSCRAPS;
	public static final DeferredItem<Item> CEILING_TILES;
	public static final DeferredItem<Item> AUTHENTICATOR;
	public static final DeferredItem<Item> PASSWORD_CHANGER;
	public static final DeferredItem<Item> RED_BRICK_SLAB;
	public static final DeferredItem<Item> RED_BRICK_STAIRS;
	public static final DeferredItem<Item> ORANGE_BRICK_SLAB;
	public static final DeferredItem<Item> ORANGE_BRICK_STAIRS;
	public static final DeferredItem<Item> YELLOW_BRICK_SLAB;
	public static final DeferredItem<Item> YELLOW_BRICK_STAIRS;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_SLAB;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_STAIRS;
	public static final DeferredItem<Item> BLUE_BRICK_SLAB;
	public static final DeferredItem<Item> BLUE_BRICK_STAIRS;
	public static final DeferredItem<Item> MAGENTA_BRICK_SLAB;
	public static final DeferredItem<Item> MAGENTA_BRICK_STAIRS;
	public static final DeferredItem<Item> PINK_BRICK_SLAB;
	public static final DeferredItem<Item> PINK_BRICK_STAIRS;
	public static final DeferredItem<Item> BROWN_BRICK_SLAB;
	public static final DeferredItem<Item> BROWN_BRICK_STAIRS;
	public static final DeferredItem<Item> BLACK_BRICK_SLAB;
	public static final DeferredItem<Item> BLACK_BRICK_STAIRS;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_SLAB;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_STAIRS;
	public static final DeferredItem<Item> TILE_SLAB;
	public static final DeferredItem<Item> TILE_STAIR;
	public static final DeferredItem<Item> CEILING_TILE_SLAB;
	public static final DeferredItem<Item> CEILING_TILE_STAIR;
	public static final DeferredItem<Item> WHITE_BRICKS;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICKS;
	public static final DeferredItem<Item> GRAY_BRICKS;
	public static final DeferredItem<Item> LIME_BRICKS;
	public static final DeferredItem<Item> CYAN_BRICKS;
	public static final DeferredItem<Item> CHERRY_BRICKS;
	public static final DeferredItem<Item> PURPLE_BRICKS;
	public static final DeferredItem<Item> LIME_BRICK_SLAB;
	public static final DeferredItem<Item> LIME_BRICK_STAIRS;
	public static final DeferredItem<Item> GREEN_BRICK_SLAB;
	public static final DeferredItem<Item> GREEN_BRICK_STAIRS;
	public static final DeferredItem<Item> CYAN_BRICK_SLAB;
	public static final DeferredItem<Item> CYAN_BRICK_STAIRS;
	public static final DeferredItem<Item> PURPLE_BRICK_SLAB;
	public static final DeferredItem<Item> PURPLE_BRICK_STAIRS;
	public static final DeferredItem<Item> WHITE_BRICK_SLAB;
	public static final DeferredItem<Item> WHITE_BRICK_STAIRS;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_SLAB;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_STAIRS;
	public static final DeferredItem<Item> GRAY_BRICK_SLAB;
	public static final DeferredItem<Item> GRAY_BRICK_STAIRS;
	public static final DeferredItem<Item> CHERRY_BRICK_SLAB;
	public static final DeferredItem<Item> CHERRY_BRICK_STAIR;
	public static final DeferredItem<Item> RED_BRICK_WALL;
	public static final DeferredItem<Item> ORANGE_BRICK_WALL;
	public static final DeferredItem<Item> YELLOW_BRICK_WALL;
	public static final DeferredItem<Item> GREEN_BRICK_WALL;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_WALL;
	public static final DeferredItem<Item> BLUE_BRICK_WALL;
	public static final DeferredItem<Item> MAGENTA_BRICK_WALL;
	public static final DeferredItem<Item> PINK_BRICK_WALL;
	public static final DeferredItem<Item> BROWN_BRICK_WALL;
	public static final DeferredItem<Item> BLACK_BRICK_WALL;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_WALL;
	public static final DeferredItem<Item> WHITE_BRICK_WALL;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_WALL;
	public static final DeferredItem<Item> GRAY_BRICK_WALL;
	public static final DeferredItem<Item> LIME_BRICK_WALL;
	public static final DeferredItem<Item> CYAN_BRICK_WALL;
	public static final DeferredItem<Item> CHERRY_BRICK_WALL;
	public static final DeferredItem<Item> PURPLE_BRICK_WALL;
	public static final DeferredItem<Item> CEILING_TILE_WALL;
	public static final DeferredItem<Item> TILE_WALL;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_FENCE;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_BUTTON;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> RED_BRICK_FENCE;
	public static final DeferredItem<Item> ORANGE_BRICK_FENCE;
	public static final DeferredItem<Item> YELLOW_BRICK_FENCE;
	public static final DeferredItem<Item> GREEN_BRICK_FENCE;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_FENCE;
	public static final DeferredItem<Item> BLUE_BRICK_FENCE;
	public static final DeferredItem<Item> MAGENTA_BRICK_FENCE;
	public static final DeferredItem<Item> PINK_BRICK_FENCE;
	public static final DeferredItem<Item> BROWN_BRICK_FENCE;
	public static final DeferredItem<Item> BLACK_BRICK_FENCE;
	public static final DeferredItem<Item> WHITE_BRICK_FENCE;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_FENCE;
	public static final DeferredItem<Item> GRAY_BRICK_FENCE;
	public static final DeferredItem<Item> LIME_BRICK_FENCE;
	public static final DeferredItem<Item> CYAN_BRICK_FENCE;
	public static final DeferredItem<Item> PURPLE_BRICK_FENCE;
	public static final DeferredItem<Item> CHERRY_BRICK_FENCE;
	public static final DeferredItem<Item> RED_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> ORANGE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> YELLOW_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> GREEN_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> BLUE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> MAGENTA_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> PINK_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> BROWN_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> BLACK_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> WHITE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> GRAY_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> LIME_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> CYAN_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> PURPLE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> CHERRY_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> RED_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> ORANGE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> YELLOW_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> GREEN_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> BLUE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> MAGENTA_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> PINK_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> BROWN_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> BLACK_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> WHITE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> GRAY_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> LIME_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> CYAN_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> PURPLE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> CHERRY_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> RED_BRICK_BUTTON;
	public static final DeferredItem<Item> ORANGE_BRICK_BUTTON;
	public static final DeferredItem<Item> YELLOW_BRICK_BUTTON;
	public static final DeferredItem<Item> GREEN_BRICK_BUTTON;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_BUTTON;
	public static final DeferredItem<Item> BLUE_BRICK_BUTTON;
	public static final DeferredItem<Item> MAGENTA_BRICK_BUTTON;
	public static final DeferredItem<Item> PINK_BRICK_BUTTON;
	public static final DeferredItem<Item> BROWN_BRICK_BUTTON;
	public static final DeferredItem<Item> BLACK_BRICK_BUTTON;
	public static final DeferredItem<Item> WHITE_BRICK_BUTTON;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_BUTTON;
	public static final DeferredItem<Item> GRAY_BRICK_BUTTON;
	public static final DeferredItem<Item> LIME_BRICK_BUTTON;
	public static final DeferredItem<Item> CYAN_BRICK_BUTTON;
	public static final DeferredItem<Item> PURPLE_BRICK_BUTTON;
	public static final DeferredItem<Item> CHERRY_BRICK_BUTTON;
	public static final DeferredItem<Item> TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> TILE_BUTTON;
	public static final DeferredItem<Item> CEILING_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> CEILING_TILE_BUTTON;
	public static final DeferredItem<Item> WHITELARGETILE;
	public static final DeferredItem<Item> WHITELARGETILESTAIR;
	public static final DeferredItem<Item> WHITELARGETILESLAB;
	public static final DeferredItem<Item> WHITELARGETILEWALL;
	public static final DeferredItem<Item> WHITELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> WHITELARGETILEBUTTON;
	public static final DeferredItem<Item> VARIABLE_LIGHT;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILE;
	public static final DeferredItem<Item> GRAYLARGETILE;
	public static final DeferredItem<Item> BLACKLARGETILE;
	public static final DeferredItem<Item> ORANGELARGETILE;
	public static final DeferredItem<Item> MAGENTALARGETILE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILE;
	public static final DeferredItem<Item> BLUELARGETILE;
	public static final DeferredItem<Item> YELLOWLARGETILE;
	public static final DeferredItem<Item> LIMELARGETILE;
	public static final DeferredItem<Item> GREENLARGETILE;
	public static final DeferredItem<Item> PINKLARGETILE;
	public static final DeferredItem<Item> CYANLARGETILE;
	public static final DeferredItem<Item> PURPLELARGETILE;
	public static final DeferredItem<Item> BROWNLARGETILE;
	public static final DeferredItem<Item> REDLARGETILE;
	public static final DeferredItem<Item> LARGETILEFENCE;
	public static final DeferredItem<Item> LARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILESTAIR;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILESLAB;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEWALL;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEFENCE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILEBUTTON;
	public static final DeferredItem<Item> GRAYLARGETILESTAIR;
	public static final DeferredItem<Item> GRAYLARGETILESLAB;
	public static final DeferredItem<Item> GRAYLARGETILEWALL;
	public static final DeferredItem<Item> GRAYLARGETILEFENCE;
	public static final DeferredItem<Item> GRAYLARGETILEFENCEGATE;
	public static final DeferredItem<Item> GRAYLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> GRAYLARGETILEBUTTON;
	public static final DeferredItem<Item> BLACKLARGETILESTAIR;
	public static final DeferredItem<Item> BLACKLARGETILESLAB;
	public static final DeferredItem<Item> BLACKLARGETILEWALL;
	public static final DeferredItem<Item> BLACKLARGETILEFENCE;
	public static final DeferredItem<Item> BLACKLARGETILEFENCEGATE;
	public static final DeferredItem<Item> BLACKLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> BLACKLARGETILEBUTTON;
	public static final DeferredItem<Item> BROWNLARGETILESTAIR;
	public static final DeferredItem<Item> BROWNLARGETILESLAB;
	public static final DeferredItem<Item> BROWNLARGETILEWALL;
	public static final DeferredItem<Item> BROWNLARGETILEFENCE;
	public static final DeferredItem<Item> BROWNLARGETILEFENCEGATE;
	public static final DeferredItem<Item> BROWNLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> BROWNLARGETILEBUTTON;
	public static final DeferredItem<Item> REDLARGETILESTAIR;
	public static final DeferredItem<Item> REDLARGETILESLAB;
	public static final DeferredItem<Item> REDLARGETILEWALL;
	public static final DeferredItem<Item> REDLARGETILEFENCE;
	public static final DeferredItem<Item> REDLARGETILEFENCEGATE;
	public static final DeferredItem<Item> REDLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> REDLARGETILEBUTTON;
	public static final DeferredItem<Item> ORANGELARGETILESTAIR;
	public static final DeferredItem<Item> ORANGELARGETILESLAB;
	public static final DeferredItem<Item> ORANGELARGETILEWALL;
	public static final DeferredItem<Item> ORANGELARGETILEFENCE;
	public static final DeferredItem<Item> ORANGELARGETILEFENCEGATE;
	public static final DeferredItem<Item> ORANGELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> ORANGELARGETILEBUTTON;
	public static final DeferredItem<Item> YELLOWLARGETILESTAIR;
	public static final DeferredItem<Item> YELLOWLARGETILESLAB;
	public static final DeferredItem<Item> YELLOWLARGETILEWALL;
	public static final DeferredItem<Item> YELLOWLARGETILEFENCE;
	public static final DeferredItem<Item> YELLOWLARGETILEFENCEGATE;
	public static final DeferredItem<Item> YELLOWLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> YELLOWLARGETILEBUTTON;
	public static final DeferredItem<Item> LIMELARGETILESTAIR;
	public static final DeferredItem<Item> LIMELARGETILESLAB;
	public static final DeferredItem<Item> LIMELARGETILEWALL;
	public static final DeferredItem<Item> LIMELARGETILEFENCE;
	public static final DeferredItem<Item> LIMELARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIMELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> LIMELARGETILEBUTTON;
	public static final DeferredItem<Item> GREENLARGETILESTAIR;
	public static final DeferredItem<Item> GREENLARGETILESLAB;
	public static final DeferredItem<Item> GREENLARGETILEWALL;
	public static final DeferredItem<Item> GREENLARGETILEFENCE;
	public static final DeferredItem<Item> GREENLARGETILEFENCEGATE;
	public static final DeferredItem<Item> GREENLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> GREENLARGETILEBUTTON;
	public static final DeferredItem<Item> CYANLARGETILESTAIR;
	public static final DeferredItem<Item> CYANLARGETILESLAB;
	public static final DeferredItem<Item> CYANLARGETILEWALL;
	public static final DeferredItem<Item> CYANLARGETILEFENCE;
	public static final DeferredItem<Item> CYANLARGETILEFENCEGATE;
	public static final DeferredItem<Item> CYANLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> CYANLARGETILEBUTTON;
	public static final DeferredItem<Item> LIGHTBLUELARGETILESTAIR;
	public static final DeferredItem<Item> LIGHTBLUELARGETILESLAB;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEWALL;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEFENCE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEFENCEGATE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> LIGHTBLUELARGETILEBUTTON;
	public static final DeferredItem<Item> BLUELARGETILESTAIR;
	public static final DeferredItem<Item> BLUELARGETILESLAB;
	public static final DeferredItem<Item> BLUELARGETILEWALL;
	public static final DeferredItem<Item> BLUELARGETILEFENCE;
	public static final DeferredItem<Item> BLUELARGETILEFENCEGATE;
	public static final DeferredItem<Item> BLUELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> BLUELARGETILEBUTTON;
	public static final DeferredItem<Item> PURPLELARGETILESTAIR;
	public static final DeferredItem<Item> PURPLELARGETILESLAB;
	public static final DeferredItem<Item> PURPLELARGETILEWALL;
	public static final DeferredItem<Item> PURPLELARGETILEFENCE;
	public static final DeferredItem<Item> PURPLELARGETILEFENCEGATE;
	public static final DeferredItem<Item> PURPLELARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> PURPLELARGETILEBUTTON;
	public static final DeferredItem<Item> MAGENTALARGETILESTAIR;
	public static final DeferredItem<Item> MAGENTALARGETILESLAB;
	public static final DeferredItem<Item> MAGENTALARGETILEWALL;
	public static final DeferredItem<Item> MAGENTALARGETILEFENCE;
	public static final DeferredItem<Item> MAGENTALARGETILEFENCEGATE;
	public static final DeferredItem<Item> MAGENTALARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> MAGENTALARGETILEBUTTON;
	public static final DeferredItem<Item> PINKLARGETILESTAIR;
	public static final DeferredItem<Item> PINKLARGETILESLAB;
	public static final DeferredItem<Item> PINKLARGETILEWALL;
	public static final DeferredItem<Item> PINKLARGETILEFENCE;
	public static final DeferredItem<Item> PINKLARGETILEFENCEGATE;
	public static final DeferredItem<Item> PINKLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> PINKLARGETILEBUTTON;
	public static final DeferredItem<Item> CEILING_TILE_FENCE;
	public static final DeferredItem<Item> CEILING_TILE_FENCE_GATE;
	public static final DeferredItem<Item> TILE_FENCE;
	public static final DeferredItem<Item> TILE_FENCE_GATE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILESTAIR;
	public static final DeferredItem<Item> INDUSTRIALLARGETILESLAB;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEWALL;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEFENCE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEFENCEGATE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> INDUSTRIALLARGETILEBUTTON;
	public static final DeferredItem<Item> WHITELARGETILETRAPDOOR;
	public static final DeferredItem<Item> INDUSTRIALLARGETILETRAPDOOR;
	public static final DeferredItem<Item> LIGHTGRAYLARGETILETRAPDOOR;
	public static final DeferredItem<Item> GRAYLARGETILETRAPDOOR;
	public static final DeferredItem<Item> BLACKLARGETILETRAPDOOR;
	public static final DeferredItem<Item> BROWNLARGETILETRAPDOOR;
	public static final DeferredItem<Item> REDLARGETILETRAPDOOR;
	public static final DeferredItem<Item> ORANGELARGETILETRAPDOOR;
	public static final DeferredItem<Item> YELLOWLARGETILETRAPDOOR;
	public static final DeferredItem<Item> LIMELARGETILETRAPDOOR;
	public static final DeferredItem<Item> GREENLARGETILETRAPDOOR;
	public static final DeferredItem<Item> CYANLARGETILETRAPDOOR;
	public static final DeferredItem<Item> LIGHTBLUELARGETILETRAPDOOR;
	public static final DeferredItem<Item> BLUELARGETILETRAPDOOR;
	public static final DeferredItem<Item> PURPLELARGETILETRAPDOOR;
	public static final DeferredItem<Item> MAGENTALARGETILETRAPDOOR;
	public static final DeferredItem<Item> PINKLARGETILETRAPDOOR;
	public static final DeferredItem<Item> WHITE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> GRAY_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> BLACK_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> BROWN_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> RED_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> ORANGE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> YELLOW_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> LIME_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> GREEN_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> CYAN_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> BLUE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> PURPLE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> MAGENTA_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> PINK_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> CHERRY_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> CEILING_TILE_TRAPDOOR;
	public static final DeferredItem<Item> TILE_TRAPDOOR;
	public static final DeferredItem<Item> CHERRYLARGETILE;
	public static final DeferredItem<Item> CHERRYLARGETILESTAIR;
	public static final DeferredItem<Item> CHERRYLARGETILESLAB;
	public static final DeferredItem<Item> CHERRYLARGETILEWALL;
	public static final DeferredItem<Item> CHERRYLARGETILEFENCE;
	public static final DeferredItem<Item> CHERRYLARGETILEFENCEGATE;
	public static final DeferredItem<Item> CHERRYLARGETILETRAPDOOR;
	public static final DeferredItem<Item> CHERRYLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> CHERRYLARGETILEBUTTON;
	public static final DeferredItem<Item> SECURE_STORAGE_BLOCK;
	public static final DeferredItem<Item> TEAL_BRICKS;
	public static final DeferredItem<Item> TEALLARGETILE;
	public static final DeferredItem<Item> TEALLARGETILESTAIR;
	public static final DeferredItem<Item> TEALLARGETILESLAB;
	public static final DeferredItem<Item> TEALLARGETILEWALL;
	public static final DeferredItem<Item> TEALLARGETILEFENCE;
	public static final DeferredItem<Item> TEALLARGETILEFENCEGATE;
	public static final DeferredItem<Item> TEALLARGETILETRAPDOOR;
	public static final DeferredItem<Item> TEALLARGETILEPRESSUREPLATE;
	public static final DeferredItem<Item> TEALLARGETILEBUTTON;
	public static final DeferredItem<Item> TEAL_BRICK_STAIRS;
	public static final DeferredItem<Item> TEAL_BRICK_SLAB;
	public static final DeferredItem<Item> TEAL_BRICK_WALL;
	public static final DeferredItem<Item> TEAL_BRICK_FENCE;
	public static final DeferredItem<Item> TEAL_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> TEAL_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> TEAL_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> TEAL_BRICK_BUTTON;
	static {
		BANANA_PLANT = block(LlamamodModBlocks.BANANA_PLANT);
		BANANA = register("banana", BannanaItem::new);
		BACKPACK = register("backpack", BackpackItem::new);
		NETHERITE_BACKPACK = register("netherite_backpack", NetheritebackpackItem::new);
		ACID_BUCKET = register("acid_bucket", AcidItem::new);
		RED_BRICKS = block(LlamamodModBlocks.RED_BRICKS);
		ORANGE_BRICKS = block(LlamamodModBlocks.ORANGE_BRICKS);
		YELLOW_BRICKS = block(LlamamodModBlocks.YELLOW_BRICKS);
		GREEN_BRICKS = block(LlamamodModBlocks.GREEN_BRICKS);
		LIGHT_BLUE_BRICKS = block(LlamamodModBlocks.LIGHT_BLUE_BRICKS);
		BLUE_BRICKS = block(LlamamodModBlocks.BLUE_BRICKS);
		MAGENTA_BRICKS = block(LlamamodModBlocks.MAGENTA_BRICKS);
		PINK_BRICKS = block(LlamamodModBlocks.PINK_BRICKS);
		BROWN_BRICKS = block(LlamamodModBlocks.BROWN_BRICKS);
		BLACK_BRICKS = block(LlamamodModBlocks.BLACK_BRICKS);
		INDUSTRIAL_BRICKS = block(LlamamodModBlocks.INDUSTRIAL_BRICKS);
		COMPUTER = block(LlamamodModBlocks.COMPUTER);
		TILES = block(LlamamodModBlocks.TILES);
		FARMSCRAPS = register("farmscraps", FarmscrapsItem::new);
		CEILING_TILES = block(LlamamodModBlocks.CEILING_TILES);
		AUTHENTICATOR = block(LlamamodModBlocks.AUTHENTICATOR);
		PASSWORD_CHANGER = register("password_changer", PasswordchangerItem::new);
		RED_BRICK_SLAB = block(LlamamodModBlocks.RED_BRICK_SLAB);
		RED_BRICK_STAIRS = block(LlamamodModBlocks.RED_BRICK_STAIRS);
		ORANGE_BRICK_SLAB = block(LlamamodModBlocks.ORANGE_BRICK_SLAB);
		ORANGE_BRICK_STAIRS = block(LlamamodModBlocks.ORANGE_BRICK_STAIRS);
		YELLOW_BRICK_SLAB = block(LlamamodModBlocks.YELLOW_BRICK_SLAB);
		YELLOW_BRICK_STAIRS = block(LlamamodModBlocks.YELLOW_BRICK_STAIRS);
		LIGHT_BLUE_BRICK_SLAB = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_SLAB);
		LIGHT_BLUE_BRICK_STAIRS = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_STAIRS);
		BLUE_BRICK_SLAB = block(LlamamodModBlocks.BLUE_BRICK_SLAB);
		BLUE_BRICK_STAIRS = block(LlamamodModBlocks.BLUE_BRICK_STAIRS);
		MAGENTA_BRICK_SLAB = block(LlamamodModBlocks.MAGENTA_BRICK_SLAB);
		MAGENTA_BRICK_STAIRS = block(LlamamodModBlocks.MAGENTA_BRICK_STAIRS);
		PINK_BRICK_SLAB = block(LlamamodModBlocks.PINK_BRICK_SLAB);
		PINK_BRICK_STAIRS = block(LlamamodModBlocks.PINK_BRICK_STAIRS);
		BROWN_BRICK_SLAB = block(LlamamodModBlocks.BROWN_BRICK_SLAB);
		BROWN_BRICK_STAIRS = block(LlamamodModBlocks.BROWN_BRICK_STAIRS);
		BLACK_BRICK_SLAB = block(LlamamodModBlocks.BLACK_BRICK_SLAB);
		BLACK_BRICK_STAIRS = block(LlamamodModBlocks.BLACK_BRICK_STAIRS);
		INDUSTRIAL_BRICK_SLAB = block(LlamamodModBlocks.INDUSTRIAL_BRICK_SLAB);
		INDUSTRIAL_BRICK_STAIRS = block(LlamamodModBlocks.INDUSTRIAL_BRICK_STAIRS);
		TILE_SLAB = block(LlamamodModBlocks.TILE_SLAB);
		TILE_STAIR = block(LlamamodModBlocks.TILE_STAIR, new Item.Properties().fireResistant());
		CEILING_TILE_SLAB = block(LlamamodModBlocks.CEILING_TILE_SLAB);
		CEILING_TILE_STAIR = block(LlamamodModBlocks.CEILING_TILE_STAIR);
		WHITE_BRICKS = block(LlamamodModBlocks.WHITE_BRICKS);
		LIGHT_GRAY_BRICKS = block(LlamamodModBlocks.LIGHT_GRAY_BRICKS);
		GRAY_BRICKS = block(LlamamodModBlocks.GRAY_BRICKS);
		LIME_BRICKS = block(LlamamodModBlocks.LIME_BRICKS);
		CYAN_BRICKS = block(LlamamodModBlocks.CYAN_BRICKS);
		CHERRY_BRICKS = block(LlamamodModBlocks.CHERRY_BRICKS);
		PURPLE_BRICKS = block(LlamamodModBlocks.PURPLE_BRICKS);
		LIME_BRICK_SLAB = block(LlamamodModBlocks.LIME_BRICK_SLAB);
		LIME_BRICK_STAIRS = block(LlamamodModBlocks.LIME_BRICK_STAIRS);
		GREEN_BRICK_SLAB = block(LlamamodModBlocks.GREEN_BRICK_SLAB);
		GREEN_BRICK_STAIRS = block(LlamamodModBlocks.GREEN_BRICK_STAIRS);
		CYAN_BRICK_SLAB = block(LlamamodModBlocks.CYAN_BRICK_SLAB);
		CYAN_BRICK_STAIRS = block(LlamamodModBlocks.CYAN_BRICK_STAIRS);
		PURPLE_BRICK_SLAB = block(LlamamodModBlocks.PURPLE_BRICK_SLAB);
		PURPLE_BRICK_STAIRS = block(LlamamodModBlocks.PURPLE_BRICK_STAIRS);
		WHITE_BRICK_SLAB = block(LlamamodModBlocks.WHITE_BRICK_SLAB);
		WHITE_BRICK_STAIRS = block(LlamamodModBlocks.WHITE_BRICK_STAIRS);
		LIGHT_GRAY_BRICK_SLAB = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_SLAB);
		LIGHT_GRAY_BRICK_STAIRS = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_STAIRS);
		GRAY_BRICK_SLAB = block(LlamamodModBlocks.GRAY_BRICK_SLAB);
		GRAY_BRICK_STAIRS = block(LlamamodModBlocks.GRAY_BRICK_STAIRS);
		CHERRY_BRICK_SLAB = block(LlamamodModBlocks.CHERRY_BRICK_SLAB);
		CHERRY_BRICK_STAIR = block(LlamamodModBlocks.CHERRY_BRICK_STAIR);
		RED_BRICK_WALL = block(LlamamodModBlocks.RED_BRICK_WALL);
		ORANGE_BRICK_WALL = block(LlamamodModBlocks.ORANGE_BRICK_WALL);
		YELLOW_BRICK_WALL = block(LlamamodModBlocks.YELLOW_BRICK_WALL);
		GREEN_BRICK_WALL = block(LlamamodModBlocks.GREEN_BRICK_WALL);
		LIGHT_BLUE_BRICK_WALL = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_WALL);
		BLUE_BRICK_WALL = block(LlamamodModBlocks.BLUE_BRICK_WALL);
		MAGENTA_BRICK_WALL = block(LlamamodModBlocks.MAGENTA_BRICK_WALL);
		PINK_BRICK_WALL = block(LlamamodModBlocks.PINK_BRICK_WALL);
		BROWN_BRICK_WALL = block(LlamamodModBlocks.BROWN_BRICK_WALL);
		BLACK_BRICK_WALL = block(LlamamodModBlocks.BLACK_BRICK_WALL);
		INDUSTRIAL_BRICK_WALL = block(LlamamodModBlocks.INDUSTRIAL_BRICK_WALL);
		WHITE_BRICK_WALL = block(LlamamodModBlocks.WHITE_BRICK_WALL);
		LIGHT_GRAY_BRICK_WALL = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_WALL);
		GRAY_BRICK_WALL = block(LlamamodModBlocks.GRAY_BRICK_WALL);
		LIME_BRICK_WALL = block(LlamamodModBlocks.LIME_BRICK_WALL);
		CYAN_BRICK_WALL = block(LlamamodModBlocks.CYAN_BRICK_WALL);
		CHERRY_BRICK_WALL = block(LlamamodModBlocks.CHERRY_BRICK_WALL);
		PURPLE_BRICK_WALL = block(LlamamodModBlocks.PURPLE_BRICK_WALL);
		CEILING_TILE_WALL = block(LlamamodModBlocks.CEILING_TILE_WALL);
		TILE_WALL = block(LlamamodModBlocks.TILE_WALL, new Item.Properties().fireResistant());
		INDUSTRIAL_BRICK_FENCE = block(LlamamodModBlocks.INDUSTRIAL_BRICK_FENCE);
		INDUSTRIAL_BRICK_FENCE_GATE = block(LlamamodModBlocks.INDUSTRIAL_BRICK_FENCE_GATE);
		INDUSTRIAL_BRICK_BUTTON = block(LlamamodModBlocks.INDUSTRIAL_BRICK_BUTTON);
		INDUSTRIAL_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.INDUSTRIAL_BRICK_PRESSURE_PLATE);
		RED_BRICK_FENCE = block(LlamamodModBlocks.RED_BRICK_FENCE);
		ORANGE_BRICK_FENCE = block(LlamamodModBlocks.ORANGE_BRICK_FENCE);
		YELLOW_BRICK_FENCE = block(LlamamodModBlocks.YELLOW_BRICK_FENCE);
		GREEN_BRICK_FENCE = block(LlamamodModBlocks.GREEN_BRICK_FENCE);
		LIGHT_BLUE_BRICK_FENCE = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_FENCE);
		BLUE_BRICK_FENCE = block(LlamamodModBlocks.BLUE_BRICK_FENCE);
		MAGENTA_BRICK_FENCE = block(LlamamodModBlocks.MAGENTA_BRICK_FENCE);
		PINK_BRICK_FENCE = block(LlamamodModBlocks.PINK_BRICK_FENCE);
		BROWN_BRICK_FENCE = block(LlamamodModBlocks.BROWN_BRICK_FENCE);
		BLACK_BRICK_FENCE = block(LlamamodModBlocks.BLACK_BRICK_FENCE);
		WHITE_BRICK_FENCE = block(LlamamodModBlocks.WHITE_BRICK_FENCE);
		LIGHT_GRAY_BRICK_FENCE = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_FENCE);
		GRAY_BRICK_FENCE = block(LlamamodModBlocks.GRAY_BRICK_FENCE);
		LIME_BRICK_FENCE = block(LlamamodModBlocks.LIME_BRICK_FENCE);
		CYAN_BRICK_FENCE = block(LlamamodModBlocks.CYAN_BRICK_FENCE);
		PURPLE_BRICK_FENCE = block(LlamamodModBlocks.PURPLE_BRICK_FENCE);
		CHERRY_BRICK_FENCE = block(LlamamodModBlocks.CHERRY_BRICK_FENCE);
		RED_BRICK_FENCE_GATE = block(LlamamodModBlocks.RED_BRICK_FENCE_GATE);
		ORANGE_BRICK_FENCE_GATE = block(LlamamodModBlocks.ORANGE_BRICK_FENCE_GATE);
		YELLOW_BRICK_FENCE_GATE = block(LlamamodModBlocks.YELLOW_BRICK_FENCE_GATE);
		GREEN_BRICK_FENCE_GATE = block(LlamamodModBlocks.GREEN_BRICK_FENCE_GATE);
		LIGHT_BLUE_BRICK_FENCE_GATE = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_FENCE_GATE);
		BLUE_BRICK_FENCE_GATE = block(LlamamodModBlocks.BLUE_BRICK_FENCE_GATE);
		MAGENTA_BRICK_FENCE_GATE = block(LlamamodModBlocks.MAGENTA_BRICK_FENCE_GATE);
		PINK_BRICK_FENCE_GATE = block(LlamamodModBlocks.PINK_BRICK_FENCE_GATE);
		BROWN_BRICK_FENCE_GATE = block(LlamamodModBlocks.BROWN_BRICK_FENCE_GATE);
		BLACK_BRICK_FENCE_GATE = block(LlamamodModBlocks.BLACK_BRICK_FENCE_GATE);
		WHITE_BRICK_FENCE_GATE = block(LlamamodModBlocks.WHITE_BRICK_FENCE_GATE);
		LIGHT_GRAY_BRICK_FENCE_GATE = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_FENCE_GATE);
		GRAY_BRICK_FENCE_GATE = block(LlamamodModBlocks.GRAY_BRICK_FENCE_GATE);
		LIME_BRICK_FENCE_GATE = block(LlamamodModBlocks.LIME_BRICK_FENCE_GATE);
		CYAN_BRICK_FENCE_GATE = block(LlamamodModBlocks.CYAN_BRICK_FENCE_GATE);
		PURPLE_BRICK_FENCE_GATE = block(LlamamodModBlocks.PURPLE_BRICK_FENCE_GATE);
		CHERRY_BRICK_FENCE_GATE = block(LlamamodModBlocks.CHERRY_BRICK_FENCE_GATE);
		RED_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.RED_BRICK_PRESSURE_PLATE);
		ORANGE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.ORANGE_BRICK_PRESSURE_PLATE);
		YELLOW_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.YELLOW_BRICK_PRESSURE_PLATE);
		GREEN_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.GREEN_BRICK_PRESSURE_PLATE);
		LIGHT_BLUE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_PRESSURE_PLATE);
		BLUE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.BLUE_BRICK_PRESSURE_PLATE);
		MAGENTA_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.MAGENTA_BRICK_PRESSURE_PLATE);
		PINK_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.PINK_BRICK_PRESSURE_PLATE);
		BROWN_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.BROWN_BRICK_PRESSURE_PLATE);
		BLACK_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.BLACK_BRICK_PRESSURE_PLATE);
		WHITE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.WHITE_BRICK_PRESSURE_PLATE);
		LIGHT_GRAY_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_PRESSURE_PLATE);
		GRAY_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.GRAY_BRICK_PRESSURE_PLATE);
		LIME_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.LIME_BRICK_PRESSURE_PLATE);
		CYAN_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.CYAN_BRICK_PRESSURE_PLATE);
		PURPLE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.PURPLE_BRICK_PRESSURE_PLATE);
		CHERRY_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.CHERRY_BRICK_PRESSURE_PLATE);
		RED_BRICK_BUTTON = block(LlamamodModBlocks.RED_BRICK_BUTTON);
		ORANGE_BRICK_BUTTON = block(LlamamodModBlocks.ORANGE_BRICK_BUTTON);
		YELLOW_BRICK_BUTTON = block(LlamamodModBlocks.YELLOW_BRICK_BUTTON);
		GREEN_BRICK_BUTTON = block(LlamamodModBlocks.GREEN_BRICK_BUTTON);
		LIGHT_BLUE_BRICK_BUTTON = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_BUTTON);
		BLUE_BRICK_BUTTON = block(LlamamodModBlocks.BLUE_BRICK_BUTTON);
		MAGENTA_BRICK_BUTTON = block(LlamamodModBlocks.MAGENTA_BRICK_BUTTON);
		PINK_BRICK_BUTTON = block(LlamamodModBlocks.PINK_BRICK_BUTTON);
		BROWN_BRICK_BUTTON = block(LlamamodModBlocks.BROWN_BRICK_BUTTON);
		BLACK_BRICK_BUTTON = block(LlamamodModBlocks.BLACK_BRICK_BUTTON);
		WHITE_BRICK_BUTTON = block(LlamamodModBlocks.WHITE_BRICK_BUTTON);
		LIGHT_GRAY_BRICK_BUTTON = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_BUTTON);
		GRAY_BRICK_BUTTON = block(LlamamodModBlocks.GRAY_BRICK_BUTTON);
		LIME_BRICK_BUTTON = block(LlamamodModBlocks.LIME_BRICK_BUTTON);
		CYAN_BRICK_BUTTON = block(LlamamodModBlocks.CYAN_BRICK_BUTTON);
		PURPLE_BRICK_BUTTON = block(LlamamodModBlocks.PURPLE_BRICK_BUTTON);
		CHERRY_BRICK_BUTTON = block(LlamamodModBlocks.CHERRY_BRICK_BUTTON);
		TILE_PRESSURE_PLATE = block(LlamamodModBlocks.TILE_PRESSURE_PLATE);
		TILE_BUTTON = block(LlamamodModBlocks.TILE_BUTTON);
		CEILING_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.CEILING_TILE_PRESSURE_PLATE);
		CEILING_TILE_BUTTON = block(LlamamodModBlocks.CEILING_TILE_BUTTON);
		WHITELARGETILE = block(LlamamodModBlocks.WHITELARGETILE);
		WHITELARGETILESTAIR = block(LlamamodModBlocks.WHITELARGETILESTAIR);
		WHITELARGETILESLAB = block(LlamamodModBlocks.WHITELARGETILESLAB);
		WHITELARGETILEWALL = block(LlamamodModBlocks.WHITELARGETILEWALL);
		WHITELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.WHITELARGETILEPRESSUREPLATE);
		WHITELARGETILEBUTTON = block(LlamamodModBlocks.WHITELARGETILEBUTTON);
		VARIABLE_LIGHT = block(LlamamodModBlocks.VARIABLE_LIGHT);
		LIGHTGRAYLARGETILE = block(LlamamodModBlocks.LIGHTGRAYLARGETILE);
		GRAYLARGETILE = block(LlamamodModBlocks.GRAYLARGETILE);
		BLACKLARGETILE = block(LlamamodModBlocks.BLACKLARGETILE);
		ORANGELARGETILE = block(LlamamodModBlocks.ORANGELARGETILE);
		MAGENTALARGETILE = block(LlamamodModBlocks.MAGENTALARGETILE);
		LIGHTBLUELARGETILE = block(LlamamodModBlocks.LIGHTBLUELARGETILE);
		BLUELARGETILE = block(LlamamodModBlocks.BLUELARGETILE);
		YELLOWLARGETILE = block(LlamamodModBlocks.YELLOWLARGETILE);
		LIMELARGETILE = block(LlamamodModBlocks.LIMELARGETILE);
		GREENLARGETILE = block(LlamamodModBlocks.GREENLARGETILE);
		PINKLARGETILE = block(LlamamodModBlocks.PINKLARGETILE);
		CYANLARGETILE = block(LlamamodModBlocks.CYANLARGETILE);
		PURPLELARGETILE = block(LlamamodModBlocks.PURPLELARGETILE);
		BROWNLARGETILE = block(LlamamodModBlocks.BROWNLARGETILE);
		REDLARGETILE = block(LlamamodModBlocks.REDLARGETILE);
		LARGETILEFENCE = block(LlamamodModBlocks.LARGETILEFENCE);
		LARGETILEFENCEGATE = block(LlamamodModBlocks.LARGETILEFENCEGATE);
		LIGHTGRAYLARGETILESTAIR = block(LlamamodModBlocks.LIGHTGRAYLARGETILESTAIR);
		LIGHTGRAYLARGETILESLAB = block(LlamamodModBlocks.LIGHTGRAYLARGETILESLAB);
		LIGHTGRAYLARGETILEWALL = block(LlamamodModBlocks.LIGHTGRAYLARGETILEWALL);
		LIGHTGRAYLARGETILEFENCE = block(LlamamodModBlocks.LIGHTGRAYLARGETILEFENCE);
		LIGHTGRAYLARGETILEFENCEGATE = block(LlamamodModBlocks.LIGHTGRAYLARGETILEFENCEGATE);
		LIGHTGRAYLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.LIGHTGRAYLARGETILEPRESSUREPLATE);
		LIGHTGRAYLARGETILEBUTTON = block(LlamamodModBlocks.LIGHTGRAYLARGETILEBUTTON);
		GRAYLARGETILESTAIR = block(LlamamodModBlocks.GRAYLARGETILESTAIR);
		GRAYLARGETILESLAB = block(LlamamodModBlocks.GRAYLARGETILESLAB);
		GRAYLARGETILEWALL = block(LlamamodModBlocks.GRAYLARGETILEWALL);
		GRAYLARGETILEFENCE = block(LlamamodModBlocks.GRAYLARGETILEFENCE);
		GRAYLARGETILEFENCEGATE = block(LlamamodModBlocks.GRAYLARGETILEFENCEGATE);
		GRAYLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.GRAYLARGETILEPRESSUREPLATE);
		GRAYLARGETILEBUTTON = block(LlamamodModBlocks.GRAYLARGETILEBUTTON);
		BLACKLARGETILESTAIR = block(LlamamodModBlocks.BLACKLARGETILESTAIR);
		BLACKLARGETILESLAB = block(LlamamodModBlocks.BLACKLARGETILESLAB);
		BLACKLARGETILEWALL = block(LlamamodModBlocks.BLACKLARGETILEWALL);
		BLACKLARGETILEFENCE = block(LlamamodModBlocks.BLACKLARGETILEFENCE);
		BLACKLARGETILEFENCEGATE = block(LlamamodModBlocks.BLACKLARGETILEFENCEGATE);
		BLACKLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.BLACKLARGETILEPRESSUREPLATE);
		BLACKLARGETILEBUTTON = block(LlamamodModBlocks.BLACKLARGETILEBUTTON);
		BROWNLARGETILESTAIR = block(LlamamodModBlocks.BROWNLARGETILESTAIR);
		BROWNLARGETILESLAB = block(LlamamodModBlocks.BROWNLARGETILESLAB);
		BROWNLARGETILEWALL = block(LlamamodModBlocks.BROWNLARGETILEWALL);
		BROWNLARGETILEFENCE = block(LlamamodModBlocks.BROWNLARGETILEFENCE);
		BROWNLARGETILEFENCEGATE = block(LlamamodModBlocks.BROWNLARGETILEFENCEGATE);
		BROWNLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.BROWNLARGETILEPRESSUREPLATE);
		BROWNLARGETILEBUTTON = block(LlamamodModBlocks.BROWNLARGETILEBUTTON);
		REDLARGETILESTAIR = block(LlamamodModBlocks.REDLARGETILESTAIR);
		REDLARGETILESLAB = block(LlamamodModBlocks.REDLARGETILESLAB);
		REDLARGETILEWALL = block(LlamamodModBlocks.REDLARGETILEWALL);
		REDLARGETILEFENCE = block(LlamamodModBlocks.REDLARGETILEFENCE);
		REDLARGETILEFENCEGATE = block(LlamamodModBlocks.REDLARGETILEFENCEGATE);
		REDLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.REDLARGETILEPRESSUREPLATE);
		REDLARGETILEBUTTON = block(LlamamodModBlocks.REDLARGETILEBUTTON);
		ORANGELARGETILESTAIR = block(LlamamodModBlocks.ORANGELARGETILESTAIR);
		ORANGELARGETILESLAB = block(LlamamodModBlocks.ORANGELARGETILESLAB);
		ORANGELARGETILEWALL = block(LlamamodModBlocks.ORANGELARGETILEWALL);
		ORANGELARGETILEFENCE = block(LlamamodModBlocks.ORANGELARGETILEFENCE);
		ORANGELARGETILEFENCEGATE = block(LlamamodModBlocks.ORANGELARGETILEFENCEGATE);
		ORANGELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.ORANGELARGETILEPRESSUREPLATE);
		ORANGELARGETILEBUTTON = block(LlamamodModBlocks.ORANGELARGETILEBUTTON);
		YELLOWLARGETILESTAIR = block(LlamamodModBlocks.YELLOWLARGETILESTAIR);
		YELLOWLARGETILESLAB = block(LlamamodModBlocks.YELLOWLARGETILESLAB);
		YELLOWLARGETILEWALL = block(LlamamodModBlocks.YELLOWLARGETILEWALL);
		YELLOWLARGETILEFENCE = block(LlamamodModBlocks.YELLOWLARGETILEFENCE);
		YELLOWLARGETILEFENCEGATE = block(LlamamodModBlocks.YELLOWLARGETILEFENCEGATE);
		YELLOWLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.YELLOWLARGETILEPRESSUREPLATE);
		YELLOWLARGETILEBUTTON = block(LlamamodModBlocks.YELLOWLARGETILEBUTTON);
		LIMELARGETILESTAIR = block(LlamamodModBlocks.LIMELARGETILESTAIR);
		LIMELARGETILESLAB = block(LlamamodModBlocks.LIMELARGETILESLAB);
		LIMELARGETILEWALL = block(LlamamodModBlocks.LIMELARGETILEWALL);
		LIMELARGETILEFENCE = block(LlamamodModBlocks.LIMELARGETILEFENCE);
		LIMELARGETILEFENCEGATE = block(LlamamodModBlocks.LIMELARGETILEFENCEGATE);
		LIMELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.LIMELARGETILEPRESSUREPLATE);
		LIMELARGETILEBUTTON = block(LlamamodModBlocks.LIMELARGETILEBUTTON);
		GREENLARGETILESTAIR = block(LlamamodModBlocks.GREENLARGETILESTAIR);
		GREENLARGETILESLAB = block(LlamamodModBlocks.GREENLARGETILESLAB);
		GREENLARGETILEWALL = block(LlamamodModBlocks.GREENLARGETILEWALL);
		GREENLARGETILEFENCE = block(LlamamodModBlocks.GREENLARGETILEFENCE);
		GREENLARGETILEFENCEGATE = block(LlamamodModBlocks.GREENLARGETILEFENCEGATE);
		GREENLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.GREENLARGETILEPRESSUREPLATE);
		GREENLARGETILEBUTTON = block(LlamamodModBlocks.GREENLARGETILEBUTTON);
		CYANLARGETILESTAIR = block(LlamamodModBlocks.CYANLARGETILESTAIR);
		CYANLARGETILESLAB = block(LlamamodModBlocks.CYANLARGETILESLAB);
		CYANLARGETILEWALL = block(LlamamodModBlocks.CYANLARGETILEWALL);
		CYANLARGETILEFENCE = block(LlamamodModBlocks.CYANLARGETILEFENCE);
		CYANLARGETILEFENCEGATE = block(LlamamodModBlocks.CYANLARGETILEFENCEGATE);
		CYANLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.CYANLARGETILEPRESSUREPLATE);
		CYANLARGETILEBUTTON = block(LlamamodModBlocks.CYANLARGETILEBUTTON);
		LIGHTBLUELARGETILESTAIR = block(LlamamodModBlocks.LIGHTBLUELARGETILESTAIR);
		LIGHTBLUELARGETILESLAB = block(LlamamodModBlocks.LIGHTBLUELARGETILESLAB);
		LIGHTBLUELARGETILEWALL = block(LlamamodModBlocks.LIGHTBLUELARGETILEWALL);
		LIGHTBLUELARGETILEFENCE = block(LlamamodModBlocks.LIGHTBLUELARGETILEFENCE);
		LIGHTBLUELARGETILEFENCEGATE = block(LlamamodModBlocks.LIGHTBLUELARGETILEFENCEGATE);
		LIGHTBLUELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.LIGHTBLUELARGETILEPRESSUREPLATE);
		LIGHTBLUELARGETILEBUTTON = block(LlamamodModBlocks.LIGHTBLUELARGETILEBUTTON);
		BLUELARGETILESTAIR = block(LlamamodModBlocks.BLUELARGETILESTAIR);
		BLUELARGETILESLAB = block(LlamamodModBlocks.BLUELARGETILESLAB);
		BLUELARGETILEWALL = block(LlamamodModBlocks.BLUELARGETILEWALL);
		BLUELARGETILEFENCE = block(LlamamodModBlocks.BLUELARGETILEFENCE);
		BLUELARGETILEFENCEGATE = block(LlamamodModBlocks.BLUELARGETILEFENCEGATE);
		BLUELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.BLUELARGETILEPRESSUREPLATE);
		BLUELARGETILEBUTTON = block(LlamamodModBlocks.BLUELARGETILEBUTTON);
		PURPLELARGETILESTAIR = block(LlamamodModBlocks.PURPLELARGETILESTAIR);
		PURPLELARGETILESLAB = block(LlamamodModBlocks.PURPLELARGETILESLAB);
		PURPLELARGETILEWALL = block(LlamamodModBlocks.PURPLELARGETILEWALL);
		PURPLELARGETILEFENCE = block(LlamamodModBlocks.PURPLELARGETILEFENCE);
		PURPLELARGETILEFENCEGATE = block(LlamamodModBlocks.PURPLELARGETILEFENCEGATE);
		PURPLELARGETILEPRESSUREPLATE = block(LlamamodModBlocks.PURPLELARGETILEPRESSUREPLATE);
		PURPLELARGETILEBUTTON = block(LlamamodModBlocks.PURPLELARGETILEBUTTON);
		MAGENTALARGETILESTAIR = block(LlamamodModBlocks.MAGENTALARGETILESTAIR);
		MAGENTALARGETILESLAB = block(LlamamodModBlocks.MAGENTALARGETILESLAB);
		MAGENTALARGETILEWALL = block(LlamamodModBlocks.MAGENTALARGETILEWALL);
		MAGENTALARGETILEFENCE = block(LlamamodModBlocks.MAGENTALARGETILEFENCE);
		MAGENTALARGETILEFENCEGATE = block(LlamamodModBlocks.MAGENTALARGETILEFENCEGATE);
		MAGENTALARGETILEPRESSUREPLATE = block(LlamamodModBlocks.MAGENTALARGETILEPRESSUREPLATE);
		MAGENTALARGETILEBUTTON = block(LlamamodModBlocks.MAGENTALARGETILEBUTTON);
		PINKLARGETILESTAIR = block(LlamamodModBlocks.PINKLARGETILESTAIR);
		PINKLARGETILESLAB = block(LlamamodModBlocks.PINKLARGETILESLAB);
		PINKLARGETILEWALL = block(LlamamodModBlocks.PINKLARGETILEWALL);
		PINKLARGETILEFENCE = block(LlamamodModBlocks.PINKLARGETILEFENCE);
		PINKLARGETILEFENCEGATE = block(LlamamodModBlocks.PINKLARGETILEFENCEGATE);
		PINKLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.PINKLARGETILEPRESSUREPLATE);
		PINKLARGETILEBUTTON = block(LlamamodModBlocks.PINKLARGETILEBUTTON);
		CEILING_TILE_FENCE = block(LlamamodModBlocks.CEILING_TILE_FENCE);
		CEILING_TILE_FENCE_GATE = block(LlamamodModBlocks.CEILING_TILE_FENCE_GATE);
		TILE_FENCE = block(LlamamodModBlocks.TILE_FENCE, new Item.Properties().fireResistant());
		TILE_FENCE_GATE = block(LlamamodModBlocks.TILE_FENCE_GATE, new Item.Properties().fireResistant());
		INDUSTRIALLARGETILE = block(LlamamodModBlocks.INDUSTRIALLARGETILE);
		INDUSTRIALLARGETILESTAIR = block(LlamamodModBlocks.INDUSTRIALLARGETILESTAIR);
		INDUSTRIALLARGETILESLAB = block(LlamamodModBlocks.INDUSTRIALLARGETILESLAB);
		INDUSTRIALLARGETILEWALL = block(LlamamodModBlocks.INDUSTRIALLARGETILEWALL);
		INDUSTRIALLARGETILEFENCE = block(LlamamodModBlocks.INDUSTRIALLARGETILEFENCE);
		INDUSTRIALLARGETILEFENCEGATE = block(LlamamodModBlocks.INDUSTRIALLARGETILEFENCEGATE);
		INDUSTRIALLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.INDUSTRIALLARGETILEPRESSUREPLATE);
		INDUSTRIALLARGETILEBUTTON = block(LlamamodModBlocks.INDUSTRIALLARGETILEBUTTON);
		WHITELARGETILETRAPDOOR = block(LlamamodModBlocks.WHITELARGETILETRAPDOOR);
		INDUSTRIALLARGETILETRAPDOOR = block(LlamamodModBlocks.INDUSTRIALLARGETILETRAPDOOR);
		LIGHTGRAYLARGETILETRAPDOOR = block(LlamamodModBlocks.LIGHTGRAYLARGETILETRAPDOOR);
		GRAYLARGETILETRAPDOOR = block(LlamamodModBlocks.GRAYLARGETILETRAPDOOR);
		BLACKLARGETILETRAPDOOR = block(LlamamodModBlocks.BLACKLARGETILETRAPDOOR);
		BROWNLARGETILETRAPDOOR = block(LlamamodModBlocks.BROWNLARGETILETRAPDOOR);
		REDLARGETILETRAPDOOR = block(LlamamodModBlocks.REDLARGETILETRAPDOOR);
		ORANGELARGETILETRAPDOOR = block(LlamamodModBlocks.ORANGELARGETILETRAPDOOR);
		YELLOWLARGETILETRAPDOOR = block(LlamamodModBlocks.YELLOWLARGETILETRAPDOOR);
		LIMELARGETILETRAPDOOR = block(LlamamodModBlocks.LIMELARGETILETRAPDOOR);
		GREENLARGETILETRAPDOOR = block(LlamamodModBlocks.GREENLARGETILETRAPDOOR);
		CYANLARGETILETRAPDOOR = block(LlamamodModBlocks.CYANLARGETILETRAPDOOR);
		LIGHTBLUELARGETILETRAPDOOR = block(LlamamodModBlocks.LIGHTBLUELARGETILETRAPDOOR);
		BLUELARGETILETRAPDOOR = block(LlamamodModBlocks.BLUELARGETILETRAPDOOR);
		PURPLELARGETILETRAPDOOR = block(LlamamodModBlocks.PURPLELARGETILETRAPDOOR);
		MAGENTALARGETILETRAPDOOR = block(LlamamodModBlocks.MAGENTALARGETILETRAPDOOR);
		PINKLARGETILETRAPDOOR = block(LlamamodModBlocks.PINKLARGETILETRAPDOOR);
		WHITE_BRICK_TRAPDOOR = block(LlamamodModBlocks.WHITE_BRICK_TRAPDOOR);
		LIGHT_GRAY_BRICK_TRAPDOOR = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_TRAPDOOR);
		GRAY_BRICK_TRAPDOOR = block(LlamamodModBlocks.GRAY_BRICK_TRAPDOOR);
		BLACK_BRICK_TRAPDOOR = block(LlamamodModBlocks.BLACK_BRICK_TRAPDOOR);
		BROWN_BRICK_TRAPDOOR = block(LlamamodModBlocks.BROWN_BRICK_TRAPDOOR);
		RED_BRICK_TRAPDOOR = block(LlamamodModBlocks.RED_BRICK_TRAPDOOR);
		ORANGE_BRICK_TRAPDOOR = block(LlamamodModBlocks.ORANGE_BRICK_TRAPDOOR);
		YELLOW_BRICK_TRAPDOOR = block(LlamamodModBlocks.YELLOW_BRICK_TRAPDOOR);
		LIME_BRICK_TRAPDOOR = block(LlamamodModBlocks.LIME_BRICK_TRAPDOOR);
		GREEN_BRICK_TRAPDOOR = block(LlamamodModBlocks.GREEN_BRICK_TRAPDOOR);
		CYAN_BRICK_TRAPDOOR = block(LlamamodModBlocks.CYAN_BRICK_TRAPDOOR);
		LIGHT_BLUE_BRICK_TRAPDOOR = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_TRAPDOOR);
		BLUE_BRICK_TRAPDOOR = block(LlamamodModBlocks.BLUE_BRICK_TRAPDOOR);
		PURPLE_BRICK_TRAPDOOR = block(LlamamodModBlocks.PURPLE_BRICK_TRAPDOOR);
		MAGENTA_BRICK_TRAPDOOR = block(LlamamodModBlocks.MAGENTA_BRICK_TRAPDOOR);
		PINK_BRICK_TRAPDOOR = block(LlamamodModBlocks.PINK_BRICK_TRAPDOOR);
		CHERRY_BRICK_TRAPDOOR = block(LlamamodModBlocks.CHERRY_BRICK_TRAPDOOR);
		INDUSTRIAL_BRICK_TRAPDOOR = block(LlamamodModBlocks.INDUSTRIAL_BRICK_TRAPDOOR);
		CEILING_TILE_TRAPDOOR = block(LlamamodModBlocks.CEILING_TILE_TRAPDOOR);
		TILE_TRAPDOOR = block(LlamamodModBlocks.TILE_TRAPDOOR);
		CHERRYLARGETILE = block(LlamamodModBlocks.CHERRYLARGETILE);
		CHERRYLARGETILESTAIR = block(LlamamodModBlocks.CHERRYLARGETILESTAIR);
		CHERRYLARGETILESLAB = block(LlamamodModBlocks.CHERRYLARGETILESLAB);
		CHERRYLARGETILEWALL = block(LlamamodModBlocks.CHERRYLARGETILEWALL);
		CHERRYLARGETILEFENCE = block(LlamamodModBlocks.CHERRYLARGETILEFENCE);
		CHERRYLARGETILEFENCEGATE = block(LlamamodModBlocks.CHERRYLARGETILEFENCEGATE);
		CHERRYLARGETILETRAPDOOR = block(LlamamodModBlocks.CHERRYLARGETILETRAPDOOR);
		CHERRYLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.CHERRYLARGETILEPRESSUREPLATE);
		CHERRYLARGETILEBUTTON = block(LlamamodModBlocks.CHERRYLARGETILEBUTTON);
		SECURE_STORAGE_BLOCK = block(LlamamodModBlocks.SECURE_STORAGE_BLOCK);
		TEAL_BRICKS = block(LlamamodModBlocks.TEAL_BRICKS);
		TEALLARGETILE = block(LlamamodModBlocks.TEALLARGETILE);
		TEALLARGETILESTAIR = block(LlamamodModBlocks.TEALLARGETILESTAIR);
		TEALLARGETILESLAB = block(LlamamodModBlocks.TEALLARGETILESLAB);
		TEALLARGETILEWALL = block(LlamamodModBlocks.TEALLARGETILEWALL);
		TEALLARGETILEFENCE = block(LlamamodModBlocks.TEALLARGETILEFENCE);
		TEALLARGETILEFENCEGATE = block(LlamamodModBlocks.TEALLARGETILEFENCEGATE);
		TEALLARGETILETRAPDOOR = block(LlamamodModBlocks.TEALLARGETILETRAPDOOR);
		TEALLARGETILEPRESSUREPLATE = block(LlamamodModBlocks.TEALLARGETILEPRESSUREPLATE);
		TEALLARGETILEBUTTON = block(LlamamodModBlocks.TEALLARGETILEBUTTON);
		TEAL_BRICK_STAIRS = block(LlamamodModBlocks.TEAL_BRICK_STAIRS);
		TEAL_BRICK_SLAB = block(LlamamodModBlocks.TEAL_BRICK_SLAB);
		TEAL_BRICK_WALL = block(LlamamodModBlocks.TEAL_BRICK_WALL);
		TEAL_BRICK_FENCE = block(LlamamodModBlocks.TEAL_BRICK_FENCE);
		TEAL_BRICK_FENCE_GATE = block(LlamamodModBlocks.TEAL_BRICK_FENCE_GATE);
		TEAL_BRICK_TRAPDOOR = block(LlamamodModBlocks.TEAL_BRICK_TRAPDOOR);
		TEAL_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.TEAL_BRICK_PRESSURE_PLATE);
		TEAL_BRICK_BUTTON = block(LlamamodModBlocks.TEAL_BRICK_BUTTON);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new BackpackInventoryCapability(stack), BACKPACK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new NetheritebackpackInventoryCapability(stack), NETHERITE_BACKPACK.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), ACID_BUCKET.get());
	}
}