/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package mc.omegabird.llamablocks.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import mc.omegabird.llamablocks.block.*;
import mc.omegabird.llamablocks.LlamamodMod;

import java.util.function.Function;

public class LlamamodModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(LlamamodMod.MODID);
	public static final DeferredBlock<Block> BANANA_PLANT;
	public static final DeferredBlock<Block> ACID;
	public static final DeferredBlock<Block> RED_BRICKS;
	public static final DeferredBlock<Block> ORANGE_BRICKS;
	public static final DeferredBlock<Block> YELLOW_BRICKS;
	public static final DeferredBlock<Block> GREEN_BRICKS;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICKS;
	public static final DeferredBlock<Block> BLUE_BRICKS;
	public static final DeferredBlock<Block> MAGENTA_BRICKS;
	public static final DeferredBlock<Block> PINK_BRICKS;
	public static final DeferredBlock<Block> BROWN_BRICKS;
	public static final DeferredBlock<Block> BLACK_BRICKS;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICKS;
	public static final DeferredBlock<Block> COMPUTER;
	public static final DeferredBlock<Block> TILES;
	public static final DeferredBlock<Block> CEILING_TILES;
	public static final DeferredBlock<Block> AUTHENTICATOR;
	public static final DeferredBlock<Block> RED_BRICK_SLAB;
	public static final DeferredBlock<Block> RED_BRICK_STAIRS;
	public static final DeferredBlock<Block> ORANGE_BRICK_SLAB;
	public static final DeferredBlock<Block> ORANGE_BRICK_STAIRS;
	public static final DeferredBlock<Block> YELLOW_BRICK_SLAB;
	public static final DeferredBlock<Block> YELLOW_BRICK_STAIRS;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_SLAB;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_STAIRS;
	public static final DeferredBlock<Block> BLUE_BRICK_SLAB;
	public static final DeferredBlock<Block> BLUE_BRICK_STAIRS;
	public static final DeferredBlock<Block> MAGENTA_BRICK_SLAB;
	public static final DeferredBlock<Block> MAGENTA_BRICK_STAIRS;
	public static final DeferredBlock<Block> PINK_BRICK_SLAB;
	public static final DeferredBlock<Block> PINK_BRICK_STAIRS;
	public static final DeferredBlock<Block> BROWN_BRICK_SLAB;
	public static final DeferredBlock<Block> BROWN_BRICK_STAIRS;
	public static final DeferredBlock<Block> BLACK_BRICK_SLAB;
	public static final DeferredBlock<Block> BLACK_BRICK_STAIRS;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_SLAB;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_STAIRS;
	public static final DeferredBlock<Block> TILE_SLAB;
	public static final DeferredBlock<Block> TILE_STAIRS;
	public static final DeferredBlock<Block> CEILING_TILE_SLAB;
	public static final DeferredBlock<Block> CEILING_TILE_STAIRS;
	public static final DeferredBlock<Block> WHITE_BRICKS;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICKS;
	public static final DeferredBlock<Block> GRAY_BRICKS;
	public static final DeferredBlock<Block> LIME_BRICKS;
	public static final DeferredBlock<Block> CYAN_BRICKS;
	public static final DeferredBlock<Block> CHERRY_BRICKS;
	public static final DeferredBlock<Block> PURPLE_BRICKS;
	public static final DeferredBlock<Block> LIME_BRICK_SLAB;
	public static final DeferredBlock<Block> LIME_BRICK_STAIRS;
	public static final DeferredBlock<Block> GREEN_BRICK_SLAB;
	public static final DeferredBlock<Block> GREEN_BRICK_STAIRS;
	public static final DeferredBlock<Block> CYAN_BRICK_SLAB;
	public static final DeferredBlock<Block> CYAN_BRICK_STAIRS;
	public static final DeferredBlock<Block> PURPLE_BRICK_SLAB;
	public static final DeferredBlock<Block> PURPLE_BRICK_STAIRS;
	public static final DeferredBlock<Block> WHITE_BRICK_SLAB;
	public static final DeferredBlock<Block> WHITE_BRICK_STAIRS;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_SLAB;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_STAIRS;
	public static final DeferredBlock<Block> GRAY_BRICK_SLAB;
	public static final DeferredBlock<Block> GRAY_BRICK_STAIRS;
	public static final DeferredBlock<Block> CHERRY_BRICK_SLAB;
	public static final DeferredBlock<Block> CHERRY_BRICK_STAIR;
	public static final DeferredBlock<Block> RED_BRICK_WALL;
	public static final DeferredBlock<Block> ORANGE_BRICK_WALL;
	public static final DeferredBlock<Block> YELLOW_BRICK_WALL;
	public static final DeferredBlock<Block> GREEN_BRICK_WALL;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_WALL;
	public static final DeferredBlock<Block> BLUE_BRICK_WALL;
	public static final DeferredBlock<Block> MAGENTA_BRICK_WALL;
	public static final DeferredBlock<Block> PINK_BRICK_WALL;
	public static final DeferredBlock<Block> BROWN_BRICK_WALL;
	public static final DeferredBlock<Block> BLACK_BRICK_WALL;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_WALL;
	public static final DeferredBlock<Block> WHITE_BRICK_WALL;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_WALL;
	public static final DeferredBlock<Block> GRAY_BRICK_WALL;
	public static final DeferredBlock<Block> LIME_BRICK_WALL;
	public static final DeferredBlock<Block> CYAN_BRICK_WALL;
	public static final DeferredBlock<Block> CHERRY_BRICK_WALL;
	public static final DeferredBlock<Block> PURPLE_BRICK_WALL;
	public static final DeferredBlock<Block> CEILING_TILE_WALL;
	public static final DeferredBlock<Block> TILE_WALL;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_FENCE;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_BUTTON;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> RED_BRICK_FENCE;
	public static final DeferredBlock<Block> ORANGE_BRICK_FENCE;
	public static final DeferredBlock<Block> YELLOW_BRICK_FENCE;
	public static final DeferredBlock<Block> GREEN_BRICK_FENCE;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_FENCE;
	public static final DeferredBlock<Block> BLUE_BRICK_FENCE;
	public static final DeferredBlock<Block> MAGENTA_BRICK_FENCE;
	public static final DeferredBlock<Block> PINK_BRICK_FENCE;
	public static final DeferredBlock<Block> BROWN_BRICK_FENCE;
	public static final DeferredBlock<Block> BLACK_BRICK_FENCE;
	public static final DeferredBlock<Block> WHITE_BRICK_FENCE;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_FENCE;
	public static final DeferredBlock<Block> GRAY_BRICK_FENCE;
	public static final DeferredBlock<Block> LIME_BRICK_FENCE;
	public static final DeferredBlock<Block> CYAN_BRICK_FENCE;
	public static final DeferredBlock<Block> PURPLE_BRICK_FENCE;
	public static final DeferredBlock<Block> CHERRY_BRICK_FENCE;
	public static final DeferredBlock<Block> RED_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> ORANGE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> YELLOW_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> GREEN_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> BLUE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> MAGENTA_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> PINK_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> BROWN_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> BLACK_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> WHITE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> GRAY_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> LIME_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> CYAN_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> PURPLE_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> CHERRY_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> RED_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> ORANGE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> YELLOW_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> GREEN_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> BLUE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> MAGENTA_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> PINK_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> BROWN_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> BLACK_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> WHITE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> GRAY_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> LIME_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CYAN_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> PURPLE_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CHERRY_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> RED_BRICK_BUTTON;
	public static final DeferredBlock<Block> ORANGE_BRICK_BUTTON;
	public static final DeferredBlock<Block> YELLOW_BRICK_BUTTON;
	public static final DeferredBlock<Block> GREEN_BRICK_BUTTON;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_BUTTON;
	public static final DeferredBlock<Block> BLUE_BRICK_BUTTON;
	public static final DeferredBlock<Block> MAGENTA_BRICK_BUTTON;
	public static final DeferredBlock<Block> PINK_BRICK_BUTTON;
	public static final DeferredBlock<Block> BROWN_BRICK_BUTTON;
	public static final DeferredBlock<Block> BLACK_BRICK_BUTTON;
	public static final DeferredBlock<Block> WHITE_BRICK_BUTTON;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_BUTTON;
	public static final DeferredBlock<Block> GRAY_BRICK_BUTTON;
	public static final DeferredBlock<Block> LIME_BRICK_BUTTON;
	public static final DeferredBlock<Block> CYAN_BRICK_BUTTON;
	public static final DeferredBlock<Block> PURPLE_BRICK_BUTTON;
	public static final DeferredBlock<Block> CHERRY_BRICK_BUTTON;
	public static final DeferredBlock<Block> TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> TILE_BUTTON;
	public static final DeferredBlock<Block> CEILING_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CEILING_TILE_BUTTON;
	public static final DeferredBlock<Block> WHITE_LARGE_TILE;
	public static final DeferredBlock<Block> WHITE_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> WHITE_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> WHITE_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> WHITE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> WHITE_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> VARIABLE_LIGHT;
	public static final DeferredBlock<Block> LIGHT_GRAY_LARGE_TILE;
	public static final DeferredBlock<Block> GRAY_LARGE_TILE;
	public static final DeferredBlock<Block> BLACK_LARGE_TILE;
	public static final DeferredBlock<Block> ORANGE_LARGE_TILE;
	public static final DeferredBlock<Block> MAGENTA_LARGE_TILE;
	public static final DeferredBlock<Block> LIGHT_BLUE_LARGE_TILE;
	public static final DeferredBlock<Block> BLUE_LARGE_TILE;
	public static final DeferredBlock<Block> YELLOW_LARGE_TILE;
	public static final DeferredBlock<Block> LIME_LARGE_TILE;
	public static final DeferredBlock<Block> GREEN_LARGE_TILE;
	public static final DeferredBlock<Block> PINK_LARGE_TILE;
	public static final DeferredBlock<Block> CYAN_LARGE_TILE;
	public static final DeferredBlock<Block> PURPLE_LARGE_TILE;
	public static final DeferredBlock<Block> BROWN_LARGE_TILE;
	public static final DeferredBlock<Block> RED_LARGE_TILE;
	public static final DeferredBlock<Block> LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> LIGHT_GRAY_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> LIGHT_GRAY_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> LIGHT_GRAY_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> LIGHT_GRAY_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> LIGHT_GRAY_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> LIGHT_GRAY_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> LIGHT_GRAY_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> GRAY_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> GRAY_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> GRAY_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> GRAY_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> GRAY_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> GRAY_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> GRAY_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> BLACK_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> BLACK_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> BLACK_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> BLACK_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> BLACK_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> BLACK_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> BLACK_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> BROWN_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> BROWN_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> BROWN_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> BROWN_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> BROWN_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> BROWN_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> BROWN_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> RED_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> RED_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> RED_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> RED_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> RED_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> RED_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> RED_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> ORANGE_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> ORANGE_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> ORANGE_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> ORANGE_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> ORANGE_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> ORANGE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> ORANGE_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> YELLOW_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> YELLOW_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> YELLOW_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> YELLOW_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> YELLOW_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> YELLOW_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> YELLOW_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> LIME_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> LIME_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> LIME_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> LIME_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> LIME_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> LIME_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> LIME_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> GREEN_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> GREEN_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> GREEN_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> GREEN_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> GREEN_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> GREEN_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> GREEN_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> CYAN_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> CYAN_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> CYAN_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> CYAN_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> CYAN_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> CYAN_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CYAN_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> LIGHT_BLUE_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> LIGHT_BLUE_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> LIGHT_BLUE_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> LIGHT_BLUE_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> LIGHT_BLUE_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> LIGHT_BLUE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> LIGHT_BLUE_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> BLUE_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> BLUE_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> BLUE_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> BLUE_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> BLUE_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> BLUE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> BLUE_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> PURPLE_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> PURPLE_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> PURPLE_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> PURPLE_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> PURPLE_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> PURPLE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> PURPLE_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> MAGENTA_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> MAGENTA_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> MAGENTA_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> MAGENTA_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> MAGENTA_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> MAGENTA_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> MAGENTA_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> PINK_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> PINK_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> PINK_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> PINK_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> PINK_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> PINK_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> PINK_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> CEILING_TILE_FENCE;
	public static final DeferredBlock<Block> CEILING_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> TILE_FENCE;
	public static final DeferredBlock<Block> TILE_FENCE_GATE;
	public static final DeferredBlock<Block> INDUSTRIAL_LARGE_TILE;
	public static final DeferredBlock<Block> INDUSTRIAL_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> INDUSTRIAL_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> INDUSTRIAL_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> INDUSTRIAL_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> INDUSTRIAL_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> INDUSTRIAL_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> INDUSTRIAL_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> WHITE_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> INDUSTRIAL_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_GRAY_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> GRAY_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> BLACK_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> BROWN_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> RED_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> ORANGE_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> YELLOW_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> LIME_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> GREEN_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> CYAN_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_BLUE_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> BLUE_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> PURPLE_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> MAGENTA_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> PINK_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> WHITE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_GRAY_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> GRAY_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> BLACK_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> BROWN_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> RED_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> ORANGE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> YELLOW_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> LIME_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> GREEN_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> CYAN_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_BLUE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> BLUE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> PURPLE_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> MAGENTA_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> PINK_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> CHERRY_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> INDUSTRIAL_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> CEILING_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> TILE_TRAPDOOR;
	public static final DeferredBlock<Block> CHERRY_LARGE_TILE;
	public static final DeferredBlock<Block> CHERRY_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> CHERRY_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> CHERRY_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> CHERRY_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> CHERRY_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> CHERRY_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> CHERRY_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CHERRY_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> SECURE_STORAGE_BLOCK;
	public static final DeferredBlock<Block> TEAL_BRICKS;
	public static final DeferredBlock<Block> TEAL_LARGE_TILE;
	public static final DeferredBlock<Block> TEAL_LARGE_TILE_STAIRS;
	public static final DeferredBlock<Block> TEAL_LARGE_TILE_SLAB;
	public static final DeferredBlock<Block> TEAL_LARGE_TILE_WALL;
	public static final DeferredBlock<Block> TEAL_LARGE_TILE_FENCE;
	public static final DeferredBlock<Block> TEAL_LARGE_TILE_FENCE_GATE;
	public static final DeferredBlock<Block> TEAL_LARGE_TILE_TRAPDOOR;
	public static final DeferredBlock<Block> TEAL_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> TEAL_LARGE_TILE_BUTTON;
	public static final DeferredBlock<Block> TEAL_BRICK_STAIRS;
	public static final DeferredBlock<Block> TEAL_BRICK_SLAB;
	public static final DeferredBlock<Block> TEAL_BRICK_WALL;
	public static final DeferredBlock<Block> TEAL_BRICK_FENCE;
	public static final DeferredBlock<Block> TEAL_BRICK_FENCE_GATE;
	public static final DeferredBlock<Block> TEAL_BRICK_TRAPDOOR;
	public static final DeferredBlock<Block> TEAL_BRICK_PRESSURE_PLATE;
	public static final DeferredBlock<Block> TEAL_BRICK_BUTTON;
	static {
		BANANA_PLANT = register("banana_plant", BannanaplantBlock::new);
		ACID = register("acid", AcidBlock::new);
		RED_BRICKS = register("red_bricks", RedbricksBlock::new);
		ORANGE_BRICKS = register("orange_bricks", OrangebricksBlock::new);
		YELLOW_BRICKS = register("yellow_bricks", YellowbricksBlock::new);
		GREEN_BRICKS = register("green_bricks", GreenbricksBlock::new);
		LIGHT_BLUE_BRICKS = register("light_blue_bricks", LightbluebricksBlock::new);
		BLUE_BRICKS = register("blue_bricks", BluebricksBlock::new);
		MAGENTA_BRICKS = register("magenta_bricks", MagentabricksBlock::new);
		PINK_BRICKS = register("pink_bricks", PinkbricksBlock::new);
		BROWN_BRICKS = register("brown_bricks", BrownbricksBlock::new);
		BLACK_BRICKS = register("black_bricks", BlackbricksBlock::new);
		INDUSTRIAL_BRICKS = register("industrial_bricks", IndustrialbricksBlock::new);
		COMPUTER = register("computer", ComputerBlock::new);
		TILES = register("tiles", TilesBlock::new);
		CEILING_TILES = register("ceiling_tiles", CeilingtilesBlock::new);
		AUTHENTICATOR = register("authenticator", AuthenticatorblockBlock::new);
		RED_BRICK_SLAB = register("red_brick_slab", RedbrickslabBlock::new);
		RED_BRICK_STAIRS = register("red_brick_stairs", RedbrickstairBlock::new);
		ORANGE_BRICK_SLAB = register("orange_brick_slab", OrangebrickslabBlock::new);
		ORANGE_BRICK_STAIRS = register("orange_brick_stairs", OrangebrickstairBlock::new);
		YELLOW_BRICK_SLAB = register("yellow_brick_slab", YellowbrickslabBlock::new);
		YELLOW_BRICK_STAIRS = register("yellow_brick_stairs", YellowbrickstairBlock::new);
		LIGHT_BLUE_BRICK_SLAB = register("light_blue_brick_slab", LightbluebrickslabBlock::new);
		LIGHT_BLUE_BRICK_STAIRS = register("light_blue_brick_stairs", LightbluebrickstairBlock::new);
		BLUE_BRICK_SLAB = register("blue_brick_slab", BluebrickslabBlock::new);
		BLUE_BRICK_STAIRS = register("blue_brick_stairs", BluebrickstairBlock::new);
		MAGENTA_BRICK_SLAB = register("magenta_brick_slab", MagentabrickslabBlock::new);
		MAGENTA_BRICK_STAIRS = register("magenta_brick_stairs", MagentabrickstairBlock::new);
		PINK_BRICK_SLAB = register("pink_brick_slab", PinkbrickslabBlock::new);
		PINK_BRICK_STAIRS = register("pink_brick_stairs", PinkbrickstairBlock::new);
		BROWN_BRICK_SLAB = register("brown_brick_slab", BrownbrickslabBlock::new);
		BROWN_BRICK_STAIRS = register("brown_brick_stairs", BrownbrickstairBlock::new);
		BLACK_BRICK_SLAB = register("black_brick_slab", BlackbrickslabBlock::new);
		BLACK_BRICK_STAIRS = register("black_brick_stairs", BlackbrickstairBlock::new);
		INDUSTRIAL_BRICK_SLAB = register("industrial_brick_slab", IndustrialbrickslabBlock::new);
		INDUSTRIAL_BRICK_STAIRS = register("industrial_brick_stairs", IndustrialbrickstairBlock::new);
		TILE_SLAB = register("tile_slab", TileslabBlock::new);
		TILE_STAIRS = register("tile_stairs", TilestairBlock::new);
		CEILING_TILE_SLAB = register("ceiling_tile_slab", CeilingtileslabBlock::new);
		CEILING_TILE_STAIRS = register("ceiling_tile_stairs", CeilingtilestairBlock::new);
		WHITE_BRICKS = register("white_bricks", WhitebricksBlock::new);
		LIGHT_GRAY_BRICKS = register("light_gray_bricks", LightGrayBricksBlock::new);
		GRAY_BRICKS = register("gray_bricks", GrayBricksBlock::new);
		LIME_BRICKS = register("lime_bricks", LimeBricksBlock::new);
		CYAN_BRICKS = register("cyan_bricks", CyanBricksBlock::new);
		CHERRY_BRICKS = register("cherry_bricks", CherryBricksBlock::new);
		PURPLE_BRICKS = register("purple_bricks", PurpleBricksNewBlock::new);
		LIME_BRICK_SLAB = register("lime_brick_slab", LimeBrickSlabBlock::new);
		LIME_BRICK_STAIRS = register("lime_brick_stairs", LimeBrickStairBlock::new);
		GREEN_BRICK_SLAB = register("green_brick_slab", GreenbricksSlabBlock::new);
		GREEN_BRICK_STAIRS = register("green_brick_stairs", GreenbricksstairBlock::new);
		CYAN_BRICK_SLAB = register("cyan_brick_slab", CyanbrickslabBlock::new);
		CYAN_BRICK_STAIRS = register("cyan_brick_stairs", CyanbrickstairBlock::new);
		PURPLE_BRICK_SLAB = register("purple_brick_slab", PurplebrickslabBlock::new);
		PURPLE_BRICK_STAIRS = register("purple_brick_stairs", PurplebrickstairBlock::new);
		WHITE_BRICK_SLAB = register("white_brick_slab", WhitebrickslabBlock::new);
		WHITE_BRICK_STAIRS = register("white_brick_stairs", WhitebrickstairBlock::new);
		LIGHT_GRAY_BRICK_SLAB = register("light_gray_brick_slab", LightgraybrickslabBlock::new);
		LIGHT_GRAY_BRICK_STAIRS = register("light_gray_brick_stairs", LightgraybrickstairBlock::new);
		GRAY_BRICK_SLAB = register("gray_brick_slab", GraybrickslabBlock::new);
		GRAY_BRICK_STAIRS = register("gray_brick_stairs", GraybrickstairBlock::new);
		CHERRY_BRICK_SLAB = register("cherry_brick_slab", CherrybrickslabBlock::new);
		CHERRY_BRICK_STAIR = register("cherry_brick_stair", CherrybrickstairBlock::new);
		RED_BRICK_WALL = register("red_brick_wall", RedbrickwallBlock::new);
		ORANGE_BRICK_WALL = register("orange_brick_wall", OrangebrickwallBlock::new);
		YELLOW_BRICK_WALL = register("yellow_brick_wall", YellowbrickwallBlock::new);
		GREEN_BRICK_WALL = register("green_brick_wall", GreenbrickwallBlock::new);
		LIGHT_BLUE_BRICK_WALL = register("light_blue_brick_wall", LightbluebrickwallBlock::new);
		BLUE_BRICK_WALL = register("blue_brick_wall", BluebrickwallBlock::new);
		MAGENTA_BRICK_WALL = register("magenta_brick_wall", MagentabrickwallBlock::new);
		PINK_BRICK_WALL = register("pink_brick_wall", PinkbrickwallBlock::new);
		BROWN_BRICK_WALL = register("brown_brick_wall", BrownbrickwallBlock::new);
		BLACK_BRICK_WALL = register("black_brick_wall", BlackbrickwallBlock::new);
		INDUSTRIAL_BRICK_WALL = register("industrial_brick_wall", IndustrialbrickwallBlock::new);
		WHITE_BRICK_WALL = register("white_brick_wall", WhitebrickwallBlock::new);
		LIGHT_GRAY_BRICK_WALL = register("light_gray_brick_wall", LightgraybrickwallBlock::new);
		GRAY_BRICK_WALL = register("gray_brick_wall", GraybrickwallBlock::new);
		LIME_BRICK_WALL = register("lime_brick_wall", LimebrickwallBlock::new);
		CYAN_BRICK_WALL = register("cyan_brick_wall", CyanbrickwallBlock::new);
		CHERRY_BRICK_WALL = register("cherry_brick_wall", CherrybrickwallBlock::new);
		PURPLE_BRICK_WALL = register("purple_brick_wall", PurplebrickwallBlock::new);
		CEILING_TILE_WALL = register("ceiling_tile_wall", CeilingtilewallBlock::new);
		TILE_WALL = register("tile_wall", TilewallBlock::new);
		INDUSTRIAL_BRICK_FENCE = register("industrial_brick_fence", IndustrialbrickfenceBlock::new);
		INDUSTRIAL_BRICK_FENCE_GATE = register("industrial_brick_fence_gate", IndustrialbrickfencegateBlock::new);
		INDUSTRIAL_BRICK_BUTTON = register("industrial_brick_button", IndustrialbrickbuttonBlock::new);
		INDUSTRIAL_BRICK_PRESSURE_PLATE = register("industrial_brick_pressure_plate", IndustrialbrickpreasureplateBlock::new);
		RED_BRICK_FENCE = register("red_brick_fence", RedbrickfenceBlock::new);
		ORANGE_BRICK_FENCE = register("orange_brick_fence", OrangebrickfenceBlock::new);
		YELLOW_BRICK_FENCE = register("yellow_brick_fence", YellowbrickfenceBlock::new);
		GREEN_BRICK_FENCE = register("green_brick_fence", GreenbrickfenceBlock::new);
		LIGHT_BLUE_BRICK_FENCE = register("light_blue_brick_fence", LightbluebrickfenceBlock::new);
		BLUE_BRICK_FENCE = register("blue_brick_fence", BluebrickfenceBlock::new);
		MAGENTA_BRICK_FENCE = register("magenta_brick_fence", MagentabrickfenceBlock::new);
		PINK_BRICK_FENCE = register("pink_brick_fence", PinkbrickfenceBlock::new);
		BROWN_BRICK_FENCE = register("brown_brick_fence", BrownbrickfenceBlock::new);
		BLACK_BRICK_FENCE = register("black_brick_fence", BlackbrickfenceBlock::new);
		WHITE_BRICK_FENCE = register("white_brick_fence", WhitebrickfenceBlock::new);
		LIGHT_GRAY_BRICK_FENCE = register("light_gray_brick_fence", LightgraybrickfenceBlock::new);
		GRAY_BRICK_FENCE = register("gray_brick_fence", GraybrickfenceBlock::new);
		LIME_BRICK_FENCE = register("lime_brick_fence", LimebrickfenceBlock::new);
		CYAN_BRICK_FENCE = register("cyan_brick_fence", CyanbrickfenceBlock::new);
		PURPLE_BRICK_FENCE = register("purple_brick_fence", PurplebrickfenceBlock::new);
		CHERRY_BRICK_FENCE = register("cherry_brick_fence", CherrybrickfenceBlock::new);
		RED_BRICK_FENCE_GATE = register("red_brick_fence_gate", RedbrickfencegateBlock::new);
		ORANGE_BRICK_FENCE_GATE = register("orange_brick_fence_gate", OrangebrickfencegateBlock::new);
		YELLOW_BRICK_FENCE_GATE = register("yellow_brick_fence_gate", YellowbrickfenceagteBlock::new);
		GREEN_BRICK_FENCE_GATE = register("green_brick_fence_gate", GreenbrickfencegateBlock::new);
		LIGHT_BLUE_BRICK_FENCE_GATE = register("light_blue_brick_fence_gate", LightbluebrickfencegateBlock::new);
		BLUE_BRICK_FENCE_GATE = register("blue_brick_fence_gate", BluebrickfencegateBlock::new);
		MAGENTA_BRICK_FENCE_GATE = register("magenta_brick_fence_gate", MagentabrickfencegateBlock::new);
		PINK_BRICK_FENCE_GATE = register("pink_brick_fence_gate", PinkbrickfencegateBlock::new);
		BROWN_BRICK_FENCE_GATE = register("brown_brick_fence_gate", BrownbrickfencegateBlock::new);
		BLACK_BRICK_FENCE_GATE = register("black_brick_fence_gate", BlackbrickfencegateBlock::new);
		WHITE_BRICK_FENCE_GATE = register("white_brick_fence_gate", WhitebrickfencegateBlock::new);
		LIGHT_GRAY_BRICK_FENCE_GATE = register("light_gray_brick_fence_gate", LightgraybrickfencegateBlock::new);
		GRAY_BRICK_FENCE_GATE = register("gray_brick_fence_gate", GraybrickfencegateBlock::new);
		LIME_BRICK_FENCE_GATE = register("lime_brick_fence_gate", LimebrickfencegateBlock::new);
		CYAN_BRICK_FENCE_GATE = register("cyan_brick_fence_gate", CyanbrickfencegateBlock::new);
		PURPLE_BRICK_FENCE_GATE = register("purple_brick_fence_gate", PurplebrickfencegateBlock::new);
		CHERRY_BRICK_FENCE_GATE = register("cherry_brick_fence_gate", CherrybrickfencegateBlock::new);
		RED_BRICK_PRESSURE_PLATE = register("red_brick_pressure_plate", RedbrickpreasureplateBlock::new);
		ORANGE_BRICK_PRESSURE_PLATE = register("orange_brick_pressure_plate", OrangebrickfencegatepreasureplateBlock::new);
		YELLOW_BRICK_PRESSURE_PLATE = register("yellow_brick_pressure_plate", YellowbrickfenceagtepreasureplateBlock::new);
		GREEN_BRICK_PRESSURE_PLATE = register("green_brick_pressure_plate", GreenbrickpreasureplateBlock::new);
		LIGHT_BLUE_BRICK_PRESSURE_PLATE = register("light_blue_brick_pressure_plate", LightbluebrickpreasureplateBlock::new);
		BLUE_BRICK_PRESSURE_PLATE = register("blue_brick_pressure_plate", BluebrickpreasureplateBlock::new);
		MAGENTA_BRICK_PRESSURE_PLATE = register("magenta_brick_pressure_plate", MagentabrickpreasureplateBlock::new);
		PINK_BRICK_PRESSURE_PLATE = register("pink_brick_pressure_plate", PinkbrickpreasureplateBlock::new);
		BROWN_BRICK_PRESSURE_PLATE = register("brown_brick_pressure_plate", BrownbrickpreasureplateBlock::new);
		BLACK_BRICK_PRESSURE_PLATE = register("black_brick_pressure_plate", BlackbrickpreasureplateBlock::new);
		WHITE_BRICK_PRESSURE_PLATE = register("white_brick_pressure_plate", WhitebrickpreasureplateBlock::new);
		LIGHT_GRAY_BRICK_PRESSURE_PLATE = register("light_gray_brick_pressure_plate", LightgraybrickpreasureplateBlock::new);
		GRAY_BRICK_PRESSURE_PLATE = register("gray_brick_pressure_plate", GraybrickpreasureplateBlock::new);
		LIME_BRICK_PRESSURE_PLATE = register("lime_brick_pressure_plate", LimebrickpreasureplateBlock::new);
		CYAN_BRICK_PRESSURE_PLATE = register("cyan_brick_pressure_plate", CyanbrickpreasureplateBlock::new);
		PURPLE_BRICK_PRESSURE_PLATE = register("purple_brick_pressure_plate", PurplebrickpreasureplateBlock::new);
		CHERRY_BRICK_PRESSURE_PLATE = register("cherry_brick_pressure_plate", CherrybrickpreasureplateBlock::new);
		RED_BRICK_BUTTON = register("red_brick_button", RedbrickbuttonBlock::new);
		ORANGE_BRICK_BUTTON = register("orange_brick_button", OrangebrickbuttonBlock::new);
		YELLOW_BRICK_BUTTON = register("yellow_brick_button", YellowbrickbuttonBlock::new);
		GREEN_BRICK_BUTTON = register("green_brick_button", GreenbrickbuttonBlock::new);
		LIGHT_BLUE_BRICK_BUTTON = register("light_blue_brick_button", LightbluebrickbuttonBlock::new);
		BLUE_BRICK_BUTTON = register("blue_brick_button", BluebrickbuttonBlock::new);
		MAGENTA_BRICK_BUTTON = register("magenta_brick_button", MagentabrickbuttonBlock::new);
		PINK_BRICK_BUTTON = register("pink_brick_button", PinkbrickbuttonBlock::new);
		BROWN_BRICK_BUTTON = register("brown_brick_button", BrownbrickbuttonBlock::new);
		BLACK_BRICK_BUTTON = register("black_brick_button", BlackbrickbuttonBlock::new);
		WHITE_BRICK_BUTTON = register("white_brick_button", WhitebrickbuttonBlock::new);
		LIGHT_GRAY_BRICK_BUTTON = register("light_gray_brick_button", LightgraybrickbuttonBlock::new);
		GRAY_BRICK_BUTTON = register("gray_brick_button", GraybrickbuttonBlock::new);
		LIME_BRICK_BUTTON = register("lime_brick_button", LimebrickbuttonBlock::new);
		CYAN_BRICK_BUTTON = register("cyan_brick_button", CyanbrickbuttonBlock::new);
		PURPLE_BRICK_BUTTON = register("purple_brick_button", PurplebrickbuttonBlock::new);
		CHERRY_BRICK_BUTTON = register("cherry_brick_button", CherrybrickbuttonBlock::new);
		TILE_PRESSURE_PLATE = register("tile_pressure_plate", TilepressureplateBlock::new);
		TILE_BUTTON = register("tile_button", TilebuttonBlock::new);
		CEILING_TILE_PRESSURE_PLATE = register("ceiling_tile_pressure_plate", CeilingtilepressureplateBlock::new);
		CEILING_TILE_BUTTON = register("ceiling_tile_button", CeilingtilebuttonBlock::new);
		WHITE_LARGE_TILE = register("white_large_tile", LargetileBlock::new);
		WHITE_LARGE_TILE_STAIRS = register("white_large_tile_stairs", LargetilestairBlock::new);
		WHITE_LARGE_TILE_SLAB = register("white_large_tile_slab", LargetileslabBlock::new);
		WHITE_LARGE_TILE_WALL = register("white_large_tile_wall", LargetilewallBlock::new);
		WHITE_LARGE_TILE_PRESSURE_PLATE = register("white_large_tile_pressure_plate", LargetilepressureplateBlock::new);
		WHITE_LARGE_TILE_BUTTON = register("white_large_tile_button", LargetilebuttonBlock::new);
		VARIABLE_LIGHT = register("variable_light", VariablelightBlock::new);
		LIGHT_GRAY_LARGE_TILE = register("light_gray_large_tile", LightGrayLargeTileBlock::new);
		GRAY_LARGE_TILE = register("gray_large_tile", GrayLargeTileBlock::new);
		BLACK_LARGE_TILE = register("black_large_tile", BlackLargeTileBlock::new);
		ORANGE_LARGE_TILE = register("orange_large_tile", OrangeLargeTileBlock::new);
		MAGENTA_LARGE_TILE = register("magenta_large_tile", MagentaLargeTileBlock::new);
		LIGHT_BLUE_LARGE_TILE = register("light_blue_large_tile", LightBlueLargeTileBlock::new);
		BLUE_LARGE_TILE = register("blue_large_tile", BlueLargeTileBlock::new);
		YELLOW_LARGE_TILE = register("yellow_large_tile", YellowLargeTileBlock::new);
		LIME_LARGE_TILE = register("lime_large_tile", LimeLargeTileBlock::new);
		GREEN_LARGE_TILE = register("green_large_tile", GreenLargeTileBlock::new);
		PINK_LARGE_TILE = register("pink_large_tile", PinkLargeTileBlock::new);
		CYAN_LARGE_TILE = register("cyan_large_tile", CyanLargeTileBlock::new);
		PURPLE_LARGE_TILE = register("purple_large_tile", PurpleLargeTileBlock::new);
		BROWN_LARGE_TILE = register("brown_large_tile", BrownLargeTileBlock::new);
		RED_LARGE_TILE = register("red_large_tile", RedLargeTileBlock::new);
		LARGE_TILE_FENCE = register("large_tile_fence", LargetilefenceBlock::new);
		LARGE_TILE_FENCE_GATE = register("large_tile_fence_gate", LargetilefencegateBlock::new);
		LIGHT_GRAY_LARGE_TILE_STAIRS = register("light_gray_large_tile_stairs", LightGrayLargeTileStairBlock::new);
		LIGHT_GRAY_LARGE_TILE_SLAB = register("light_gray_large_tile_slab", LightGrayLargeTileSlabBlock::new);
		LIGHT_GRAY_LARGE_TILE_WALL = register("light_gray_large_tile_wall", LightGrayLargeTileWallBlock::new);
		LIGHT_GRAY_LARGE_TILE_FENCE = register("light_gray_large_tile_fence", LightGrayLargeTileFenceBlock::new);
		LIGHT_GRAY_LARGE_TILE_FENCE_GATE = register("light_gray_large_tile_fence_gate", LightGrayLargeTileFenceGateBlock::new);
		LIGHT_GRAY_LARGE_TILE_PRESSURE_PLATE = register("light_gray_large_tile_pressure_plate", LightGrayLargeTilePressurePlateBlock::new);
		LIGHT_GRAY_LARGE_TILE_BUTTON = register("light_gray_large_tile_button", LightGrayLargeTileButtonBlock::new);
		GRAY_LARGE_TILE_STAIRS = register("gray_large_tile_stairs", GrayLargeTileStairBlock::new);
		GRAY_LARGE_TILE_SLAB = register("gray_large_tile_slab", GrayLargeTileSlabBlock::new);
		GRAY_LARGE_TILE_WALL = register("gray_large_tile_wall", GrayLargeTileWallBlock::new);
		GRAY_LARGE_TILE_FENCE = register("gray_large_tile_fence", GrayLargeTileFenceBlock::new);
		GRAY_LARGE_TILE_FENCE_GATE = register("gray_large_tile_fence_gate", GrayLargeTileFenceGateBlock::new);
		GRAY_LARGE_TILE_PRESSURE_PLATE = register("gray_large_tile_pressure_plate", GrayLargeTilePressurePlateBlock::new);
		GRAY_LARGE_TILE_BUTTON = register("gray_large_tile_button", GrayLargeTileButtonBlock::new);
		BLACK_LARGE_TILE_STAIRS = register("black_large_tile_stairs", BlackLargeTileStairBlock::new);
		BLACK_LARGE_TILE_SLAB = register("black_large_tile_slab", BlackLargeTileSlabBlock::new);
		BLACK_LARGE_TILE_WALL = register("black_large_tile_wall", BlackLargeTileWallBlock::new);
		BLACK_LARGE_TILE_FENCE = register("black_large_tile_fence", BlackLargeTileFenceBlock::new);
		BLACK_LARGE_TILE_FENCE_GATE = register("black_large_tile_fence_gate", BlackLargeTileFenceGateBlock::new);
		BLACK_LARGE_TILE_PRESSURE_PLATE = register("black_large_tile_pressure_plate", BlackLargeTilePressurePlateBlock::new);
		BLACK_LARGE_TILE_BUTTON = register("black_large_tile_button", BlackLargeTileButtonBlock::new);
		BROWN_LARGE_TILE_STAIRS = register("brown_large_tile_stairs", BrownLargeTileStairBlock::new);
		BROWN_LARGE_TILE_SLAB = register("brown_large_tile_slab", BrownLargeTileSlabBlock::new);
		BROWN_LARGE_TILE_WALL = register("brown_large_tile_wall", BrownLargeTileWallBlock::new);
		BROWN_LARGE_TILE_FENCE = register("brown_large_tile_fence", BrownLargeTileFenceBlock::new);
		BROWN_LARGE_TILE_FENCE_GATE = register("brown_large_tile_fence_gate", BrownLargeTileFenceGateBlock::new);
		BROWN_LARGE_TILE_PRESSURE_PLATE = register("brown_large_tile_pressure_plate", BrownLargeTilePressurePlateBlock::new);
		BROWN_LARGE_TILE_BUTTON = register("brown_large_tile_button", BrownLargeTileButtonBlock::new);
		RED_LARGE_TILE_STAIRS = register("red_large_tile_stairs", RedLargeTileStairBlock::new);
		RED_LARGE_TILE_SLAB = register("red_large_tile_slab", RedLargeTileSlabBlock::new);
		RED_LARGE_TILE_WALL = register("red_large_tile_wall", RedLargeTileWallBlock::new);
		RED_LARGE_TILE_FENCE = register("red_large_tile_fence", RedLargeTileFenceBlock::new);
		RED_LARGE_TILE_FENCE_GATE = register("red_large_tile_fence_gate", RedLargeTileFenceGateBlock::new);
		RED_LARGE_TILE_PRESSURE_PLATE = register("red_large_tile_pressure_plate", RedLargeTilePressurePlateBlock::new);
		RED_LARGE_TILE_BUTTON = register("red_large_tile_button", RedLargeTileButtonBlock::new);
		ORANGE_LARGE_TILE_STAIRS = register("orange_large_tile_stairs", OrangeLargeTileStairBlock::new);
		ORANGE_LARGE_TILE_SLAB = register("orange_large_tile_slab", OrangeLargeTileSlabBlock::new);
		ORANGE_LARGE_TILE_WALL = register("orange_large_tile_wall", OrangeLargeTileWallBlock::new);
		ORANGE_LARGE_TILE_FENCE = register("orange_large_tile_fence", OrangeLargeTileFenceBlock::new);
		ORANGE_LARGE_TILE_FENCE_GATE = register("orange_large_tile_fence_gate", OrangeLargeTileFenceGateBlock::new);
		ORANGE_LARGE_TILE_PRESSURE_PLATE = register("orange_large_tile_pressure_plate", OrangeLargeTilePressurePlateBlock::new);
		ORANGE_LARGE_TILE_BUTTON = register("orange_large_tile_button", OrangeLargeTileButtonBlock::new);
		YELLOW_LARGE_TILE_STAIRS = register("yellow_large_tile_stairs", YellowLargeTileStairBlock::new);
		YELLOW_LARGE_TILE_SLAB = register("yellow_large_tile_slab", YellowLargeTileSlabBlock::new);
		YELLOW_LARGE_TILE_WALL = register("yellow_large_tile_wall", YellowLargeTileWallBlock::new);
		YELLOW_LARGE_TILE_FENCE = register("yellow_large_tile_fence", YellowLargeTileFenceBlock::new);
		YELLOW_LARGE_TILE_FENCE_GATE = register("yellow_large_tile_fence_gate", YellowLargeTileFenceGateBlock::new);
		YELLOW_LARGE_TILE_PRESSURE_PLATE = register("yellow_large_tile_pressure_plate", YellowLargeTilePressurePlateBlock::new);
		YELLOW_LARGE_TILE_BUTTON = register("yellow_large_tile_button", YellowLargeTileButtonBlock::new);
		LIME_LARGE_TILE_STAIRS = register("lime_large_tile_stairs", LimeLargeTileStairBlock::new);
		LIME_LARGE_TILE_SLAB = register("lime_large_tile_slab", LimeLargeTileSlabBlock::new);
		LIME_LARGE_TILE_WALL = register("lime_large_tile_wall", LimeLargeTileWallBlock::new);
		LIME_LARGE_TILE_FENCE = register("lime_large_tile_fence", LimeLargeTileFenceBlock::new);
		LIME_LARGE_TILE_FENCE_GATE = register("lime_large_tile_fence_gate", LimeLargeTileFenceGateBlock::new);
		LIME_LARGE_TILE_PRESSURE_PLATE = register("lime_large_tile_pressure_plate", LimeLargeTilePressurePlateBlock::new);
		LIME_LARGE_TILE_BUTTON = register("lime_large_tile_button", LimeLargeTileButtonBlock::new);
		GREEN_LARGE_TILE_STAIRS = register("green_large_tile_stairs", GreenLargeTileStairBlock::new);
		GREEN_LARGE_TILE_SLAB = register("green_large_tile_slab", GreenLargeTileSlabBlock::new);
		GREEN_LARGE_TILE_WALL = register("green_large_tile_wall", GreenLargeTileWallBlock::new);
		GREEN_LARGE_TILE_FENCE = register("green_large_tile_fence", GreenLargeTileFenceBlock::new);
		GREEN_LARGE_TILE_FENCE_GATE = register("green_large_tile_fence_gate", GreenLargeTileFenceGateBlock::new);
		GREEN_LARGE_TILE_PRESSURE_PLATE = register("green_large_tile_pressure_plate", GreenLargeTilePressurePlateBlock::new);
		GREEN_LARGE_TILE_BUTTON = register("green_large_tile_button", GreenLargeTileButtonBlock::new);
		CYAN_LARGE_TILE_STAIRS = register("cyan_large_tile_stairs", CyanLargeTileStairBlock::new);
		CYAN_LARGE_TILE_SLAB = register("cyan_large_tile_slab", CyanLargeTileSlabBlock::new);
		CYAN_LARGE_TILE_WALL = register("cyan_large_tile_wall", CyanLargeTileWallBlock::new);
		CYAN_LARGE_TILE_FENCE = register("cyan_large_tile_fence", CyanLargeTileFenceBlock::new);
		CYAN_LARGE_TILE_FENCE_GATE = register("cyan_large_tile_fence_gate", CyanLargeTileFenceGateBlock::new);
		CYAN_LARGE_TILE_PRESSURE_PLATE = register("cyan_large_tile_pressure_plate", CyanLargeTilePressurePlateBlock::new);
		CYAN_LARGE_TILE_BUTTON = register("cyan_large_tile_button", CyanLargeTileButtonBlock::new);
		LIGHT_BLUE_LARGE_TILE_STAIRS = register("light_blue_large_tile_stairs", LightBlueLargeTileStairBlock::new);
		LIGHT_BLUE_LARGE_TILE_SLAB = register("light_blue_large_tile_slab", LightBlueLargeTileSlabBlock::new);
		LIGHT_BLUE_LARGE_TILE_WALL = register("light_blue_large_tile_wall", LightBlueLargeTileWallBlock::new);
		LIGHT_BLUE_LARGE_TILE_FENCE = register("light_blue_large_tile_fence", LightBlueLargeTileFenceBlock::new);
		LIGHT_BLUE_LARGE_TILE_FENCE_GATE = register("light_blue_large_tile_fence_gate", LightBlueLargeTileFenceGateBlock::new);
		LIGHT_BLUE_LARGE_TILE_PRESSURE_PLATE = register("light_blue_large_tile_pressure_plate", LightBlueLargeTilePressurePlateBlock::new);
		LIGHT_BLUE_LARGE_TILE_BUTTON = register("light_blue_large_tile_button", LightBlueLargeTileButtonBlock::new);
		BLUE_LARGE_TILE_STAIRS = register("blue_large_tile_stairs", BlueLargeTileStairBlock::new);
		BLUE_LARGE_TILE_SLAB = register("blue_large_tile_slab", BlueLargeTileSlabBlock::new);
		BLUE_LARGE_TILE_WALL = register("blue_large_tile_wall", BlueLargeTileWallBlock::new);
		BLUE_LARGE_TILE_FENCE = register("blue_large_tile_fence", BlueLargeTileFenceBlock::new);
		BLUE_LARGE_TILE_FENCE_GATE = register("blue_large_tile_fence_gate", BlueLargeTileFenceGateBlock::new);
		BLUE_LARGE_TILE_PRESSURE_PLATE = register("blue_large_tile_pressure_plate", BlueLargeTilePressurePlateBlock::new);
		BLUE_LARGE_TILE_BUTTON = register("blue_large_tile_button", BlueLargeTileButtonBlock::new);
		PURPLE_LARGE_TILE_STAIRS = register("purple_large_tile_stairs", PurpleLargeTileStairBlock::new);
		PURPLE_LARGE_TILE_SLAB = register("purple_large_tile_slab", PurpleLargeTileSlabBlock::new);
		PURPLE_LARGE_TILE_WALL = register("purple_large_tile_wall", PurpleLargeTileWallBlock::new);
		PURPLE_LARGE_TILE_FENCE = register("purple_large_tile_fence", PurpleLargeTileFenceBlock::new);
		PURPLE_LARGE_TILE_FENCE_GATE = register("purple_large_tile_fence_gate", PurpleLargeTileFenceGateBlock::new);
		PURPLE_LARGE_TILE_PRESSURE_PLATE = register("purple_large_tile_pressure_plate", PurpleLargeTilePressurePlateBlock::new);
		PURPLE_LARGE_TILE_BUTTON = register("purple_large_tile_button", PurpleLargeTileButtonBlock::new);
		MAGENTA_LARGE_TILE_STAIRS = register("magenta_large_tile_stairs", MagentaLargeTileStairBlock::new);
		MAGENTA_LARGE_TILE_SLAB = register("magenta_large_tile_slab", MagentaLargeTileSlabBlock::new);
		MAGENTA_LARGE_TILE_WALL = register("magenta_large_tile_wall", MagentaLargeTileWallBlock::new);
		MAGENTA_LARGE_TILE_FENCE = register("magenta_large_tile_fence", MagentaLargeTileFenceBlock::new);
		MAGENTA_LARGE_TILE_FENCE_GATE = register("magenta_large_tile_fence_gate", MagentaLargeTileFenceGateBlock::new);
		MAGENTA_LARGE_TILE_PRESSURE_PLATE = register("magenta_large_tile_pressure_plate", MagentaLargeTilePressurePlateBlock::new);
		MAGENTA_LARGE_TILE_BUTTON = register("magenta_large_tile_button", MagentaLargeTileButtonBlock::new);
		PINK_LARGE_TILE_STAIRS = register("pink_large_tile_stairs", PinkLargeTileStairBlock::new);
		PINK_LARGE_TILE_SLAB = register("pink_large_tile_slab", PinkLargeTileSlabBlock::new);
		PINK_LARGE_TILE_WALL = register("pink_large_tile_wall", PinkLargeTileWallBlock::new);
		PINK_LARGE_TILE_FENCE = register("pink_large_tile_fence", PinkLargeTileFenceBlock::new);
		PINK_LARGE_TILE_FENCE_GATE = register("pink_large_tile_fence_gate", PinkLargeTileFenceGateBlock::new);
		PINK_LARGE_TILE_PRESSURE_PLATE = register("pink_large_tile_pressure_plate", PinkLargeTilePressurePlateBlock::new);
		PINK_LARGE_TILE_BUTTON = register("pink_large_tile_button", PinkLargeTileButtonBlock::new);
		CEILING_TILE_FENCE = register("ceiling_tile_fence", CeilingtilefenceBlock::new);
		CEILING_TILE_FENCE_GATE = register("ceiling_tile_fence_gate", CeilingtilefencegateBlock::new);
		TILE_FENCE = register("tile_fence", TilefenceBlock::new);
		TILE_FENCE_GATE = register("tile_fence_gate", TilefencegateBlock::new);
		INDUSTRIAL_LARGE_TILE = register("industrial_large_tile", IndustrialLargeTileBlock::new);
		INDUSTRIAL_LARGE_TILE_STAIRS = register("industrial_large_tile_stairs", IndustrialLargeTileStairBlock::new);
		INDUSTRIAL_LARGE_TILE_SLAB = register("industrial_large_tile_slab", IndustrialLargeTileSlabBlock::new);
		INDUSTRIAL_LARGE_TILE_WALL = register("industrial_large_tile_wall", IndustrialLargeTileWallBlock::new);
		INDUSTRIAL_LARGE_TILE_FENCE = register("industrial_large_tile_fence", IndustrialLargeTileFenceBlock::new);
		INDUSTRIAL_LARGE_TILE_FENCE_GATE = register("industrial_large_tile_fence_gate", IndustrialLargeTileFenceGateBlock::new);
		INDUSTRIAL_LARGE_TILE_PRESSURE_PLATE = register("industrial_large_tile_pressure_plate", IndustrialLargeTilePressurePlateBlock::new);
		INDUSTRIAL_LARGE_TILE_BUTTON = register("industrial_large_tile_button", IndustrialLargeTileButtonBlock::new);
		WHITE_LARGE_TILE_TRAPDOOR = register("white_large_tile_trapdoor", WhitelargetiletrapdoorBlock::new);
		INDUSTRIAL_LARGE_TILE_TRAPDOOR = register("industrial_large_tile_trapdoor", IndustriallargetiletrapdoorBlock::new);
		LIGHT_GRAY_LARGE_TILE_TRAPDOOR = register("light_gray_large_tile_trapdoor", LightgraylargetiletrapdoorBlock::new);
		GRAY_LARGE_TILE_TRAPDOOR = register("gray_large_tile_trapdoor", GraylargetiletrapdoorBlock::new);
		BLACK_LARGE_TILE_TRAPDOOR = register("black_large_tile_trapdoor", BlacklargetiletrapdoorBlock::new);
		BROWN_LARGE_TILE_TRAPDOOR = register("brown_large_tile_trapdoor", BrownlargetiletrapdoorBlock::new);
		RED_LARGE_TILE_TRAPDOOR = register("red_large_tile_trapdoor", RedlargetiletrapdoorBlock::new);
		ORANGE_LARGE_TILE_TRAPDOOR = register("orange_large_tile_trapdoor", OrangelargetiletrapdoorBlock::new);
		YELLOW_LARGE_TILE_TRAPDOOR = register("yellow_large_tile_trapdoor", YellowlargetiletrapdoorBlock::new);
		LIME_LARGE_TILE_TRAPDOOR = register("lime_large_tile_trapdoor", LimelargetiletrapdoorBlock::new);
		GREEN_LARGE_TILE_TRAPDOOR = register("green_large_tile_trapdoor", GreenlargetiletrapdoorBlock::new);
		CYAN_LARGE_TILE_TRAPDOOR = register("cyan_large_tile_trapdoor", CyanlargetiletrapdoorBlock::new);
		LIGHT_BLUE_LARGE_TILE_TRAPDOOR = register("light_blue_large_tile_trapdoor", LightbluelargetiletrapdoorBlock::new);
		BLUE_LARGE_TILE_TRAPDOOR = register("blue_large_tile_trapdoor", BluelargetiletrapdoorBlock::new);
		PURPLE_LARGE_TILE_TRAPDOOR = register("purple_large_tile_trapdoor", PurplelargetiletrapdoorBlock::new);
		MAGENTA_LARGE_TILE_TRAPDOOR = register("magenta_large_tile_trapdoor", MagentalargetiletrapdoorBlock::new);
		PINK_LARGE_TILE_TRAPDOOR = register("pink_large_tile_trapdoor", PinklargetiletrapdoorBlock::new);
		WHITE_BRICK_TRAPDOOR = register("white_brick_trapdoor", WhitebricktrapdoorBlock::new);
		LIGHT_GRAY_BRICK_TRAPDOOR = register("light_gray_brick_trapdoor", LightgraybricktrapdoorBlock::new);
		GRAY_BRICK_TRAPDOOR = register("gray_brick_trapdoor", GraybricktrapdoorBlock::new);
		BLACK_BRICK_TRAPDOOR = register("black_brick_trapdoor", BlackbricktrapdoorBlock::new);
		BROWN_BRICK_TRAPDOOR = register("brown_brick_trapdoor", BrownbricktrapdoorBlock::new);
		RED_BRICK_TRAPDOOR = register("red_brick_trapdoor", RedbricktrapdoorBlock::new);
		ORANGE_BRICK_TRAPDOOR = register("orange_brick_trapdoor", OrangebricktrapdoorBlock::new);
		YELLOW_BRICK_TRAPDOOR = register("yellow_brick_trapdoor", YellowbricktrapdoorBlock::new);
		LIME_BRICK_TRAPDOOR = register("lime_brick_trapdoor", LimebricktrapdoorBlock::new);
		GREEN_BRICK_TRAPDOOR = register("green_brick_trapdoor", GreenbricktrapdoorBlock::new);
		CYAN_BRICK_TRAPDOOR = register("cyan_brick_trapdoor", CyanbricktrapdoorBlock::new);
		LIGHT_BLUE_BRICK_TRAPDOOR = register("light_blue_brick_trapdoor", LightbluebricktrapdoorBlock::new);
		BLUE_BRICK_TRAPDOOR = register("blue_brick_trapdoor", BluebricktrapdoorBlock::new);
		PURPLE_BRICK_TRAPDOOR = register("purple_brick_trapdoor", PurplebricktrapdoorBlock::new);
		MAGENTA_BRICK_TRAPDOOR = register("magenta_brick_trapdoor", MagentabricktrapdoorBlock::new);
		PINK_BRICK_TRAPDOOR = register("pink_brick_trapdoor", PinkbricktrapdoorBlock::new);
		CHERRY_BRICK_TRAPDOOR = register("cherry_brick_trapdoor", CherrybricktrapdoorBlock::new);
		INDUSTRIAL_BRICK_TRAPDOOR = register("industrial_brick_trapdoor", IndustrialbricktrapdoorBlock::new);
		CEILING_TILE_TRAPDOOR = register("ceiling_tile_trapdoor", CeilingtiletrapdoorBlock::new);
		TILE_TRAPDOOR = register("tile_trapdoor", TiletrapdoorBlock::new);
		CHERRY_LARGE_TILE = register("cherry_large_tile", CherrylargetileBlock::new);
		CHERRY_LARGE_TILE_STAIRS = register("cherry_large_tile_stairs", CherrylargetilestairBlock::new);
		CHERRY_LARGE_TILE_SLAB = register("cherry_large_tile_slab", CherrylargetileslabBlock::new);
		CHERRY_LARGE_TILE_WALL = register("cherry_large_tile_wall", CherrylargetilewallBlock::new);
		CHERRY_LARGE_TILE_FENCE = register("cherry_large_tile_fence", CherrylargetilefenceBlock::new);
		CHERRY_LARGE_TILE_FENCE_GATE = register("cherry_large_tile_fence_gate", CherrylargetilefencegateBlock::new);
		CHERRY_LARGE_TILE_TRAPDOOR = register("cherry_large_tile_trapdoor", CherrylargetiletrapdoorBlock::new);
		CHERRY_LARGE_TILE_PRESSURE_PLATE = register("cherry_large_tile_pressure_plate", CherrylargetilepressureplateBlock::new);
		CHERRY_LARGE_TILE_BUTTON = register("cherry_large_tile_button", CherrylargetilebuttonBlock::new);
		SECURE_STORAGE_BLOCK = register("secure_storage_block", SecurestorageblockBlock::new);
		TEAL_BRICKS = register("teal_bricks", TealbricksBlock::new);
		TEAL_LARGE_TILE = register("teal_large_tile", TealLargeTileBlock::new);
		TEAL_LARGE_TILE_STAIRS = register("teal_large_tile_stairs", TealLargeTileStairBlock::new);
		TEAL_LARGE_TILE_SLAB = register("teal_large_tile_slab", TeallargetileslabBlock::new);
		TEAL_LARGE_TILE_WALL = register("teal_large_tile_wall", TeallargetilewallBlock::new);
		TEAL_LARGE_TILE_FENCE = register("teal_large_tile_fence", TeallargetilefenceBlock::new);
		TEAL_LARGE_TILE_FENCE_GATE = register("teal_large_tile_fence_gate", TeallargetilefencegateBlock::new);
		TEAL_LARGE_TILE_TRAPDOOR = register("teal_large_tile_trapdoor", TeallargetiletrapdoorBlock::new);
		TEAL_LARGE_TILE_PRESSURE_PLATE = register("teal_large_tile_pressure_plate", TeallargetilepressureplateBlock::new);
		TEAL_LARGE_TILE_BUTTON = register("teal_large_tile_button", TeallargetilebuttonBlock::new);
		TEAL_BRICK_STAIRS = register("teal_brick_stairs", TealbrickstairBlock::new);
		TEAL_BRICK_SLAB = register("teal_brick_slab", TealbrickslabBlock::new);
		TEAL_BRICK_WALL = register("teal_brick_wall", TealbrickwallBlock::new);
		TEAL_BRICK_FENCE = register("teal_brick_fence", TealbrickfenceBlock::new);
		TEAL_BRICK_FENCE_GATE = register("teal_brick_fence_gate", TealbrickfencegateBlock::new);
		TEAL_BRICK_TRAPDOOR = register("teal_brick_trapdoor", TealbricktrapdoorBlock::new);
		TEAL_BRICK_PRESSURE_PLATE = register("teal_brick_pressure_plate", TealbrickpressureplateBlock::new);
		TEAL_BRICK_BUTTON = register("teal_brick_button", TealbrickbuttonBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			BannanaplantBlock.blockColorLoad(event);
		}
	}
}