/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package mc.omegabird.llamablocks.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import mc.omegabird.llamablocks.item.inventory.NetheritebackpackInventoryCapability;
import mc.omegabird.llamablocks.item.inventory.BackpackInventoryCapability;
import mc.omegabird.llamablocks.item.*;
import mc.omegabird.llamablocks.LlamamodMod;

import java.util.function.Function;

@EventBusSubscriber
public class LlamamodModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(LlamamodMod.MODID);
	public static final DeferredItem<Item> BANANA_PLANT;
	public static final DeferredItem<Item> BANANA;
	public static final DeferredItem<Item> BACKPACK;
	public static final DeferredItem<Item> NETHERITE_BACKPACK;
	public static final DeferredItem<Item> ACID_BUCKET;
	public static final DeferredItem<Item> RED_BRICKS;
	public static final DeferredItem<Item> ORANGE_BRICKS;
	public static final DeferredItem<Item> YELLOW_BRICKS;
	public static final DeferredItem<Item> GREEN_BRICKS;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICKS;
	public static final DeferredItem<Item> BLUE_BRICKS;
	public static final DeferredItem<Item> MAGENTA_BRICKS;
	public static final DeferredItem<Item> PINK_BRICKS;
	public static final DeferredItem<Item> BROWN_BRICKS;
	public static final DeferredItem<Item> BLACK_BRICKS;
	public static final DeferredItem<Item> INDUSTRIAL_BRICKS;
	public static final DeferredItem<Item> COMPUTER;
	public static final DeferredItem<Item> TILES;
	public static final DeferredItem<Item> FARM_SCRAPS;
	public static final DeferredItem<Item> CEILING_TILES;
	public static final DeferredItem<Item> AUTHENTICATOR;
	public static final DeferredItem<Item> PASSWORD_CHANGER;
	public static final DeferredItem<Item> RED_BRICK_SLAB;
	public static final DeferredItem<Item> RED_BRICK_STAIRS;
	public static final DeferredItem<Item> ORANGE_BRICK_SLAB;
	public static final DeferredItem<Item> ORANGE_BRICK_STAIRS;
	public static final DeferredItem<Item> YELLOW_BRICK_SLAB;
	public static final DeferredItem<Item> YELLOW_BRICK_STAIRS;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_SLAB;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_STAIRS;
	public static final DeferredItem<Item> BLUE_BRICK_SLAB;
	public static final DeferredItem<Item> BLUE_BRICK_STAIRS;
	public static final DeferredItem<Item> MAGENTA_BRICK_SLAB;
	public static final DeferredItem<Item> MAGENTA_BRICK_STAIRS;
	public static final DeferredItem<Item> PINK_BRICK_SLAB;
	public static final DeferredItem<Item> PINK_BRICK_STAIRS;
	public static final DeferredItem<Item> BROWN_BRICK_SLAB;
	public static final DeferredItem<Item> BROWN_BRICK_STAIRS;
	public static final DeferredItem<Item> BLACK_BRICK_SLAB;
	public static final DeferredItem<Item> BLACK_BRICK_STAIRS;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_SLAB;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_STAIRS;
	public static final DeferredItem<Item> TILE_SLAB;
	public static final DeferredItem<Item> TILE_STAIRS;
	public static final DeferredItem<Item> CEILING_TILE_SLAB;
	public static final DeferredItem<Item> CEILING_TILE_STAIRS;
	public static final DeferredItem<Item> WHITE_BRICKS;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICKS;
	public static final DeferredItem<Item> GRAY_BRICKS;
	public static final DeferredItem<Item> LIME_BRICKS;
	public static final DeferredItem<Item> CYAN_BRICKS;
	public static final DeferredItem<Item> CHERRY_BRICKS;
	public static final DeferredItem<Item> PURPLE_BRICKS;
	public static final DeferredItem<Item> LIME_BRICK_SLAB;
	public static final DeferredItem<Item> LIME_BRICK_STAIRS;
	public static final DeferredItem<Item> GREEN_BRICK_SLAB;
	public static final DeferredItem<Item> GREEN_BRICK_STAIRS;
	public static final DeferredItem<Item> CYAN_BRICK_SLAB;
	public static final DeferredItem<Item> CYAN_BRICK_STAIRS;
	public static final DeferredItem<Item> PURPLE_BRICK_SLAB;
	public static final DeferredItem<Item> PURPLE_BRICK_STAIRS;
	public static final DeferredItem<Item> WHITE_BRICK_SLAB;
	public static final DeferredItem<Item> WHITE_BRICK_STAIRS;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_SLAB;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_STAIRS;
	public static final DeferredItem<Item> GRAY_BRICK_SLAB;
	public static final DeferredItem<Item> GRAY_BRICK_STAIRS;
	public static final DeferredItem<Item> CHERRY_BRICK_SLAB;
	public static final DeferredItem<Item> CHERRY_BRICK_STAIR;
	public static final DeferredItem<Item> RED_BRICK_WALL;
	public static final DeferredItem<Item> ORANGE_BRICK_WALL;
	public static final DeferredItem<Item> YELLOW_BRICK_WALL;
	public static final DeferredItem<Item> GREEN_BRICK_WALL;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_WALL;
	public static final DeferredItem<Item> BLUE_BRICK_WALL;
	public static final DeferredItem<Item> MAGENTA_BRICK_WALL;
	public static final DeferredItem<Item> PINK_BRICK_WALL;
	public static final DeferredItem<Item> BROWN_BRICK_WALL;
	public static final DeferredItem<Item> BLACK_BRICK_WALL;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_WALL;
	public static final DeferredItem<Item> WHITE_BRICK_WALL;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_WALL;
	public static final DeferredItem<Item> GRAY_BRICK_WALL;
	public static final DeferredItem<Item> LIME_BRICK_WALL;
	public static final DeferredItem<Item> CYAN_BRICK_WALL;
	public static final DeferredItem<Item> CHERRY_BRICK_WALL;
	public static final DeferredItem<Item> PURPLE_BRICK_WALL;
	public static final DeferredItem<Item> CEILING_TILE_WALL;
	public static final DeferredItem<Item> TILE_WALL;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_FENCE;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_BUTTON;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> RED_BRICK_FENCE;
	public static final DeferredItem<Item> ORANGE_BRICK_FENCE;
	public static final DeferredItem<Item> YELLOW_BRICK_FENCE;
	public static final DeferredItem<Item> GREEN_BRICK_FENCE;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_FENCE;
	public static final DeferredItem<Item> BLUE_BRICK_FENCE;
	public static final DeferredItem<Item> MAGENTA_BRICK_FENCE;
	public static final DeferredItem<Item> PINK_BRICK_FENCE;
	public static final DeferredItem<Item> BROWN_BRICK_FENCE;
	public static final DeferredItem<Item> BLACK_BRICK_FENCE;
	public static final DeferredItem<Item> WHITE_BRICK_FENCE;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_FENCE;
	public static final DeferredItem<Item> GRAY_BRICK_FENCE;
	public static final DeferredItem<Item> LIME_BRICK_FENCE;
	public static final DeferredItem<Item> CYAN_BRICK_FENCE;
	public static final DeferredItem<Item> PURPLE_BRICK_FENCE;
	public static final DeferredItem<Item> CHERRY_BRICK_FENCE;
	public static final DeferredItem<Item> RED_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> ORANGE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> YELLOW_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> GREEN_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> BLUE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> MAGENTA_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> PINK_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> BROWN_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> BLACK_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> WHITE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> GRAY_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> LIME_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> CYAN_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> PURPLE_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> CHERRY_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> RED_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> ORANGE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> YELLOW_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> GREEN_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> BLUE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> MAGENTA_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> PINK_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> BROWN_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> BLACK_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> WHITE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> GRAY_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> LIME_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> CYAN_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> PURPLE_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> CHERRY_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> RED_BRICK_BUTTON;
	public static final DeferredItem<Item> ORANGE_BRICK_BUTTON;
	public static final DeferredItem<Item> YELLOW_BRICK_BUTTON;
	public static final DeferredItem<Item> GREEN_BRICK_BUTTON;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_BUTTON;
	public static final DeferredItem<Item> BLUE_BRICK_BUTTON;
	public static final DeferredItem<Item> MAGENTA_BRICK_BUTTON;
	public static final DeferredItem<Item> PINK_BRICK_BUTTON;
	public static final DeferredItem<Item> BROWN_BRICK_BUTTON;
	public static final DeferredItem<Item> BLACK_BRICK_BUTTON;
	public static final DeferredItem<Item> WHITE_BRICK_BUTTON;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_BUTTON;
	public static final DeferredItem<Item> GRAY_BRICK_BUTTON;
	public static final DeferredItem<Item> LIME_BRICK_BUTTON;
	public static final DeferredItem<Item> CYAN_BRICK_BUTTON;
	public static final DeferredItem<Item> PURPLE_BRICK_BUTTON;
	public static final DeferredItem<Item> CHERRY_BRICK_BUTTON;
	public static final DeferredItem<Item> TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> TILE_BUTTON;
	public static final DeferredItem<Item> CEILING_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> CEILING_TILE_BUTTON;
	public static final DeferredItem<Item> WHITE_LARGE_TILE;
	public static final DeferredItem<Item> WHITE_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> WHITE_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> WHITE_LARGE_TILE_WALL;
	public static final DeferredItem<Item> WHITE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> WHITE_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> VARIABLE_LIGHT;
	public static final DeferredItem<Item> LIGHT_GRAY_LARGE_TILE;
	public static final DeferredItem<Item> GRAY_LARGE_TILE;
	public static final DeferredItem<Item> BLACK_LARGE_TILE;
	public static final DeferredItem<Item> ORANGE_LARGE_TILE;
	public static final DeferredItem<Item> MAGENTA_LARGE_TILE;
	public static final DeferredItem<Item> LIGHT_BLUE_LARGE_TILE;
	public static final DeferredItem<Item> BLUE_LARGE_TILE;
	public static final DeferredItem<Item> YELLOW_LARGE_TILE;
	public static final DeferredItem<Item> LIME_LARGE_TILE;
	public static final DeferredItem<Item> GREEN_LARGE_TILE;
	public static final DeferredItem<Item> PINK_LARGE_TILE;
	public static final DeferredItem<Item> CYAN_LARGE_TILE;
	public static final DeferredItem<Item> PURPLE_LARGE_TILE;
	public static final DeferredItem<Item> BROWN_LARGE_TILE;
	public static final DeferredItem<Item> RED_LARGE_TILE;
	public static final DeferredItem<Item> LARGE_TILE_FENCE;
	public static final DeferredItem<Item> LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> LIGHT_GRAY_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> LIGHT_GRAY_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> LIGHT_GRAY_LARGE_TILE_WALL;
	public static final DeferredItem<Item> LIGHT_GRAY_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> LIGHT_GRAY_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> LIGHT_GRAY_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> LIGHT_GRAY_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> GRAY_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> GRAY_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> GRAY_LARGE_TILE_WALL;
	public static final DeferredItem<Item> GRAY_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> GRAY_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> GRAY_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> GRAY_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> BLACK_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> BLACK_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> BLACK_LARGE_TILE_WALL;
	public static final DeferredItem<Item> BLACK_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> BLACK_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> BLACK_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> BLACK_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> BROWN_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> BROWN_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> BROWN_LARGE_TILE_WALL;
	public static final DeferredItem<Item> BROWN_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> BROWN_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> BROWN_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> BROWN_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> RED_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> RED_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> RED_LARGE_TILE_WALL;
	public static final DeferredItem<Item> RED_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> RED_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> RED_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> RED_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> ORANGE_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> ORANGE_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> ORANGE_LARGE_TILE_WALL;
	public static final DeferredItem<Item> ORANGE_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> ORANGE_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> ORANGE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> ORANGE_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> YELLOW_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> YELLOW_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> YELLOW_LARGE_TILE_WALL;
	public static final DeferredItem<Item> YELLOW_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> YELLOW_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> YELLOW_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> YELLOW_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> LIME_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> LIME_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> LIME_LARGE_TILE_WALL;
	public static final DeferredItem<Item> LIME_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> LIME_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> LIME_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> LIME_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> GREEN_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> GREEN_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> GREEN_LARGE_TILE_WALL;
	public static final DeferredItem<Item> GREEN_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> GREEN_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> GREEN_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> GREEN_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> CYAN_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> CYAN_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> CYAN_LARGE_TILE_WALL;
	public static final DeferredItem<Item> CYAN_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> CYAN_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> CYAN_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> CYAN_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> LIGHT_BLUE_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> LIGHT_BLUE_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> LIGHT_BLUE_LARGE_TILE_WALL;
	public static final DeferredItem<Item> LIGHT_BLUE_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> LIGHT_BLUE_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> LIGHT_BLUE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> LIGHT_BLUE_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> BLUE_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> BLUE_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> BLUE_LARGE_TILE_WALL;
	public static final DeferredItem<Item> BLUE_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> BLUE_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> BLUE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> BLUE_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> PURPLE_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> PURPLE_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> PURPLE_LARGE_TILE_WALL;
	public static final DeferredItem<Item> PURPLE_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> PURPLE_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> PURPLE_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> PURPLE_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> MAGENTA_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> MAGENTA_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> MAGENTA_LARGE_TILE_WALL;
	public static final DeferredItem<Item> MAGENTA_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> MAGENTA_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> MAGENTA_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> MAGENTA_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> PINK_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> PINK_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> PINK_LARGE_TILE_WALL;
	public static final DeferredItem<Item> PINK_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> PINK_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> PINK_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> PINK_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> CEILING_TILE_FENCE;
	public static final DeferredItem<Item> CEILING_TILE_FENCE_GATE;
	public static final DeferredItem<Item> TILE_FENCE;
	public static final DeferredItem<Item> TILE_FENCE_GATE;
	public static final DeferredItem<Item> INDUSTRIAL_LARGE_TILE;
	public static final DeferredItem<Item> INDUSTRIAL_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> INDUSTRIAL_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> INDUSTRIAL_LARGE_TILE_WALL;
	public static final DeferredItem<Item> INDUSTRIAL_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> INDUSTRIAL_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> INDUSTRIAL_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> INDUSTRIAL_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> WHITE_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> INDUSTRIAL_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_GRAY_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> GRAY_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> BLACK_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> BROWN_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> RED_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> ORANGE_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> YELLOW_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> LIME_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> GREEN_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> CYAN_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_BLUE_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> BLUE_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> PURPLE_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> MAGENTA_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> PINK_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> WHITE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_GRAY_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> GRAY_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> BLACK_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> BROWN_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> RED_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> ORANGE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> YELLOW_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> LIME_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> GREEN_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> CYAN_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_BLUE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> BLUE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> PURPLE_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> MAGENTA_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> PINK_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> CHERRY_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> INDUSTRIAL_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> CEILING_TILE_TRAPDOOR;
	public static final DeferredItem<Item> TILE_TRAPDOOR;
	public static final DeferredItem<Item> CHERRY_LARGE_TILE;
	public static final DeferredItem<Item> CHERRY_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> CHERRY_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> CHERRY_LARGE_TILE_WALL;
	public static final DeferredItem<Item> CHERRY_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> CHERRY_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> CHERRY_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> CHERRY_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> CHERRY_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> SECURE_STORAGE_BLOCK;
	public static final DeferredItem<Item> TEAL_BRICKS;
	public static final DeferredItem<Item> TEAL_LARGE_TILE;
	public static final DeferredItem<Item> TEAL_LARGE_TILE_STAIRS;
	public static final DeferredItem<Item> TEAL_LARGE_TILE_SLAB;
	public static final DeferredItem<Item> TEAL_LARGE_TILE_WALL;
	public static final DeferredItem<Item> TEAL_LARGE_TILE_FENCE;
	public static final DeferredItem<Item> TEAL_LARGE_TILE_FENCE_GATE;
	public static final DeferredItem<Item> TEAL_LARGE_TILE_TRAPDOOR;
	public static final DeferredItem<Item> TEAL_LARGE_TILE_PRESSURE_PLATE;
	public static final DeferredItem<Item> TEAL_LARGE_TILE_BUTTON;
	public static final DeferredItem<Item> TEAL_BRICK_STAIRS;
	public static final DeferredItem<Item> TEAL_BRICK_SLAB;
	public static final DeferredItem<Item> TEAL_BRICK_WALL;
	public static final DeferredItem<Item> TEAL_BRICK_FENCE;
	public static final DeferredItem<Item> TEAL_BRICK_FENCE_GATE;
	public static final DeferredItem<Item> TEAL_BRICK_TRAPDOOR;
	public static final DeferredItem<Item> TEAL_BRICK_PRESSURE_PLATE;
	public static final DeferredItem<Item> TEAL_BRICK_BUTTON;
	public static final DeferredItem<Item> GOLDEN_BANANA;
	static {
		BANANA_PLANT = block(LlamamodModBlocks.BANANA_PLANT);
		BANANA = register("banana", BannanaItem::new);
		BACKPACK = register("backpack", BackpackItem::new);
		NETHERITE_BACKPACK = register("netherite_backpack", NetheritebackpackItem::new);
		ACID_BUCKET = register("acid_bucket", AcidItem::new);
		RED_BRICKS = block(LlamamodModBlocks.RED_BRICKS);
		ORANGE_BRICKS = block(LlamamodModBlocks.ORANGE_BRICKS);
		YELLOW_BRICKS = block(LlamamodModBlocks.YELLOW_BRICKS);
		GREEN_BRICKS = block(LlamamodModBlocks.GREEN_BRICKS);
		LIGHT_BLUE_BRICKS = block(LlamamodModBlocks.LIGHT_BLUE_BRICKS);
		BLUE_BRICKS = block(LlamamodModBlocks.BLUE_BRICKS);
		MAGENTA_BRICKS = block(LlamamodModBlocks.MAGENTA_BRICKS);
		PINK_BRICKS = block(LlamamodModBlocks.PINK_BRICKS);
		BROWN_BRICKS = block(LlamamodModBlocks.BROWN_BRICKS);
		BLACK_BRICKS = block(LlamamodModBlocks.BLACK_BRICKS);
		INDUSTRIAL_BRICKS = block(LlamamodModBlocks.INDUSTRIAL_BRICKS);
		COMPUTER = block(LlamamodModBlocks.COMPUTER);
		TILES = block(LlamamodModBlocks.TILES);
		FARM_SCRAPS = register("farm_scraps", FarmscrapsItem::new);
		CEILING_TILES = block(LlamamodModBlocks.CEILING_TILES);
		AUTHENTICATOR = block(LlamamodModBlocks.AUTHENTICATOR);
		PASSWORD_CHANGER = register("password_changer", PasswordchangerItem::new);
		RED_BRICK_SLAB = block(LlamamodModBlocks.RED_BRICK_SLAB);
		RED_BRICK_STAIRS = block(LlamamodModBlocks.RED_BRICK_STAIRS);
		ORANGE_BRICK_SLAB = block(LlamamodModBlocks.ORANGE_BRICK_SLAB);
		ORANGE_BRICK_STAIRS = block(LlamamodModBlocks.ORANGE_BRICK_STAIRS);
		YELLOW_BRICK_SLAB = block(LlamamodModBlocks.YELLOW_BRICK_SLAB);
		YELLOW_BRICK_STAIRS = block(LlamamodModBlocks.YELLOW_BRICK_STAIRS);
		LIGHT_BLUE_BRICK_SLAB = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_SLAB);
		LIGHT_BLUE_BRICK_STAIRS = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_STAIRS);
		BLUE_BRICK_SLAB = block(LlamamodModBlocks.BLUE_BRICK_SLAB);
		BLUE_BRICK_STAIRS = block(LlamamodModBlocks.BLUE_BRICK_STAIRS);
		MAGENTA_BRICK_SLAB = block(LlamamodModBlocks.MAGENTA_BRICK_SLAB);
		MAGENTA_BRICK_STAIRS = block(LlamamodModBlocks.MAGENTA_BRICK_STAIRS);
		PINK_BRICK_SLAB = block(LlamamodModBlocks.PINK_BRICK_SLAB);
		PINK_BRICK_STAIRS = block(LlamamodModBlocks.PINK_BRICK_STAIRS);
		BROWN_BRICK_SLAB = block(LlamamodModBlocks.BROWN_BRICK_SLAB);
		BROWN_BRICK_STAIRS = block(LlamamodModBlocks.BROWN_BRICK_STAIRS);
		BLACK_BRICK_SLAB = block(LlamamodModBlocks.BLACK_BRICK_SLAB);
		BLACK_BRICK_STAIRS = block(LlamamodModBlocks.BLACK_BRICK_STAIRS);
		INDUSTRIAL_BRICK_SLAB = block(LlamamodModBlocks.INDUSTRIAL_BRICK_SLAB);
		INDUSTRIAL_BRICK_STAIRS = block(LlamamodModBlocks.INDUSTRIAL_BRICK_STAIRS);
		TILE_SLAB = block(LlamamodModBlocks.TILE_SLAB);
		TILE_STAIRS = block(LlamamodModBlocks.TILE_STAIRS, new Item.Properties().fireResistant());
		CEILING_TILE_SLAB = block(LlamamodModBlocks.CEILING_TILE_SLAB);
		CEILING_TILE_STAIRS = block(LlamamodModBlocks.CEILING_TILE_STAIRS);
		WHITE_BRICKS = block(LlamamodModBlocks.WHITE_BRICKS);
		LIGHT_GRAY_BRICKS = block(LlamamodModBlocks.LIGHT_GRAY_BRICKS);
		GRAY_BRICKS = block(LlamamodModBlocks.GRAY_BRICKS);
		LIME_BRICKS = block(LlamamodModBlocks.LIME_BRICKS);
		CYAN_BRICKS = block(LlamamodModBlocks.CYAN_BRICKS);
		CHERRY_BRICKS = block(LlamamodModBlocks.CHERRY_BRICKS);
		PURPLE_BRICKS = block(LlamamodModBlocks.PURPLE_BRICKS);
		LIME_BRICK_SLAB = block(LlamamodModBlocks.LIME_BRICK_SLAB);
		LIME_BRICK_STAIRS = block(LlamamodModBlocks.LIME_BRICK_STAIRS);
		GREEN_BRICK_SLAB = block(LlamamodModBlocks.GREEN_BRICK_SLAB);
		GREEN_BRICK_STAIRS = block(LlamamodModBlocks.GREEN_BRICK_STAIRS);
		CYAN_BRICK_SLAB = block(LlamamodModBlocks.CYAN_BRICK_SLAB);
		CYAN_BRICK_STAIRS = block(LlamamodModBlocks.CYAN_BRICK_STAIRS);
		PURPLE_BRICK_SLAB = block(LlamamodModBlocks.PURPLE_BRICK_SLAB);
		PURPLE_BRICK_STAIRS = block(LlamamodModBlocks.PURPLE_BRICK_STAIRS);
		WHITE_BRICK_SLAB = block(LlamamodModBlocks.WHITE_BRICK_SLAB);
		WHITE_BRICK_STAIRS = block(LlamamodModBlocks.WHITE_BRICK_STAIRS);
		LIGHT_GRAY_BRICK_SLAB = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_SLAB);
		LIGHT_GRAY_BRICK_STAIRS = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_STAIRS);
		GRAY_BRICK_SLAB = block(LlamamodModBlocks.GRAY_BRICK_SLAB);
		GRAY_BRICK_STAIRS = block(LlamamodModBlocks.GRAY_BRICK_STAIRS);
		CHERRY_BRICK_SLAB = block(LlamamodModBlocks.CHERRY_BRICK_SLAB);
		CHERRY_BRICK_STAIR = block(LlamamodModBlocks.CHERRY_BRICK_STAIR);
		RED_BRICK_WALL = block(LlamamodModBlocks.RED_BRICK_WALL);
		ORANGE_BRICK_WALL = block(LlamamodModBlocks.ORANGE_BRICK_WALL);
		YELLOW_BRICK_WALL = block(LlamamodModBlocks.YELLOW_BRICK_WALL);
		GREEN_BRICK_WALL = block(LlamamodModBlocks.GREEN_BRICK_WALL);
		LIGHT_BLUE_BRICK_WALL = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_WALL);
		BLUE_BRICK_WALL = block(LlamamodModBlocks.BLUE_BRICK_WALL);
		MAGENTA_BRICK_WALL = block(LlamamodModBlocks.MAGENTA_BRICK_WALL);
		PINK_BRICK_WALL = block(LlamamodModBlocks.PINK_BRICK_WALL);
		BROWN_BRICK_WALL = block(LlamamodModBlocks.BROWN_BRICK_WALL);
		BLACK_BRICK_WALL = block(LlamamodModBlocks.BLACK_BRICK_WALL);
		INDUSTRIAL_BRICK_WALL = block(LlamamodModBlocks.INDUSTRIAL_BRICK_WALL);
		WHITE_BRICK_WALL = block(LlamamodModBlocks.WHITE_BRICK_WALL);
		LIGHT_GRAY_BRICK_WALL = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_WALL);
		GRAY_BRICK_WALL = block(LlamamodModBlocks.GRAY_BRICK_WALL);
		LIME_BRICK_WALL = block(LlamamodModBlocks.LIME_BRICK_WALL);
		CYAN_BRICK_WALL = block(LlamamodModBlocks.CYAN_BRICK_WALL);
		CHERRY_BRICK_WALL = block(LlamamodModBlocks.CHERRY_BRICK_WALL);
		PURPLE_BRICK_WALL = block(LlamamodModBlocks.PURPLE_BRICK_WALL);
		CEILING_TILE_WALL = block(LlamamodModBlocks.CEILING_TILE_WALL);
		TILE_WALL = block(LlamamodModBlocks.TILE_WALL, new Item.Properties().fireResistant());
		INDUSTRIAL_BRICK_FENCE = block(LlamamodModBlocks.INDUSTRIAL_BRICK_FENCE);
		INDUSTRIAL_BRICK_FENCE_GATE = block(LlamamodModBlocks.INDUSTRIAL_BRICK_FENCE_GATE);
		INDUSTRIAL_BRICK_BUTTON = block(LlamamodModBlocks.INDUSTRIAL_BRICK_BUTTON);
		INDUSTRIAL_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.INDUSTRIAL_BRICK_PRESSURE_PLATE);
		RED_BRICK_FENCE = block(LlamamodModBlocks.RED_BRICK_FENCE);
		ORANGE_BRICK_FENCE = block(LlamamodModBlocks.ORANGE_BRICK_FENCE);
		YELLOW_BRICK_FENCE = block(LlamamodModBlocks.YELLOW_BRICK_FENCE);
		GREEN_BRICK_FENCE = block(LlamamodModBlocks.GREEN_BRICK_FENCE);
		LIGHT_BLUE_BRICK_FENCE = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_FENCE);
		BLUE_BRICK_FENCE = block(LlamamodModBlocks.BLUE_BRICK_FENCE);
		MAGENTA_BRICK_FENCE = block(LlamamodModBlocks.MAGENTA_BRICK_FENCE);
		PINK_BRICK_FENCE = block(LlamamodModBlocks.PINK_BRICK_FENCE);
		BROWN_BRICK_FENCE = block(LlamamodModBlocks.BROWN_BRICK_FENCE);
		BLACK_BRICK_FENCE = block(LlamamodModBlocks.BLACK_BRICK_FENCE);
		WHITE_BRICK_FENCE = block(LlamamodModBlocks.WHITE_BRICK_FENCE);
		LIGHT_GRAY_BRICK_FENCE = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_FENCE);
		GRAY_BRICK_FENCE = block(LlamamodModBlocks.GRAY_BRICK_FENCE);
		LIME_BRICK_FENCE = block(LlamamodModBlocks.LIME_BRICK_FENCE);
		CYAN_BRICK_FENCE = block(LlamamodModBlocks.CYAN_BRICK_FENCE);
		PURPLE_BRICK_FENCE = block(LlamamodModBlocks.PURPLE_BRICK_FENCE);
		CHERRY_BRICK_FENCE = block(LlamamodModBlocks.CHERRY_BRICK_FENCE);
		RED_BRICK_FENCE_GATE = block(LlamamodModBlocks.RED_BRICK_FENCE_GATE);
		ORANGE_BRICK_FENCE_GATE = block(LlamamodModBlocks.ORANGE_BRICK_FENCE_GATE);
		YELLOW_BRICK_FENCE_GATE = block(LlamamodModBlocks.YELLOW_BRICK_FENCE_GATE);
		GREEN_BRICK_FENCE_GATE = block(LlamamodModBlocks.GREEN_BRICK_FENCE_GATE);
		LIGHT_BLUE_BRICK_FENCE_GATE = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_FENCE_GATE);
		BLUE_BRICK_FENCE_GATE = block(LlamamodModBlocks.BLUE_BRICK_FENCE_GATE);
		MAGENTA_BRICK_FENCE_GATE = block(LlamamodModBlocks.MAGENTA_BRICK_FENCE_GATE);
		PINK_BRICK_FENCE_GATE = block(LlamamodModBlocks.PINK_BRICK_FENCE_GATE);
		BROWN_BRICK_FENCE_GATE = block(LlamamodModBlocks.BROWN_BRICK_FENCE_GATE);
		BLACK_BRICK_FENCE_GATE = block(LlamamodModBlocks.BLACK_BRICK_FENCE_GATE);
		WHITE_BRICK_FENCE_GATE = block(LlamamodModBlocks.WHITE_BRICK_FENCE_GATE);
		LIGHT_GRAY_BRICK_FENCE_GATE = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_FENCE_GATE);
		GRAY_BRICK_FENCE_GATE = block(LlamamodModBlocks.GRAY_BRICK_FENCE_GATE);
		LIME_BRICK_FENCE_GATE = block(LlamamodModBlocks.LIME_BRICK_FENCE_GATE);
		CYAN_BRICK_FENCE_GATE = block(LlamamodModBlocks.CYAN_BRICK_FENCE_GATE);
		PURPLE_BRICK_FENCE_GATE = block(LlamamodModBlocks.PURPLE_BRICK_FENCE_GATE);
		CHERRY_BRICK_FENCE_GATE = block(LlamamodModBlocks.CHERRY_BRICK_FENCE_GATE);
		RED_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.RED_BRICK_PRESSURE_PLATE);
		ORANGE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.ORANGE_BRICK_PRESSURE_PLATE);
		YELLOW_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.YELLOW_BRICK_PRESSURE_PLATE);
		GREEN_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.GREEN_BRICK_PRESSURE_PLATE);
		LIGHT_BLUE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_PRESSURE_PLATE);
		BLUE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.BLUE_BRICK_PRESSURE_PLATE);
		MAGENTA_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.MAGENTA_BRICK_PRESSURE_PLATE);
		PINK_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.PINK_BRICK_PRESSURE_PLATE);
		BROWN_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.BROWN_BRICK_PRESSURE_PLATE);
		BLACK_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.BLACK_BRICK_PRESSURE_PLATE);
		WHITE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.WHITE_BRICK_PRESSURE_PLATE);
		LIGHT_GRAY_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_PRESSURE_PLATE);
		GRAY_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.GRAY_BRICK_PRESSURE_PLATE);
		LIME_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.LIME_BRICK_PRESSURE_PLATE);
		CYAN_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.CYAN_BRICK_PRESSURE_PLATE);
		PURPLE_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.PURPLE_BRICK_PRESSURE_PLATE);
		CHERRY_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.CHERRY_BRICK_PRESSURE_PLATE);
		RED_BRICK_BUTTON = block(LlamamodModBlocks.RED_BRICK_BUTTON);
		ORANGE_BRICK_BUTTON = block(LlamamodModBlocks.ORANGE_BRICK_BUTTON);
		YELLOW_BRICK_BUTTON = block(LlamamodModBlocks.YELLOW_BRICK_BUTTON);
		GREEN_BRICK_BUTTON = block(LlamamodModBlocks.GREEN_BRICK_BUTTON);
		LIGHT_BLUE_BRICK_BUTTON = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_BUTTON);
		BLUE_BRICK_BUTTON = block(LlamamodModBlocks.BLUE_BRICK_BUTTON);
		MAGENTA_BRICK_BUTTON = block(LlamamodModBlocks.MAGENTA_BRICK_BUTTON);
		PINK_BRICK_BUTTON = block(LlamamodModBlocks.PINK_BRICK_BUTTON);
		BROWN_BRICK_BUTTON = block(LlamamodModBlocks.BROWN_BRICK_BUTTON);
		BLACK_BRICK_BUTTON = block(LlamamodModBlocks.BLACK_BRICK_BUTTON);
		WHITE_BRICK_BUTTON = block(LlamamodModBlocks.WHITE_BRICK_BUTTON);
		LIGHT_GRAY_BRICK_BUTTON = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_BUTTON);
		GRAY_BRICK_BUTTON = block(LlamamodModBlocks.GRAY_BRICK_BUTTON);
		LIME_BRICK_BUTTON = block(LlamamodModBlocks.LIME_BRICK_BUTTON);
		CYAN_BRICK_BUTTON = block(LlamamodModBlocks.CYAN_BRICK_BUTTON);
		PURPLE_BRICK_BUTTON = block(LlamamodModBlocks.PURPLE_BRICK_BUTTON);
		CHERRY_BRICK_BUTTON = block(LlamamodModBlocks.CHERRY_BRICK_BUTTON);
		TILE_PRESSURE_PLATE = block(LlamamodModBlocks.TILE_PRESSURE_PLATE);
		TILE_BUTTON = block(LlamamodModBlocks.TILE_BUTTON);
		CEILING_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.CEILING_TILE_PRESSURE_PLATE);
		CEILING_TILE_BUTTON = block(LlamamodModBlocks.CEILING_TILE_BUTTON);
		WHITE_LARGE_TILE = block(LlamamodModBlocks.WHITE_LARGE_TILE);
		WHITE_LARGE_TILE_STAIRS = block(LlamamodModBlocks.WHITE_LARGE_TILE_STAIRS);
		WHITE_LARGE_TILE_SLAB = block(LlamamodModBlocks.WHITE_LARGE_TILE_SLAB);
		WHITE_LARGE_TILE_WALL = block(LlamamodModBlocks.WHITE_LARGE_TILE_WALL);
		WHITE_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.WHITE_LARGE_TILE_PRESSURE_PLATE);
		WHITE_LARGE_TILE_BUTTON = block(LlamamodModBlocks.WHITE_LARGE_TILE_BUTTON);
		VARIABLE_LIGHT = block(LlamamodModBlocks.VARIABLE_LIGHT);
		LIGHT_GRAY_LARGE_TILE = block(LlamamodModBlocks.LIGHT_GRAY_LARGE_TILE);
		GRAY_LARGE_TILE = block(LlamamodModBlocks.GRAY_LARGE_TILE);
		BLACK_LARGE_TILE = block(LlamamodModBlocks.BLACK_LARGE_TILE);
		ORANGE_LARGE_TILE = block(LlamamodModBlocks.ORANGE_LARGE_TILE);
		MAGENTA_LARGE_TILE = block(LlamamodModBlocks.MAGENTA_LARGE_TILE);
		LIGHT_BLUE_LARGE_TILE = block(LlamamodModBlocks.LIGHT_BLUE_LARGE_TILE);
		BLUE_LARGE_TILE = block(LlamamodModBlocks.BLUE_LARGE_TILE);
		YELLOW_LARGE_TILE = block(LlamamodModBlocks.YELLOW_LARGE_TILE);
		LIME_LARGE_TILE = block(LlamamodModBlocks.LIME_LARGE_TILE);
		GREEN_LARGE_TILE = block(LlamamodModBlocks.GREEN_LARGE_TILE);
		PINK_LARGE_TILE = block(LlamamodModBlocks.PINK_LARGE_TILE);
		CYAN_LARGE_TILE = block(LlamamodModBlocks.CYAN_LARGE_TILE);
		PURPLE_LARGE_TILE = block(LlamamodModBlocks.PURPLE_LARGE_TILE);
		BROWN_LARGE_TILE = block(LlamamodModBlocks.BROWN_LARGE_TILE);
		RED_LARGE_TILE = block(LlamamodModBlocks.RED_LARGE_TILE);
		LARGE_TILE_FENCE = block(LlamamodModBlocks.LARGE_TILE_FENCE);
		LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.LARGE_TILE_FENCE_GATE);
		LIGHT_GRAY_LARGE_TILE_STAIRS = block(LlamamodModBlocks.LIGHT_GRAY_LARGE_TILE_STAIRS);
		LIGHT_GRAY_LARGE_TILE_SLAB = block(LlamamodModBlocks.LIGHT_GRAY_LARGE_TILE_SLAB);
		LIGHT_GRAY_LARGE_TILE_WALL = block(LlamamodModBlocks.LIGHT_GRAY_LARGE_TILE_WALL);
		LIGHT_GRAY_LARGE_TILE_FENCE = block(LlamamodModBlocks.LIGHT_GRAY_LARGE_TILE_FENCE);
		LIGHT_GRAY_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.LIGHT_GRAY_LARGE_TILE_FENCE_GATE);
		LIGHT_GRAY_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.LIGHT_GRAY_LARGE_TILE_PRESSURE_PLATE);
		LIGHT_GRAY_LARGE_TILE_BUTTON = block(LlamamodModBlocks.LIGHT_GRAY_LARGE_TILE_BUTTON);
		GRAY_LARGE_TILE_STAIRS = block(LlamamodModBlocks.GRAY_LARGE_TILE_STAIRS);
		GRAY_LARGE_TILE_SLAB = block(LlamamodModBlocks.GRAY_LARGE_TILE_SLAB);
		GRAY_LARGE_TILE_WALL = block(LlamamodModBlocks.GRAY_LARGE_TILE_WALL);
		GRAY_LARGE_TILE_FENCE = block(LlamamodModBlocks.GRAY_LARGE_TILE_FENCE);
		GRAY_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.GRAY_LARGE_TILE_FENCE_GATE);
		GRAY_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.GRAY_LARGE_TILE_PRESSURE_PLATE);
		GRAY_LARGE_TILE_BUTTON = block(LlamamodModBlocks.GRAY_LARGE_TILE_BUTTON);
		BLACK_LARGE_TILE_STAIRS = block(LlamamodModBlocks.BLACK_LARGE_TILE_STAIRS);
		BLACK_LARGE_TILE_SLAB = block(LlamamodModBlocks.BLACK_LARGE_TILE_SLAB);
		BLACK_LARGE_TILE_WALL = block(LlamamodModBlocks.BLACK_LARGE_TILE_WALL);
		BLACK_LARGE_TILE_FENCE = block(LlamamodModBlocks.BLACK_LARGE_TILE_FENCE);
		BLACK_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.BLACK_LARGE_TILE_FENCE_GATE);
		BLACK_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.BLACK_LARGE_TILE_PRESSURE_PLATE);
		BLACK_LARGE_TILE_BUTTON = block(LlamamodModBlocks.BLACK_LARGE_TILE_BUTTON);
		BROWN_LARGE_TILE_STAIRS = block(LlamamodModBlocks.BROWN_LARGE_TILE_STAIRS);
		BROWN_LARGE_TILE_SLAB = block(LlamamodModBlocks.BROWN_LARGE_TILE_SLAB);
		BROWN_LARGE_TILE_WALL = block(LlamamodModBlocks.BROWN_LARGE_TILE_WALL);
		BROWN_LARGE_TILE_FENCE = block(LlamamodModBlocks.BROWN_LARGE_TILE_FENCE);
		BROWN_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.BROWN_LARGE_TILE_FENCE_GATE);
		BROWN_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.BROWN_LARGE_TILE_PRESSURE_PLATE);
		BROWN_LARGE_TILE_BUTTON = block(LlamamodModBlocks.BROWN_LARGE_TILE_BUTTON);
		RED_LARGE_TILE_STAIRS = block(LlamamodModBlocks.RED_LARGE_TILE_STAIRS);
		RED_LARGE_TILE_SLAB = block(LlamamodModBlocks.RED_LARGE_TILE_SLAB);
		RED_LARGE_TILE_WALL = block(LlamamodModBlocks.RED_LARGE_TILE_WALL);
		RED_LARGE_TILE_FENCE = block(LlamamodModBlocks.RED_LARGE_TILE_FENCE);
		RED_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.RED_LARGE_TILE_FENCE_GATE);
		RED_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.RED_LARGE_TILE_PRESSURE_PLATE);
		RED_LARGE_TILE_BUTTON = block(LlamamodModBlocks.RED_LARGE_TILE_BUTTON);
		ORANGE_LARGE_TILE_STAIRS = block(LlamamodModBlocks.ORANGE_LARGE_TILE_STAIRS);
		ORANGE_LARGE_TILE_SLAB = block(LlamamodModBlocks.ORANGE_LARGE_TILE_SLAB);
		ORANGE_LARGE_TILE_WALL = block(LlamamodModBlocks.ORANGE_LARGE_TILE_WALL);
		ORANGE_LARGE_TILE_FENCE = block(LlamamodModBlocks.ORANGE_LARGE_TILE_FENCE);
		ORANGE_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.ORANGE_LARGE_TILE_FENCE_GATE);
		ORANGE_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.ORANGE_LARGE_TILE_PRESSURE_PLATE);
		ORANGE_LARGE_TILE_BUTTON = block(LlamamodModBlocks.ORANGE_LARGE_TILE_BUTTON);
		YELLOW_LARGE_TILE_STAIRS = block(LlamamodModBlocks.YELLOW_LARGE_TILE_STAIRS);
		YELLOW_LARGE_TILE_SLAB = block(LlamamodModBlocks.YELLOW_LARGE_TILE_SLAB);
		YELLOW_LARGE_TILE_WALL = block(LlamamodModBlocks.YELLOW_LARGE_TILE_WALL);
		YELLOW_LARGE_TILE_FENCE = block(LlamamodModBlocks.YELLOW_LARGE_TILE_FENCE);
		YELLOW_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.YELLOW_LARGE_TILE_FENCE_GATE);
		YELLOW_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.YELLOW_LARGE_TILE_PRESSURE_PLATE);
		YELLOW_LARGE_TILE_BUTTON = block(LlamamodModBlocks.YELLOW_LARGE_TILE_BUTTON);
		LIME_LARGE_TILE_STAIRS = block(LlamamodModBlocks.LIME_LARGE_TILE_STAIRS);
		LIME_LARGE_TILE_SLAB = block(LlamamodModBlocks.LIME_LARGE_TILE_SLAB);
		LIME_LARGE_TILE_WALL = block(LlamamodModBlocks.LIME_LARGE_TILE_WALL);
		LIME_LARGE_TILE_FENCE = block(LlamamodModBlocks.LIME_LARGE_TILE_FENCE);
		LIME_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.LIME_LARGE_TILE_FENCE_GATE);
		LIME_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.LIME_LARGE_TILE_PRESSURE_PLATE);
		LIME_LARGE_TILE_BUTTON = block(LlamamodModBlocks.LIME_LARGE_TILE_BUTTON);
		GREEN_LARGE_TILE_STAIRS = block(LlamamodModBlocks.GREEN_LARGE_TILE_STAIRS);
		GREEN_LARGE_TILE_SLAB = block(LlamamodModBlocks.GREEN_LARGE_TILE_SLAB);
		GREEN_LARGE_TILE_WALL = block(LlamamodModBlocks.GREEN_LARGE_TILE_WALL);
		GREEN_LARGE_TILE_FENCE = block(LlamamodModBlocks.GREEN_LARGE_TILE_FENCE);
		GREEN_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.GREEN_LARGE_TILE_FENCE_GATE);
		GREEN_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.GREEN_LARGE_TILE_PRESSURE_PLATE);
		GREEN_LARGE_TILE_BUTTON = block(LlamamodModBlocks.GREEN_LARGE_TILE_BUTTON);
		CYAN_LARGE_TILE_STAIRS = block(LlamamodModBlocks.CYAN_LARGE_TILE_STAIRS);
		CYAN_LARGE_TILE_SLAB = block(LlamamodModBlocks.CYAN_LARGE_TILE_SLAB);
		CYAN_LARGE_TILE_WALL = block(LlamamodModBlocks.CYAN_LARGE_TILE_WALL);
		CYAN_LARGE_TILE_FENCE = block(LlamamodModBlocks.CYAN_LARGE_TILE_FENCE);
		CYAN_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.CYAN_LARGE_TILE_FENCE_GATE);
		CYAN_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.CYAN_LARGE_TILE_PRESSURE_PLATE);
		CYAN_LARGE_TILE_BUTTON = block(LlamamodModBlocks.CYAN_LARGE_TILE_BUTTON);
		LIGHT_BLUE_LARGE_TILE_STAIRS = block(LlamamodModBlocks.LIGHT_BLUE_LARGE_TILE_STAIRS);
		LIGHT_BLUE_LARGE_TILE_SLAB = block(LlamamodModBlocks.LIGHT_BLUE_LARGE_TILE_SLAB);
		LIGHT_BLUE_LARGE_TILE_WALL = block(LlamamodModBlocks.LIGHT_BLUE_LARGE_TILE_WALL);
		LIGHT_BLUE_LARGE_TILE_FENCE = block(LlamamodModBlocks.LIGHT_BLUE_LARGE_TILE_FENCE);
		LIGHT_BLUE_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.LIGHT_BLUE_LARGE_TILE_FENCE_GATE);
		LIGHT_BLUE_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.LIGHT_BLUE_LARGE_TILE_PRESSURE_PLATE);
		LIGHT_BLUE_LARGE_TILE_BUTTON = block(LlamamodModBlocks.LIGHT_BLUE_LARGE_TILE_BUTTON);
		BLUE_LARGE_TILE_STAIRS = block(LlamamodModBlocks.BLUE_LARGE_TILE_STAIRS);
		BLUE_LARGE_TILE_SLAB = block(LlamamodModBlocks.BLUE_LARGE_TILE_SLAB);
		BLUE_LARGE_TILE_WALL = block(LlamamodModBlocks.BLUE_LARGE_TILE_WALL);
		BLUE_LARGE_TILE_FENCE = block(LlamamodModBlocks.BLUE_LARGE_TILE_FENCE);
		BLUE_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.BLUE_LARGE_TILE_FENCE_GATE);
		BLUE_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.BLUE_LARGE_TILE_PRESSURE_PLATE);
		BLUE_LARGE_TILE_BUTTON = block(LlamamodModBlocks.BLUE_LARGE_TILE_BUTTON);
		PURPLE_LARGE_TILE_STAIRS = block(LlamamodModBlocks.PURPLE_LARGE_TILE_STAIRS);
		PURPLE_LARGE_TILE_SLAB = block(LlamamodModBlocks.PURPLE_LARGE_TILE_SLAB);
		PURPLE_LARGE_TILE_WALL = block(LlamamodModBlocks.PURPLE_LARGE_TILE_WALL);
		PURPLE_LARGE_TILE_FENCE = block(LlamamodModBlocks.PURPLE_LARGE_TILE_FENCE);
		PURPLE_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.PURPLE_LARGE_TILE_FENCE_GATE);
		PURPLE_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.PURPLE_LARGE_TILE_PRESSURE_PLATE);
		PURPLE_LARGE_TILE_BUTTON = block(LlamamodModBlocks.PURPLE_LARGE_TILE_BUTTON);
		MAGENTA_LARGE_TILE_STAIRS = block(LlamamodModBlocks.MAGENTA_LARGE_TILE_STAIRS);
		MAGENTA_LARGE_TILE_SLAB = block(LlamamodModBlocks.MAGENTA_LARGE_TILE_SLAB);
		MAGENTA_LARGE_TILE_WALL = block(LlamamodModBlocks.MAGENTA_LARGE_TILE_WALL);
		MAGENTA_LARGE_TILE_FENCE = block(LlamamodModBlocks.MAGENTA_LARGE_TILE_FENCE);
		MAGENTA_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.MAGENTA_LARGE_TILE_FENCE_GATE);
		MAGENTA_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.MAGENTA_LARGE_TILE_PRESSURE_PLATE);
		MAGENTA_LARGE_TILE_BUTTON = block(LlamamodModBlocks.MAGENTA_LARGE_TILE_BUTTON);
		PINK_LARGE_TILE_STAIRS = block(LlamamodModBlocks.PINK_LARGE_TILE_STAIRS);
		PINK_LARGE_TILE_SLAB = block(LlamamodModBlocks.PINK_LARGE_TILE_SLAB);
		PINK_LARGE_TILE_WALL = block(LlamamodModBlocks.PINK_LARGE_TILE_WALL);
		PINK_LARGE_TILE_FENCE = block(LlamamodModBlocks.PINK_LARGE_TILE_FENCE);
		PINK_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.PINK_LARGE_TILE_FENCE_GATE);
		PINK_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.PINK_LARGE_TILE_PRESSURE_PLATE);
		PINK_LARGE_TILE_BUTTON = block(LlamamodModBlocks.PINK_LARGE_TILE_BUTTON);
		CEILING_TILE_FENCE = block(LlamamodModBlocks.CEILING_TILE_FENCE);
		CEILING_TILE_FENCE_GATE = block(LlamamodModBlocks.CEILING_TILE_FENCE_GATE);
		TILE_FENCE = block(LlamamodModBlocks.TILE_FENCE, new Item.Properties().fireResistant());
		TILE_FENCE_GATE = block(LlamamodModBlocks.TILE_FENCE_GATE, new Item.Properties().fireResistant());
		INDUSTRIAL_LARGE_TILE = block(LlamamodModBlocks.INDUSTRIAL_LARGE_TILE);
		INDUSTRIAL_LARGE_TILE_STAIRS = block(LlamamodModBlocks.INDUSTRIAL_LARGE_TILE_STAIRS);
		INDUSTRIAL_LARGE_TILE_SLAB = block(LlamamodModBlocks.INDUSTRIAL_LARGE_TILE_SLAB);
		INDUSTRIAL_LARGE_TILE_WALL = block(LlamamodModBlocks.INDUSTRIAL_LARGE_TILE_WALL);
		INDUSTRIAL_LARGE_TILE_FENCE = block(LlamamodModBlocks.INDUSTRIAL_LARGE_TILE_FENCE);
		INDUSTRIAL_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.INDUSTRIAL_LARGE_TILE_FENCE_GATE);
		INDUSTRIAL_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.INDUSTRIAL_LARGE_TILE_PRESSURE_PLATE);
		INDUSTRIAL_LARGE_TILE_BUTTON = block(LlamamodModBlocks.INDUSTRIAL_LARGE_TILE_BUTTON);
		WHITE_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.WHITE_LARGE_TILE_TRAPDOOR);
		INDUSTRIAL_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.INDUSTRIAL_LARGE_TILE_TRAPDOOR);
		LIGHT_GRAY_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.LIGHT_GRAY_LARGE_TILE_TRAPDOOR);
		GRAY_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.GRAY_LARGE_TILE_TRAPDOOR);
		BLACK_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.BLACK_LARGE_TILE_TRAPDOOR);
		BROWN_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.BROWN_LARGE_TILE_TRAPDOOR);
		RED_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.RED_LARGE_TILE_TRAPDOOR);
		ORANGE_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.ORANGE_LARGE_TILE_TRAPDOOR);
		YELLOW_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.YELLOW_LARGE_TILE_TRAPDOOR);
		LIME_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.LIME_LARGE_TILE_TRAPDOOR);
		GREEN_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.GREEN_LARGE_TILE_TRAPDOOR);
		CYAN_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.CYAN_LARGE_TILE_TRAPDOOR);
		LIGHT_BLUE_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.LIGHT_BLUE_LARGE_TILE_TRAPDOOR);
		BLUE_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.BLUE_LARGE_TILE_TRAPDOOR);
		PURPLE_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.PURPLE_LARGE_TILE_TRAPDOOR);
		MAGENTA_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.MAGENTA_LARGE_TILE_TRAPDOOR);
		PINK_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.PINK_LARGE_TILE_TRAPDOOR);
		WHITE_BRICK_TRAPDOOR = block(LlamamodModBlocks.WHITE_BRICK_TRAPDOOR);
		LIGHT_GRAY_BRICK_TRAPDOOR = block(LlamamodModBlocks.LIGHT_GRAY_BRICK_TRAPDOOR);
		GRAY_BRICK_TRAPDOOR = block(LlamamodModBlocks.GRAY_BRICK_TRAPDOOR);
		BLACK_BRICK_TRAPDOOR = block(LlamamodModBlocks.BLACK_BRICK_TRAPDOOR);
		BROWN_BRICK_TRAPDOOR = block(LlamamodModBlocks.BROWN_BRICK_TRAPDOOR);
		RED_BRICK_TRAPDOOR = block(LlamamodModBlocks.RED_BRICK_TRAPDOOR);
		ORANGE_BRICK_TRAPDOOR = block(LlamamodModBlocks.ORANGE_BRICK_TRAPDOOR);
		YELLOW_BRICK_TRAPDOOR = block(LlamamodModBlocks.YELLOW_BRICK_TRAPDOOR);
		LIME_BRICK_TRAPDOOR = block(LlamamodModBlocks.LIME_BRICK_TRAPDOOR);
		GREEN_BRICK_TRAPDOOR = block(LlamamodModBlocks.GREEN_BRICK_TRAPDOOR);
		CYAN_BRICK_TRAPDOOR = block(LlamamodModBlocks.CYAN_BRICK_TRAPDOOR);
		LIGHT_BLUE_BRICK_TRAPDOOR = block(LlamamodModBlocks.LIGHT_BLUE_BRICK_TRAPDOOR);
		BLUE_BRICK_TRAPDOOR = block(LlamamodModBlocks.BLUE_BRICK_TRAPDOOR);
		PURPLE_BRICK_TRAPDOOR = block(LlamamodModBlocks.PURPLE_BRICK_TRAPDOOR);
		MAGENTA_BRICK_TRAPDOOR = block(LlamamodModBlocks.MAGENTA_BRICK_TRAPDOOR);
		PINK_BRICK_TRAPDOOR = block(LlamamodModBlocks.PINK_BRICK_TRAPDOOR);
		CHERRY_BRICK_TRAPDOOR = block(LlamamodModBlocks.CHERRY_BRICK_TRAPDOOR);
		INDUSTRIAL_BRICK_TRAPDOOR = block(LlamamodModBlocks.INDUSTRIAL_BRICK_TRAPDOOR);
		CEILING_TILE_TRAPDOOR = block(LlamamodModBlocks.CEILING_TILE_TRAPDOOR);
		TILE_TRAPDOOR = block(LlamamodModBlocks.TILE_TRAPDOOR);
		CHERRY_LARGE_TILE = block(LlamamodModBlocks.CHERRY_LARGE_TILE);
		CHERRY_LARGE_TILE_STAIRS = block(LlamamodModBlocks.CHERRY_LARGE_TILE_STAIRS);
		CHERRY_LARGE_TILE_SLAB = block(LlamamodModBlocks.CHERRY_LARGE_TILE_SLAB);
		CHERRY_LARGE_TILE_WALL = block(LlamamodModBlocks.CHERRY_LARGE_TILE_WALL);
		CHERRY_LARGE_TILE_FENCE = block(LlamamodModBlocks.CHERRY_LARGE_TILE_FENCE);
		CHERRY_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.CHERRY_LARGE_TILE_FENCE_GATE);
		CHERRY_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.CHERRY_LARGE_TILE_TRAPDOOR);
		CHERRY_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.CHERRY_LARGE_TILE_PRESSURE_PLATE);
		CHERRY_LARGE_TILE_BUTTON = block(LlamamodModBlocks.CHERRY_LARGE_TILE_BUTTON);
		SECURE_STORAGE_BLOCK = block(LlamamodModBlocks.SECURE_STORAGE_BLOCK, new Item.Properties().fireResistant());
		TEAL_BRICKS = block(LlamamodModBlocks.TEAL_BRICKS);
		TEAL_LARGE_TILE = block(LlamamodModBlocks.TEAL_LARGE_TILE);
		TEAL_LARGE_TILE_STAIRS = block(LlamamodModBlocks.TEAL_LARGE_TILE_STAIRS);
		TEAL_LARGE_TILE_SLAB = block(LlamamodModBlocks.TEAL_LARGE_TILE_SLAB);
		TEAL_LARGE_TILE_WALL = block(LlamamodModBlocks.TEAL_LARGE_TILE_WALL);
		TEAL_LARGE_TILE_FENCE = block(LlamamodModBlocks.TEAL_LARGE_TILE_FENCE);
		TEAL_LARGE_TILE_FENCE_GATE = block(LlamamodModBlocks.TEAL_LARGE_TILE_FENCE_GATE);
		TEAL_LARGE_TILE_TRAPDOOR = block(LlamamodModBlocks.TEAL_LARGE_TILE_TRAPDOOR);
		TEAL_LARGE_TILE_PRESSURE_PLATE = block(LlamamodModBlocks.TEAL_LARGE_TILE_PRESSURE_PLATE);
		TEAL_LARGE_TILE_BUTTON = block(LlamamodModBlocks.TEAL_LARGE_TILE_BUTTON);
		TEAL_BRICK_STAIRS = block(LlamamodModBlocks.TEAL_BRICK_STAIRS);
		TEAL_BRICK_SLAB = block(LlamamodModBlocks.TEAL_BRICK_SLAB);
		TEAL_BRICK_WALL = block(LlamamodModBlocks.TEAL_BRICK_WALL);
		TEAL_BRICK_FENCE = block(LlamamodModBlocks.TEAL_BRICK_FENCE);
		TEAL_BRICK_FENCE_GATE = block(LlamamodModBlocks.TEAL_BRICK_FENCE_GATE);
		TEAL_BRICK_TRAPDOOR = block(LlamamodModBlocks.TEAL_BRICK_TRAPDOOR);
		TEAL_BRICK_PRESSURE_PLATE = block(LlamamodModBlocks.TEAL_BRICK_PRESSURE_PLATE);
		TEAL_BRICK_BUTTON = block(LlamamodModBlocks.TEAL_BRICK_BUTTON);
		GOLDEN_BANANA = register("golden_banana", GoldenBannanaItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new BackpackInventoryCapability(stack), BACKPACK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new NetheritebackpackInventoryCapability(stack), NETHERITE_BACKPACK.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), ACID_BUCKET.get());
	}
}